#!/bin/bash
# Run leanprover/comparator against both challenge/solution pairs:
#   config.json      — 13 architecture-free theorems, Challenge imports only Mathlib
#   config-arch.json — 39 architecture theorems, ChallengeArch imports the project
#   config-tier.json — the tie / faithfulness / whole-net / DP / float / certificate
#                      theorems (35 as of 2026-09-21), machine-generated by
#                      scripts/gen_comparator_tier.py.
#                      This is exactly formalization.yaml's advertised set minus the
#                      four config-arch.json already covers, so the three files together
#                      kernel-recheck every declaration the project puts forward.
#
# What it verifies (per Lean's kernel, independently of the elaborator):
#   1. Solution's theorem statements bit-identically match Challenge's
#      (so the prover didn't redefine the goal).
#   2. Each proof's transitive axiom closure is a subset of
#      [propext, Quot.sound, Classical.choice] — i.e. zero project axioms.
#   3. The proof typechecks against Lean's kernel.
#
# Prerequisites (one-time setup):
#   - a kernel with Landlock (ABI v5 = kernel ≥ 6.10 is the full sandbox profile;
#     older ABIs run under landrun --best-effort, silently weaker — see README.md)
#   - landrun: https://github.com/Zouuup/landrun (prebuilt binary)
#   - lean4export: https://github.com/leanprover/lean4export (lake build)
#   - comparator: https://github.com/leanprover/comparator (lake build)
#
# All three binaries must be on PATH. See README.md for a setup recipe.
#
# Usage: ./run.sh

set -e

cd "$(dirname "$0")"

# landrun v0.1.13 doesn't recognize the single-dash flags comparator emits
# (-ldd / -add-exec) and comparator's `--rox /usr/bin/git` is too narrow
# for lake's path lookup. Wrap landrun in a shim that fixes both.
WRAPPER_DIR="$(mktemp -d)"
trap 'rm -rf "$WRAPPER_DIR"' EXIT
cat > "$WRAPPER_DIR/landrun" <<'WRAP'
#!/bin/bash
# Translate single-dash flags + ensure /usr is exec-able.
args=(--rox /usr)
for a in "$@"; do
  case "$a" in
    -ldd)      args+=(--ldd) ;;
    -add-exec) args+=(--add-exec) ;;
    *)         args+=("$a") ;;
  esac
done
exec landrun-real "${args[@]}"
WRAP
chmod +x "$WRAPPER_DIR/landrun"

# Stash the real landrun under a different name and prepend the wrapper.
REAL_LANDRUN="$(command -v landrun)"
ln -sf "$REAL_LANDRUN" "$WRAPPER_DIR/landrun-real"

# Pre-resolve Mathlib via the parent project's manifest, then build
# Solution outside the sandbox (so the sandbox doesn't try to write to
# the parent's .lake/build/).
echo "[1/3] lake update + cache get (resolving + fetching Mathlib)…"
lake update >/dev/null
# Fetch Mathlib's prebuilt oleans into this sub-project's own .lake tree
# rather than recompiling ~5k Mathlib files from source. The comparator
# path-requires the parent (../..), so its Mathlib rev matches the parent's
# exactly and the Azure olean cache always hits. Without this, the
# `lake build Solution` below compiles Mathlib from scratch (~30-40 min) —
# the "built/cached twice" cost flagged in comparator.yml.
# `|| true`: a cache miss/network blip degrades to a source build (slow but
# correct) instead of aborting the run under `set -e` — matches proofs.yml.
lake exe cache get >/dev/null || true

echo "[2/3] lake build Solution SolutionArch SolutionTier (outside sandbox)…"
lake build Solution SolutionArch SolutionTier

echo "[3/3] lake env comparator — the Mathlib-only pair, the architectures, then the tier…"
# One `[comparator] <config>: <n> theorems OK in <s> s` line per config, printed only after
# comparator exits 0 (set -e). comparator.yml's job summary is built from these lines.
for cfg in config.json config-arch.json config-tier.json; do
  n="$(python3 -c 'import json, sys; print(len(json.load(open(sys.argv[1]))["theorem_names"]))' "$cfg")"
  t0=$SECONDS
  PATH="$WRAPPER_DIR:$PATH" lake env comparator "$cfg"
  echo "[comparator] $cfg: $n theorems OK in $((SECONDS - t0)) s"
done
