import LeanMlir.Proofs.Codegen.StableHLOPretty

/-! # The chapter 1–4 forward-artifact writers

The `#eval` below writes the committed `verified_mlir/{linear,mlp,cnn,cifar,cifar8,cifar8_bn,cifar8w}_*`
forwards and the linear train step from `StableHLOPretty`'s `*ModuleV` renderers, when this module is
elaborated. Nothing imports this file, so building the modules that import `StableHLOPretty`
never rewrites an artifact. `scripts/regen_verified_mlir.sh proofs` and the proofs.yml
drift guard both elaborate it. -/

-- The exact `pretty (emit g)` text the verified trainers compile and run. `pretty` ignores
-- operand/param *values* (only names/shapes reach the text), so the constant placeholders below
-- render exactly the text `den` is faithful to. The train-step lr literal is 0.1/128 (mean-loss
-- equiv of the book's 0.1). Regenerate with `lake env lean LeanMlir/Proofs/Codegen/ChapterArtifacts.lean`.
#eval (do
  IO.FS.createDirAll "verified_mlir"
  IO.FS.writeFile "verified_mlir/linear_fwd.mlir"
    (Proofs.StableHLO.linearFwdModuleV 128 784 10 (fun _ _ => 0) (fun _ => 0) (fun _ => 0))
  -- Whole train step rendered from the verified AST (cotangent + weightSgd/biasSgd
  -- nodes), the den-certified renderer LinearFold proves; see that file +
  -- planning/archive/verified_faithful_sweep.md. (linearTrainStepModuleV — forward-AST +
  -- hand-written tail — is its structural predecessor, kept for reference.)
  IO.FS.writeFile "verified_mlir/linear_train_step.mlir"
    (Proofs.StableHLO.linTrainStepFaithfulV 128 784 10 "0.00078125"
       (fun _ _ => 0) (fun _ => 0) (fun _ => 0))
  -- Chapter 2 MLP (784→512→512→10): forward + full SGD train step.
  IO.FS.writeFile "verified_mlir/mlp_fwd.mlir"
    (Proofs.StableHLO.mlpFwdModuleV 128 784 512 512 10
       (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
       (fun _ => 0))
  -- mlp_train_step.mlir is generated by the faithful renderer in MlpRender.lean
  -- (mlpTrainStepFaithfulV, den-certified in MlpFold.lean).
  -- Chapter 3 CNN forward (1→32→32 conv, 28×28→14×14 maxpool, 6272→512→512→10).
  IO.FS.writeFile "verified_mlir/cnn_fwd.mlir"
    (Proofs.StableHLO.cnnFwdModuleV 128 1 32 14 14 512 10 3 3
       (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
       (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
       (fun _ => 0))
  -- cnn_train_step.mlir is generated by the faithful renderer in CnnRender.lean
  -- (cnnTrainStepFaithfulV, den-certified in CnnFold.lean).
  -- Chapter 4 CIFAR forward (3→32→32 conv, 32×32→16×16 pool, 32→64→64 conv,
  -- 16×16→8×8 pool, flatten 4096→512→512→10). h=w=8 ⇒ input 3·32·32 = 3072.
  IO.FS.writeFile "verified_mlir/cifar_fwd.mlir"
    (Proofs.StableHLO.cifarFwdModuleV 128 3 32 64 8 8 512 10 3 3
       (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
       (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
       (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
       (fun _ => 0))
  -- cifar_train_step.mlir is generated by the faithful renderer in CnnRender.lean
  -- (cifarTrainStepFaithfulV, den-certified in CifarFold.lean).
  -- Deeper 8-conv CIFAR (no BN): 4 conv→conv→pool stages, channels [16,16,32,32],
  -- 32→16→8→4→2 spatial, flat 32·2·2 = 128 → 64 → 64 → 10. lr = 0.1/128.
  -- cifar8_fwd.mlir is rendered from the verified cifar8FwdGraph (cifar8FwdGraph_faithful).
  -- Dims: h=w=2 final pooled (image 32×32, 4 pools).
  IO.FS.writeFile "verified_mlir/cifar8_fwd.mlir"
    (Proofs.StableHLO.cifar8FwdModuleV 128 3 16 16 32 32 2 2 64 10 3 3
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
      (fun _ => 0))
  -- cifar8_train_step.mlir is generated by the faithful renderer in CnnRender.lean
  -- (cifar8TrainStepFaithfulV, den-certified in Cifar8StepTie.lean).
  -- Deeper 8-conv CIFAR **per-channel BatchNorm** (ε=1e-5; lr = 0.1/128).
  -- cifar8_bn_fwd.mlir is rendered from the verified cifar8BnFwdGraph (cifar8BnFwdGraph_faithful).
  -- Per conv layer: W b ε γ β (ε render-erased; epsStr carries it).
  IO.FS.writeFile "verified_mlir/cifar8_bn_fwd.mlir"
    (Proofs.StableHLO.cifar8BnFwdModuleV 128 3 16 16 32 32 2 2 64 10 3 3 "1.0e-05"
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
      (fun _ => 0))
  -- cifar8_bn_train_step.mlir is generated by the faithful renderer in CnnRender.lean
  -- (cifar8BnTrainStepFaithfulV, den-certified by the existing generics).
  -- ── §2i: the cifar8-WIDE eval forwards, d1 := 512 ────────────────────────────────────────
  -- `cifar8w` is `cifar8` with the MNIST-style 2×512 head — measured 2026-07-30, the two
  -- `VerifiedNetSpec`s agree layer-for-layer up to the head width, and the committed
  -- `cifar8w_bn_adam_train_step.mlir` is BYTE-IDENTICAL (modulo the entry name) to the width-sweep's
  -- `cifar8_bn_512_adam_train_step.mlir`. So the wide family needs NO new renderer: it is these same
  -- certified modules at `d1 := 512`, which is also what the `cifar8_bn_{d}` sweep already does.
  -- It is NOT prunable — `runs/ablation_cifar8w/README.md` is the Chapter-5 "bridge" table (6 cells,
  -- both forwards), and the width sweep is adam-only so it covers just 1 of those 6.
  -- ✅ SWAPPED 2026-07-30: both ties came back logits BIT-EXACT 1280/1280 against the retired
  -- hand-written text emitters, and each `#eval` is now its artifact's ONLY writer. Entry renamed because these renderers emit
  -- `@cifar8{,_bn}_fwd` — the same `.replace` the retired hand-written writer used, so
  -- `trainAdamSched`'s `m.cifar8w{,_bn}_fwd` eval call still resolves.
  IO.FS.writeFile "verified_mlir/cifar8w_fwd.mlir"
    ((Proofs.StableHLO.cifar8FwdModuleV 128 3 16 16 32 32 2 2 512 10 3 3
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) (fun _ _ _ _ => 0) (fun _ => 0)
      (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
      (fun _ => 0)).replace "@cifar8_fwd" "@cifar8w_fwd")
  IO.FS.writeFile "verified_mlir/cifar8w_bn_fwd.mlir"
    ((Proofs.StableHLO.cifar8BnFwdModuleV 128 3 16 16 32 32 2 2 512 10 3 3 "1.0e-05"
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ _ _ => 0) (fun _ => 0) 0 (fun _ => 0) (fun _ => 0)
      (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0) (fun _ _ => 0) (fun _ => 0)
      (fun _ => 0)).replace "@cifar8_bn_fwd" "@cifar8w_bn_fwd")
  pure () : IO Unit)

