import Lake.CLI.Main

/-! # `lake exe blueprint-checkdecls` — split-aware blueprint declaration check

A repo-owned variant of `PatrickMassot/checkdecls` (same logic, two filters):
verify that every declaration the blueprint references (`blueprint/lean_decls`,
generated by `leanblueprint web`) exists — importing the roots of every lib
EXCEPT `CertsHeavy` and except the trainer-side `apps` tree. The upstream tool
imports every lib of the workspace, which over-imports twice over:

* **`CertsHeavy`** — importing heavy oleans the blueprint workflow deliberately
  does not build (they OOM the shared runners; that's why the split exists).
* **`apps.*` roots** — `leanLibs` picks up libs rooted under `apps`, but this
  workflow builds `lake build LeanMlir Certs`, not the apps tree, so importing
  them dies with `unknown module prefix 'apps'`.
* **`demos.*` roots** — **the same failure, one prefix over.** A lib rooted
  under `demos` (e.g. `demos.Yolov1VisdroneFpnCommon`) makes `leanLibs` pick up
  a `demos` root, and this dies with `unknown module prefix 'demos'` — after the
  full build, since checkdecls runs last.
  The filter is a prefix test against known prefixes, not against "roots this
  workflow does not build", so it does not generalise: a third demo/trainer tree
  will fail the same way. The durable fix is to invert the rule (allow-list
  `LeanMlir`/`Proofs`) rather than keep naming offenders; this keeps the two
  known cases explicit.

The blueprint text only cites core declarations — measurably so: every `\lean{}`
in content.tex is a `Proofs.*` or `Layer.*` name, and zero are `apps` or `demos`
— so the filtered import set is the honest one. If a blueprint chapter ever cites
a heavy-corpus or trainer declaration, add that module here explicitly rather
than re-importing the whole lib.

**Second argument: the dependency edges.** `lake exe blueprint-checkdecls
blueprint/lean_decls blueprint/lean_deps` also writes the real dependency edges among
the cited declarations (`dep name` per line), which `scripts/book/blueprint_uses.py --check`
holds the blueprint's `\uses{}` lines to. Same environment, one more walk; no second
import. -/

open Lake Lean

/-- The IR's denotations: one recursion over every StableHLO op, so each body names every
layer's semantics and VJP. A fold states `den` of ONE graph; the layers it actually uses
arrive through its proof. Walking into these bodies instead would give the MNIST-linear
fold edges from conv2d, depthwise, GELU, maxPool and SE. Matched by prefix, so the equation
lemmas and the `._f` auxiliary stop here too. -/
def walkBoundary : List Name := [`Proofs.StableHLO.den, `Proofs.StableHLO.denOp]

/-- Real dependency edges among the cited declarations: for each cited `n`, walk the
constants its type and value use, expanding through this project's own (`LeanMlir.*`)
helpers (not `walkBoundary`) and stopping at other cited declarations. Constructors (the
Bestiary's `Layer.*` catalogue rows) are not proofs and get no edges. Sorted, so the file
is stable across runs. -/
def writeDeps (env : Environment) (cited : Array Name) (out : System.FilePath) : IO Nat := do
  let citedSet := cited.foldl (·.insert ·) ({} : NameSet)
  let isProject (u : Name) : Bool :=
    match env.getModuleIdxFor? u with
    | some idx => (env.header.moduleNames[idx.toNat]!).toString.startsWith "LeanMlir"
    | none => false
  let mut lines : Array String := #[]
  for n in cited do
    match env.find? n with
    | none | some (.ctorInfo _) => continue
    | some _ => pure ()
    let mut visited : NameSet := {}
    let mut stack : Array Name := #[n]
    let mut deps : Array Name := #[]
    while stack.size > 0 do
      let c := stack.back!
      stack := stack.pop
      -- A project constant that is referenced but absent means the oleans in the
      -- environment were built from different sources (a stale `.lake/build`): the
      -- walk would silently stop here and the block would lose its edges. Say so —
      -- CI's fresh build is the authority, and locally the fix is `lake build`.
      let some ci := env.find? c
        | IO.eprintln s!"warning: {c} is referenced by {n} but not in the environment \
            (stale oleans?) — the dependency walk is truncated there"; continue
      for u in ci.getUsedConstantsAsSet.toArray do
        if visited.contains u then continue
        visited := visited.insert u
        if u != n && citedSet.contains u then deps := deps.push u
        else if isProject u && !walkBoundary.any (·.isPrefixOf u) then stack := stack.push u
    for d in deps.qsort (·.toString < ·.toString) do
      lines := lines.push s!"{d} {n}"
  IO.FS.writeFile out (String.intercalate "\n" lines.toList ++ "\n")
  return lines.size

unsafe def main (args : List String) : IO UInt32 := do
  unless args.length == 1 || args.length == 2 do
    println! "This command takes one or two arguments: the path to a file containing a \
      list of declarations to check, and optionally a path to write their dependency \
      edges to (read by scripts/book/blueprint_uses.py)."
    return 1
  let filename : System.FilePath := args[0]!
  unless ← filename.pathExists do
    println! "Could not find declaration list {filename}."
    return 1
  let (elanInstall?, leanInstall?, lakeInstall?) ← findInstall?
  let config ← MonadError.runEIO <| mkLoadConfig { elanInstall?, leanInstall?, lakeInstall? }
  let (ws?, log) ← (loadWorkspace config).run?
  log.replay (logger := .stderr)
  let some ws := ws? | return 1
  let coreLibs := ws.root.leanLibs.filter fun lib => lib.name != `CertsHeavy
  -- Filter ROOTS, not libs: a lib that ever mixes `apps` and `LeanMlir` roots
  -- still contributes the half this workflow actually builds.
  -- `demos` is here for the same reason as `apps` — see the header. Both are trainer/demo
  -- trees this workflow does not build.
  let unbuiltTrees : List Name := [`apps, `demos]
  let imports := coreLibs.flatMap fun lib =>
    lib.config.roots.filterMap fun module =>
      if unbuiltTrees.any (·.isPrefixOf module) then none else some { module }
  -- see comments in https://github.com/leanprover/lean4/pull/6325
  enableInitializersExecution
  let env ← Lean.importModules imports {}
  let cited := (← IO.FS.lines filename).filterMap fun line =>
    let line := line.trimAscii.toString
    if line.isEmpty then none else some line.toName
  let mut ok := true
  for n in cited do
    unless env.contains n do
      println! "{n} is missing."
      ok := false
  if let some (out : String) := args[1]? then
    let n ← writeDeps env cited out
    println! "wrote {n} dependency edges among {cited.size} declarations to {out}"
  return if ok then 0 else 1
