#!/usr/bin/env python3
"""Cross-check bestiary param counts against timm reference models.

Companion to `tests/test_bestiary_params.py`. That one is a drift
detector (does our count match yesterday's?); this one is a
correctness spot-check against an independent reference (does our
count match what timm thinks the architecture should be?).

For each entry in `tests/bestiary_timm_mapping.py` with a timm name,
instantiate the timm model and sum its `model.parameters()` counts,
then compare to the count our bestiary binary emits (read from
`tests/bestiary_params.yml`). Writes a markdown report at
`tests/bestiary_timm_report.md`.

Heavy deps (torch, torchvision, timm) — not in the project's main
`.venv`. Intended to be run against a separate venv; takes the python
path as the first argv, or looks for `/tmp/timm-venv/bin/python`.

Usage:
  tests/verify_bestiary_timm.py [path/to/timm-python]

Exit 0 always — this is a report generator, not a gate. Scan the
report for rows with large deltas when you want to check what our
specs look like vs the rest of the field.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GOLDEN = REPO / "tests" / "bestiary_params.yml"
REPORT = REPO / "tests" / "bestiary_timm_report.md"

# ⭐ The PINNED reference env (`requirements-timm-lock.txt`), not a scratch venv in /tmp. timm is
# the specification the ImageNet recipes are implemented against, so which timm has to survive a
# reboot. ⚠ It is deliberately NOT the main `.venv`: timm drags in torch, and torch pulls
# `nvidia-cudnn-cu13`, which overwrites the pinned cu12 cuDNN in place and breaks every JAX conv.
DEFAULT_TIMM_PY = str(REPO / ".venv-timm" / "bin" / "python")


def load_golden(path: Path) -> dict[str, dict[str, int]]:
    """Same minimal YAML parser as test_bestiary_params.py. See that file."""
    out: dict[str, dict[str, int]] = {}
    current: str | None = None
    for line in path.read_text().splitlines():
        stripped = line.split("#", 1)[0].rstrip()
        if not stripped:
            continue
        if not stripped.startswith(" "):
            current = stripped.rstrip(":")
            out.setdefault(current, {})
            continue
        m = re.match(r'\s+"(.+)":\s*(\d+)\s*$', line.split("#", 1)[0])
        if m and current is not None:
            out[current][m.group(1)] = int(m.group(2))
    return out


TIMM_QUERY_SCRIPT = r"""
import json, sys, timm, torch

name = sys.argv[1]
num_classes = int(sys.argv[2])
try:
    m = timm.create_model(name, pretrained=False, num_classes=num_classes)
    total = sum(p.numel() for p in m.parameters())
    print(json.dumps({"ok": True, "params": total}))
except Exception as e:
    print(json.dumps({"ok": False, "error": repr(e)}))
"""


def query_timm(python: str, model_name: str, num_classes: int) -> dict:
    r = subprocess.run(
        [python, "-c", TIMM_QUERY_SCRIPT, model_name, str(num_classes)],
        capture_output=True, text=True, timeout=120,
    )
    if r.returncode != 0:
        return {"ok": False, "error": f"subprocess exit {r.returncode}: {r.stderr[:500]}"}
    import json
    try:
        return json.loads(r.stdout.strip().splitlines()[-1])
    except Exception as e:
        return {"ok": False, "error": f"parse: {e}; stdout={r.stdout[:500]}"}


def main() -> int:
    timm_python = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TIMM_PY
    if not Path(timm_python).exists():
        print(f"timm-python not found: {timm_python}", file=sys.stderr)
        print("Create a venv with `torch torchvision timm`, pass its bin/python as argv[1].", file=sys.stderr)
        return 2

    from tests.bestiary_timm_mapping import MAPPING

    golden = load_golden(GOLDEN)

    rows: list[tuple[str, str, str, int | None, int | None, str]] = []
    for (bin_name, variant), timm_name in MAPPING.items():
        our_params = golden.get(bin_name, {}).get(variant)
        if our_params is None:
            rows.append((bin_name, variant, timm_name or "(n/a)", None, None, "variant missing from golden"))
            continue
        if timm_name is None:
            rows.append((bin_name, variant, "(no timm equivalent)", our_params, None, "no timm counterpart"))
            continue
        result = query_timm(timm_python, timm_name, 1000)
        if not result.get("ok"):
            rows.append((bin_name, variant, timm_name, our_params, None, result.get("error", "?")))
            continue
        timm_params = result["params"]
        delta_pct = (our_params - timm_params) / timm_params * 100
        note = f"{delta_pct:+.2f}% vs timm"
        rows.append((bin_name, variant, timm_name, our_params, timm_params, note))

    lines = [
        "# Bestiary vs timm — param-count cross-check",
        "",
        "Generated by `tests/verify_bestiary_timm.py`. Not a CI gate — a",
        "reference check. Large Δ% rows are worth investigating; small ones",
        "likely reflect bestiary-level simplifications (LRN omission, fused",
        "BN, classifier head choices) which are by design.",
        "",
        "| bestiary binary | variant | timm model | ours | timm | Δ% or note |",
        "|---|---|---|---:|---:|---|",
    ]
    for bin_name, variant, timm_name, ours, timm_p, note in rows:
        ours_s = f"{ours:,}" if ours is not None else "—"
        timm_s = f"{timm_p:,}" if timm_p is not None else "—"
        lines.append(f"| `{bin_name}` | {variant} | `{timm_name}` | {ours_s} | {timm_s} | {note} |")
    lines.append("")

    REPORT.write_text("\n".join(lines))
    print(f"wrote {REPORT}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    # Allow running from repo root via `python3 tests/verify_bestiary_timm.py`
    sys.path.insert(0, str(REPO))
    sys.exit(main())
