import LeanMlir.Proofs.LipschitzCertInstance

/-! # Interval bound propagation (IBP), sound and kernel-checkable

The `L∞` counterpart of the Lipschitz scorecard: push an axis-aligned box
through the network (sign-split interval arithmetic for the bias-free dense
layers, endpoint `max` for ReLU) and certify the prediction whenever the
output boxes separate — `denseHi … j < denseLo … y` for every `j ≠ y` gives
`∀ δ, (∀ i, |δ i| ≤ ε) → argmax fixed` (`ibp2_certified_at_eps`).

Why this matters here: IBP is LINEAR in width (two interval dots per neuron),
where the Gram/Schatten and LipSDP certificates are quadratic-to-cubic — this
is the certificate that scales past the h=16 wall to canonical widths. And
the perturbation model is the literature-standard pixel `L∞` ball, stated
coordinatewise (`∀ i, |δ i| ≤ ε`) with no norm-instance games.

The first layer sees a UNIFORM box `x ∓ ε`, where the interval image
collapses to `⟨w, x⟩ ∓ ε·‖w‖₁` (`denseLo_uniform`/`denseHi_uniform`) — so
the generated files reuse the scorecard's kernel `dotZ` facts for `⟨w, x⟩`
and one `absSumZ` kernel fact per row for `‖w‖₁` (`ListDot.lean`).

Everything is elementary and 3-axiom clean; instance files:
`LipschitzCertScorecardIBP*.lean` (generated by
`scripts/lipschitz_cert_scorecard_ibp.py`). -/

namespace Proofs
namespace LipschitzCertDemo

open scoped BigOperators

-- ════════════════════════════════════════════════════════════════
-- § Interval images of the layer maps
-- ════════════════════════════════════════════════════════════════

/-- Sign-split LOWER image of a bias-free dense layer on the box `[lo, hi]`:
    positive weights pull from `lo`, negative from `hi`. -/
noncomputable def denseLo {m n : ℕ} (W : Fin m → Fin n → ℝ) (lo hi : Fin n → ℝ) :
    Fin m → ℝ :=
  fun k => ∑ j, if 0 ≤ W k j then W k j * lo j else W k j * hi j

/-- Sign-split UPPER image. -/
noncomputable def denseHi {m n : ℕ} (W : Fin m → Fin n → ℝ) (lo hi : Fin n → ℝ) :
    Fin m → ℝ :=
  fun k => ∑ j, if 0 ≤ W k j then W k j * hi j else W k j * lo j

/-- ReLU box endpoints. -/
noncomputable def reluLo {n : ℕ} (lo : Fin n → ℝ) : Fin n → ℝ := fun j => max (lo j) 0
noncomputable def reluHi {n : ℕ} (hi : Fin n → ℝ) : Fin n → ℝ := fun j => max (hi j) 0

-- ════════════════════════════════════════════════════════════════
-- § Soundness
-- ════════════════════════════════════════════════════════════════

/-- `f` is *certified at `L∞` radius ε* on input `x` with class `y`: every
    coordinatewise-bounded perturbation keeps `y` the strict argmax. The
    `L∞` peer of `CertifiedAt` (`LipschitzCertScorecard.lean`). -/
def CertifiedAtLinf {n k : ℕ} (f : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin k))
    (ε : ℝ) (x : EuclideanSpace ℝ (Fin n)) (y : Fin k) : Prop :=
  ∀ δ : EuclideanSpace ℝ (Fin n), (∀ i, |δ i| ≤ ε) →
    ∀ j, j ≠ y → f (x + δ) j < f (x + δ) y

theorem denseLo_le {m n : ℕ} (W : Fin m → Fin n → ℝ) {lo hi : Fin n → ℝ}
    {x : EuclideanSpace ℝ (Fin n)} (hbox : ∀ j, lo j ≤ x j ∧ x j ≤ hi j) (k : Fin m) :
    denseLo W lo hi k ≤ denseE W x k := by
  rw [denseE_apply]
  refine Finset.sum_le_sum fun j _ => ?_
  by_cases h : 0 ≤ W k j
  · rw [if_pos h]
    exact mul_le_mul_of_nonneg_left (hbox j).1 h
  · rw [if_neg h]
    exact mul_le_mul_of_nonpos_left (hbox j).2 (le_of_not_ge h)

theorem le_denseHi {m n : ℕ} (W : Fin m → Fin n → ℝ) {lo hi : Fin n → ℝ}
    {x : EuclideanSpace ℝ (Fin n)} (hbox : ∀ j, lo j ≤ x j ∧ x j ≤ hi j) (k : Fin m) :
    denseE W x k ≤ denseHi W lo hi k := by
  rw [denseE_apply]
  refine Finset.sum_le_sum fun j _ => ?_
  by_cases h : 0 ≤ W k j
  · rw [if_pos h]
    exact mul_le_mul_of_nonneg_left (hbox j).2 h
  · rw [if_neg h]
    exact mul_le_mul_of_nonpos_left (hbox j).1 (le_of_not_ge h)

/-- ReLU maps the box `[lo, hi]` into `[reluLo lo, reluHi hi]`. -/
theorem relu_box {n : ℕ} {lo hi : Fin n → ℝ} {u : EuclideanSpace ℝ (Fin n)}
    (hbox : ∀ j, lo j ≤ u j ∧ u j ≤ hi j) (j : Fin n) :
    reluLo lo j ≤ reluE u j ∧ reluE u j ≤ reluHi hi j := by
  rw [reluE_apply]
  exact ⟨max_le_max_right 0 (hbox j).1, max_le_max_right 0 (hbox j).2⟩

-- ════════════════════════════════════════════════════════════════
-- § The uniform first layer: `x ∓ ε` collapses to `⟨w,x⟩ ∓ ε·‖w‖₁`
-- ════════════════════════════════════════════════════════════════

theorem denseLo_uniform {m n : ℕ} (W : Fin m → Fin n → ℝ)
    (x : EuclideanSpace ℝ (Fin n)) (ε : ℝ) (k : Fin m) :
    denseLo W (fun j => x j - ε) (fun j => x j + ε) k
      = (∑ j, W k j * x j) - ε * ∑ j, |W k j| := by
  unfold denseLo
  rw [Finset.mul_sum, ← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl fun j _ => ?_
  by_cases h : 0 ≤ W k j
  · rw [if_pos h, abs_of_nonneg h]; ring
  · rw [if_neg h, abs_of_neg (lt_of_not_ge h)]; ring

theorem denseHi_uniform {m n : ℕ} (W : Fin m → Fin n → ℝ)
    (x : EuclideanSpace ℝ (Fin n)) (ε : ℝ) (k : Fin m) :
    denseHi W (fun j => x j - ε) (fun j => x j + ε) k
      = (∑ j, W k j * x j) + ε * ∑ j, |W k j| := by
  unfold denseHi
  rw [Finset.mul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun j _ => ?_
  by_cases h : 0 ≤ W k j
  · rw [if_pos h, abs_of_nonneg h]; ring
  · rw [if_neg h, abs_of_neg (lt_of_not_ge h)]; ring

/-- The 2-layer LOWER box endpoint, evaluated: outer sign-split over the
    ReLU'd first-layer uniform box, with the inner sums left as `⟨w,x⟩` and
    `Σ|w|` (which instance files rewrite via their `hpre`/`absSumZ` data —
    the 784-sums must be REWRITTEN, never unfolded). -/
theorem denseLo2_eval {n h k : ℕ} (W1 : Fin h → Fin n → ℝ) (W2 : Fin k → Fin h → ℝ)
    (x : EuclideanSpace ℝ (Fin n)) (ε : ℝ) (c : Fin k) :
    denseLo W2 (reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)))
               (reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε))) c
      = ∑ t, if 0 ≤ W2 c t
             then W2 c t * max ((∑ j, W1 t j * x j) - ε * ∑ j, |W1 t j|) 0
             else W2 c t * max ((∑ j, W1 t j * x j) + ε * ∑ j, |W1 t j|) 0 := by
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [show reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)) t
        = max (denseLo W1 (fun i => x i - ε) (fun i => x i + ε) t) 0 from rfl,
      show reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε)) t
        = max (denseHi W1 (fun i => x i - ε) (fun i => x i + ε) t) 0 from rfl,
      denseLo_uniform, denseHi_uniform]

/-- The 2-layer UPPER box endpoint, evaluated (sibling of `denseLo2_eval`). -/
theorem denseHi2_eval {n h k : ℕ} (W1 : Fin h → Fin n → ℝ) (W2 : Fin k → Fin h → ℝ)
    (x : EuclideanSpace ℝ (Fin n)) (ε : ℝ) (c : Fin k) :
    denseHi W2 (reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)))
               (reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε))) c
      = ∑ t, if 0 ≤ W2 c t
             then W2 c t * max ((∑ j, W1 t j * x j) + ε * ∑ j, |W1 t j|) 0
             else W2 c t * max ((∑ j, W1 t j * x j) - ε * ∑ j, |W1 t j|) 0 := by
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [show reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)) t
        = max (denseLo W1 (fun i => x i - ε) (fun i => x i + ε) t) 0 from rfl,
      show reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε)) t
        = max (denseHi W1 (fun i => x i - ε) (fun i => x i + ε) t) 0 from rfl,
      denseLo_uniform, denseHi_uniform]

-- ════════════════════════════════════════════════════════════════
-- § The two-layer capstone: box separation ⇒ L∞ certificate
-- ════════════════════════════════════════════════════════════════

/-- **IBP `L∞` certificate for `dense ∘ relu ∘ dense`.** If the propagated
    output boxes separate — the upper bound of every wrong logit is strictly
    below the lower bound of the true one on the box `x ∓ ε` — then EVERY
    perturbation with `|δ i| ≤ ε` coordinatewise keeps class `y` the strict
    argmax. Boxes are data; separation is finitely many rational comparisons. -/
theorem ibp2_certified_at_eps {n h k : ℕ}
    (W1 : Fin h → Fin n → ℝ) (W2 : Fin k → Fin h → ℝ)
    {x : EuclideanSpace ℝ (Fin n)} {ε : ℝ} {y : Fin k}
    (hcmp : ∀ j, j ≠ y →
      denseHi W2 (reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)))
                 (reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε))) j
        < denseLo W2 (reluLo (denseLo W1 (fun i => x i - ε) (fun i => x i + ε)))
                     (reluHi (denseHi W1 (fun i => x i - ε) (fun i => x i + ε))) y)
    (δ : EuclideanSpace ℝ (Fin n)) (hδ : ∀ i, |δ i| ≤ ε) :
    ∀ j, j ≠ y → (denseE W2 ∘ reluE ∘ denseE W1) (x + δ) j
        < (denseE W2 ∘ reluE ∘ denseE W1) (x + δ) y := by
  intro j hj
  set lo0 : Fin n → ℝ := fun i => x i - ε with hlo0
  set hi0 : Fin n → ℝ := fun i => x i + ε with hhi0
  -- the perturbed input lives in the box
  have hbox0 : ∀ i, lo0 i ≤ (x + δ) i ∧ (x + δ) i ≤ hi0 i := by
    intro i
    have h1 := abs_le.mp (hδ i)
    have hxi : (x + δ) i = x i + δ i := rfl
    constructor <;> · rw [hxi]; simp only [hlo0, hhi0]; linarith [h1.1, h1.2]
  -- layer 1 box
  have hbox1 : ∀ t, denseLo W1 lo0 hi0 t ≤ denseE W1 (x + δ) t ∧
      denseE W1 (x + δ) t ≤ denseHi W1 lo0 hi0 t :=
    fun t => ⟨denseLo_le W1 hbox0 t, le_denseHi W1 hbox0 t⟩
  -- ReLU box
  have hbox2 : ∀ t, reluLo (denseLo W1 lo0 hi0) t ≤ reluE (denseE W1 (x + δ)) t ∧
      reluE (denseE W1 (x + δ)) t ≤ reluHi (denseHi W1 lo0 hi0) t :=
    fun t => relu_box hbox1 t
  -- layer 2 bounds at y and j
  have hy : denseLo W2 (reluLo (denseLo W1 lo0 hi0)) (reluHi (denseHi W1 lo0 hi0)) y
      ≤ denseE W2 (reluE (denseE W1 (x + δ))) y :=
    denseLo_le W2 hbox2 y
  have hjb : denseE W2 (reluE (denseE W1 (x + δ))) j
      ≤ denseHi W2 (reluLo (denseLo W1 lo0 hi0)) (reluHi (denseHi W1 lo0 hi0)) j :=
    le_denseHi W2 hbox2 j
  have hc := hcmp j hj
  show denseE W2 (reluE (denseE W1 (x + δ))) j < denseE W2 (reluE (denseE W1 (x + δ))) y
  linarith [hy, hjb, hc]

end LipschitzCertDemo
end Proofs
