"""ResNet-34 — Generated by Lean 4 → JAX
Architecture: Conv(3→64,7x7/2)+BN → Pool(3x3) → Res3(64→64,s1) → Res4(64→128,s2) → Res6(128→256,s2) → Res3(256→512,s2) → GAP → 512→10
Parameters: 21289802
Matching: Convolutional Neural Networks with Swift for TensorFlow
"""
import jax
import jax.numpy as jnp
from jax import random, jit, value_and_grad
from jax.sharding import Mesh, NamedSharding, PartitionSpec as P
import numpy as np
import struct, os, time, json

# ═══════════════════════════════════════════════════════════════════════
#  Imagenette data loading. The phase-3 preprocessor stores TRAIN at
#  256×256 (so the Lean trainer's random-crop aug can pull a 224×224
#  window per step) but stores VAL at 224×224 already (no aug at
#  eval). The loader auto-detects by checking the per-record byte
#  count from the file size + count header. Both paths center-crop
#  to 224×224 + ImageNet-normalize.
# ═══════════════════════════════════════════════════════════════════════

def load_imagenette(path):
    DST = 224
    with open(path, "rb") as f:
        count = struct.unpack("<I", f.read(4))[0]
        data = np.frombuffer(f.read(), dtype=np.uint8)
    record_size = len(data) // count
    # Each record is 1-byte label + 3*SRC*SRC image bytes.
    src_pixels = (record_size - 1) // 3
    SRC = int(np.sqrt(src_pixels))
    assert SRC * SRC * 3 + 1 == record_size, (record_size, SRC, path)
    off = (SRC - DST) // 2
    data = data.reshape(count, record_size)
    labels = data[:, 0].astype(np.int32)
    images = data[:, 1:].astype(np.float32) / 255.0
    images = images.reshape(count, 3, SRC, SRC)
    if SRC != DST:
        images = images[:, :, off:off+DST, off:off+DST]
    mean = np.array([0.485, 0.456, 0.406]).reshape(1, 3, 1, 1)
    std = np.array([0.229, 0.224, 0.225]).reshape(1, 3, 1, 1)
    images = ((images - mean) / std).reshape(count, -1)
    return images, labels

# Matmul compute dtype (mixed precision). bf16 casts matmul operands and
# returns fp32; master weights / LayerNorm / softmax stay fp32.
# Helps matmul-bound nets (ViT/transformers ~2.7-3.6x on gfx1100).
DT = jnp.float32
def mm(a, b):
    return (a.astype(DT) @ b.astype(DT)).astype(jnp.float32)

# Conv compute dtype. Independent of DT: convs stay fp32 on MIOpen/gfx1100
# (bf16 conv is slower there), but opt into bf16 on cuDNN/CUDA where tensor
# cores make bf16 conv ~1.6x faster. CONV_DT=float32 -> casts are no-ops.
CONV_DT = jnp.float32
def convdt(x):
    return x.astype(CONV_DT)

# ═══════════════════════════════════════════════════════════════════════
#  Conv / Pool helpers
# ═══════════════════════════════════════════════════════════════════════

def conv2d(x, w, b, padding='SAME', stride=(1,1)):
    x = jax.lax.conv_general_dilated(convdt(x), convdt(w), stride, padding,
          dimension_numbers=('NCHW', 'OIHW', 'NCHW')).astype(jnp.float32)
    return x + b.reshape(1, -1, 1, 1)

def max_pool2d(x, size=2, stride=2):
    return jax.lax.reduce_window(x, -jnp.inf, jax.lax.max,
             (1, 1, size, size), (1, 1, stride, stride), 'SAME')

def conv_bn(x, w, gamma, beta, stride=(1,1), padding='SAME'):
    x = jax.lax.conv_general_dilated(convdt(x), convdt(w), stride, padding,
          dimension_numbers=('NCHW', 'OIHW', 'NCHW')).astype(jnp.float32)
    # Batch normalization: mean/var over (N, H, W) per channel,
    # matching LeanMlir.MlirCodegen.emitConvBn's 2-step reduction
    # across dims [2,3] then [0] (divisor b*oH*oW).
    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)
    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)
    x = (x - mean) / jnp.sqrt(var + 1e-5)
    return x * gamma.reshape(1, -1, 1, 1) + beta.reshape(1, -1, 1, 1)

def basic_block(params, x, idx):
    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2])
    out = jax.nn.relu(out)
    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2])
    return jax.nn.relu(out + x)

def basic_block_down(params, x, idx, stride):
    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2], stride=(stride,stride))
    out = jax.nn.relu(out)
    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2])
    shortcut = conv_bn(x, params[idx+2][0], params[idx+2][1], params[idx+2][2], stride=(stride,stride))
    return jax.nn.relu(out + shortcut)

def global_avg_pool(x):
    return jnp.mean(x, axis=(2, 3))

# ═══════════════════════════════════════════════════════════════════════
#  Multi-GPU data parallelism
# ═══════════════════════════════════════════════════════════════════════

devices = jax.devices()
n_devices = len(devices)
mesh = Mesh(np.array(devices), axis_names=('batch',))
data_sharding = NamedSharding(mesh, P('batch'))
replicated_sharding = NamedSharding(mesh, P())

# ═══════════════════════════════════════════════════════════════════════
#  Model (from Lean spec)
# ═══════════════════════════════════════════════════════════════════════

def init_params(key):
    """Xavier/Kaiming uniform init."""
    params = []
    # ConvBN 3→64, 7x7
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 3136)
    params.append((random.uniform(k_, (64, 3, 7, 7), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv1 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv2 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv1 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv2 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv1 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock conv2 64→64
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 576)
    params.append((random.uniform(k_, (64, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(64), jnp.zeros(64)))
    # ResBlock ↓ conv1 64→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 64, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock ↓ conv2 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock ↓ proj 64→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 128)
    params.append((random.uniform(k_, (128, 64, 1, 1), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv1 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv2 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv1 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv2 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv1 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock conv2 128→128
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 1152)
    params.append((random.uniform(k_, (128, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(128), jnp.zeros(128)))
    # ResBlock ↓ conv1 128→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 128, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock ↓ conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock ↓ proj 128→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 256)
    params.append((random.uniform(k_, (256, 128, 1, 1), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv1 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv1 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv1 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv1 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv1 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock conv2 256→256
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 2304)
    params.append((random.uniform(k_, (256, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(256), jnp.zeros(256)))
    # ResBlock ↓ conv1 256→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 256, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock ↓ conv2 512→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 512, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock ↓ proj 256→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 512)
    params.append((random.uniform(k_, (512, 256, 1, 1), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock conv1 512→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 512, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock conv2 512→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 512, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock conv1 512→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 512, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # ResBlock conv2 512→512
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 4608)
    params.append((random.uniform(k_, (512, 512, 3, 3), minval=-scale, maxval=scale),
                   jnp.ones(512), jnp.zeros(512)))
    # Dense 512→10
    key, k_ = random.split(key)
    scale = jnp.sqrt(6.0 / 522)
    params.append((random.uniform(k_, (10, 512), minval=-scale, maxval=scale), jnp.zeros(10)))
    return params

def init_params_from_file(path):
    buf = np.frombuffer(open(path, 'rb').read(), dtype=np.float32)
    idx = 0
    params = []
    # convBn 3→64, 7×7 (W, γ, β)
    W = jnp.array(buf[idx:idx+9408].reshape(64, 3, 7, 7)); idx += 9408
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[0] conv1 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[0] conv2 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[1] conv1 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[1] conv2 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[2] conv1 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[2] conv2 64→64 (W, γ, β)
    W = jnp.array(buf[idx:idx+36864].reshape(64, 64, 3, 3)); idx += 36864
    gamma = jnp.array(buf[idx:idx+64]); idx += 64
    beta = jnp.array(buf[idx:idx+64]); idx += 64
    params.append((W, gamma, beta))
    # resBlock[0] conv1 64→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+73728].reshape(128, 64, 3, 3)); idx += 73728
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[0] conv2 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[0] proj 64→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+8192].reshape(128, 64, 1, 1)); idx += 8192
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[1] conv1 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[1] conv2 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[2] conv1 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[2] conv2 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[3] conv1 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[3] conv2 128→128 (W, γ, β)
    W = jnp.array(buf[idx:idx+147456].reshape(128, 128, 3, 3)); idx += 147456
    gamma = jnp.array(buf[idx:idx+128]); idx += 128
    beta = jnp.array(buf[idx:idx+128]); idx += 128
    params.append((W, gamma, beta))
    # resBlock[0] conv1 128→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+294912].reshape(256, 128, 3, 3)); idx += 294912
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[0] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[0] proj 128→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+32768].reshape(256, 128, 1, 1)); idx += 32768
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[1] conv1 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[1] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[2] conv1 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[2] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[3] conv1 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[3] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[4] conv1 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[4] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[5] conv1 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[5] conv2 256→256 (W, γ, β)
    W = jnp.array(buf[idx:idx+589824].reshape(256, 256, 3, 3)); idx += 589824
    gamma = jnp.array(buf[idx:idx+256]); idx += 256
    beta = jnp.array(buf[idx:idx+256]); idx += 256
    params.append((W, gamma, beta))
    # resBlock[0] conv1 256→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+1179648].reshape(512, 256, 3, 3)); idx += 1179648
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[0] conv2 512→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+2359296].reshape(512, 512, 3, 3)); idx += 2359296
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[0] proj 256→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+131072].reshape(512, 256, 1, 1)); idx += 131072
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[1] conv1 512→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+2359296].reshape(512, 512, 3, 3)); idx += 2359296
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[1] conv2 512→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+2359296].reshape(512, 512, 3, 3)); idx += 2359296
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[2] conv1 512→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+2359296].reshape(512, 512, 3, 3)); idx += 2359296
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # resBlock[2] conv2 512→512 (W, γ, β)
    W = jnp.array(buf[idx:idx+2359296].reshape(512, 512, 3, 3)); idx += 2359296
    gamma = jnp.array(buf[idx:idx+512]); idx += 512
    beta = jnp.array(buf[idx:idx+512]); idx += 512
    params.append((W, gamma, beta))
    # dense 512 → 10
    W = jnp.array(buf[idx:idx+5120].reshape(512, 10).T); idx += 5120
    b = jnp.array(buf[idx:idx+10]); idx += 10
    params.append((W, b))
    return params

def params_to_file(params, path):
    """Mirror of init_params_from_file. Walks the JAX `params`
    list in spec order and serializes each tensor as float32 bytes
    in the same on-disk byte layout the phase-3 Lean trainer uses.
    Drop the resulting .bin into TrainConfig.bootstrapBackbone.
    """
    idx = 0
    f = open(path, 'wb')
    # convBn 3→64, 7×7 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv1 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv2 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv1 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv2 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv1 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv2 64→64 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv1 64→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv2 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] proj 64→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv1 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv2 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv1 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv2 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[3] conv1 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[3] conv2 128→128 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv1 128→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] proj 128→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv1 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv1 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[3] conv1 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[3] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[4] conv1 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[4] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[5] conv1 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[5] conv2 256→256 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv1 256→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] conv2 512→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[0] proj 256→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv1 512→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[1] conv2 512→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv1 512→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # resBlock[2] conv2 512→512 (W, γ, β)
    W, gamma, beta = params[idx]; idx += 1
    f.write(np.asarray(W).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(gamma).astype(np.float32).flatten().tobytes())
    f.write(np.asarray(beta).astype(np.float32).flatten().tobytes())
    # dense 512 → 10
    W, b = params[idx]; idx += 1
    f.write(np.asarray(W).T.astype(np.float32).flatten().tobytes())
    f.write(np.asarray(b).astype(np.float32).flatten().tobytes())
    f.close()
    print(f'saved {idx} param-groups to {path} ({os.path.getsize(path)} bytes)')

def forward(params, x, drop_key=None):
    x = x.reshape(-1, 3, 224, 224)
    x = conv_bn(x, params[0][0], params[0][1], params[0][2], stride=(2,2), padding='SAME')
    x = jax.nn.relu(x)
    x = max_pool2d(x, 3, 2)
    x = basic_block(params, x, 1)
    x = basic_block(params, x, 3)
    x = basic_block(params, x, 5)
    x = basic_block_down(params, x, 7, 2)
    x = basic_block(params, x, 10)
    x = basic_block(params, x, 12)
    x = basic_block(params, x, 14)
    x = basic_block_down(params, x, 16, 2)
    x = basic_block(params, x, 19)
    x = basic_block(params, x, 21)
    x = basic_block(params, x, 23)
    x = basic_block(params, x, 25)
    x = basic_block(params, x, 27)
    x = basic_block_down(params, x, 29, 2)
    x = basic_block(params, x, 32)
    x = basic_block(params, x, 34)
    x = global_avg_pool(x)
    x = mm(x, params[36][0].T) + params[36][1]
    return x

def loss_fn(params, x, y, drop_key=None):
    logits = forward(params, x, drop_key)
    log_probs = jax.nn.log_softmax(logits, axis=-1)
    # y is int32 [B] (hard labels) or float [B,NC] (soft labels, mixup/cutmix).
    # y.ndim is static at trace time, so this branch is jit-safe.
    if y.ndim == 1:
        tgt = jax.nn.one_hot(y, 10)
    else:
        tgt = y
    return -jnp.mean(jnp.sum(log_probs * tgt, axis=-1))

def augment_batch(x, rng):
    """Random crop (numpy, CPU): pad 224→252, crop back to 224x224."""
    x = x.reshape(-1, 3, 224, 224)
    x = np.pad(x, ((0,0), (0,0), (14,14), (14,14)))
    top = rng.randint(0, 29)
    left = rng.randint(0, 29)
    x = x[:, :, top:top+224, left:left+224]
    return x.reshape(x.shape[0], -1)

# ═══════════════════════════════════════════════════════════════════════
#  Training  (Adam + cosine LR)
# ═══════════════════════════════════════════════════════════════════════

LR = 0.001000
WD = 0.000100

@jit
def train_step(params, opt_state, x, y, lr, drop_key=None):
    loss, grads = value_and_grad(loss_fn)(params, x, y, drop_key)
    m, v, t = opt_state
    t = t + 1
    m = jax.tree.map(lambda mi, g: 0.9 * mi + 0.1 * g, m, grads)
    v = jax.tree.map(lambda vi, g: 0.999 * vi + 0.001 * g * g, v, grads)
    mc = jax.tree.map(lambda mi: mi / (1 - 0.9 ** t), m)
    vc = jax.tree.map(lambda vi: vi / (1 - 0.999 ** t), v)
    params = jax.tree.map(lambda p, mi, vi: p - lr * (mi / (jnp.sqrt(vi) + 1e-8) + WD * p), params, mc, vc)
    return params, (m, v, t), loss

@jit
def eval_batch(params, x, y):
    logits = forward(params, x)
    preds = jnp.argmax(logits, axis=-1)
    log_probs = jax.nn.log_softmax(logits, axis=-1)
    loss = -jnp.mean(jnp.sum(log_probs * jax.nn.one_hot(y, 10), axis=-1))
    correct1 = jnp.sum(preds == y)
    # top-5: jax.lax.top_k's indices are broken on ROCm/gfx1100 (garbage on
    # device, HIP error to host), so rank the true class instead — top-5 is
    # correct iff fewer than 5 classes have a strictly-greater logit.
    true_logit = jnp.take_along_axis(logits, y[:, None], axis=1)
    correct5 = jnp.sum(jnp.sum(logits > true_logit, axis=1) < 5)
    return correct1, correct5, loss

def evaluate(params, images, labels, batch_size=512):
    batch_size = (batch_size // n_devices) * n_devices or n_devices
    correct1 = 0
    correct5 = 0
    total_loss = 0.0
    n_batches = 0
    for i in range(0, len(images) - batch_size + 1, batch_size):
        c1, c5, l = eval_batch(params,
            jax.device_put(images[i:i+batch_size], data_sharding),
            jax.device_put(labels[i:i+batch_size], data_sharding))
        correct1 += int(c1)
        correct5 += int(c5)
        total_loss += float(l)
        n_batches += 1
    evaluated = n_batches * batch_size
    return correct1, correct5, evaluated, total_loss / max(n_batches, 1)

# ═══════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("ResNet-34 · Lean 4 → JAX")
    print("  " + "Conv(3→64,7x7/2)+BN → Pool(3x3) → Res3(64→64,s1) → Res4(64→128,s2) → Res6(128→256,s2) → Res3(256→512,s2) → GAP → 512→10")
    print()

    data_dir = "data/imagenette"
    print("Loading Imagenette …")
    train_images, train_labels = load_imagenette(os.path.join(data_dir, "train.bin"))
    test_images, test_labels = load_imagenette(os.path.join(data_dir, "val.bin"))
    print("  " + str(len(train_images)) + " train, " + str(len(test_images)) + " val, 224x224x3")

    BATCH_SIZE = (192 // n_devices) * n_devices or n_devices
    EPOCHS = 80
    print("lr=0.001000  batch_size=" + str(BATCH_SIZE) + " (" + str(n_devices) + " devices x " + str(BATCH_SIZE // n_devices) + ")  epochs=" + str(EPOCHS) + "  params=21289802")
    print("backend=" + str(jax.default_backend()) + "  devices=" + str(jax.devices()))
    print("Starting training...")

    _init_load = os.environ.get('LEAN_MLIR_INIT_LOAD')
    if _init_load:
        print(f'Loading phase-3 init from {_init_load}')
        params = init_params_from_file(_init_load)
    else:
        params = init_params(random.PRNGKey(314159))
    params = jax.device_put(params, replicated_sharding)
    rng = np.random.RandomState(42)
    opt_m = jax.tree.map(jnp.zeros_like, params)
    opt_v = jax.tree.map(jnp.zeros_like, params)
    opt_state = (opt_m, opt_v, jnp.float32(0))

    # Data stays on CPU; batches transferred to GPU on the fly

    # Trace emission (opt-in via LEAN_MLIR_TRACE_OUT env var). Matches
    # the phase-3 format so cross-phase diffs work with tests/diff_traces.py.
    _trace_path = os.environ.get('LEAN_MLIR_TRACE_OUT')
    _trace_f = open(_trace_path, 'w') if _trace_path else None
    if _trace_f:
        _hdr = {
            'kind': 'header', 'phase': 'phase2',
            'netspec_name': "ResNet-34",
            'config': {
                'lr': 0.001000,
                'batch_size': 192,
                'epochs': 80,
                'use_adam': True,
                'weight_decay': 0.000100,
                'cosine': True,
                'warmup_epochs': 3,
                'augment': True,
                'label_smoothing': 0.000000,
                'seed': 314159,
            },
            'total_params': 21289802,
            'dataset': 'imagenette',
            'emitter_version': '1',
        }
        _trace_f.write(json.dumps(_hdr) + '\n')
    _global_step = 0
    t0 = time.time()
    for epoch in range(EPOCHS):
        # Cosine LR schedule with warmup
        if epoch < 3:
            lr = jnp.float32(LR * (epoch + 1) / 3)
        else:
            lr = jnp.float32(LR * 0.5 * (1 + np.cos(np.pi * (epoch - 3) / (EPOCHS - 3))))
        if os.environ.get('LEAN_MLIR_NO_SHUFFLE'):
            shuf_images = train_images
            shuf_labels = train_labels
        else:
            perm = rng.permutation(len(train_images))
            shuf_images = train_images[perm]
            shuf_labels = train_labels[perm]
        # Random horizontal flip (data augmentation)
        flip = rng.random(len(shuf_images)) > 0.5
        imgs4d = shuf_images.reshape(-1, 3, 224, 224)
        imgs4d[flip] = imgs4d[flip, :, :, ::-1]
        shuf_images = imgs4d.reshape(len(shuf_images), -1)
        epoch_loss = 0.0
        n_batches = 0
        for i in range(0, len(train_images) - BATCH_SIZE + 1, BATCH_SIZE):
            batch = augment_batch(shuf_images[i:i+BATCH_SIZE].copy(), rng)
            x = jax.device_put(batch, data_sharding)
            y = jax.device_put(shuf_labels[i:i+BATCH_SIZE], data_sharding)
            params, opt_state, loss = train_step(params, opt_state, x, y, lr)
            epoch_loss += float(loss)
            n_batches += 1
            _global_step += 1
            if _trace_f:
                _trace_f.write(json.dumps({
                    'kind': 'step', 'step': _global_step, 'epoch': epoch,
                    'loss': float(loss), 'lr': float(lr),
                }) + '\n')

        correct1, correct5, total, test_loss = evaluate(params, test_images, test_labels)
        acc1 = correct1 / total
        acc5 = correct5 / total
        elapsed = time.time() - t0
        print("[Epoch " + str(epoch+1) + "] lr=" + str(round(float(lr), 6)) +
              " top1: " + str(correct1) + "/" + str(total) +
              " (" + str(round(acc1, 4)) + ")" +
              " top5: " + str(round(acc5, 4)) +
              " Loss: " + str(round(test_loss, 4)) +
              "  [" + str(round(elapsed, 1)) + "s]")

    print("")
    print("Done. Total time: " + str(round(time.time() - t0, 1)) + "s")
    if _trace_f: _trace_f.close()
