import LeanMlir.Types
import LeanMlir.Spec
/-! JAX code generator: emit Python training scripts from NetSpec. -/

namespace JaxCodegen

private def emitHeader (spec : NetSpec) : String :=
  "\"\"\"" ++ spec.name ++ " — Generated by Lean 4 → JAX\n" ++
  "Architecture: " ++ spec.archStr ++ "\n" ++
  "Parameters: " ++ toString spec.totalParams ++ "\n" ++
  "Matching: Convolutional Neural Networks with Swift for TensorFlow\n" ++
  "\"\"\"\n"

private def emitImports : String :=
  "import jax\n" ++
  "import jax.numpy as jnp\n" ++
  "from jax import random, jit, value_and_grad\n" ++
  "from jax.sharding import Mesh, NamedSharding, PartitionSpec as P\n" ++
  "import numpy as np\n" ++
  "import struct, os, time, json\n\n"

private def emitDataLoading (ds : DatasetKind) : String :=
  match ds with
  | .mnist =>
    "# ═══════════════════════════════════════════════════════════════════════\n" ++
    "#  MNIST data loading (raw IDX format)\n" ++
    "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
    "def load_mnist_images(path):\n" ++
    "    with open(path, \"rb\") as f:\n" ++
    "        magic, n, rows, cols = struct.unpack(\">4I\", f.read(16))\n" ++
    "        assert magic == 2051\n" ++
    "        return np.frombuffer(f.read(), dtype=np.uint8).reshape(n, rows * cols).astype(np.float32) / 255.0\n\n" ++
    "def load_mnist_labels(path):\n" ++
    "    with open(path, \"rb\") as f:\n" ++
    "        magic, n = struct.unpack(\">2I\", f.read(8))\n" ++
    "        assert magic == 2049\n" ++
    "        return np.frombuffer(f.read(), dtype=np.uint8).astype(np.int32)\n\n"
  | .cifar10 =>
    "# ═══════════════════════════════════════════════════════════════════════\n" ++
    "#  CIFAR-10 data loading (binary batch format)\n" ++
    "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
    "def load_cifar10_batch(path):\n" ++
    "    with open(path, \"rb\") as f:\n" ++
    "        data = np.frombuffer(f.read(), dtype=np.uint8)\n" ++
    "    n = len(data) // 3073\n" ++
    "    data = data.reshape(n, 3073)\n" ++
    "    labels = data[:, 0].astype(np.int32)\n" ++
    "    images = data[:, 1:].astype(np.float32) / 255.0\n" ++
    "    return images, labels\n\n" ++
    "def load_cifar10(data_dir):\n" ++
    "    train_imgs, train_lbls = [], []\n" ++
    "    for i in range(1, 6):\n" ++
    "        imgs, lbls = load_cifar10_batch(os.path.join(data_dir, \"data_batch_\" + str(i) + \".bin\"))\n" ++
    "        train_imgs.append(imgs)\n" ++
    "        train_lbls.append(lbls)\n" ++
    "    test_imgs, test_lbls = load_cifar10_batch(os.path.join(data_dir, \"test_batch.bin\"))\n" ++
    "    return np.concatenate(train_imgs), np.concatenate(train_lbls), test_imgs, test_lbls\n\n"
  | .imagenette =>
    "# ═══════════════════════════════════════════════════════════════════════\n" ++
    "#  Imagenette data loading (binary format: 224×224×3, CHW)\n" ++
    "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
    "def load_imagenette(path):\n" ++
    "    with open(path, \"rb\") as f:\n" ++
    "        count = struct.unpack(\"<I\", f.read(4))[0]\n" ++
    "        data = np.frombuffer(f.read(), dtype=np.uint8)\n" ++
    "    record_size = 1 + 224 * 224 * 3\n" ++
    "    data = data.reshape(count, record_size)\n" ++
    "    labels = data[:, 0].astype(np.int32)\n" ++
    "    images = data[:, 1:].astype(np.float32) / 255.0\n" ++
    "    # Normalize with ImageNet statistics (data is CHW)\n" ++
    "    images = images.reshape(count, 3, 224, 224)\n" ++
    "    mean = np.array([0.485, 0.456, 0.406]).reshape(1, 3, 1, 1)\n" ++
    "    std = np.array([0.229, 0.224, 0.225]).reshape(1, 3, 1, 1)\n" ++
    "    images = ((images - mean) / std).reshape(count, -1)\n" ++
    "    return images, labels\n\n"

private def emitHelpers (spec : NetSpec) : String := Id.run do
  let mut code := ""
  if spec.hasConv then
    code := code ++
      "# ═══════════════════════════════════════════════════════════════════════\n" ++
      "#  Conv / Pool helpers\n" ++
      "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
      "def conv2d(x, w, b, padding='SAME', stride=(1,1)):\n" ++
      "    x = jax.lax.conv_general_dilated(x, w, stride, padding,\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    return x + b.reshape(1, -1, 1, 1)\n\n"
  if spec.hasPool then
    code := code ++
      "def max_pool2d(x, size=2, stride=2):\n" ++
      "    return jax.lax.reduce_window(x, -jnp.inf, jax.lax.max,\n" ++
      "             (1, 1, size, size), (1, 1, stride, stride), 'SAME')\n\n"
  if spec.hasBn then
    code := code ++
      "def conv_bn(x, w, gamma, beta, stride=(1,1), padding='SAME'):\n" ++
      "    x = jax.lax.conv_general_dilated(x, w, stride, padding,\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    # Batch normalization: mean/var over (N, H, W) per channel,\n" ++
      "    # matching LeanMlir.MlirCodegen.emitConvBn's 2-step reduction\n" ++
      "    # across dims [2,3] then [0] (divisor b*oH*oW).\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    return x * gamma.reshape(1, -1, 1, 1) + beta.reshape(1, -1, 1, 1)\n\n"
  if spec.hasResidual then
    code := code ++
      "def basic_block(params, x, idx):\n" ++
      "    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2])\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2])\n" ++
      "    return jax.nn.relu(out + x)\n\n" ++
      "def basic_block_down(params, x, idx, stride):\n" ++
      "    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2], stride=(stride,stride))\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2])\n" ++
      "    shortcut = conv_bn(x, params[idx+2][0], params[idx+2][1], params[idx+2][2], stride=(stride,stride))\n" ++
      "    return jax.nn.relu(out + shortcut)\n\n"
  if spec.hasBottleneck then
    code := code ++
      "def bottleneck_block(params, x, idx):\n" ++
      "    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2])\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2])\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+2][0], params[idx+2][1], params[idx+2][2])\n" ++
      "    return jax.nn.relu(out + x)\n\n" ++
      "def bottleneck_block_down(params, x, idx, stride):\n" ++
      "    out = conv_bn(x, params[idx][0], params[idx][1], params[idx][2])\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+1][0], params[idx+1][1], params[idx+1][2], stride=(stride,stride))\n" ++
      "    out = jax.nn.relu(out)\n" ++
      "    out = conv_bn(out, params[idx+2][0], params[idx+2][1], params[idx+2][2])\n" ++
      "    shortcut = conv_bn(x, params[idx+3][0], params[idx+3][1], params[idx+3][2], stride=(stride,stride))\n" ++
      "    return jax.nn.relu(out + shortcut)\n\n"
  if spec.hasSeparable then
    code := code ++
      "def depthwise_conv(x, w, stride=(1,1), padding='SAME'):\n" ++
      "    return jax.lax.conv_general_dilated(x, w, stride, padding,\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'),\n" ++
      "          feature_group_count=x.shape[1])\n\n" ++
      "def sep_conv(x, dw, dw_g, dw_b, pw, pw_g, pw_b, stride=(1,1)):\n" ++
      "    \"\"\"Depthwise 3x3 + BN + ReLU6, then pointwise 1x1 + BN + ReLU6.\"\"\"\n" ++
      "    x = depthwise_conv(x, dw, stride=stride)\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * dw_g.reshape(1, -1, 1, 1) + dw_b.reshape(1, -1, 1, 1)\n" ++
      "    x = jnp.minimum(jax.nn.relu(x), 6.0)\n" ++
      "    x = jax.lax.conv_general_dilated(x, pw, (1,1), 'SAME',\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * pw_g.reshape(1, -1, 1, 1) + pw_b.reshape(1, -1, 1, 1)\n" ++
      "    return jnp.minimum(jax.nn.relu(x), 6.0)\n\n"
  if spec.hasInvertedResidual then
    code := code ++
      "def invres_block(params, x, idx, stride, expand, use_skip):\n" ++
      "    \"\"\"Inverted residual: expand 1x1 → depthwise 3x3 → project 1x1, + skip.\"\"\"\n" ++
      "    residual = x\n" ++
      "    i = idx\n" ++
      "    if expand > 1:\n" ++
      "        # Expand\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "        x = jnp.minimum(jax.nn.relu(x), 6.0)\n" ++
      "        i += 1\n" ++
      "    # Depthwise\n" ++
      "    x = depthwise_conv(x, params[i][0], stride=(stride,stride))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    x = jnp.minimum(jax.nn.relu(x), 6.0)\n" ++
      "    i += 1\n" ++
      "    # Project (linear, no activation)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    if use_skip:\n" ++
      "        x = x + residual\n" ++
      "    return x\n\n"
  if spec.hasMbConv || spec.layers.any fun | .mbConvV3 .. => true | _ => false then
    code := code ++
      "def swish(x):\n" ++
      "    return x * jax.nn.sigmoid(x)\n\n" ++
      "def hard_swish(x):\n" ++
      "    return x * jnp.minimum(jax.nn.relu(x + 3.0), 6.0) / 6.0\n\n" ++
      "def hard_sigmoid(x):\n" ++
      "    return jnp.minimum(jax.nn.relu(x + 3.0), 6.0) / 6.0\n\n"
  if spec.hasMbConv then
    code := code ++
      "def mbconv_block(params, x, idx, stride, expand, ksize, use_se):\n" ++
      "    \"\"\"MBConv: expand → depthwise → SE → project, with Swish.\"\"\"\n" ++
      "    residual = x\n" ++
      "    i = idx\n" ++
      "    if expand > 1:\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "        x = swish(x)\n" ++
      "        i += 1\n" ++
      "    # Depthwise conv\n" ++
      "    pad = ((ksize - 1) // 2, (ksize - 1) // 2)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (stride,stride), (pad,pad),\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'),\n" ++
      "          feature_group_count=x.shape[1])\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    x = swish(x)\n" ++
      "    i += 1\n" ++
      "    # Squeeze-and-Excitation\n" ++
      "    if use_se:\n" ++
      "        se = jnp.mean(x, axis=(2, 3), keepdims=True)\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = swish(se)\n" ++
      "        i += 1\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = jax.nn.sigmoid(se)\n" ++
      "        x = x * se\n" ++
      "        i += 1\n" ++
      "    # Project (linear)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    if residual.shape == x.shape and stride == 1:\n" ++
      "        x = x + residual\n" ++
      "    return x\n\n" ++
      "def fused_mbconv_block(params, x, idx, stride, expand, ksize, use_se):\n" ++
      "    \"\"\"Fused-MBConv: kxk conv (expand) → SE → 1x1 project, with Swish.\"\"\"\n" ++
      "    residual = x\n" ++
      "    i = idx\n" ++
      "    # Fused expand: kxk conv instead of 1x1 + depthwise\n" ++
      "    pad = ((ksize - 1) // 2, (ksize - 1) // 2)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (stride,stride), (pad,pad),\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    x = swish(x)\n" ++
      "    i += 1\n" ++
      "    # Squeeze-and-Excitation\n" ++
      "    if use_se:\n" ++
      "        se = jnp.mean(x, axis=(2, 3), keepdims=True)\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = swish(se)\n" ++
      "        i += 1\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = jax.nn.sigmoid(se)\n" ++
      "        x = x * se\n" ++
      "        i += 1\n" ++
      "    # Project (linear) — only if expand > 1\n" ++
      "    if expand > 1:\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    if residual.shape == x.shape and stride == 1:\n" ++
      "        x = x + residual\n" ++
      "    return x\n\n"
  if spec.layers.any fun | .mbConvV3 .. => true | _ => false then
    code := code ++
      "def mbconv_v3_block(params, x, idx, stride, expand_ch, ksize, use_se, use_hs):\n" ++
      "    \"\"\"MBConv v3: hard-swish/relu, hard-sigmoid SE.\"\"\"\n" ++
      "    act = hard_swish if use_hs else jax.nn.relu\n" ++
      "    residual = x\n" ++
      "    i = idx\n" ++
      "    ic = x.shape[1]\n" ++
      "    if expand_ch != ic:\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "        x = act(x)\n" ++
      "        i += 1\n" ++
      "    # Depthwise\n" ++
      "    pad = ((ksize - 1) // 2, (ksize - 1) // 2)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (stride,stride), (pad,pad),\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'),\n" ++
      "          feature_group_count=x.shape[1])\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    x = act(x)\n" ++
      "    i += 1\n" ++
      "    if use_se:\n" ++
      "        se = jnp.mean(x, axis=(2, 3), keepdims=True)\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = jax.nn.relu(se)\n" ++
      "        i += 1\n" ++
      "        se = jax.lax.conv_general_dilated(se, params[i][0], (1,1), 'SAME',\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "        se = se + params[i][1].reshape(1, -1, 1, 1)\n" ++
      "        se = hard_sigmoid(se)\n" ++
      "        x = x * se\n" ++
      "        i += 1\n" ++
      "    # Project (linear)\n" ++
      "    x = jax.lax.conv_general_dilated(x, params[i][0], (1,1), 'SAME',\n" ++
      "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n" ++
      "    mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "    x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "    x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "    if residual.shape == x.shape and stride == 1:\n" ++
      "        x = x + residual\n" ++
      "    return x\n\n"
  if spec.layers.any fun | .uib .. => true | _ => false then
    code := code ++
      "def uib_block(params, x, idx, stride, pre_dw_k, post_dw_k):\n" ++
      "    \"\"\"Universal Inverted Bottleneck: optional DW → expand 1x1 → optional DW → project 1x1.\"\"\"\n" ++
      "    residual = x\n" ++
      "    i = idx\n" ++
      "    # Optional pre-depthwise\n" ++
      "    if pre_dw_k > 0:\n" ++
      "        pad = ((pre_dw_k - 1) // 2, (pre_dw_k - 1) // 2)\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (stride,stride), (pad,pad),\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'),\n" ++
      "              feature_group_count=x.shape[1])\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "        x = jax.nn.relu(x)\n" ++
      "        i += 1\n" ++
      "        stride = 1  # stride consumed by pre-DW\n" ++
      "    # Expand 1x1\n" ++
      "    x = conv_bn(x, params[i][0], params[i][1], params[i][2])\n" ++
      "    x = jax.nn.relu(x)\n" ++
      "    i += 1\n" ++
      "    # Optional post-depthwise\n" ++
      "    if post_dw_k > 0:\n" ++
      "        pad = ((post_dw_k - 1) // 2, (post_dw_k - 1) // 2)\n" ++
      "        x = jax.lax.conv_general_dilated(x, params[i][0], (stride,stride), (pad,pad),\n" ++
      "              dimension_numbers=('NCHW', 'OIHW', 'NCHW'),\n" ++
      "              feature_group_count=x.shape[1])\n" ++
      "        mean = jnp.mean(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        var = jnp.var(x, axis=(0, 2, 3), keepdims=True)\n" ++
      "        x = (x - mean) / jnp.sqrt(var + 1e-5)\n" ++
      "        x = x * params[i][1].reshape(1, -1, 1, 1) + params[i][2].reshape(1, -1, 1, 1)\n" ++
      "        x = jax.nn.relu(x)\n" ++
      "        i += 1\n" ++
      "    # Project 1x1 (linear)\n" ++
      "    x = conv_bn(x, params[i][0], params[i][1], params[i][2])\n" ++
      "    if residual.shape == x.shape:\n" ++
      "        x = x + residual\n" ++
      "    return x\n\n"
  if spec.layers.any fun | .fireModule .. => true | _ => false then
    code := code ++
      "def fire_module(params, x, idx):\n" ++
      "    \"\"\"Fire: squeeze 1x1 → expand (1x1 || 3x3) → concat.\"\"\"\n" ++
      "    sq = conv_bn(x, params[idx][0], params[idx][1], params[idx][2])\n" ++
      "    sq = jax.nn.relu(sq)\n" ++
      "    e1 = conv_bn(sq, params[idx+1][0], params[idx+1][1], params[idx+1][2])\n" ++
      "    e1 = jax.nn.relu(e1)\n" ++
      "    e3 = conv_bn(sq, params[idx+2][0], params[idx+2][1], params[idx+2][2])\n" ++
      "    e3 = jax.nn.relu(e3)\n" ++
      "    return jnp.concatenate([e1, e3], axis=1)\n\n"
  if spec.hasGlobalAvgPool then
    code := code ++
      "def global_avg_pool(x):\n" ++
      "    return jnp.mean(x, axis=(2, 3))\n\n"
  if spec.hasTransformer then
    code := code ++
      "def layer_norm(x, gamma, beta):\n" ++
      "    mean = jnp.mean(x, axis=-1, keepdims=True)\n" ++
      "    var = jnp.var(x, axis=-1, keepdims=True)\n" ++
      "    return (x - mean) / jnp.sqrt(var + 1e-5) * gamma + beta\n\n" ++
      "def mhsa(x, wq, bq, wk, bk, wv, bv, wo, bo, n_heads):\n" ++
      "    B, N, D = x.shape\n" ++
      "    head_dim = D // n_heads\n" ++
      "    q = (x @ wq.T + bq).reshape(B, N, n_heads, head_dim).transpose(0, 2, 1, 3)\n" ++
      "    k = (x @ wk.T + bk).reshape(B, N, n_heads, head_dim).transpose(0, 2, 1, 3)\n" ++
      "    v = (x @ wv.T + bv).reshape(B, N, n_heads, head_dim).transpose(0, 2, 1, 3)\n" ++
      "    scale = jnp.sqrt(jnp.float32(head_dim))\n" ++
      "    attn = jax.nn.softmax(q @ k.transpose(0, 1, 3, 2) / scale, axis=-1)\n" ++
      "    out = (attn @ v).transpose(0, 2, 1, 3).reshape(B, N, D)\n" ++
      "    return out @ wo.T + bo\n\n" ++
      "def transformer_block(params, x, idx, n_heads):\n" ++
      "    g1, b1 = params[idx]\n" ++
      "    x2 = layer_norm(x, g1, b1)\n" ++
      "    wq, bq = params[idx+1]\n" ++
      "    wk, bk = params[idx+2]\n" ++
      "    wv, bv = params[idx+3]\n" ++
      "    wo, bo = params[idx+4]\n" ++
      "    x = x + mhsa(x2, wq, bq, wk, bk, wv, bv, wo, bo, n_heads)\n" ++
      "    g2, b2 = params[idx+5]\n" ++
      "    x2 = layer_norm(x, g2, b2)\n" ++
      "    w1, b1m = params[idx+6]\n" ++
      "    w2, b2m = params[idx+7]\n" ++
      "    h = jax.nn.gelu(x2 @ w1.T + b1m)\n" ++
      "    x = x + (h @ w2.T + b2m)\n" ++
      "    return x\n\n"
  code

-- Helper: emit init code for one conv+BN param group (w, gamma, beta)
private def emitConvBnInit (comment : String) (ic oc k : Nat) (zeroGamma : Bool := false) : String :=
  let fanOut := oc * k * k
  let gammaInit := if zeroGamma then "jnp.zeros(" ++ toString oc ++ ")" else "jnp.ones(" ++ toString oc ++ ")"
  "    # " ++ comment ++ "\n" ++
  "    key, k_ = random.split(key)\n" ++
  "    scale = jnp.sqrt(6.0 / " ++ toString fanOut ++ ")\n" ++
  "    params.append((random.uniform(k_, (" ++ toString oc ++ ", " ++ toString ic ++ ", " ++
    toString k ++ ", " ++ toString k ++ "), minval=-scale, maxval=scale),\n" ++
  "                   " ++ gammaInit ++ ", jnp.zeros(" ++ toString oc ++ ")))\n"

-- Helper: emit init code for layer norm (gamma, beta)
private def emitLNInit (comment : String) (dim : Nat) : String :=
  "    # " ++ comment ++ "\n" ++
  "    params.append((jnp.ones(" ++ toString dim ++ "), jnp.zeros(" ++ toString dim ++ ")))\n"

-- Helper: emit init_params_from_file code for one convBn param group.
-- Reads W[oc,ic,k,k] + γ[oc] + β[oc] from `buf` in the order
-- LeanMlir.SpecHelpers.paramShapes emits them and appends a 3-tuple to
-- `params`.
private def emitConvBnFromBuf (comment : String) (ic oc k : Nat) : String :=
  let nW := oc * ic * k * k
  s!"    # {comment} (W, γ, β)\n" ++
  s!"    W = jnp.array(buf[idx:idx+{nW}].reshape({oc}, {ic}, {k}, {k})); idx += {nW}\n" ++
  s!"    gamma = jnp.array(buf[idx:idx+{oc}]); idx += {oc}\n" ++
  s!"    beta = jnp.array(buf[idx:idx+{oc}]); idx += {oc}\n" ++
  "    params.append((W, gamma, beta))\n"

-- Helper: emit init code for dense layer (weight, bias) with Xavier uniform
private def emitDenseInit (comment : String) (fanIn fanOut : Nat) : String :=
  "    # " ++ comment ++ "\n" ++
  "    key, k_ = random.split(key)\n" ++
  "    scale = jnp.sqrt(6.0 / " ++ toString (fanIn + fanOut) ++ ")\n" ++
  "    params.append((random.uniform(k_, (" ++ toString fanOut ++ ", " ++ toString fanIn ++
    "), minval=-scale, maxval=scale), jnp.zeros(" ++ toString fanOut ++ ")))\n"

private def emitInitParams (spec : NetSpec) : String := Id.run do
  let mut code :=
    "# ═══════════════════════════════════════════════════════════════════════\n" ++
    "#  Model (from Lean spec)\n" ++
    "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
    "def init_params(key):\n" ++
    "    \"\"\"Xavier/Kaiming uniform init.\"\"\"\n" ++
    "    params = []\n"
  for l in spec.layers do
    match l with
    | .conv2d ic oc k _ _ =>
      let fanIn := ic * k * k
      let fanOut := oc * k * k
      code := code ++
        "    # Conv2D " ++ toString ic ++ "→" ++ toString oc ++ ", " ++ toString k ++ "x" ++ toString k ++ "\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString (fanIn + fanOut) ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString oc ++ ", " ++ toString ic ++ ", " ++
          toString k ++ ", " ++ toString k ++ "), minval=-scale, maxval=scale), jnp.zeros(" ++ toString oc ++ ")))\n"
    | .convBn ic oc k _ _ =>
      code := code ++ emitConvBnInit s!"ConvBN {ic}→{oc}, {k}x{k}" ic oc k
    | .dense fi fo _ =>
      code := code ++
        "    # Dense " ++ toString fi ++ "→" ++ toString fo ++ "\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString (fi + fo) ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString fo ++ ", " ++ toString fi ++
          "), minval=-scale, maxval=scale), jnp.zeros(" ++ toString fo ++ ")))\n"
    | .residualBlock ic oc n fs =>
      let needsProj := !(ic == oc && fs == 1)
      if needsProj then
        code := code ++ emitConvBnInit s!"ResBlock ↓ conv1 {ic}→{oc}" ic oc 3
        code := code ++ emitConvBnInit s!"ResBlock ↓ conv2 {oc}→{oc}" oc oc 3
        code := code ++ emitConvBnInit s!"ResBlock ↓ proj {ic}→{oc}" ic oc 1
      else
        code := code ++ emitConvBnInit s!"ResBlock conv1 {oc}→{oc}" oc oc 3
        code := code ++ emitConvBnInit s!"ResBlock conv2 {oc}→{oc}" oc oc 3
      for _ in List.range (n - 1) do
        code := code ++ emitConvBnInit s!"ResBlock conv1 {oc}→{oc}" oc oc 3
        code := code ++ emitConvBnInit s!"ResBlock conv2 {oc}→{oc}" oc oc 3
    | .bottleneckBlock ic oc n fs =>
      let mid := oc / 4
      let needsProj := !(ic == oc && fs == 1)
      if needsProj then
        code := code ++ emitConvBnInit s!"Bottleneck ↓ 1x1 {ic}→{mid}" ic mid 1
        code := code ++ emitConvBnInit s!"Bottleneck ↓ 3x3 {mid}→{mid}" mid mid 3
        code := code ++ emitConvBnInit s!"Bottleneck ↓ 1x1 {mid}→{oc}" mid oc 1 (zeroGamma := true)
        code := code ++ emitConvBnInit s!"Bottleneck ↓ proj {ic}→{oc}" ic oc 1
      else
        code := code ++ emitConvBnInit s!"Bottleneck 1x1 {oc}→{mid}" oc mid 1
        code := code ++ emitConvBnInit s!"Bottleneck 3x3 {mid}→{mid}" mid mid 3
        code := code ++ emitConvBnInit s!"Bottleneck 1x1 {mid}→{oc}" mid oc 1 (zeroGamma := true)
      for _ in List.range (n - 1) do
        code := code ++ emitConvBnInit s!"Bottleneck 1x1 {oc}→{mid}" oc mid 1
        code := code ++ emitConvBnInit s!"Bottleneck 3x3 {mid}→{mid}" mid mid 3
        code := code ++ emitConvBnInit s!"Bottleneck 1x1 {mid}→{oc}" mid oc 1 (zeroGamma := true)
    | .separableConv ic oc _ =>
      -- Depthwise: weight shape (ic, 1, 3, 3), Kaiming init
      let dwFanOut := 9
      code := code ++
        "    # SepConv DW " ++ toString ic ++ "ch, 3x3\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString ic ++ ", 1, 3, 3), minval=-scale, maxval=scale),\n" ++
        "                   jnp.ones(" ++ toString ic ++ "), jnp.zeros(" ++ toString ic ++ ")))\n"
      -- Pointwise: reuse emitConvBnInit for 1x1 conv
      code := code ++ emitConvBnInit s!"SepConv PW {ic}→{oc}" ic oc 1
    | .invertedResidual ic oc expand stride n =>
      -- First block: ic→mid→oc
      let mid := ic * expand
      if expand != 1 then
        code := code ++ emitConvBnInit s!"IR expand {ic}→{mid}" ic mid 1
      -- Depthwise
      let dwFanOut := 9
      code := code ++
        "    # IR DW " ++ toString mid ++ "ch, 3x3\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString mid ++ ", 1, 3, 3), minval=-scale, maxval=scale),\n" ++
        "                   jnp.ones(" ++ toString mid ++ "), jnp.zeros(" ++ toString mid ++ ")))\n"
      code := code ++ emitConvBnInit s!"IR project {mid}→{oc}" mid oc 1
      -- Remaining blocks: oc→oc*expand→oc, stride=1
      for _ in List.range (n - 1) do
        let midR := oc * expand
        if expand != 1 then
          code := code ++ emitConvBnInit s!"IR expand {oc}→{midR}" oc midR 1
        code := code ++
          "    # IR DW " ++ toString midR ++ "ch, 3x3\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString midR ++ ", 1, 3, 3), minval=-scale, maxval=scale),\n" ++
          "                   jnp.ones(" ++ toString midR ++ "), jnp.zeros(" ++ toString midR ++ ")))\n"
        code := code ++ emitConvBnInit s!"IR project {midR}→{oc}" midR oc 1
    | .mbConv ic oc expand kSize _ n useSE =>
      -- Helper to emit one block's params
      let emitBlock (blockIc blockOc : Nat) : String := Id.run do
        let mid := blockIc * expand
        let mut code := ""
        -- Expand
        if expand != 1 then
          code := code ++ emitConvBnInit s!"MB expand {blockIc}→{mid}" blockIc mid 1
        -- Depthwise
        let dwFanOut := kSize * kSize
        code := code ++
          "    # MB DW " ++ toString mid ++ "ch, " ++ toString kSize ++ "x" ++ toString kSize ++ "\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString mid ++ ", 1, " ++
            toString kSize ++ ", " ++ toString kSize ++ "), minval=-scale, maxval=scale),\n" ++
          "                   jnp.ones(" ++ toString mid ++ "), jnp.zeros(" ++ toString mid ++ ")))\n"
        -- SE
        if useSE then
          let seMid := Nat.max 1 (mid / 4)
          code := code ++
            "    # SE down " ++ toString mid ++ "→" ++ toString seMid ++ "\n" ++
            "    key, k_ = random.split(key)\n" ++
            "    scale = jnp.sqrt(6.0 / " ++ toString seMid ++ ")\n" ++
            "    params.append((random.uniform(k_, (" ++ toString seMid ++ ", " ++ toString mid ++
              ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString seMid ++ ")))\n" ++
            "    # SE up " ++ toString seMid ++ "→" ++ toString mid ++ "\n" ++
            "    key, k_ = random.split(key)\n" ++
            "    scale = jnp.sqrt(6.0 / " ++ toString mid ++ ")\n" ++
            "    params.append((random.uniform(k_, (" ++ toString mid ++ ", " ++ toString seMid ++
              ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString mid ++ ")))\n"
        -- Project
        code := code ++ emitConvBnInit s!"MB project {mid}→{blockOc}" mid blockOc 1
        code
      -- First block
      code := code ++ emitBlock ic oc
      -- Remaining blocks
      for _ in List.range (n - 1) do
        code := code ++ emitBlock oc oc
    | .mbConvV3 ic oc expandCh kSize _ useSE _ =>
      -- Expand (if expandCh != ic)
      if expandCh != ic then
        code := code ++ emitConvBnInit s!"V3 expand {ic}→{expandCh}" ic expandCh 1
      -- Depthwise
      code := code ++
        "    # V3 DW " ++ toString expandCh ++ "ch, " ++ toString kSize ++ "x" ++ toString kSize ++ "\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString (kSize * kSize) ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString expandCh ++ ", 1, " ++
          toString kSize ++ ", " ++ toString kSize ++ "), minval=-scale, maxval=scale),\n" ++
        "                   jnp.ones(" ++ toString expandCh ++ "), jnp.zeros(" ++ toString expandCh ++ ")))\n"
      -- SE
      if useSE then
        let seMid := Nat.max 1 (expandCh / 4)
        code := code ++
          "    # V3 SE down " ++ toString expandCh ++ "→" ++ toString seMid ++ "\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString seMid ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString seMid ++ ", " ++ toString expandCh ++
            ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString seMid ++ ")))\n" ++
          "    # V3 SE up " ++ toString seMid ++ "→" ++ toString expandCh ++ "\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString expandCh ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString expandCh ++ ", " ++ toString seMid ++
            ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString expandCh ++ ")))\n"
      -- Project
      code := code ++ emitConvBnInit s!"V3 project {expandCh}→{oc}" expandCh oc 1
    | .uib ic oc expand _stride preDWk postDWk =>
      let mid := ic * expand
      -- Pre-depthwise (on ic channels)
      if preDWk > 0 then
        let dwFanOut := preDWk * preDWk
        code := code ++
          "    # UIB pre-DW " ++ toString ic ++ "ch, " ++ toString preDWk ++ "x" ++ toString preDWk ++ "\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString ic ++ ", 1, " ++
            toString preDWk ++ ", " ++ toString preDWk ++ "), minval=-scale, maxval=scale),\n" ++
          "                   jnp.ones(" ++ toString ic ++ "), jnp.zeros(" ++ toString ic ++ ")))\n"
      -- Expand 1x1
      code := code ++ emitConvBnInit s!"UIB expand {ic}→{mid}" ic mid 1
      -- Post-depthwise (on mid channels)
      if postDWk > 0 then
        let dwFanOut := postDWk * postDWk
        code := code ++
          "    # UIB post-DW " ++ toString mid ++ "ch, " ++ toString postDWk ++ "x" ++ toString postDWk ++ "\n" ++
          "    key, k_ = random.split(key)\n" ++
          "    scale = jnp.sqrt(6.0 / " ++ toString dwFanOut ++ ")\n" ++
          "    params.append((random.uniform(k_, (" ++ toString mid ++ ", 1, " ++
            toString postDWk ++ ", " ++ toString postDWk ++ "), minval=-scale, maxval=scale),\n" ++
          "                   jnp.ones(" ++ toString mid ++ "), jnp.zeros(" ++ toString mid ++ ")))\n"
      -- Project 1x1
      code := code ++ emitConvBnInit s!"UIB project {mid}→{oc}" mid oc 1
    | .fusedMbConv ic oc expand kSize _ n useSE =>
      let emitFusedBlock (blockIc blockOc : Nat) : String := Id.run do
        let mid := if expand == 1 then blockOc else blockIc * expand
        let mut code := ""
        -- Fused expand: kxk conv
        code := code ++ emitConvBnInit s!"FMB fused {blockIc}→{mid}, {kSize}x{kSize}" blockIc mid kSize
        -- SE
        if useSE then
          let seMid := Nat.max 1 (mid / 4)
          code := code ++
            "    # SE down " ++ toString mid ++ "→" ++ toString seMid ++ "\n" ++
            "    key, k_ = random.split(key)\n" ++
            "    scale = jnp.sqrt(6.0 / " ++ toString seMid ++ ")\n" ++
            "    params.append((random.uniform(k_, (" ++ toString seMid ++ ", " ++ toString mid ++
              ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString seMid ++ ")))\n" ++
            "    # SE up " ++ toString seMid ++ "→" ++ toString mid ++ "\n" ++
            "    key, k_ = random.split(key)\n" ++
            "    scale = jnp.sqrt(6.0 / " ++ toString mid ++ ")\n" ++
            "    params.append((random.uniform(k_, (" ++ toString mid ++ ", " ++ toString seMid ++
              ", 1, 1), minval=-scale, maxval=scale), jnp.zeros(" ++ toString mid ++ ")))\n"
        -- Project (only if expand > 1)
        if expand != 1 then
          code := code ++ emitConvBnInit s!"FMB project {mid}→{blockOc}" mid blockOc 1
        code
      code := code ++ emitFusedBlock ic oc
      for _ in List.range (n - 1) do
        code := code ++ emitFusedBlock oc oc
    | .fireModule ic sq e1 e3 =>
      code := code ++ emitConvBnInit s!"Fire squeeze {ic}→{sq}" ic sq 1
      code := code ++ emitConvBnInit s!"Fire expand1x1 {sq}→{e1}" sq e1 1
      code := code ++ emitConvBnInit s!"Fire expand3x3 {sq}→{e3}" sq e3 3
    | .patchEmbed ic dim p _nP =>
      -- Patch embedding conv
      let fanOut := dim * p * p
      code := code ++
        "    # Patch embedding conv " ++ toString ic ++ "→" ++ toString dim ++ ", " ++ toString p ++ "x" ++ toString p ++ "\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    scale = jnp.sqrt(6.0 / " ++ toString fanOut ++ ")\n" ++
        "    params.append((random.uniform(k_, (" ++ toString dim ++ ", " ++ toString ic ++ ", " ++
          toString p ++ ", " ++ toString p ++ "), minval=-scale, maxval=scale),\n" ++
        "                   jnp.zeros(" ++ toString dim ++ ")))\n"
      -- CLS token
      code := code ++
        "    # CLS token\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    params.append((random.normal(k_, (" ++ toString dim ++ ",)) * 0.02,))\n"
      -- Positional embeddings
      let nTokens := _nP + 1
      code := code ++
        "    # Positional embedding (" ++ toString nTokens ++ ", " ++ toString dim ++ ")\n" ++
        "    key, k_ = random.split(key)\n" ++
        "    params.append((random.normal(k_, (" ++ toString nTokens ++ ", " ++ toString dim ++ ")) * 0.02,))\n"
    | .transformerEncoder dim _heads mlpDim nBlocks =>
      for i in List.range nBlocks do
        code := code ++ emitLNInit s!"Transformer block {i} LN1" dim
        code := code ++ emitDenseInit s!"Transformer block {i} Q {dim}→{dim}" dim dim
        code := code ++ emitDenseInit s!"Transformer block {i} K {dim}→{dim}" dim dim
        code := code ++ emitDenseInit s!"Transformer block {i} V {dim}→{dim}" dim dim
        code := code ++ emitDenseInit s!"Transformer block {i} Out {dim}→{dim}" dim dim
        code := code ++ emitLNInit s!"Transformer block {i} LN2" dim
        code := code ++ emitDenseInit s!"Transformer block {i} MLP fc1 {dim}→{mlpDim}" dim mlpDim
        code := code ++ emitDenseInit s!"Transformer block {i} MLP fc2 {mlpDim}→{dim}" mlpDim dim
      code := code ++ emitLNInit "Final LN" dim
    | _ => pure ()
  code := code ++ "    return params\n\n"
  -- Init-from-file path: load a flat float32 buffer produced by phase 3
  -- (LEAN_MLIR_INIT_DUMP=...). Used for step-level cross-compiler diff.
  -- Supports dense, conv2d, convBn (MNIST MLP + MNIST CNN). Params are
  -- walked in the same order `LeanMlir.SpecHelpers.paramShapes` emits.
  code := code ++
    "def init_params_from_file(path):\n" ++
    "    buf = np.frombuffer(open(path, 'rb').read(), dtype=np.float32)\n" ++
    "    idx = 0\n" ++
    "    params = []\n"
  for l in spec.layers do
    match l with
    | .dense fi fo _ =>
      let nW := fi * fo
      code := code ++
        s!"    # dense {fi} → {fo}\n" ++
        s!"    W = jnp.array(buf[idx:idx+{nW}].reshape({fi}, {fo}).T); idx += {nW}\n" ++
        s!"    b = jnp.array(buf[idx:idx+{fo}]); idx += {fo}\n" ++
        "    params.append((W, b))\n"
    | .conv2d ic oc k _ _ =>
      let nW := oc * ic * k * k
      code := code ++
        s!"    # conv2d {ic}→{oc}, {k}×{k}\n" ++
        s!"    W = jnp.array(buf[idx:idx+{nW}].reshape({oc}, {ic}, {k}, {k})); idx += {nW}\n" ++
        s!"    b = jnp.array(buf[idx:idx+{oc}]); idx += {oc}\n" ++
        "    params.append((W, b))\n"
    | .convBn ic oc k _ _ =>
      code := code ++ emitConvBnFromBuf s!"convBn {ic}→{oc}, {k}×{k}" ic oc k
    | .residualBlock ic oc nBlocks firstStride =>
      -- Order matches LeanMlir.SpecHelpers.paramShapes: for each sub-block,
      -- (conv1 W,γ,β) + (conv2 W,γ,β), plus projection (W,γ,β) on sub-block 0
      -- iff ic != oc or firstStride != 1.
      let needsProj := !(ic == oc && firstStride == 1)
      for bi in [:nBlocks] do
        let blockIc := if bi == 0 then ic else oc
        code := code ++ emitConvBnFromBuf s!"resBlock[{bi}] conv1 {blockIc}→{oc}" blockIc oc 3
        code := code ++ emitConvBnFromBuf s!"resBlock[{bi}] conv2 {oc}→{oc}" oc oc 3
        if bi == 0 && needsProj then
          code := code ++ emitConvBnFromBuf s!"resBlock[{bi}] proj {ic}→{oc}" ic oc 1
    | .invertedResidual ic oc expand _stride n =>
      -- Order: for each sub-block, (expand 1×1 convBn if expand != 1)
      -- + (depthwise 3×3 convBn, W[mid,1,3,3]) + (project 1×1 convBn).
      for bi in [:n] do
        let blockIc := if bi == 0 then ic else oc
        let mid := blockIc * expand
        if expand != 1 then
          code := code ++ emitConvBnFromBuf s!"invRes[{bi}] expand {blockIc}→{mid}" blockIc mid 1
        -- Depthwise weight shape is (mid, 1, 3, 3); emitConvBnFromBuf handles
        -- it by setting ic=1 and oc=mid so the reshape comes out right.
        code := code ++ emitConvBnFromBuf s!"invRes[{bi}] depthwise {mid}" 1 mid 3
        code := code ++ emitConvBnFromBuf s!"invRes[{bi}] project {mid}→{oc}" mid oc 1
    | .maxPool _ _ | .globalAvgPool | .flatten =>
      pure ()  -- no params
    | _ =>
      code := code ++ "    raise NotImplementedError('init_params_from_file: unsupported layer')\n"
  code := code ++ "    return params\n\n"
  code

private def emitForward (spec : NetSpec) : String := Id.run do
  let mut code := "def forward(params, x):\n"
  -- Reshape flat images to NCHW if first layer is conv
  match spec.layers.head? with
  | some (.conv2d ic _ _ _ _) =>
    code := code ++ "    x = x.reshape(-1, " ++ toString ic ++ ", " ++
      toString spec.imageH ++ ", " ++ toString spec.imageW ++ ")\n"
  | some (.convBn ic _ _ _ _) =>
    code := code ++ "    x = x.reshape(-1, " ++ toString ic ++ ", " ++
      toString spec.imageH ++ ", " ++ toString spec.imageW ++ ")\n"
  | some (.patchEmbed ic _ _ _) =>
    code := code ++ "    x = x.reshape(-1, " ++ toString ic ++ ", " ++
      toString spec.imageH ++ ", " ++ toString spec.imageW ++ ")\n"
  | _ => pure ()
  let mut pidx : Nat := 0
  for l in spec.layers do
    match l with
    | .conv2d _ _ _ pad act =>
      let padStr := match pad with | .same => "SAME" | .valid => "VALID"
      code := code ++ "    x = conv2d(x, params[" ++ toString pidx ++ "][0], params[" ++
        toString pidx ++ "][1], '" ++ padStr ++ "')\n"
      if act == .relu then code := code ++ "    x = jax.nn.relu(x)\n"
      if act == .relu6 then code := code ++ "    x = jnp.minimum(jax.nn.relu(x), 6.0)\n"
      pidx := pidx + 1
    | .convBn _ _ _ s pad =>
      let padStr := match pad with | .same => "SAME" | .valid => "VALID"
      let strideStr := if s == 1 then "" else ", stride=(" ++ toString s ++ "," ++ toString s ++ ")"
      code := code ++ "    x = conv_bn(x, params[" ++ toString pidx ++ "][0], params[" ++
        toString pidx ++ "][1], params[" ++ toString pidx ++ "][2]" ++
        strideStr ++ ", padding='" ++ padStr ++ "')\n"
      code := code ++ "    x = jax.nn.relu(x)\n"
      pidx := pidx + 1
    | .maxPool size stride =>
      code := code ++ "    x = max_pool2d(x, " ++ toString size ++ ", " ++ toString stride ++ ")\n"
    | .globalAvgPool =>
      code := code ++ "    x = global_avg_pool(x)\n"
    | .flatten =>
      code := code ++ "    x = x.reshape(x.shape[0], -1)\n"
    | .dense _ _ act =>
      code := code ++ "    x = x @ params[" ++ toString pidx ++ "][0].T + params[" ++
        toString pidx ++ "][1]\n"
      if act == .relu then code := code ++ "    x = jax.nn.relu(x)\n"
      if act == .relu6 then code := code ++ "    x = jnp.minimum(jax.nn.relu(x), 6.0)\n"
      pidx := pidx + 1
    | .residualBlock ic oc n fs =>
      let needsProj := !(ic == oc && fs == 1)
      if needsProj then
        code := code ++ "    x = basic_block_down(params, x, " ++ toString pidx ++ ", " ++ toString fs ++ ")\n"
        pidx := pidx + 3
      else
        code := code ++ "    x = basic_block(params, x, " ++ toString pidx ++ ")\n"
        pidx := pidx + 2
      for _ in List.range (n - 1) do
        code := code ++ "    x = basic_block(params, x, " ++ toString pidx ++ ")\n"
        pidx := pidx + 2
    | .bottleneckBlock ic oc n fs =>
      let needsProj := !(ic == oc && fs == 1)
      if needsProj then
        code := code ++ "    x = bottleneck_block_down(params, x, " ++ toString pidx ++ ", " ++ toString fs ++ ")\n"
        pidx := pidx + 4
      else
        code := code ++ "    x = bottleneck_block(params, x, " ++ toString pidx ++ ")\n"
        pidx := pidx + 3
      for _ in List.range (n - 1) do
        code := code ++ "    x = bottleneck_block(params, x, " ++ toString pidx ++ ")\n"
        pidx := pidx + 3
    | .separableConv _ _ s =>
      let strideStr := "(" ++ toString s ++ "," ++ toString s ++ ")"
      code := code ++ "    x = sep_conv(x, params[" ++ toString pidx ++ "][0], params[" ++
        toString pidx ++ "][1], params[" ++ toString pidx ++ "][2], params[" ++
        toString (pidx + 1) ++ "][0], params[" ++ toString (pidx + 1) ++ "][1], params[" ++
        toString (pidx + 1) ++ "][2], stride=" ++ strideStr ++ ")\n"
      pidx := pidx + 2
    | .mbConv ic oc expand kSize stride n useSE =>
      let nPerBlock (blockExpand : Nat) (se : Bool) :=
        (if blockExpand != 1 then 1 else 0) + 1 + (if se then 2 else 0) + 1
      let useSkipFirst := if ic == oc && stride == 1 then "True" else "False"
      let _ := useSkipFirst  -- used in string below
      code := code ++ "    x = mbconv_block(params, x, " ++ toString pidx ++ ", " ++
        toString stride ++ ", " ++ toString expand ++ ", " ++ toString kSize ++ ", " ++
        (if useSE then "True" else "False") ++ ")\n"
      pidx := pidx + nPerBlock expand useSE
      for _ in List.range (n - 1) do
        code := code ++ "    x = mbconv_block(params, x, " ++ toString pidx ++ ", 1, " ++
          toString expand ++ ", " ++ toString kSize ++ ", " ++
          (if useSE then "True" else "False") ++ ")\n"
        pidx := pidx + nPerBlock expand useSE
    | .invertedResidual ic oc expand stride n =>
      let nParamsPerBlock (hasExpand : Bool) := (if hasExpand then 1 else 0) + 1 + 1  -- expand? + dw + proj
      let hasExpand := expand != 1
      -- First block: may have stride, no skip (ic≠oc or stride≠1 typically)
      let useSkip := if ic == oc && stride == 1 then "True" else "False"
      code := code ++ "    x = invres_block(params, x, " ++ toString pidx ++ ", " ++
        toString stride ++ ", " ++ toString expand ++ ", " ++ useSkip ++ ")\n"
      pidx := pidx + nParamsPerBlock hasExpand
      -- Remaining blocks: stride=1, skip when oc==oc (always true)
      for _ in List.range (n - 1) do
        code := code ++ "    x = invres_block(params, x, " ++ toString pidx ++ ", 1, " ++
          toString expand ++ ", True)\n"
        pidx := pidx + nParamsPerBlock hasExpand
    | .mbConvV3 ic _ expandCh kSize stride useSE useHSwish =>
      let nP := (if expandCh != ic then 1 else 0) + 1 + (if useSE then 2 else 0) + 1
      code := code ++ "    x = mbconv_v3_block(params, x, " ++ toString pidx ++ ", " ++
        toString stride ++ ", " ++ toString expandCh ++ ", " ++ toString kSize ++ ", " ++
        (if useSE then "True" else "False") ++ ", " ++
        (if useHSwish then "True" else "False") ++ ")\n"
      pidx := pidx + nP
    | .uib _ic _oc _expand stride preDWk postDWk =>
      let nP := (if preDWk > 0 then 1 else 0) + 1 + (if postDWk > 0 then 1 else 0) + 1
      code := code ++ "    x = uib_block(params, x, " ++ toString pidx ++ ", " ++
        toString stride ++ ", " ++ toString preDWk ++ ", " ++ toString postDWk ++ ")\n"
      pidx := pidx + nP
    | .fusedMbConv _ic _oc expand kSize stride n useSE =>
      let nPerBlock (blockExpand : Nat) (se : Bool) :=
        1 + (if se then 2 else 0) + (if blockExpand != 1 then 1 else 0)
      code := code ++ "    x = fused_mbconv_block(params, x, " ++ toString pidx ++ ", " ++
        toString stride ++ ", " ++ toString expand ++ ", " ++ toString kSize ++ ", " ++
        (if useSE then "True" else "False") ++ ")\n"
      pidx := pidx + nPerBlock expand useSE
      for _ in List.range (n - 1) do
        code := code ++ "    x = fused_mbconv_block(params, x, " ++ toString pidx ++ ", 1, " ++
          toString expand ++ ", " ++ toString kSize ++ ", " ++
          (if useSE then "True" else "False") ++ ")\n"
        pidx := pidx + nPerBlock expand useSE
    | .fireModule _ _ _ _ =>
      code := code ++ "    x = fire_module(params, x, " ++ toString pidx ++ ")\n"
      pidx := pidx + 3
    | .patchEmbed _ic dim p _nP =>
      -- Conv patch embedding
      code := code ++ "    x = jax.lax.conv_general_dilated(x, params[" ++ toString pidx ++ "][0], (" ++
        toString p ++ "," ++ toString p ++ "), 'VALID',\n" ++
        "          dimension_numbers=('NCHW', 'OIHW', 'NCHW'))\n"
      code := code ++ "    x = x + params[" ++ toString pidx ++ "][1].reshape(1, -1, 1, 1)\n"
      pidx := pidx + 1
      -- Reshape from (B, dim, H', W') to (B, nPatches, dim)
      code := code ++ "    x = x.reshape(x.shape[0], " ++ toString dim ++ ", -1).transpose(0, 2, 1)\n"
      -- Prepend CLS token
      code := code ++ "    cls = jnp.broadcast_to(params[" ++ toString pidx ++ "][0], (x.shape[0], 1, " ++ toString dim ++ "))\n"
      pidx := pidx + 1
      code := code ++ "    x = jnp.concatenate([cls, x], axis=1)\n"
      -- Add positional embedding
      code := code ++ "    x = x + params[" ++ toString pidx ++ "][0]\n"
      pidx := pidx + 1
    | .transformerEncoder _dim heads _mlpDim nBlocks =>
      for _ in List.range nBlocks do
        code := code ++ "    x = transformer_block(params, x, " ++ toString pidx ++ ", " ++ toString heads ++ ")\n"
        pidx := pidx + 8
      -- Final layer norm
      code := code ++ "    x = layer_norm(x, params[" ++ toString pidx ++ "][0], params[" ++ toString pidx ++ "][1])\n"
      pidx := pidx + 1
      -- Extract CLS token
      code := code ++ "    x = x[:, 0]\n"
    | _ =>
      -- Bestiary-only primitives (mambaBlock, swinStage, unetDown/Up,
      -- transformerDecoder, etc.) are not supported by phase-2 codegen;
      -- they're bestiary-only and emit UNSUPPORTED on phase-3 too.
      code := code ++ "    # UNSUPPORTED layer in phase-2 codegen\n"
  code := code ++ "    return x\n\n"
  code

private def emitLossAndTraining (spec : NetSpec) (cfg : TrainConfig) : String :=
  let nClasses := spec.numClasses
  let lr := toString cfg.learningRate
  let hasMomentum := cfg.momentum > 0.0
  let hasCosine := cfg.cosineDecay
  "def loss_fn(params, x, y):\n" ++
  "    logits = forward(params, x)\n" ++
  "    log_probs = jax.nn.log_softmax(logits, axis=-1)\n" ++
  "    one_hot = jax.nn.one_hot(y, " ++ toString nClasses ++ ")\n" ++
  "    return -jnp.mean(jnp.sum(log_probs * one_hot, axis=-1))\n\n" ++
  let ic := match spec.layers.head? with
    | some (.conv2d ic ..) => ic | some (.convBn ic ..) => ic
    | some (.patchEmbed ic ..) => ic | _ => 3
  (if cfg.augment && spec.imageH > 32 then
    let pad := 14  -- pad each side by 14 pixels (224→252)
    let padded := spec.imageH + 2 * pad
    "def augment_batch(x, rng):\n" ++
    "    \"\"\"Random crop (numpy, CPU): pad " ++ toString spec.imageH ++ "→" ++ toString padded ++
      ", crop back to " ++ toString spec.imageH ++ "x" ++ toString spec.imageW ++ ".\"\"\"\n" ++
    "    x = x.reshape(-1, " ++ toString ic ++ ", " ++ toString spec.imageH ++ ", " ++ toString spec.imageW ++ ")\n" ++
    "    x = np.pad(x, ((0,0), (0,0), (" ++ toString pad ++ "," ++ toString pad ++
      "), (" ++ toString pad ++ "," ++ toString pad ++ ")))\n" ++
    "    top = rng.randint(0, " ++ toString (2 * pad + 1) ++ ")\n" ++
    "    left = rng.randint(0, " ++ toString (2 * pad + 1) ++ ")\n" ++
    "    x = x[:, :, top:top+" ++ toString spec.imageH ++ ", left:left+" ++ toString spec.imageW ++ "]\n" ++
    "    return x.reshape(x.shape[0], -1)\n\n"
  else "") ++
  let useAdam := cfg.useAdam
  let optName := if useAdam then "Adam" else "SGD" ++ (if hasMomentum then " + momentum" else "")
  "# ═══════════════════════════════════════════════════════════════════════\n" ++
  "#  Training  (" ++ optName ++
    (if hasCosine then " + cosine LR" else "") ++ ")\n" ++
  "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
  let hasWD := cfg.weightDecay > 0.0
  let wd := toString cfg.weightDecay
  "LR = " ++ lr ++ "\n" ++
  (if hasMomentum && !useAdam then "MOMENTUM = " ++ toString cfg.momentum ++ "\n" else "") ++
  (if hasWD then "WD = " ++ wd ++ "\n" else "") ++
  "\n" ++
  (if useAdam then
    "@jit\n" ++
    "def train_step(params, opt_state, x, y, lr):\n" ++
    "    loss, grads = value_and_grad(loss_fn)(params, x, y)\n" ++
    (if hasWD then "    grads = jax.tree.map(lambda g, p: g + WD * p, grads, params)\n" else "") ++
    "    m, v, t = opt_state\n" ++
    "    t = t + 1\n" ++
    "    m = jax.tree.map(lambda mi, g: 0.9 * mi + 0.1 * g, m, grads)\n" ++
    "    v = jax.tree.map(lambda vi, g: 0.999 * vi + 0.001 * g * g, v, grads)\n" ++
    "    mc = jax.tree.map(lambda mi: mi / (1 - 0.9 ** t), m)\n" ++
    "    vc = jax.tree.map(lambda vi: vi / (1 - 0.999 ** t), v)\n" ++
    "    params = jax.tree.map(lambda p, mi, vi: p - lr * mi / (jnp.sqrt(vi) + 1e-8), params, mc, vc)\n" ++
    "    return params, (m, v, t), loss\n\n"
  else if hasMomentum then
    "@jit\n" ++
    "def train_step(params, velocity, x, y, lr):\n" ++
    "    loss, grads = value_and_grad(loss_fn)(params, x, y)\n" ++
    (if hasWD then "    grads = jax.tree.map(lambda g, p: g + WD * p, grads, params)\n" else "") ++
    "    velocity = jax.tree.map(lambda v, g: MOMENTUM * v + g, velocity, grads)\n" ++
    "    params = jax.tree.map(lambda p, v: p - lr * v, params, velocity)\n" ++
    "    return params, velocity, loss\n\n"
  else
    "@jit\n" ++
    "def train_step(params, x, y, lr):\n" ++
    "    loss, grads = value_and_grad(loss_fn)(params, x, y)\n" ++
    (if hasWD then "    grads = jax.tree.map(lambda g, p: g + WD * p, grads, params)\n" else "") ++
    "    params = jax.tree.map(lambda p, g: p - lr * g, params, grads)\n" ++
    "    return params, loss\n\n") ++
  "@jit\n" ++
  "def eval_batch(params, x, y):\n" ++
  "    logits = forward(params, x)\n" ++
  "    preds = jnp.argmax(logits, axis=-1)\n" ++
  "    log_probs = jax.nn.log_softmax(logits, axis=-1)\n" ++
  "    loss = -jnp.mean(jnp.sum(log_probs * jax.nn.one_hot(y, " ++ toString nClasses ++ "), axis=-1))\n" ++
  "    correct = jnp.sum(preds == y)\n" ++
  "    return correct, loss\n\n" ++
  "def evaluate(params, images, labels, batch_size=512):\n" ++
  "    batch_size = (batch_size // n_devices) * n_devices or n_devices\n" ++
  "    correct = 0\n" ++
  "    total_loss = 0.0\n" ++
  "    n_batches = 0\n" ++
  "    for i in range(0, len(images) - batch_size + 1, batch_size):\n" ++
  "        c, l = eval_batch(params,\n" ++
  "            jax.device_put(images[i:i+batch_size], data_sharding),\n" ++
  "            jax.device_put(labels[i:i+batch_size], data_sharding))\n" ++
  "        correct += int(c)\n" ++
  "        total_loss += float(l)\n" ++
  "        n_batches += 1\n" ++
  "    evaluated = n_batches * batch_size\n" ++
  "    return correct, evaluated, total_loss / max(n_batches, 1)\n\n"

private def emitDataLoadCalls (ds : DatasetKind) (dataDir : String) (spec : NetSpec) : String :=
  let imgDesc := toString spec.imageH ++ "x" ++ toString spec.imageW
  match ds with
  | .mnist =>
    "    data_dir = \"" ++ dataDir ++ "\"\n" ++
    "    print(\"Loading training set …\")\n" ++
    "    train_images = load_mnist_images(os.path.join(data_dir, \"train-images-idx3-ubyte\"))\n" ++
    "    train_labels = load_mnist_labels(os.path.join(data_dir, \"train-labels-idx1-ubyte\"))\n" ++
    "    print(\"  \" + str(len(train_images)) + \" images, " ++ imgDesc ++ "\")\n\n" ++
    "    print(\"Loading test set …\")\n" ++
    "    test_images = load_mnist_images(os.path.join(data_dir, \"t10k-images-idx3-ubyte\"))\n" ++
    "    test_labels = load_mnist_labels(os.path.join(data_dir, \"t10k-labels-idx1-ubyte\"))\n" ++
    "    print(\"  \" + str(len(test_images)) + \" images, " ++ imgDesc ++ "\")\n\n"
  | .cifar10 =>
    "    data_dir = \"" ++ dataDir ++ "\"\n" ++
    "    print(\"Loading CIFAR-10 …\")\n" ++
    "    train_images, train_labels, test_images, test_labels = load_cifar10(data_dir)\n" ++
    "    print(\"  \" + str(len(train_images)) + \" train, \" + str(len(test_images)) + \" test, " ++ imgDesc ++ "x3\")\n\n"
  | .imagenette =>
    "    data_dir = \"" ++ dataDir ++ "\"\n" ++
    "    print(\"Loading Imagenette …\")\n" ++
    "    train_images, train_labels = load_imagenette(os.path.join(data_dir, \"train.bin\"))\n" ++
    "    test_images, test_labels = load_imagenette(os.path.join(data_dir, \"val.bin\"))\n" ++
    "    print(\"  \" + str(len(train_images)) + \" train, \" + str(len(test_images)) + \" val, " ++ imgDesc ++ "x3\")\n\n"

private def emitMain (spec : NetSpec) (cfg : TrainConfig) (ds : DatasetKind) (dataDir : String) : String :=
  let bs := toString cfg.batchSize
  let ep := toString cfg.epochs
  let lr := toString cfg.learningRate
  let nParams := toString spec.totalParams
  let seed := toString cfg.seed
  let hasMomentum := cfg.momentum > 0.0
  -- Pre-stage small datasets to GPU; keep large ones on CPU (batch transfer)
  let preStage := spec.imageH * spec.imageW ≤ 32 * 32
  "# ═══════════════════════════════════════════════════════════════════════\n" ++
  "#  Main\n" ++
  "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
  "if __name__ == \"__main__\":\n" ++
  "    print(\"" ++ spec.name ++ " · Lean 4 → JAX\")\n" ++
  "    print(\"  \" + \"" ++ spec.archStr ++ "\")\n" ++
  "    print()\n\n" ++
  emitDataLoadCalls ds dataDir spec ++
  "    BATCH_SIZE = (" ++ bs ++ " // n_devices) * n_devices or n_devices\n" ++
  "    EPOCHS = " ++ ep ++ "\n" ++
  "    print(\"lr=" ++ lr ++ "  batch_size=\" + str(BATCH_SIZE) + \" (\" + str(n_devices) + \" devices x \" + str(BATCH_SIZE // n_devices) + \")  epochs=\" + str(EPOCHS) + \"  params=" ++ nParams ++ "\")\n" ++
  "    print(\"backend=\" + str(jax.default_backend()) + \"  devices=\" + str(jax.devices()))\n" ++
  "    print(\"Starting training...\")\n\n" ++
  -- Init: load phase-3 dump if LEAN_MLIR_INIT_LOAD set, else JAX random.
  "    _init_load = os.environ.get('LEAN_MLIR_INIT_LOAD')\n" ++
  "    if _init_load:\n" ++
  "        print(f'Loading phase-3 init from {_init_load}')\n" ++
  "        params = init_params_from_file(_init_load)\n" ++
  "    else:\n" ++
  "        params = init_params(random.PRNGKey(" ++ seed ++ "))\n" ++
  "    params = jax.device_put(params, replicated_sharding)\n" ++
  "    rng = np.random.RandomState(42)\n" ++
  let useAdam := cfg.useAdam
  (if useAdam then
    "    opt_m = jax.tree.map(jnp.zeros_like, params)\n" ++
    "    opt_v = jax.tree.map(jnp.zeros_like, params)\n" ++
    "    opt_state = (opt_m, opt_v, jnp.float32(0))\n"
  else if hasMomentum then "    velocity = jax.tree.map(jnp.zeros_like, params)\n"
  else "") ++
  "\n" ++
  (if preStage then
  "    # Pre-stage all data as JAX arrays (one transfer, not per-batch)\n" ++
  "    train_images = jnp.array(train_images)\n" ++
  "    train_labels = jnp.array(train_labels)\n" ++
  "    test_images = jnp.array(test_images)\n" ++
  "    test_labels = jnp.array(test_labels)\n\n"
  else
  "    # Data stays on CPU; batches transferred to GPU on the fly\n\n") ++
  let warmup := toString cfg.warmupEpochs
  let hasCosine := cfg.cosineDecay
  "    # Trace emission (opt-in via LEAN_MLIR_TRACE_OUT env var). Matches\n" ++
  "    # the phase-3 format so cross-phase diffs work with tests/diff_traces.py.\n" ++
  "    _trace_path = os.environ.get('LEAN_MLIR_TRACE_OUT')\n" ++
  "    _trace_f = open(_trace_path, 'w') if _trace_path else None\n" ++
  "    if _trace_f:\n" ++
  "        _hdr = {\n" ++
  "            'kind': 'header', 'phase': 'phase2',\n" ++
  "            'netspec_name': " ++ "\"" ++ spec.name ++ "\"" ++ ",\n" ++
  "            'config': {\n" ++
  "                'lr': " ++ lr ++ ",\n" ++
  "                'batch_size': " ++ bs ++ ",\n" ++
  "                'epochs': " ++ ep ++ ",\n" ++
  "                'use_adam': " ++ (if cfg.useAdam then "True" else "False") ++ ",\n" ++
  "                'weight_decay': " ++ toString cfg.weightDecay ++ ",\n" ++
  "                'cosine': " ++ (if cfg.cosineDecay then "True" else "False") ++ ",\n" ++
  "                'warmup_epochs': " ++ toString cfg.warmupEpochs ++ ",\n" ++
  "                'augment': " ++ (if cfg.augment then "True" else "False") ++ ",\n" ++
  "                'label_smoothing': " ++ toString cfg.labelSmoothing ++ ",\n" ++
  "                'seed': " ++ seed ++ ",\n" ++
  "            },\n" ++
  "            'total_params': " ++ nParams ++ ",\n" ++
  "            'dataset': " ++ (match ds with
                                | .mnist => "'mnist'"
                                | .cifar10 => "'cifar10'"
                                | .imagenette => "'imagenette'") ++ ",\n" ++
  "            'emitter_version': '1',\n" ++
  "        }\n" ++
  "        _trace_f.write(json.dumps(_hdr) + '\\n')\n" ++
  "    _global_step = 0\n" ++
  "    t0 = time.time()\n" ++
  "    for epoch in range(EPOCHS):\n" ++
  (if hasCosine then
  "        # Cosine LR schedule" ++ (if cfg.warmupEpochs > 0 then " with warmup" else "") ++ "\n" ++
  (if cfg.warmupEpochs > 0 then
  "        if epoch < " ++ warmup ++ ":\n" ++
  "            lr = jnp.float32(LR * (epoch + 1) / " ++ warmup ++ ")\n" ++
  "        else:\n" ++
  "            lr = jnp.float32(LR * 0.5 * (1 + np.cos(np.pi * (epoch - " ++ warmup ++ ") / (EPOCHS - " ++ warmup ++ "))))\n"
  else
  "        lr = jnp.float32(LR * 0.5 * (1 + np.cos(np.pi * epoch / EPOCHS)))\n")
  else
  "        lr = jnp.float32(LR)\n") ++
  -- LEAN_MLIR_NO_SHUFFLE=1 disables per-epoch shuffling (matches phase 3
  -- under the same env var). Used for cross-phase step-level diffing.
  "        if os.environ.get('LEAN_MLIR_NO_SHUFFLE'):\n" ++
  "            shuf_images = train_images\n" ++
  "            shuf_labels = train_labels\n" ++
  "        else:\n" ++
  "            perm = rng.permutation(len(train_images))\n" ++
  "            shuf_images = train_images[perm]\n" ++
  "            shuf_labels = train_labels[perm]\n" ++
  let ic := match spec.layers.head? with
    | some (.conv2d ic ..) => ic | some (.convBn ic ..) => ic | _ => 3
  (if ¬preStage then  -- large images: random horizontal flip
  "        # Random horizontal flip (data augmentation)\n" ++
  "        flip = rng.random(len(shuf_images)) > 0.5\n" ++
  "        imgs4d = shuf_images.reshape(-1, " ++ toString ic ++ ", " ++
    toString spec.imageH ++ ", " ++ toString spec.imageW ++ ")\n" ++
  "        imgs4d[flip] = imgs4d[flip, :, :, ::-1]\n" ++
  "        shuf_images = imgs4d.reshape(len(shuf_images), -1)\n"
  else "") ++
  "        epoch_loss = 0.0\n" ++
  "        n_batches = 0\n" ++
  "        for i in range(0, len(train_images) - BATCH_SIZE + 1, BATCH_SIZE):\n" ++
  (if cfg.augment && spec.imageH > 32 then
  "            batch = augment_batch(shuf_images[i:i+BATCH_SIZE].copy(), rng)\n" ++
  "            x = jax.device_put(batch, data_sharding)\n"
  else
  "            x = jax.device_put(shuf_images[i:i+BATCH_SIZE], data_sharding)\n") ++
  "            y = jax.device_put(shuf_labels[i:i+BATCH_SIZE], data_sharding)\n" ++
  (if useAdam then
  "            params, opt_state, loss = train_step(params, opt_state, x, y, lr)\n"
  else if hasMomentum then
  "            params, velocity, loss = train_step(params, velocity, x, y, lr)\n"
  else
  "            params, loss = train_step(params, x, y, lr)\n") ++
  "            epoch_loss += float(loss)\n" ++
  "            n_batches += 1\n" ++
  "            _global_step += 1\n" ++
  "            if _trace_f:\n" ++
  "                _trace_f.write(json.dumps({\n" ++
  "                    'kind': 'step', 'step': _global_step, 'epoch': epoch,\n" ++
  "                    'loss': float(loss), 'lr': float(lr),\n" ++
  "                }) + '\\n')\n\n" ++
  "        correct, total, test_loss = evaluate(params, test_images, test_labels)\n" ++
  "        accuracy = correct / total\n" ++
  "        elapsed = time.time() - t0\n" ++
  "        print(\"[Epoch \" + str(epoch+1) + \"] lr=\" + str(round(float(lr), 6)) +\n" ++
  "              \" Accuracy: \" + str(correct) + \"/\" + str(total) +\n" ++
  "              \" (\" + str(round(accuracy, 4)) + \") Loss: \" + str(round(test_loss, 4)) +\n" ++
  "              \"  [\" + str(round(elapsed, 1)) + \"s]\")\n\n" ++
  "    print(\"\")\n" ++
  "    print(\"Done. Total time: \" + str(round(time.time() - t0, 1)) + \"s\")\n" ++
  "    if _trace_f: _trace_f.close()\n"

private def emitShardingSetup : String :=
  "# ═══════════════════════════════════════════════════════════════════════\n" ++
  "#  Multi-GPU data parallelism\n" ++
  "# ═══════════════════════════════════════════════════════════════════════\n\n" ++
  "devices = jax.devices()\n" ++
  "n_devices = len(devices)\n" ++
  "mesh = Mesh(np.array(devices), axis_names=('batch',))\n" ++
  "data_sharding = NamedSharding(mesh, P('batch'))\n" ++
  "replicated_sharding = NamedSharding(mesh, P())\n\n"

/-- Generate a complete, self-contained JAX training script from a Lean spec. -/
def generate (spec : NetSpec) (cfg : TrainConfig) (ds : DatasetKind) (dataDir : String) : String :=
  emitHeader spec ++
  emitImports ++
  emitDataLoading ds ++
  emitHelpers spec ++
  emitShardingSetup ++
  emitInitParams spec ++
  emitForward spec ++
  emitLossAndTraining spec cfg ++
  emitMain spec cfg ds dataDir

end JaxCodegen
