#!/usr/bin/env python3
"""NAME LINT — declaration names in `LeanMlir/` against Mathlib's naming convention.

The rules are Mathlib's (https://leanprover-community.github.io/contribute/naming.html) plus the
local addendum in `LeanMlir/NAMING.md`. Only what a regex over declaration headers can decide is
checked:

    theorem-case   a theorem/lemma name is snake_case — no lowerCamel/UpperCamel-only names
                   (`sealPos`), none starting upper-case (`EDiff_bn`; a Prop-valued def is
                   referenced lowerCamel: `eDiff_bn`)
    def-case       a def/abbrev/opaque name is lowerCamel (data) or UpperCamel (a Prop/Type) — no
                   underscores (`vjp_comp`), no ALL-CAPS constants (`NTOK`)
    retired-atom   spellings retired by the 2026-09 naming pass: `has_vjp` (the structure is
                   `HasVJP`, so the atom is `HasVJP`/`hasVJP`)

Two rules the regex cannot see stay review items: a `def` whose type is a `Prop` should be a
`theorem`, and a `_diff` / `_eq` / `_iff` suffix must say what the statement is (NAMING.md).

Files whose header says they were generated (`Generated by` / `GENERATED by`) are skipped: their
names are indexed certificate tables (NAMING.md, "Exemptions").

⚠ A ratchet, like `convention_audit.py`: `name_lint_baseline.txt` lists the names this repo still
carries. It may SHRINK, never grow — a name not in it fails the gate.

Usage:
    python3 scripts/gates/name_lint.py                    # gate: exit 1 on a name not in the baseline
    python3 scripts/gates/name_lint.py --update-baseline  # rewrite the baseline from the tree
"""
import argparse, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BASELINE = ROOT / "scripts" / "gates" / "name_lint_baseline.txt"
GENERATED = re.compile(r"Generated by|GENERATED by")
DECL = re.compile(
    r"^[ \t]*(?:@\[[^\]]*\][ \t]*)?(?:(?:private|protected|noncomputable|partial|unsafe|nonrec)[ \t]+)*"
    r"(theorem|lemma|def|abbrev|opaque)[ \t]+([^\s(:{\[]+)", re.M)


def violations(kind: str, name: str) -> list[str]:
    s = name.removeprefix("_root_.").split(".")[-1]
    if not s or not re.match(r"[A-Za-z]", s):   # `_foo` here is Python quoted in a docstring
        return []
    out = []
    if "has_vjp" in s:
        out.append("retired-atom")
    if kind in ("theorem", "lemma"):
        if s[0].isupper() or ("_" not in s and re.search(r"[A-Z]", s)):
            out.append("theorem-case")
    elif "_" in s.strip("_") or re.fullmatch(r"[A-Z][A-Z0-9_]+", s):
        out.append("def-case")
    return out


def scan() -> list[str]:
    files = subprocess.check_output(["git", "ls-files", "LeanMlir.lean", "LeanMlir/*.lean"],
                                    cwd=ROOT, text=True).split()
    rows = []
    for f in files:
        text = (ROOT / f).read_text(encoding="utf-8")
        if GENERATED.search(text[:4000]):
            continue
        for m in DECL.finditer(text):
            for rule in violations(m.group(1), m.group(2)):
                rows.append(f"{f}\t{m.group(2)}\t{rule}")
    return sorted(set(rows))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-baseline", action="store_true")
    args = ap.parse_args()
    rows = scan()
    if args.update_baseline:
        head = [l for l in BASELINE.read_text().splitlines() if l.startswith("#")] if BASELINE.exists() else []
        BASELINE.write_text("\n".join(head + rows) + "\n")
        print(f"wrote {BASELINE.relative_to(ROOT)}: {len(rows)} names")
        return 0
    base = {l for l in BASELINE.read_text().splitlines() if l and not l.startswith("#")}
    new = [r for r in rows if r not in base]
    gone = sorted(base - set(rows))
    for r in new:
        f, n, rule = r.split("\t")
        print(f"✗ {rule}: {n}  ({f})")
    if gone:
        print(f"note: {len(gone)} baseline name(s) no longer occur — shrink the baseline with --update-baseline")
    if new:
        print(f"✗ {len(new)} name(s) outside the naming convention and not in the baseline "
              "(LeanMlir/NAMING.md)")
        return 1
    print(f"✓ name lint: {len(rows)} grandfathered name(s), none new")
    return 0


if __name__ == "__main__":
    sys.exit(main())
