#!/usr/bin/env python3
"""Generate PLATFORMS.md from every runs/platform/*/manifest.json + results.tsv.

One row per run, newest first. scripts/platform/check.sh calls this after each run; `--check`
fails if the committed file is stale.
"""
import csv, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUNS = ROOT / 'runs' / 'platform'
OUT = ROOT / 'PLATFORMS.md'

HEAD = """# Platforms

Which GPU platforms run which build of this repo. Generated by
`scripts/platform/platforms_md.py` from `runs/platform/*/` — do not hand-edit. The suite is
`scripts/platform/check.sh` (`--plan` shows what it runs); the design is
[`planning/platform_integration.md`](planning/platform_integration.md).

A run is green when every test matches the platform's baseline in
`scripts/platform/expected/`. When a run turns red, diff its `manifest.json` against the last
green run on the same box: core equal and platform changed points at the driver or plugin;
platform equal and core changed points at this repo.

| date | host | GPUs | driver | runtime | plugin | PJRT API | repo | tiers | pass | xfail | fail | skip | |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
"""


def row(d):
    m = json.loads((d / 'manifest.json').read_text())
    with open(d / 'results.tsv') as f:
        res = [r for r in csv.DictReader(f, delimiter='\t') if not r['test'].startswith('build:')
               or r['status'] != 'PASS']
    n = {s: sum(r['status'] == s for r in res) for s in ('PASS', 'XFAIL', 'FAIL', 'XPASS', 'SKIP')}
    c, p = m['core'], m['platform']
    names = sorted({g['name'] for g in p['gpus']}) or [p.get('platform_name') or '?']
    gpus = f"{len(p['gpus']) or p['gpu_count_visible']}× " + ' / '.join(
        x.replace('NVIDIA GeForce ', '') for x in names)
    rt = p.get('runtime') or {}
    runtime = ', '.join(f'{k} {v}' for k, v in rt.items() if k in ('runtime', 'dnn')) or p.get('platform_version') or ''
    plugin = p.get('plugin_package') or Path(p.get('plugin_path') or '?').name
    api = f"{p.get('pjrt_api_plugin')} (hdr {c.get('pjrt_api_header')})"
    repo = c['repo_sha'][:8] + ('+dirty' if c.get('repo_dirty') else '')
    verdict = '✅' if n['FAIL'] == 0 and n['XPASS'] == 0 else ('⚠ xpass' if n['FAIL'] == 0 else '❌')
    link = f"[{verdict}](runs/platform/{d.name}/results.tsv)"
    return (m['date'], f"| {m['date'][:10]} | {p['host']} | {gpus} | {p.get('driver') or ''} | {runtime} "
            f"| {plugin} | {api} | `{repo}` | 0–{c['tier']} | {n['PASS']} | {n['XFAIL']} "
            f"| {n['FAIL']} | {n['SKIP']} | {link} |")


def render():
    rows = sorted((row(d) for d in RUNS.iterdir()
                   if (d / 'manifest.json').exists() and (d / 'results.tsv').exists()),
                  reverse=True) if RUNS.exists() else []
    return HEAD + ''.join(r + '\n' for _, r in rows)


def main():
    text = render()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit('PLATFORMS.md is stale — run scripts/platform/platforms_md.py')
        print('✓ PLATFORMS.md matches runs/platform/')
        return
    OUT.write_text(text)


if __name__ == '__main__':
    main()
