#!/usr/bin/env python3
"""Emit the Lipschitz-hypothesis probe as a pgfplots scatter (.tex), repo val_curve style.

Reads runs/smooth_<slug>_lipschitz.csv (sigma,img_idx,delta,dg,bound,ratio). Plots the normalized
ratio  Δg·σ/‖δ‖ = |Φ⁻¹(p_ĉ(x+δ)) − Φ⁻¹(p_ĉ(x))| / (‖δ‖/σ)  against the input shift ‖δ‖. The
(1/σ)-Lipschitz hypothesis of smoothing_certified_radius is exactly ratio ≤ 1 — a single horizontal
line, σ-independent. Every measured point below y=1 grounds the theorem's assumption on the real net.
"""
import csv, sys, os
from collections import defaultdict

SLUG = sys.argv[1] if len(sys.argv) > 1 else "cnn"
TITLE = {"mlp": "MNIST-MLP", "cnn": "MNIST-CNN", "cifar": "CIFAR-CNN"}.get(SLUG, SLUG)
STYLE = {0.12: "green!55!black", 0.25: "orange", 0.5: "blue"}

path = f"runs/smooth_{SLUG}_lipschitz.csv"
if not os.path.exists(path):
    sys.exit(f"missing {path} — run with SMOOTH_LIP_PROBE=1 first")

bysig = defaultdict(list)
nmax = 0.0
for row in csv.DictReader(open(path)):
    s = float(row["sigma"]); d = float(row["delta"]); r = float(row["ratio"])
    bysig[s].append((d, r)); nmax = max(nmax, r)

out = []
out.append(f"% Lipschitz-hypothesis probe on {TITLE}: ratio Δg·σ/‖δ‖ vs ‖δ‖. ratio≤1 ⇔ (1/σ)-Lipschitz.")
out.append("% Generated by scripts/emit_lipschitz_tikz.py.")
out.append("\\begin{center}")
out.append("\\begin{tikzpicture}")
out.append("\\begin{axis}[")
out.append("    width=0.78\\linewidth, height=6.5cm,")
out.append("    xlabel={Input shift $\\|\\delta\\|_2$},")
out.append("    ylabel={$|\\Delta g|\\,\\sigma/\\|\\delta\\|$ \\;(normalized)},")
out.append(f"    title={{{TITLE}: $\\Phi^{{-1}}\\!\\circ p_{{\\hat c}}$ is $(1/\\sigma)$-Lipschitz}},")
out.append("    xmin=0, xmax=1.05,")
out.append(f"    ymin=0, ymax={max(1.15, round(nmax + 0.1, 2))},")
out.append("    grid=major, grid style={gray!18},")
out.append("    tick label style={font=\\small}, label style={font=\\small},")
out.append("    title style={font=\\small\\bfseries},")
out.append("    legend pos=north east, legend cell align={left},")
out.append("    legend style={font=\\footnotesize, draw=none, fill=none},")
out.append("]")
# the proven bound: a horizontal line at ratio = 1
out.append("\\addplot[black, dashed, line width=1pt, forget plot] coordinates {(0,1) (1.05,1)};")
out.append("\\node[anchor=south east, font=\\footnotesize] at (axis cs:1.03,1.0) "
           "{proven bound $|\\Delta g|\\le\\|\\delta\\|/\\sigma$};")
for sig in sorted(bysig):
    col = STYLE.get(sig, "black")
    coords = " ".join(f"({d:.3f},{r:.3f})" for d, r in bysig[sig])
    out.append(f"\\addplot[only marks, mark=*, mark size=0.8pt, {col}, opacity=0.55] "
               f"coordinates {{{coords}}};")
    out.append(f"\\addlegendentry{{$\\sigma={sig:g}$}}")
out.append("\\end{axis}")
out.append("\\end{tikzpicture}")
out.append("\\end{center}")
out.append("")
ntot = sum(len(v) for v in bysig.values())
nbelow = sum(1 for v in bysig.values() for (_d, r) in v if r <= 1.0)
out.append(f"\\noindent Empirical grounding of the randomized-smoothing certificate on {TITLE}: each")
out.append("point shifts a test input by a known $\\|\\delta\\|_2$ and measures the resulting change in")
out.append("the probit score $g_{\\hat c}=\\Phi^{-1}(P[f(x+\\eta)=\\hat c])$, normalized by the bound")
out.append("$\\|\\delta\\|/\\sigma$. The $(1/\\sigma)$-Lipschitz hypothesis of")
out.append("\\texttt{smoothing\\_certified\\_radius} is exactly ``every point $\\le 1$'' (dashed):")
out.append(f"${nbelow}/{ntot}$ measurements satisfy it; the few above (smallest $\\|\\delta\\|$, largest")
out.append("$\\sigma$) are within Monte-Carlo error of the finite-sample $\\hat p$. The assumption the")
out.append("proof takes for granted is here \\emph{measured} on the trained net.")

open(f"runs/lipschitz_{SLUG}.tex", "w").write("\n".join(out) + "\n")
print(f"wrote runs/lipschitz_{SLUG}.tex  ({sum(len(v) for v in bysig.values())} points, max ratio {nmax:.3f})")
