#!/usr/bin/env python3
"""Emit the randomized-smoothing radius–accuracy frontier as a pgfplots groupplot (.tex),
matching the repo's jax/runs/*_val_curve.tex style. Reads runs/smooth_<slug>_radii.csv.

Certified accuracy at radius r = #(correct AND certified radius >= r) / n_sample. The vertical
drop at the right of each curve is the n-ceiling sigma*Phi^{-1}(alpha^{1/n}) — the max attainable
radius. Needs \\usepgfplotslibrary{groupplots} in the preamble.
"""
import csv, os
from collections import defaultdict
import numpy as np

NETS = [("mlp", "MNIST-MLP"), ("cnn", "MNIST-CNN"), ("cifar", "CIFAR-CNN")]
# sigma -> (xcolor name, dash) ; colours from the repo palette (blue/orange) + a green
STYLE = {0.12: ("green!55!black", ""), 0.25: ("orange", ""), 0.5: ("blue", "")}

def load(slug):
    path = f"runs/smooth_{slug}_radii.csv"
    if not os.path.exists(path):
        return None
    corr = defaultdict(list); tot = defaultdict(int)
    for row in csv.DictReader(open(path)):
        s = float(row["sigma"]); tot[s] += 1
        if row["abstain"] == "0" and row["pred"] == row["label"]:
            corr[s].append(float(row["radius"]))
    return {s: (np.array(sorted(corr[s])), tot[s]) for s in sorted(tot)}

def curve_coords(radii, n, npts=26):
    """(x,y) along the frontier from r=0 to the n-ceiling, then a vertical drop to 0."""
    if not len(radii):
        return [(0.0, 0.0)]
    ceil = radii.max()
    xs = np.linspace(0, ceil, npts)
    ys = (len(radii) - np.searchsorted(radii, xs, side="left")) / n * 100.0
    pts = [(round(float(x), 3), round(float(y), 1)) for x, y in zip(xs, ys)]
    pts.append((round(float(ceil), 3), 0.0))            # the n-ceiling cliff
    return pts

def fmt(pts):
    return " ".join(f"({x},{y})" for x, y in pts)

out = []
out.append("% Randomized-smoothing certified accuracy on the verified nets (Cohen 2019, n=10112,")
out.append("% alpha=0.001, forward-only). Generated by scripts/emit_smoothing_tikz.py.")
out.append("% Preamble needs: \\usepgfplotslibrary{groupplots}")
out.append("\\begin{center}")
out.append("\\begin{tikzpicture}")
out.append("\\begin{groupplot}[")
out.append("    group style={group size=3 by 1, horizontal sep=1.1cm},")
out.append("    width=0.39\\linewidth, height=6cm,")
out.append("    xmin=0, xmax=1.7, ymin=0, ymax=102,")
out.append("    xtick={0,0.4,0.8,1.2,1.6}, ytick={0,20,40,60,80,100},")
out.append("    xlabel={Certified $L_2$ radius},")
out.append("    grid=major, grid style={gray!18},")
out.append("    tick label style={font=\\small}, label style={font=\\small},")
out.append("    title style={font=\\small\\bfseries},")
out.append("    legend pos=south west, legend cell align={left},")
out.append("    legend style={font=\\footnotesize, draw=none, fill=none},")
out.append("    every axis plot/.append style={line width=1pt},")
out.append("]")

acr_summary = []  # (title, [(sig, acr), ...]) for the caption
for slug, title in NETS:
    data = load(slug)
    opts = [f"title={{{title}}}"]
    if slug == "mlp":   opts.append("ylabel={Certified accuracy (\\%)}")
    if slug == "cifar": opts.append("legend pos=north east")  # CIFAR curves sit low-left
    out.append(f"\\nextgroupplot[{', '.join(opts)}]")
    if not data:
        continue
    acrs = []
    for sig in sorted(data):
        radii, n = data[sig]
        acrs.append((sig, radii.sum() / n))
        col, _ = STYLE.get(sig, ("black", ""))
        out.append(f"\\addplot[{col}] coordinates {{{fmt(curve_coords(radii, n))}}};")
        out.append(f"\\addlegendentry{{$\\sigma={sig:g}$}}")
    acr_summary.append((title, acrs))

out.append("\\end{groupplot}")
out.append("\\end{tikzpicture}")
out.append("\\end{center}")
out.append("")
acr_str = "; ".join(t + " " + "/".join(f"{a:.2f}" for _, a in xs) for t, xs in acr_summary)
out.append("\\noindent Randomized-smoothing certified accuracy vs.\\ $L_2$ radius on the verified")
out.append("nets (Cohen et al.\\ 2019; $n{=}10112$ samples, $\\alpha{=}0.001$; forward-only). Each")
out.append("curve is one noise level $\\sigma$; the vertical drop is the $n$-ceiling")
out.append("$\\sigma\\,\\Phi^{-1}(\\alpha^{1/n})$. The Lipschitz-product certificate is $0\\%$ at every")
out.append("radius on these same nets. Average certified radius (ACR) per $\\sigma$:")
out.append(acr_str + ".")

open("runs/smoothing_frontier.tex", "w").write("\n".join(out) + "\n")
print("wrote runs/smoothing_frontier.tex")
