#!/usr/bin/env python3
"""Generate `ffi/pjrt_compile_options.h` — the serialized CompileOptionsProto
that `PJRT_Client_Compile` requires.

This is the *only* place Python touches the XLA/PJRT path, and it runs at
**build time**, not run time: the output is a checked-in C header holding a byte
array. The trainers themselves are pure Lean + C.

Why a blob at all: `PJRT_Program` takes StableHLO text directly (no protobuf),
but `PJRT_Client_Compile` wants `compile_options` as a serialized
`CompileOptionsProto`. Passing zero bytes is *not* equivalent to defaults —
proto3 zero-defaults give `replica_count = 0`, and XLA aborts with
`Check failed: replica_count > 0`. Capturing the options the installed XLA
actually constructs also keeps `DebugOptions` identical to what JAX would use,
so timing comparisons against JAX are apples-to-apples.

Regenerate (only needed if the XLA/PJRT plugin version changes):

    /home/skoonce/lean/claude_max/lean4-jax/.venv/bin/python3 \
        scripts/gen_pjrt_compile_options.py > ffi/pjrt_compile_options.h
"""
import sys

from jax._src.lib import xla_client as xc

# One blob per supported replica count. Multi-GPU (replica_groups in the emitted
# graph) needs num_replicas to match, and embedding a small table keeps the run
# time free of any generated-file dependency.
REPLICAS = [1, 2, 4, 8]

def blob_for(n):
    o = xc.CompileOptions()
    o.executable_build_options.num_replicas = n
    o.executable_build_options.num_partitions = 1
    return o.SerializeAsString()

blobs = {n: blob_for(n) for n in REPLICAS}

out = sys.stdout
out.write("// GENERATED by scripts/gen_pjrt_compile_options.py — do not edit by hand.\n")
out.write("// Serialized xla.CompileOptionsProto, one per replica count (num_partitions=1).\n")
out.write("#ifndef PJRT_COMPILE_OPTIONS_H_\n#define PJRT_COMPILE_OPTIONS_H_\n\n")
out.write("#include <stddef.h>\n\n")
for n in REPLICAS:
    b = blobs[n]
    out.write("static const unsigned char kPjrtCompileOptions%d[] = {\n" % n)
    for i in range(0, len(b), 12):
        out.write("    %s,\n" % ", ".join("0x%02x" % c for c in b[i:i + 12]))
    out.write("};\n\n")

# Back-compat aliases: the single-replica blob.
out.write("#define kPjrtCompileOptions      kPjrtCompileOptions1\n")
out.write("#define kPjrtCompileOptionsSize  sizeof(kPjrtCompileOptions1)\n\n")

out.write("// Options for `n` replicas, or NULL if `n` is not in the table.\n")
out.write("static const unsigned char* pjrt_compile_options_for(int n, size_t* len) {\n")
out.write("  switch (n) {\n")
for n in REPLICAS:
    out.write("    case %d: *len = sizeof(kPjrtCompileOptions%d); return kPjrtCompileOptions%d;\n" % (n, n, n))
out.write("    default: *len = 0; return 0;\n  }\n}\n\n")
out.write("#endif  // PJRT_COMPILE_OPTIONS_H_\n")
