#!/usr/bin/env python3
"""Generate `ffi/pjrt_compile_options.h` — the serialized CompileOptionsProto
that `PJRT_Client_Compile` requires.

This is the *only* place Python touches the XLA/PJRT path, and it runs at
**build time**, not run time: the output is a checked-in C header holding a byte
array. The trainers themselves are pure Lean + C.

Why a blob at all: `PJRT_Program` takes StableHLO text directly (no protobuf),
but `PJRT_Client_Compile` wants `compile_options` as a serialized
`CompileOptionsProto`. Passing zero bytes is *not* equivalent to defaults —
proto3 zero-defaults give `replica_count = 0`, and XLA aborts with
`Check failed: replica_count > 0`. Capturing the options the installed XLA
actually constructs also keeps `DebugOptions` identical to what JAX would use,
so timing comparisons against JAX are apples-to-apples.

Regenerate (only needed if the XLA/PJRT plugin version changes):

    /home/skoonce/lean/claude_max/lean4-jax/.venv/bin/python3 \
        scripts/gen_pjrt_compile_options.py > ffi/pjrt_compile_options.h
"""
import sys

from jax._src.lib import xla_client as xc

opts = xc.CompileOptions()
opts.executable_build_options.num_replicas = 1
opts.executable_build_options.num_partitions = 1
blob = opts.SerializeAsString()

out = sys.stdout
out.write("// GENERATED by scripts/gen_pjrt_compile_options.py — do not edit by hand.\n")
out.write("// Serialized xla.CompileOptionsProto (num_replicas=1, num_partitions=1).\n")
out.write("#ifndef PJRT_COMPILE_OPTIONS_H_\n#define PJRT_COMPILE_OPTIONS_H_\n\n")
out.write("#include <stddef.h>\n\n")
out.write("static const unsigned char kPjrtCompileOptions[] = {\n")
for i in range(0, len(blob), 12):
    row = ", ".join("0x%02x" % b for b in blob[i:i + 12])
    out.write("    %s,\n" % row)
out.write("};\n\n")
out.write("static const size_t kPjrtCompileOptionsSize = sizeof(kPjrtCompileOptions);\n\n")
out.write("#endif  // PJRT_COMPILE_OPTIONS_H_\n")
