#!/usr/bin/env python3
"""Generate `ffi/pjrt_compile_options.h` — the serialized CompileOptionsProto
that `PJRT_Client_Compile` requires.

This is the *only* place Python touches the XLA/PJRT path, and it runs at
**build time**, not run time: the output is a checked-in C header holding a byte
array. The trainers themselves are pure Lean + C.

Why a blob at all: `PJRT_Program` takes StableHLO text directly (no protobuf),
but `PJRT_Client_Compile` wants `compile_options` as a serialized
`CompileOptionsProto`. Passing zero bytes is *not* equivalent to defaults —
proto3 zero-defaults give `replica_count = 0`, and XLA aborts with
`Check failed: replica_count > 0`. Capturing the options the installed XLA
actually constructs also keeps `DebugOptions` identical to what JAX would use,
so timing comparisons against JAX are apples-to-apples.

⚠⚠ **THE BLOB IS FROZEN, SO `$XLA_FLAGS` DOES NOTHING TO A TRAINER.** JAX builds
its CompileOptions in-process and picks the environment up; we hand PJRT these
bytes, which override it. Setting a flag on the command line and watching it be
ignored — with an identical backtrace either side — is a genuinely expensive
way to learn that. Anything you need changed has to be baked in HERE.

⚠ The DebugOptions fields are NOT settable through the Python binding
(`jaxlib._jax.DebugOptions` exposes no `xla_gpu_enable_command_buffer`), which
is why the ROCm variant below goes through `env_option_overrides` — the same
map JAX uses to pass flags per-compile.

Two tables are emitted:

  kPjrtCompileOptions<n>       stock — what the installed XLA constructs
  kPjrtCompileOptionsNoCB<n>   the same, plus command buffers disabled

`ffi/pjrt_ffi.c` selects between them by PLATFORM at run time: ROCm gets NoCB,
CUDA gets stock. See the comment at `command_buffers_disabled()` there for why
that default exists and what it costs (measured: nothing).

Regenerate (only needed if the XLA/PJRT plugin version changes):

    /home/skoonce/lean/claude_max/lean4-jax/.venv/bin/python3 \
        scripts/gen_pjrt_compile_options.py > ffi/pjrt_compile_options.h
"""
import sys

from jax._src.lib import xla_client as xc

# One blob per supported replica count. Multi-GPU (replica_groups in the emitted
# graph) needs num_replicas to match, and embedding a small table keeps the run
# time free of any generated-file dependency.
REPLICAS = [1, 2, 4, 8]

# Disabling command buffers = an EMPTY list of command-buffer command types,
# which is exactly what `XLA_FLAGS=--xla_gpu_enable_command_buffer=` expresses.
NO_COMMAND_BUFFERS = [("xla_gpu_enable_command_buffer", "")]


def blob_for(n, overrides=None):
    o = xc.CompileOptions()
    o.executable_build_options.num_replicas = n
    o.executable_build_options.num_partitions = 1
    if overrides:
        o.env_option_overrides = list(overrides)
    return o.SerializeAsString()


blobs = {n: blob_for(n) for n in REPLICAS}
blobs_nocb = {n: blob_for(n, NO_COMMAND_BUFFERS) for n in REPLICAS}

# A regeneration where the override silently did nothing would hand ROCm the
# stock options under a name promising otherwise — the exact class of failure
# this file's header comment is about. One `==` catches it at generation.
for n in REPLICAS:
    if blobs[n] == blobs_nocb[n]:
        sys.exit("FAIL: env_option_overrides had no effect on the %d-replica blob — "
                 "the installed xla_client may have dropped the field; the ROCm "
                 "table would be a silent copy of the stock one." % n)

out = sys.stdout
out.write("// GENERATED by scripts/gen_pjrt_compile_options.py — do not edit by hand.\n")
out.write("// Serialized xla.CompileOptionsProto, one per replica count (num_partitions=1).\n")
out.write("// Two tables: stock, and one with XLA's command buffers disabled (ROCm — see\n")
out.write("// ffi/pjrt_ffi.c `command_buffers_disabled()`).\n")
out.write("#ifndef PJRT_COMPILE_OPTIONS_H_\n#define PJRT_COMPILE_OPTIONS_H_\n\n")
out.write("#include <stddef.h>\n\n")


def emit(name, table):
    for n in REPLICAS:
        b = table[n]
        out.write("static const unsigned char %s%d[] = {\n" % (name, n))
        for i in range(0, len(b), 12):
            out.write("    %s,\n" % ", ".join("0x%02x" % c for c in b[i:i + 12]))
        out.write("};\n\n")


emit("kPjrtCompileOptions", blobs)
emit("kPjrtCompileOptionsNoCB", blobs_nocb)

# Back-compat aliases: the single-replica blob.
out.write("#define kPjrtCompileOptions      kPjrtCompileOptions1\n")
out.write("#define kPjrtCompileOptionsSize  sizeof(kPjrtCompileOptions1)\n\n")

out.write("// Options for `n` replicas, or NULL if `n` is not in the table.\n")
out.write("// `nocb` selects the command-buffer-free table (ROCm).\n")
out.write("static const unsigned char* pjrt_compile_options_for(int n, int nocb, size_t* len) {\n")
out.write("  if (nocb) {\n    switch (n) {\n")
for n in REPLICAS:
    out.write("      case %d: *len = sizeof(kPjrtCompileOptionsNoCB%d); return kPjrtCompileOptionsNoCB%d;\n" % (n, n, n))
out.write("      default: *len = 0; return 0;\n    }\n  }\n")
out.write("  switch (n) {\n")
for n in REPLICAS:
    out.write("    case %d: *len = sizeof(kPjrtCompileOptions%d); return kPjrtCompileOptions%d;\n" % (n, n, n))
out.write("    default: *len = 0; return 0;\n  }\n}\n\n")
out.write("#endif  // PJRT_COMPILE_OPTIONS_H_\n")
