import numpy as np, struct
from fractions import Fraction
from math import isqrt, ceil

rng = np.random.default_rng(0)
D = "/home/skoonce/lean/klawd_max_power/lean4-jax/data/"

def load_images(fn):
    with open(fn, "rb") as f:
        _, n, r, c = struct.unpack(">IIII", f.read(16))
        return np.frombuffer(f.read(), dtype=np.uint8).reshape(n, r, c)

def load_labels(fn):
    with open(fn, "rb") as f:
        _, n = struct.unpack(">II", f.read(8))
        return np.frombuffer(f.read(), dtype=np.uint8)

Xtr_raw = load_images(D + "train-images-idx3-ubyte")
ytr = load_labels(D + "train-labels-idx1-ubyte")
Xte_raw = load_images(D + "t10k-images-idx3-ubyte")
yte = load_labels(D + "t10k-labels-idx1-ubyte")

# 4x4 average pool -> 7x7 = 49 features; keep integer pixel-sums for exactness
def pool_sums(X):  # integer sums in 0..4080
    return X.reshape(-1, 7, 4, 7, 4).astype(np.int64).sum(axis=(2, 4)).reshape(-1, 49)

Str = pool_sums(Xtr_raw); Ste = pool_sums(Xte_raw)
Xtr = Str / 4080.0; Xte = Ste / 4080.0

# ── train bias-free 49->8->10 MLP, softmax CE, plain SGD ──
H, K, DIM = 8, 10, 49
W1 = rng.normal(0, np.sqrt(2.0 / DIM), (H, DIM))
W2 = rng.normal(0, np.sqrt(2.0 / H), (K, H))
lr, bs = 0.15, 64
for ep in range(12):
    idx = rng.permutation(len(Xtr))
    for b in range(0, len(Xtr), bs):
        xb = Xtr[idx[b:b+bs]]; yb = ytr[idx[b:b+bs]]
        h = xb @ W1.T; hr = np.maximum(h, 0)
        z = hr @ W2.T
        z -= z.max(1, keepdims=True)
        p = np.exp(z); p /= p.sum(1, keepdims=True)
        g = p.copy(); g[np.arange(len(yb)), yb] -= 1; g /= len(yb)
        gW2 = g.T @ hr
        gh = (g @ W2) * (h > 0)
        gW1 = gh.T @ xb
        W1 -= lr * gW1; W2 -= lr * gW2
    hr = np.maximum(Xte @ W1.T, 0)
    acc = (np.argmax(hr @ W2.T, 1) == yte).mean()
    print(f"epoch {ep}: test acc {acc:.4f}")

# ── rationalize to /128 ──
W1q = np.round(W1 * 128).astype(np.int64)   # H x DIM
W2q = np.round(W2 * 128).astype(np.int64)   # K x H
hrq = np.maximum(Xte @ (W1q / 128).T, 0)
zq = hrq @ (W2q / 128).T
accq = (np.argmax(zq, 1) == yte).mean()
print(f"quantized (/128) test acc {accq:.4f}")
print(f"|W1q| max {abs(W1q).max()}, |W2q| max {abs(W2q).max()}")

# ── pick correctly-classified test sample with max margin (quantized net) ──
top = np.argmax(zq, 1)
z2 = np.partition(zq, -2, axis=1)[:, -2]
margin = zq[np.arange(len(zq)), top] - z2
ok = top == yte
cand = np.argmax(np.where(ok, margin, -1))
print(f"sample idx {cand}, label {yte[cand]}, float margin {margin[cand]:.4f}")

# ── exact rational recomputation ──
s = [int(v) for v in Ste[cand]]                      # x_j = s_j / 4080
DEN_X, DEN_W = 4080, 128
pre_num = [sum(int(W1q[k, j]) * s[j] for j in range(DIM)) for k in range(H)]
# preact_k = pre_num[k] / (128*4080)
DEN_H = DEN_W * DEN_X                                # 522240
hid_num = [max(n, 0) for n in pre_num]               # relu, same denominator
logit = [Fraction(sum(int(W2q[c, k]) * hid_num[k] for k in range(H)), DEN_W * DEN_H)
         for c in range(K)]
i0 = max(range(K), key=lambda c: logit[c])
assert i0 == yte[cand] == top[cand]
runner = max(logit[c] for c in range(K) if c != i0)
margin_exact = logit[i0] - runner
m = Fraction(int(margin_exact * 1000), 1000)         # floor to /1000, m <= margin
assert 0 < m <= margin_exact
print(f"exact margin {float(margin_exact):.6f}, m = {m} = {float(m):.4f}")

# ── Frobenius bounds: C = ceil(sqrt(S)*1000)/1000, verified exactly ──
def frob_C(Wq):
    S = Fraction(int((Wq.astype(object) ** 2).sum()), DEN_W * DEN_W)
    c = Fraction(ceil((float(S) ** 0.5) * 1000), 1000)
    while c * c < S:
        c += Fraction(1, 1000)
    return S, c

S1, C1 = frob_C(W1q); S2, C2 = frob_C(W2q)
LL = C2 * C1
print(f"S1={float(S1):.4f} C1={C1}({float(C1)}), S2={float(S2):.4f} C2={C2}({float(C2)})")
print(f"L = C2*C1 = {LL} = {float(LL):.4f}")
rad = float(m) / (2 ** 0.5 * float(LL))
print(f"certified radius = m/(sqrt2*L) ~= {rad:.6f}   (input norm {np.linalg.norm(Xte[cand]):.3f})")

# ── emit Lean ──
def frac(q):
    q = Fraction(q)
    if q.denominator == 1:
        return f"({q.numerator} : ℝ)"
    return f"(({q.numerator} : ℝ)/{q.denominator})"

def row(vals, den):
    return "![" + ", ".join(f"(({int(v)} : ℝ)/{den})" for v in vals) + "]"

lines = []
A = lines.append
A("")
A("-- ════════════════════════════════════════════════════════════")
A("-- § Instance 3: TRAINED weights (MNIST, 4×4-pooled to 7×7), rationalized")
A("--")
A(f"-- 49→8→10 bias-free ReLU MLP trained on pooled MNIST (test acc ≈{acc:.3f});")
A(f"-- weights rounded to /128 rationals (quantized test acc ≈{accq:.3f}). Test image")
A(f"-- #{cand} (digit {int(yte[cand])}); every quantity below is exact rational arithmetic")
A("-- checked in-kernel. Generated by scripts (see planning); weights are DATA here.")
A("-- ════════════════════════════════════════════════════════════")
A("")
A("/-- Trained hidden-layer weights (8×49), entries `k/128`. -/")
A("def W1t : Fin 8 → Fin 49 → ℝ :=")
A("  ![" + ",\n    ".join(row(W1q[k], 128) for k in range(H)) + "]")
A("")
A("/-- Trained output-layer weights (10×8), entries `k/128`. -/")
A("def W2t : Fin 10 → Fin 8 → ℝ :=")
A("  ![" + ",\n    ".join(row(W2q[c], 128) for c in range(K)) + "]")
A("")
A(f"/-- MNIST test image #{cand} (digit {int(yte[cand])}), 4×4-average-pooled: exact pixel")
A("    sums over 4080 (= 255·16). -/")
A("noncomputable def xt : EuclideanSpace ℝ (Fin 49) :=")
A("  WithLp.toLp 2 " + row(s, 4080))
A("")
A("/-- The trained MLP: dense → ReLU → dense. -/")
A("noncomputable def mlpT : EuclideanSpace ℝ (Fin 49) → EuclideanSpace ℝ (Fin 10) :=")
A("  denseE W2t ∘ reluE ∘ denseE W1t")
A("")
A("/-- Exact hidden pre-activations of `xt` (denominator 128·4080). -/")
A("def hpreVals : Fin 8 → ℝ :=")
A("  " + row(pre_num, DEN_H))
A("")
A("theorem hpre_eval : ∀ k : Fin 8, denseE W1t xt k = hpreVals k := by")
A("  intro k")
A("  fin_cases k <;>")
A("    · simp [denseE_apply, W1t, xt, hpreVals, Fin.sum_univ_succ]")
A("      norm_num")
A("")
A(f"/-- Frobenius² of `W1t` is ≤ C₁² for C₁ = {C1} ≈ ‖W1t‖_F. -/")
A(f"theorem W1t_lip : LipschitzL2 {frac(C1)} (denseE W1t) := by")
A("  refine denseE_lipschitzL2 W1t (by norm_num) ?_")
A("  simp [W1t, Fin.sum_univ_succ]")
A("  norm_num")
A("")
A(f"theorem W2t_lip : LipschitzL2 {frac(C2)} (denseE W2t) := by")
A("  refine denseE_lipschitzL2 W2t (by norm_num) ?_")
A("  simp [W2t, Fin.sum_univ_succ]")
A("  norm_num")
A("")
A(f"/-- Product certificate for the trained net: L = C₂·(1·C₁) = {LL}. -/")
A(f"theorem mlpT_lip : LipschitzL2 {frac(LL)} mlpT := by")
A(f"  have h := W2t_lip.comp (reluE_lipschitzL2.comp W1t_lip (by norm_num)) (by norm_num)")
A(f"  have e : {frac(C2)} * (1 * {frac(C1)}) = {frac(LL)} := by norm_num")
A("  rw [e] at h; exact h")
A("")
A(f"/-- In-kernel margin: class {i0} leads every other class at `xt` by ≥ {m}. -/")
A(f"theorem xt_margin : ∀ j : Fin 10, j ≠ {i0} →")
A(f"    {frac(m)} ≤ mlpT xt {i0} - mlpT xt j := by")
A("  have hout : ∀ jj : Fin 10, mlpT xt jj = ∑ k : Fin 8, W2t jj k * max (hpreVals k) 0 := by")
A("    intro jj")
A("    simp only [mlpT, Function.comp_apply, denseE_apply, reluE_apply]")
A("    exact Finset.sum_congr rfl fun k _ => by rw [hpre_eval k]")
A("  intro j hj")
A("  fin_cases j <;>")
A("    first")
A("    | exact absurd rfl hj")
A("    | · rw [hout, hout]")
A("        simp [W2t, hpreVals, Fin.sum_univ_succ, max_def]")
A("        norm_num")
A("")
A(f"theorem trained_radius_pos : 0 < {frac(m)} / (Real.sqrt 2 * {frac(LL)}) :=")
A("  div_pos (by norm_num)")
A("    (mul_pos (Real.sqrt_pos.mpr (by norm_num)) (by norm_num))")
A("")
A(f"/-- **The Tsuzuku certificate at TRAINED weights.** Every L2 perturbation of")
A(f"    the pooled MNIST digit-{int(yte[cand])} with `‖δ‖ < {float(m):.3f}/(√2·{float(LL):.3f}) ≈ {rad:.4f}`")
A(f"    leaves class {i0} the strict argmax of the trained, rationalized network. -/")
A(f"theorem trained_demo_certified (δ : EuclideanSpace ℝ (Fin 49))")
A(f"    (hδ : ‖δ‖ < {frac(m)} / (Real.sqrt 2 * {frac(LL)})) :")
A(f"    ∀ j, j ≠ {i0} → mlpT (xt + δ) j < mlpT (xt + δ) {i0} :=")
A("  lipschitz_margin_certified_radius mlpT_lip (by norm_num) xt_margin hδ")

snippet = "\n".join(lines) + "\n"
out = "/tmp/claude-1000/-home-skoonce-lean-klawd-max-power-lean4-jax/8f48005c-0a69-42db-9283-1fd4bbae3fe3/scratchpad/trained_snippet.lean"
with open(out, "w") as f:
    f.write(snippet)
print("wrote", out, len(snippet), "bytes")
