#!/usr/bin/env python3
"""Generate the smoothing CP scorecard corpus (planning/gaussian_smoothing_next.md 3c-data).

Reads the fixed-protocol driver CSVs (runs/smooth_<slug>_scorecard.csv, columns
sigma,img_idx,label,pred,abstain,radius,count,n) and emits per-image kernel tail
checks: for each certified image the largest 4-decimal rational q0 = a/10000 with

    1000 * sum_{j=k}^{n} C(n,j) a^j (10000-a)^(n-j)  <=  10000^n      (exact, int)

i.e. binomTail n k (a/10000) <= 1/1000 — verified here in EXACT integer
arithmetic before emission, then re-verified in Lean by `decide +kernel`
(Proofs.binomTail_le_of_kernel_check). The emitted radius column is
sigma * Phi^-1(a/10000) — display-only (the Lean side keeps Phi^-1 symbolic).

Output: LeanMlir/Proofs/Certificates/SmoothingCPScorecard.lean
"""

import csv
import math
import sys
from pathlib import Path

ALPHA_INV = 1000          # alpha = 1/1000
D = 10000                 # q0 denominator (4 decimals)
NETS = [("mlp", "MNIST-MLP"), ("cnn", "MNIST-CNN"), ("cifar", "CIFAR-CNN")]
RUNS = Path("runs")
OUT = Path("LeanMlir/Proofs/Certificates/SmoothingCPScorecard.lean")


def tail_check(n: int, k: int, a: int) -> bool:
    """Exact: ALPHA_INV * sum_{j=k}^n C(n,j) a^j (D-a)^(n-j) <= D^n."""
    if a <= 0 or a >= D:
        return False
    b = D - a
    # incremental terms from j = k upward; T_{j+1} = T_j*(n-j)*a // ((j+1)*b)
    t = math.comb(n, k) * pow(a, k) * pow(b, n - k)
    s = t
    bound = pow(D, n)
    lim = bound // ALPHA_INV  # s <= lim  <=>  ALPHA_INV*s <= bound (floor ok: s integer)
    for j in range(k, n):
        t = t * (n - j) * a // ((j + 1) * b)
        s += t
        if s > lim:
            return False
    return ALPHA_INV * s <= bound


def largest_a(n: int, k: int) -> int | None:
    """Largest a in (D/2, D) passing tail_check — binary search (tail is
    monotone increasing in a)."""
    lo, hi = D // 2 + 1, D - 1  # need q0 > 1/2 for a positive radius
    if not tail_check(n, k, lo):
        return None
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if tail_check(n, k, mid):
            lo = mid
        else:
            hi = mid - 1
    return lo


def phi_inv(p: float) -> float:
    """Acklam probit (same algorithm family as the driver) — display only."""
    a = [-3.969683028665376e+01, 2.209460984245205e+02, -2.759285104469687e+02,
         1.383577518672690e+02, -3.066479806614716e+01, 2.506628277459239e+00]
    b = [-5.447609879822406e+01, 1.615858368580409e+02, -1.556989798598866e+02,
         6.680131188771972e+01, -1.328068155288572e+01]
    c = [-7.784894002430293e-03, -3.223964580411365e-01, -2.400758277161838e+00,
         -2.549732539343734e+00, 4.374664141464968e+00, 2.938163982698783e+00]
    d = [7.784695709041462e-03, 3.224671290700398e-01, 2.445134137142996e+00,
         3.754408661907416e+00]
    plow, phigh = 0.02425, 1 - 0.02425
    if p < plow:
        q = math.sqrt(-2 * math.log(p))
        return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
               ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
    if p > phigh:
        q = math.sqrt(-2 * math.log(1 - p))
        return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
               ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
    q = p - 0.5
    r = q * q
    return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q / \
           (((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)


def main() -> None:
    per_net = {}
    for slug, _name in NETS:
        path = RUNS / f"smooth_{slug}_scorecard.csv"
        if not path.exists():
            sys.exit(f"missing {path} — run ./run_smooth_scorecard.sh first")
        rows = []
        with open(path) as f:
            for r in csv.DictReader(f):
                rows.append(r)
        entries = []   # (img_idx, label, pred, k, n, a, radius, correct)
        for r in rows:
            n, k = int(r["n"]), int(r["count"])
            sigma = float(r["sigma"])
            if int(r["abstain"]) == 1:
                continue
            a = largest_a(n, k)
            if a is None:
                continue
            radius = sigma * phi_inv(a / D)
            entries.append((int(r["img_idx"]), int(r["label"]), int(r["pred"]),
                            k, n, a, radius, r["label"] == r["pred"]))
        per_net[slug] = (entries, len(rows), sigma)
        print(f"{slug}: {len(rows)} images, {len(entries)} certified "
              f"({sum(1 for e in entries if e[7])} also correct)")

    L = []
    L.append("import LeanMlir.Proofs.Certificates.SmoothingCP\n")
    L.append("/-! # The smoothing CP scorecard — the driver's reported bounds, kernel-checked\n")
    L.append("GENERATED by scripts/smooth_scorecard_gen.py from the fixed-protocol driver runs")
    L.append("(run_smooth_scorecard.sh: first-100 test images, σ = 0.5, n = 10112 samples,")
    L.append("α = 1/1000; CSVs runs/smooth_<slug>_scorecard.csv). Per certified image, the")
    L.append("largest 4-decimal q₀ = a/10000 with `binomTail n k q₀ ≤ α` — verified in exact")
    L.append("integer arithmetic at generation AND re-proved here by `decide +kernel`")
    L.append("(`binomTail_le_of_kernel_check`). Through `smoothing_cp_certified_solved`, each")
    L.append("entry certifies the radius σ·Φ⁻¹(q₀) for its observed count, w.p. ≥ 1−α.")
    L.append("")
    L.append("Honest scope: this ties the driver's REPORTED (k, n, α) arithmetic to the")
    L.append("theorem. The float Φ⁻¹ printout is closed corpus-wide by the decimal-radius")
    L.append("scorecard (SmoothingDecScorecard.lean); the net-semantics hypotheses (C = a")
    L.append("net's argmax + `hp` interiority) are discharged for a concrete trained net in")
    L.append("SmoothingNetWitness.lean — this scorecard's own 784-dim driver checkpoints")
    L.append("remain untied (the same witness-generator pass at full width). -/")
    L.append("")
    L.append("namespace Proofs")
    L.append("")
    for slug, name in NETS:
        entries, nimg, sigma = per_net[slug]
        ncorrect = sum(1 for e in entries if e[7])
        L.append(f"-- ── {name}: {len(entries)}/{nimg} certified (σ={sigma}, of which "
                 f"{ncorrect} correctly classified) ──")
        L.append("")
        for (idx, label, pred, k, n, a, radius, correct) in entries:
            tag = "" if correct else "  (misclassified)"
            L.append(f"/-- img {idx}: label {label}, pred {pred}, count {k}/{n} → "
                     f"q₀ = {a}/10000, radius ≈ {radius:.3f}{tag} -/")
            L.append(f"lemma smooth_cp_{slug}_i{idx} :")
            L.append(f"    binomTail {n} {k} (({a}:ℝ)/10000) ≤ 1/(1000:ℝ) :=")
            L.append(f"  binomTail_le_of_kernel_check (by norm_num) (by norm_num) "
                     f"(by norm_num)")
            L.append(f"    (by norm_num) (by decide +kernel)")
            L.append("")
        # aggregate: entries list + Forall theorem assembled from the lemmas
        triples = ", ".join(f"({e[4]}, {e[3]}, {e[5]})" for e in entries)
        L.append(f"/-- {name} aggregate: (n, count, a) per certified image. -/")
        L.append(f"def smoothCp{slug.capitalize()}Entries : List (ℕ × ℕ × ℕ) := [{triples}]")
        L.append("")
        L.append(f"/-- Every {name} scorecard entry's tail check is a theorem "
                 f"({len(entries)}/{nimg} first-100 images certified at σ={sigma}, "
                 f"α=1/1000). -/")
        L.append(f"theorem smoothCp{slug.capitalize()}_certified :")
        L.append(f"    ∀ e ∈ smoothCp{slug.capitalize()}Entries,")
        L.append(f"      binomTail e.1 e.2.1 ((e.2.2:ℝ)/10000) ≤ 1/(1000:ℝ) :=")
        names = [f"smooth_cp_{slug}_i{e[0]}" for e in entries]
        if not names:
            L.append("  fun e he => absurd he (List.not_mem_nil)")
        elif len(names) == 1:
            L.append(f"  List.forall_iff_forall_mem.mp {names[0]}")
        else:
            L.append("  List.forall_iff_forall_mem.mp")
            for i in range(0, len(names), 5):
                chunk = ", ".join(names[i:i+5])
                prefix = "    ⟨" if i == 0 else "     "
                suffix = "⟩" if i + 5 >= len(names) else ","
                L.append(f"{prefix}{chunk}{suffix}")
        L.append("")
    L.append("end Proofs")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
