#!/usr/bin/env python3
"""Generate per-class strict-argmax witnesses for the smoothing net tie
(planning/gaussian_smoothing_next.md, the net-semantics closure).

`Proofs.argmaxNet_smoothProb_mem_Ioo` discharges the smoothing chain's `hp`
interiority hypothesis from ONE strict-argmax witness per class. This script
finds those witnesses for the trained /128-rationalized 49->8->10 pooled-MNIST
MLP (`mlpT` in LipschitzCertInstance.lean):

  * parse W1t / W2t rationals straight out of LipschitzCertInstance.lean
    (the committed weights are the ground truth -- no retraining drift);
  * exact rational forward over the 4x4-pooled MNIST test set;
  * per class c: the correctly-predicted image with the LARGEST exact margin
    (strictness verified in exact integer arithmetic before emission);
  * emit LeanMlir/Proofs/Certificates/SmoothingNetWitness.lean: witness vectors, exact
    hidden-preactivation tables, per-witness strict-argmax theorems
    (re-proved in-kernel), the witness bundle netW/netW_strict, and the
    INSTANTIATED capstone smoothing_cp_certified_mlpT + a deployed-scale demo.

Output: LeanMlir/Proofs/Certificates/SmoothingNetWitness.lean
"""

import re
import struct
from fractions import Fraction
from pathlib import Path

import numpy as np

D = "data/"
SRC = Path("LeanMlir/Proofs/Certificates/LipschitzCertInstance.lean")
OUT = Path("LeanMlir/Proofs/Certificates/SmoothingNetWitness.lean")
H, K, DIM = 8, 10, 49
DEN_X, DEN_W = 4080, 128


def load_images(fn):
    with open(fn, "rb") as f:
        _, n, r, c = struct.unpack(">IIII", f.read(16))
        return np.frombuffer(f.read(), dtype=np.uint8).reshape(n, r, c)


def load_labels(fn):
    with open(fn, "rb") as f:
        _, n = struct.unpack(">II", f.read(8))
        return np.frombuffer(f.read(), dtype=np.uint8)


def parse_weights(name: str, rows: int, cols: int) -> list[list[int]]:
    """Parse `def <name> ... := ![![((n : ℝ)/128), ...], ...]` numerators."""
    src = SRC.read_text()
    m = re.search(rf"def {name} : Fin {rows} → Fin {cols} → ℝ :=\n(.*?)\n\n",
                  src, re.S)
    assert m, f"could not find {name}"
    body = m.group(1)
    out = []
    for rowm in re.finditer(r"!\[((?:\(\((-?\d+) : ℝ\)/128\)(?:, )?)+)\]", body):
        nums = [int(v) for v in re.findall(r"\(\((-?\d+) : ℝ\)/128\)", rowm.group(1))]
        assert len(nums) == cols, (name, len(nums))
        out.append(nums)
    assert len(out) == rows, (name, len(out))
    return out


def main() -> None:
    W1 = parse_weights("W1t", H, DIM)   # numerators over 128
    W2 = parse_weights("W2t", K, H)
    Xte_raw = load_images(D + "t10k-images-idx3-ubyte")
    yte = load_labels(D + "t10k-labels-idx1-ubyte")
    Ste = Xte_raw.reshape(-1, 7, 4, 7, 4).astype(np.int64).sum(axis=(2, 4)) \
        .reshape(-1, DIM)   # integer pooled sums, x_j = s_j/4080

    # exact integer forward: logits share denominator 128*128*4080
    best = {}   # class -> (margin_fraction, img_idx, s, pre_nums, logit_nums)
    for i in range(len(Ste)):
        s = [int(v) for v in Ste[i]]
        pre = [sum(W1[k][j] * s[j] for j in range(DIM)) for k in range(H)]
        hid = [max(p, 0) for p in pre]
        log = [sum(W2[c][k] * hid[k] for k in range(H)) for c in range(K)]
        top = max(range(K), key=lambda c: (log[c], -c))
        if top != int(yte[i]):
            continue
        runner = max(log[c] for c in range(K) if c != top)
        margin = log[top] - runner
        if margin <= 0:
            continue   # strictness is the whole point
        if top not in best or margin > best[top][0]:
            best[top] = (margin, i, s, pre, log)
    assert set(best) == set(range(K)), f"classes missing: {set(range(K)) - set(best)}"

    L = []
    A = L.append
    A("import LeanMlir.Proofs.Certificates.SmoothingNetSemantics\n")
    A("/-! # The net-semantics tie, INSTANTIATED — CERTIFY for a concrete trained net\n")
    A("GENERATED by scripts/smoothing_net_witness_gen.py. The smoothing chain's last")
    A("informal hypotheses — `hC` measurability and `hp` interiority for the abstract")
    A("classifier — are here DISCHARGED for `mlpT`, the trained /128-rationalized")
    A("49→8→10 pooled-MNIST MLP (LipschitzCertInstance.lean): measurability from the")
    A("logits' continuity, interiority from ONE strict-argmax witness per class")
    A("(argmaxNet_smoothProb_mem_Ioo). Each witness is a pooled test image whose")
    A("predicted class leads every other logit STRICTLY — checked in exact integer")
    A("arithmetic at generation and re-proved in-kernel below.")
    A("")
    A("`smoothing_cp_certified_mlpT` is Cohen's CERTIFY guarantee for THIS network's")
    A("argmax with every semantic hypothesis discharged; the demo instantiates it at")
    A("the deployed scorecard scale (N = 10112, α = 1/1000). Honest scope: mlpT is")
    A("the Lipschitz-thread pooled net, not the 784-dim smoothing-driver checkpoint")
    A("(that tie = the same generator pass at full width), and the driver's float")
    A("forward vs this real-semantics net is the FloatBridge tier's story. -/")
    A("")
    A("namespace Proofs.LipschitzCertDemo")
    A("")
    A("open MeasureTheory ProbabilityTheory")
    A("")
    for c in range(K):
        margin, idx, s, pre, log = best[c]
        runner = max(log[j] for j in range(K) if j != c)
        A(f"/-- Class-{c} witness: pooled test image #{idx} (label {c}); exact logit")
        A(f"    margin over the runner-up is {margin}/66846720 ≈ "
          f"{float(Fraction(margin, 66846720)):.4f}. -/")
        A(f"noncomputable def netW{c} : EuclideanSpace ℝ (Fin 49) :=")
        A("  WithLp.toLp 2 ![" + ", ".join(f"(({v} : ℝ)/4080)" for v in s) + "]")
        A("")
        A(f"/-- Exact hidden pre-activations of `netW{c}` (denominator 128·4080). -/")
        A(f"noncomputable def netWpre{c} : Fin 8 → ℝ :=")
        A("  ![" + ", ".join(f"(({p} : ℝ)/522240)" for p in pre) + "]")
        A("")
        A(f"theorem netW{c}_pre : ∀ k : Fin 8, denseE W1t netW{c} k = netWpre{c} k := by")
        A("  intro k")
        A("  fin_cases k <;>")
        A(f"    · simp [denseE_apply, W1t, netW{c}, netWpre{c}, Fin.sum_univ_succ]")
        A("      norm_num")
        A("")
        A(f"/-- In-kernel STRICT argmax at the class-{c} witness. -/")
        A(f"theorem netW{c}_strict : ∀ j : Fin 10, j ≠ {c} → mlpT netW{c} j < mlpT netW{c} {c} := by")
        A("  have hout : ∀ jj : Fin 10, mlpT netW" + str(c)
          + " jj = ∑ k : Fin 8, W2t jj k * max (netWpre" + str(c) + " k) 0 := by")
        A("    intro jj")
        A("    show denseE W2t (reluE (denseE W1t netW" + str(c) + ")) jj = _")
        A("    rw [denseE_apply]")
        A("    refine Finset.sum_congr rfl fun k _ => ?_")
        A(f"    rw [reluE_apply, netW{c}_pre k]")
        A("  intro j hj")
        A("  fin_cases j <;>")
        A("    first")
        A("    | exact absurd rfl hj")
        A("    | · rw [hout, hout]")
        A(f"        simp [W2t, netWpre{c}, Fin.sum_univ_succ, max_def]")
        A("        norm_num")
        A("")
    A("/-- The witness bundle: one strict-argmax point per class. -/")
    A("noncomputable def netW : Fin 10 → EuclideanSpace ℝ (Fin 49) :=")
    A("  ![" + ", ".join(f"netW{c}" for c in range(K)) + "]")
    A("")
    A("theorem netW_strict : ∀ c : Fin 10, ∀ j, j ≠ c →")
    A("    mlpT (netW c) j < mlpT (netW c) c := by")
    A("  intro c")
    A("  fin_cases c")
    for c in range(K):
        A(f"  · exact netW{c}_strict")
    A("")
    A("/-- **CERTIFY for the CONCRETE net.** `smoothing_cp_certified_net` with the")
    A("    classifier = `mlpT`'s argmax: measurability and `hp` interiority both")
    A("    DISCHARGED (continuity + the ten witnesses above). With probability")
    A("    `≥ 1 − α` over the `N` Gaussian samples: if the vote count for `y` at")
    A("    `x` comes out `k₀`, every `‖δ‖ < σ·Φ⁻¹(q₀)` leaves `y` the strict")
    A("    argmax of the smoothed `mlpT`. -/")
    A("theorem smoothing_cp_certified_mlpT {σ : ℝ} (hσ : 0 < σ)")
    A("    (x : EuclideanSpace ℝ (Fin 49)) (y : Fin 10)")
    A("    {N k₀ : ℕ} (hk₀ : k₀ ≤ N) {α q₀ : ℝ} (hα : 0 ≤ α) (hα1 : α < 1)")
    A("    (hq₀ : q₀ ∈ Set.Ioo (0:ℝ) 1) (htail : binomTail N k₀ q₀ ≤ α) :")
    A("    1 - α")
    A("      ≤ (Measure.pi fun _ : Fin N => stdGaussian (EuclideanSpace ℝ (Fin 49))).real")
    A("          {ω | (∑ i, if argmaxNet (fun v j => mlpT v j) (x + σ • ω i) = y then 1 else 0) = k₀ →")
    A("            ∀ δ : EuclideanSpace ℝ (Fin 49),")
    A("            ‖δ‖ < σ * stdNormalQuantile q₀ →")
    A("            ∀ j, j ≠ y →")
    A("              (∫ z, (if argmaxNet (fun v j => mlpT v j) (x + δ + σ • z) = j then (1:ℝ) else 0)")
    A("                  ∂(stdGaussian (EuclideanSpace ℝ (Fin 49))))")
    A("                < ∫ z, (if argmaxNet (fun v j => mlpT v j) (x + δ + σ • z) = y then (1:ℝ) else 0)")
    A("                    ∂(stdGaussian (EuclideanSpace ℝ (Fin 49)))} :=")
    A("  smoothing_cp_certified_net hσ mlpT_logit_continuous netW netW_strict")
    A("    x y hk₀ hα hα1 hq₀ htail")
    A("")
    A("/-- The deployed-protocol demo: at the scorecard's `N = 10112`, `α = 1/1000`,")
    A("    a count of `10084` certifies radius `σ·Φ⁻¹(0.9952)` for the smoothed")
    A("    `mlpT` — the per-image scorecard shape with NO abstract-classifier")
    A("    hypotheses left (the tail check is one kernel evaluation). -/")
    A("theorem smooth_cp_mlpT_demo {σ : ℝ} (hσ : 0 < σ)")
    A("    (x : EuclideanSpace ℝ (Fin 49)) (y : Fin 10) :")
    A("    1 - 1/(1000:ℝ)")
    A("      ≤ (Measure.pi fun _ : Fin 10112 => stdGaussian (EuclideanSpace ℝ (Fin 49))).real")
    A("          {ω | (∑ i, if argmaxNet (fun v j => mlpT v j) (x + σ • ω i) = y then 1 else 0) = 10084 →")
    A("            ∀ δ : EuclideanSpace ℝ (Fin 49),")
    A("            ‖δ‖ < σ * stdNormalQuantile ((9952:ℝ)/10000) →")
    A("            ∀ j, j ≠ y →")
    A("              (∫ z, (if argmaxNet (fun v j => mlpT v j) (x + δ + σ • z) = j then (1:ℝ) else 0)")
    A("                  ∂(stdGaussian (EuclideanSpace ℝ (Fin 49))))")
    A("                < ∫ z, (if argmaxNet (fun v j => mlpT v j) (x + δ + σ • z) = y then (1:ℝ) else 0)")
    A("                    ∂(stdGaussian (EuclideanSpace ℝ (Fin 49)))} :=")
    A("  smoothing_cp_certified_mlpT hσ x y (by norm_num) (by norm_num) (by norm_num)")
    A("    (by constructor <;> norm_num)")
    A("    (binomTail_le_of_kernel_check (by norm_num) (by norm_num) (by norm_num)")
    A("      (by norm_num) (by decide +kernel))")
    A("")
    A("end Proofs.LipschitzCertDemo")
    OUT.write_text("\n".join(L) + "\n")
    for c in range(K):
        margin, idx, _, _, _ = best[c]
        print(f"class {c}: test image #{idx}, margin {float(Fraction(margin, 66846720)):.4f}")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
