import LeanMlir.Proofs.Certificates.IbpConvScorecardNet

/-! # Conv IBP scorecard, image chunk C — test images #4, #5

Per-image `CertifiedAtLinf3` theorems for the conv net of
`IbpConvScorecardNet.lean`: each image's exact data and one kernel check of
its box at the largest certifying radius; smaller radii follow by `.mono`.
The aggregate lives in `IbpConvScorecard.lean`. Generated by
`scripts/ibp_conv_scorecard.py`. -/

namespace Proofs
namespace IBP
namespace ConvNet

-- ═══════════════ MNIST test image #4 (label 4) ═══════════════
/-- MNIST test image #4, pooled to 8×8, exact. -/
def img4Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((137:ℚ)/2040), (0:ℚ), ((33:ℚ)/1360), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((59:ℚ)/680), ((1393:ℚ)/4080), (0:ℚ), ((99:ℚ)/272), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((657:ℚ)/1360), ((53:ℚ)/4080), ((83:ℚ)/2040), ((1073:ℚ)/2040), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((977:ℚ)/2040), ((337:ℚ)/1020), ((215:ℚ)/408), ((233:ℚ)/680), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((49:ℚ)/4080), ((7:ℚ)/85), ((97:ℚ)/255), ((31:ℚ)/120), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((55:ℚ)/204), ((71:ℚ)/816), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img4 : Tensor3 1 8 8 := castT img4Q

/-- **Certified at ε = 4/255** (MNIST test image #4, class 4): EVERY
    pixel-`L∞` perturbation of size ≤ 4/255 leaves class 4 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert4e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img4 4 := by
  simpa [img4] using net_certified_of_check img4Q ((4:ℚ)/255) 4 (by decide +kernel)

/-- Certified at ε = 1/255 (image #4) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert4e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img4 4 :=
  cert4e4.mono (by norm_num)

/-- Certified at ε = 2/255 (image #4) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert4e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img4 4 :=
  cert4e4.mono (by norm_num)

-- ═══════════════ MNIST test image #5 (label 1) ═══════════════
/-- MNIST test image #5, pooled to 8×8, exact. -/
def img5Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((331:ℚ)/4080), ((11:ℚ)/408), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((77:ℚ)/120), ((251:ℚ)/2040), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((169:ℚ)/4080), ((2953:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((245:ℚ)/816), ((106:ℚ)/255), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((1177:ℚ)/2040), ((61:ℚ)/680), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((1531:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img5 : Tensor3 1 8 8 := castT img5Q

/-- **Certified at ε = 8/255** (MNIST test image #5, class 1): EVERY
    pixel-`L∞` perturbation of size ≤ 8/255 leaves class 1 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert5e8 : CertifiedAtLinf3 net ((8:ℝ)/255) img5 1 := by
  simpa [img5] using net_certified_of_check img5Q ((8:ℚ)/255) 1 (by decide +kernel)

/-- Certified at ε = 1/255 (image #5) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert5e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img5 1 :=
  cert5e8.mono (by norm_num)

/-- Certified at ε = 2/255 (image #5) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert5e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img5 1 :=
  cert5e8.mono (by norm_num)

/-- Certified at ε = 4/255 (image #5) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert5e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img5 1 :=
  cert5e8.mono (by norm_num)

end ConvNet
end IBP
end Proofs
