import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsA
import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsB

/-! # Full-input certified-accuracy scorecard (4/4): the certificates

The pooled 49-dim scorecard, lifted to FULL 784-dim input (the 2026-07 audit's
gap #3): pixel-L2 ε = 1/10 and 3/10, two 784→16→10 nets. Counts below are
MEASURED over the first 100 MNIST test images by exact rational arithmetic:

* **spectrally capped** (σ ≤ 2 projected SGD, q-acc 0.924, Schatten-8
  L = 4.95): **92/100 certified at ε = 0.1** (L2-PGD leaves 93/100
  robust — the certificate is within 1 image(s) of the attack bound), and
  **72/100 at ε = 0.3** (PGD: 92/100);
* **unconstrained** (q-acc 0.951, L = 29.85): 76/100 at ε = 0.1
  (PGD: 94/100), collapsing to **2/100 at ε = 0.3** (PGD: 86/100) —
  at the larger radius the σ-projection is what keeps the certificate alive.

ε here is FULL-pixel-space L2 (pixels in [0,1]), not the pooled-feature L2 of
`LipschitzCertScorecard.lean` — a strictly stronger, directly comparable-to-
the-literature perturbation model. Width 16 (vs the canonical 512) is the
honest cost: 512-wide Gram certificates are ~10⁵× this kernel work.

**Theorem vs. measurement — read this before quoting a number.** Soundness
lives in the ENGINE (`LipschitzCert.lean`), proved once; kernel-checking the
57th image buys nothing the 56th didn't. So the counts above are exact-rational
MEASUREMENTS over the first 100 images, while the first 8 certifying images (test-
set order — an unbiased, reproducible rule) each carry a `CertifiedAt` THEOREM.
`scorecardFull` below states ONLY those proved counts. The images witness that
the certificate is non-vacuous at real trained weights; they are not what makes
it sound.

Aggregates are lower bounds only — an upper-bound L cannot prove an image
UNcertifiable. Generated by `scripts/lipschitz_cert_scorecard_full.py`. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 3200000

namespace Proofs
namespace LipschitzCertDemo

open scoped BigOperators

/-- Test #0 (digit 7), net SF: certified at ε = 1/10 — margin 5.632 ≥ √2·L·ε. -/
theorem certSF10_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF0 + δ) j < mlpSF (imgF0 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #1 (digit 2), net SF: certified at ε = 1/10 — margin 2.817 ≥ √2·L·ε. -/
theorem certSF10_1 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF1 + δ) j < mlpSF (imgF1 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF1 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net SF: certified at ε = 1/10 — margin 3.815 ≥ √2·L·ε. -/
theorem certSF10_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF2 + δ) j < mlpSF (imgF2 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net SF: certified at ε = 1/10 — margin 5.384 ≥ √2·L·ε. -/
theorem certSF10_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF3 + δ) j < mlpSF (imgF3 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net SF: certified at ε = 1/10 — margin 2.377 ≥ √2·L·ε. -/
theorem certSF10_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF4 + δ) j < mlpSF (imgF4 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net SF: certified at ε = 1/10 — margin 4.312 ≥ √2·L·ε. -/
theorem certSF10_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF5 + δ) j < mlpSF (imgF5 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net SF: certified at ε = 1/10 — margin 2.587 ≥ √2·L·ε. -/
theorem certSF10_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF6 + δ) j < mlpSF (imgF6 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net SF: certified at ε = 1/10 — margin 2.537 ≥ √2·L·ε. -/
theorem certSF10_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF7 + δ) j < mlpSF (imgF7 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF7 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net SF, ε = 1/10. -/
noncomputable def cappedFullCerts10 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (1, imgF1, 2),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9)]

theorem cappedFullCerts10_certified :
    ∀ p ∈ cappedFullCerts10, CertifiedAt mlpSF ((1 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certSF10_0, certSF10_1, certSF10_2, certSF10_3, certSF10_4, certSF10_5, certSF10_6, certSF10_7⟩

/-- Test #0 (digit 7), net SF: certified at ε = 3/10 — margin 5.632 ≥ √2·L·ε. -/
theorem certSF30_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF0 + δ) j < mlpSF (imgF0 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #1 (digit 2), net SF: certified at ε = 3/10 — margin 2.817 ≥ √2·L·ε. -/
theorem certSF30_1 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF1 + δ) j < mlpSF (imgF1 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF1 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net SF: certified at ε = 3/10 — margin 3.815 ≥ √2·L·ε. -/
theorem certSF30_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF2 + δ) j < mlpSF (imgF2 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net SF: certified at ε = 3/10 — margin 5.384 ≥ √2·L·ε. -/
theorem certSF30_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF3 + δ) j < mlpSF (imgF3 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net SF: certified at ε = 3/10 — margin 2.377 ≥ √2·L·ε. -/
theorem certSF30_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF4 + δ) j < mlpSF (imgF4 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net SF: certified at ε = 3/10 — margin 4.312 ≥ √2·L·ε. -/
theorem certSF30_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF5 + δ) j < mlpSF (imgF5 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net SF: certified at ε = 3/10 — margin 2.587 ≥ √2·L·ε. -/
theorem certSF30_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF6 + δ) j < mlpSF (imgF6 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net SF: certified at ε = 3/10 — margin 2.537 ≥ √2·L·ε. -/
theorem certSF30_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF7 + δ) j < mlpSF (imgF7 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF7 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net SF, ε = 3/10. -/
noncomputable def cappedFullCerts30 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (1, imgF1, 2),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9)]

theorem cappedFullCerts30_certified :
    ∀ p ∈ cappedFullCerts30, CertifiedAt mlpSF ((3 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certSF30_0, certSF30_1, certSF30_2, certSF30_3, certSF30_4, certSF30_5, certSF30_6, certSF30_7⟩

/-- Test #0 (digit 7), net TF: certified at ε = 1/10 — margin 4.551 ≥ √2·L·ε. -/
theorem certTF10_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF0 + δ) j < mlpTF (imgF0 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net TF: certified at ε = 1/10 — margin 7.083 ≥ √2·L·ε. -/
theorem certTF10_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF2 + δ) j < mlpTF (imgF2 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net TF: certified at ε = 1/10 — margin 9.403 ≥ √2·L·ε. -/
theorem certTF10_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF3 + δ) j < mlpTF (imgF3 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net TF: certified at ε = 1/10 — margin 6.060 ≥ √2·L·ε. -/
theorem certTF10_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF4 + δ) j < mlpTF (imgF4 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net TF: certified at ε = 1/10 — margin 6.346 ≥ √2·L·ε. -/
theorem certTF10_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF5 + δ) j < mlpTF (imgF5 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net TF: certified at ε = 1/10 — margin 5.388 ≥ √2·L·ε. -/
theorem certTF10_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF6 + δ) j < mlpTF (imgF6 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net TF: certified at ε = 1/10 — margin 5.549 ≥ √2·L·ε. -/
theorem certTF10_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF7 + δ) j < mlpTF (imgF7 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF7 (by norm_num)
    (by norm_num) δ hδ

/-- Test #9 (digit 9), net TF: certified at ε = 1/10 — margin 5.232 ≥ √2·L·ε. -/
theorem certTF10_9 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF9 + δ) j < mlpTF (imgF9 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF9 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net TF, ε = 1/10. -/
noncomputable def unconFullCerts10 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9),
   (9, imgF9, 9)]

theorem unconFullCerts10_certified :
    ∀ p ∈ unconFullCerts10, CertifiedAt mlpTF ((1 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certTF10_0, certTF10_2, certTF10_3, certTF10_4, certTF10_5, certTF10_6, certTF10_7, certTF10_9⟩

/-- Test #25 (digit 0), net TF: certified at ε = 3/10 — margin 13.368 ≥ √2·L·ε. -/
theorem certTF30_25 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF25 + δ) j < mlpTF (imgF25 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF25 (by norm_num)
    (by norm_num) δ hδ

/-- Test #71 (digit 0), net TF: certified at ε = 3/10 — margin 14.174 ≥ √2·L·ε. -/
theorem certTF30_71 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF71 + δ) j < mlpTF (imgF71 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF71 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net TF, ε = 3/10. -/
noncomputable def unconFullCerts30 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(25, imgF25, 0),
   (71, imgF71, 0)]

theorem unconFullCerts30_certified :
    ∀ p ∈ unconFullCerts30, CertifiedAt mlpTF ((3 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certTF30_25, certTF30_71⟩

/-- **The proved core of the full-input scorecard** — counts tied to the
    per-image `CertifiedAt` proofs, both nets, both radii. These are the emitted
    witnesses, NOT the measured dataset counts in the header (which are
    exact-rational measurements rather than theorems). Lower bounds only. -/
theorem scorecardFull :
    (cappedFullCerts10.length = 8 ∧
      ∀ p ∈ cappedFullCerts10, CertifiedAt mlpSF ((1 : ℝ)/10) p.2.1 p.2.2) ∧
    (cappedFullCerts30.length = 8 ∧
      ∀ p ∈ cappedFullCerts30, CertifiedAt mlpSF ((3 : ℝ)/10) p.2.1 p.2.2) ∧
    (unconFullCerts10.length = 8 ∧
      ∀ p ∈ unconFullCerts10, CertifiedAt mlpTF ((1 : ℝ)/10) p.2.1 p.2.2) ∧
    (unconFullCerts30.length = 2 ∧
      ∀ p ∈ unconFullCerts30, CertifiedAt mlpTF ((3 : ℝ)/10) p.2.1 p.2.2) :=
  ⟨⟨rfl, cappedFullCerts10_certified⟩, ⟨rfl, cappedFullCerts30_certified⟩,
   ⟨rfl, unconFullCerts10_certified⟩, ⟨rfl, unconFullCerts30_certified⟩⟩

end LipschitzCertDemo
end Proofs
