import LeanMlir.Proofs.Foundation.IntervalBound
import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsA
import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsB
import LeanMlir.Proofs.Certificates.LipschitzCertScorecardIBP

/-! # IBP L∞ scorecard, full 784-dim input — unconstrained net (`mlpTF`)

Pixel-L∞ certificates by exact interval bound propagation over the SAME
first-100 MNIST test subset as the L2 scorecard: at ε = 1/255, 2/255,
4/255, 8/255 the box certificate proves
**87/100**, **42/100**, **2/100**, **0/100** predictions robust (PGD-L∞ bracket: 95, 92, 85, 36).
For comparison, pushing the L2 Lipschitz certificate through
`‖δ‖₂ ≤ √784·ε∞` certifies only 71, 14, 0, 0 — at small L∞ radii the box beats the ball.


**Theorem vs. measurement.** Soundness is in the ENGINE
(`Foundation/IntervalBound.lean`), proved once — kernel-checking the 57th
image buys nothing the 56th didn't. The counts above are exact-rational
MEASUREMENTS over the first 100 images; the first 8 certifying images at
each radius carry a `CertifiedAtLinf` THEOREM, and the aggregate below states
only those. The images witness non-vacuity; they are not what makes it sound.

Engine: `IntervalBound.lean`. The first layer is a uniform box, so its
interval image is `⟨w,x⟩ ∓ ε·‖w‖₁` — `⟨w,x⟩` reuses the committed `dotZ`
pre-activation facts (`hpre*`), `‖w‖₁` is ONE new kernel fact per row
(`absSumZ`, `decide +kernel`); the 16-wide second layer is sign-split
rational arithmetic. Counts are lower bounds (a loose box cannot prove
an image UNcertifiable). Generated by
`scripts/lipschitz_cert_scorecard_ibp.py`; weights/images are DATA. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 3200000

namespace Proofs
namespace LipschitzCertDemo

open scoped BigOperators

-- ════════ per-row ℓ1 norms: one kernel `absSumZ` fact each ════════

theorem azTF0 : absSumZ w1zTF0 = 19274 := by decide +kernel
theorem azTF1 : absSumZ w1zTF1 = 16583 := by decide +kernel
theorem azTF2 : absSumZ w1zTF2 = 19113 := by decide +kernel
theorem azTF3 : absSumZ w1zTF3 = 20576 := by decide +kernel
theorem azTF4 : absSumZ w1zTF4 = 15304 := by decide +kernel
theorem azTF5 : absSumZ w1zTF5 = 19965 := by decide +kernel
theorem azTF6 : absSumZ w1zTF6 = 18602 := by decide +kernel
theorem azTF7 : absSumZ w1zTF7 = 16745 := by decide +kernel
theorem azTF8 : absSumZ w1zTF8 = 18074 := by decide +kernel
theorem azTF9 : absSumZ w1zTF9 = 16950 := by decide +kernel
theorem azTF10 : absSumZ w1zTF10 = 19491 := by decide +kernel
theorem azTF11 : absSumZ w1zTF11 = 18284 := by decide +kernel
theorem azTF12 : absSumZ w1zTF12 = 16888 := by decide +kernel
theorem azTF13 : absSumZ w1zTF13 = 20232 := by decide +kernel
theorem azTF14 : absSumZ w1zTF14 = 19106 := by decide +kernel
theorem azTF15 : absSumZ w1zTF15 = 17907 := by decide +kernel

/-- `absrTF t = ‖row t of W1TF‖₁` (data, verified below). -/
noncomputable def absrTF : Fin 16 → ℝ :=
  ![((19274 : ℝ)/256), ((16583 : ℝ)/256), ((19113 : ℝ)/256), ((20576 : ℝ)/256), ((15304 : ℝ)/256), ((19965 : ℝ)/256), ((18602 : ℝ)/256), ((16745 : ℝ)/256), ((18074 : ℝ)/256), ((16950 : ℝ)/256), ((19491 : ℝ)/256), ((18284 : ℝ)/256), ((16888 : ℝ)/256), ((20232 : ℝ)/256), ((19106 : ℝ)/256), ((17907 : ℝ)/256)]

theorem absrowTF_0 : (∑ j, |W1TF 0 j|) = absrTF 0 := by
  rw [show absrTF 0 = ((19274 : ℝ)/256) from rfl, W1TFr0]
  simp only [w1rTF0]
  rw [sum_getD_abs_div w1zTF0_len azTF0 (by norm_num)]
  norm_num

theorem absrowTF_1 : (∑ j, |W1TF 1 j|) = absrTF 1 := by
  rw [show absrTF 1 = ((16583 : ℝ)/256) from rfl, W1TFr1]
  simp only [w1rTF1]
  rw [sum_getD_abs_div w1zTF1_len azTF1 (by norm_num)]
  norm_num

theorem absrowTF_2 : (∑ j, |W1TF 2 j|) = absrTF 2 := by
  rw [show absrTF 2 = ((19113 : ℝ)/256) from rfl, W1TFr2]
  simp only [w1rTF2]
  rw [sum_getD_abs_div w1zTF2_len azTF2 (by norm_num)]
  norm_num

theorem absrowTF_3 : (∑ j, |W1TF 3 j|) = absrTF 3 := by
  rw [show absrTF 3 = ((20576 : ℝ)/256) from rfl, W1TFr3]
  simp only [w1rTF3]
  rw [sum_getD_abs_div w1zTF3_len azTF3 (by norm_num)]
  norm_num

theorem absrowTF_4 : (∑ j, |W1TF 4 j|) = absrTF 4 := by
  rw [show absrTF 4 = ((15304 : ℝ)/256) from rfl, W1TFr4]
  simp only [w1rTF4]
  rw [sum_getD_abs_div w1zTF4_len azTF4 (by norm_num)]
  norm_num

theorem absrowTF_5 : (∑ j, |W1TF 5 j|) = absrTF 5 := by
  rw [show absrTF 5 = ((19965 : ℝ)/256) from rfl, W1TFr5]
  simp only [w1rTF5]
  rw [sum_getD_abs_div w1zTF5_len azTF5 (by norm_num)]
  norm_num

theorem absrowTF_6 : (∑ j, |W1TF 6 j|) = absrTF 6 := by
  rw [show absrTF 6 = ((18602 : ℝ)/256) from rfl, W1TFr6]
  simp only [w1rTF6]
  rw [sum_getD_abs_div w1zTF6_len azTF6 (by norm_num)]
  norm_num

theorem absrowTF_7 : (∑ j, |W1TF 7 j|) = absrTF 7 := by
  rw [show absrTF 7 = ((16745 : ℝ)/256) from rfl, W1TFr7]
  simp only [w1rTF7]
  rw [sum_getD_abs_div w1zTF7_len azTF7 (by norm_num)]
  norm_num

theorem absrowTF_8 : (∑ j, |W1TF 8 j|) = absrTF 8 := by
  rw [show absrTF 8 = ((18074 : ℝ)/256) from rfl, W1TFr8]
  simp only [w1rTF8]
  rw [sum_getD_abs_div w1zTF8_len azTF8 (by norm_num)]
  norm_num

theorem absrowTF_9 : (∑ j, |W1TF 9 j|) = absrTF 9 := by
  rw [show absrTF 9 = ((16950 : ℝ)/256) from rfl, W1TFr9]
  simp only [w1rTF9]
  rw [sum_getD_abs_div w1zTF9_len azTF9 (by norm_num)]
  norm_num

theorem absrowTF_10 : (∑ j, |W1TF 10 j|) = absrTF 10 := by
  rw [show absrTF 10 = ((19491 : ℝ)/256) from rfl, W1TFr10]
  simp only [w1rTF10]
  rw [sum_getD_abs_div w1zTF10_len azTF10 (by norm_num)]
  norm_num

theorem absrowTF_11 : (∑ j, |W1TF 11 j|) = absrTF 11 := by
  rw [show absrTF 11 = ((18284 : ℝ)/256) from rfl, W1TFr11]
  simp only [w1rTF11]
  rw [sum_getD_abs_div w1zTF11_len azTF11 (by norm_num)]
  norm_num

theorem absrowTF_12 : (∑ j, |W1TF 12 j|) = absrTF 12 := by
  rw [show absrTF 12 = ((16888 : ℝ)/256) from rfl, W1TFr12]
  simp only [w1rTF12]
  rw [sum_getD_abs_div w1zTF12_len azTF12 (by norm_num)]
  norm_num

theorem absrowTF_13 : (∑ j, |W1TF 13 j|) = absrTF 13 := by
  rw [show absrTF 13 = ((20232 : ℝ)/256) from rfl, W1TFr13]
  simp only [w1rTF13]
  rw [sum_getD_abs_div w1zTF13_len azTF13 (by norm_num)]
  norm_num

theorem absrowTF_14 : (∑ j, |W1TF 14 j|) = absrTF 14 := by
  rw [show absrTF 14 = ((19106 : ℝ)/256) from rfl, W1TFr14]
  simp only [w1rTF14]
  rw [sum_getD_abs_div w1zTF14_len azTF14 (by norm_num)]
  norm_num

theorem absrowTF_15 : (∑ j, |W1TF 15 j|) = absrTF 15 := by
  rw [show absrTF 15 = ((17907 : ℝ)/256) from rfl, W1TFr15]
  simp only [w1rTF15]
  rw [sum_getD_abs_div w1zTF15_len azTF15 (by norm_num)]
  norm_num

theorem absrowTF : ∀ t, (∑ j, |W1TF t j|) = absrTF t := by
  intro t
  fin_cases t <;>
    [ exact absrowTF_0; exact absrowTF_1; exact absrowTF_2; exact absrowTF_3; exact absrowTF_4; exact absrowTF_5; exact absrowTF_6; exact absrowTF_7; exact absrowTF_8; exact absrowTF_9; exact absrowTF_10; exact absrowTF_11; exact absrowTF_12; exact absrowTF_13; exact absrowTF_14; exact absrowTF_15 ]

-- ════════ per-image certificates ════════

theorem hpreTF0_sum : ∀ t, (∑ j, W1TF t j * imgF0 j) = hpreTF0 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF0_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_0 : ∀ j : Fin 10, j ≠ 7 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF0 q - ((1 : ℝ)/255)) (fun q => imgF0 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF0 q - ((1 : ℝ)/255)) (fun q => imgF0 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF0 q - ((1 : ℝ)/255)) (fun q => imgF0 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF0 q - ((1 : ℝ)/255)) (fun q => imgF0 q + ((1 : ℝ)/255)))) 7 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF0_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF0, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #0 (digit 7): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_0 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 7 → mlpTF (imgF0 + δ) j < mlpTF (imgF0 + δ) 7 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_0 δ hδ

-- net TF pre-activations for #1 (not in the base L2-certified set)
theorem pzITF_1_0 : dotZ w1zTF0 imgz1 = 656915 := by decide +kernel
theorem pzITF_1_1 : dotZ w1zTF1 imgz1 = -299566 := by decide +kernel
theorem pzITF_1_2 : dotZ w1zTF2 imgz1 = -199022 := by decide +kernel
theorem pzITF_1_3 : dotZ w1zTF3 imgz1 = 250067 := by decide +kernel
theorem pzITF_1_4 : dotZ w1zTF4 imgz1 = 10603 := by decide +kernel
theorem pzITF_1_5 : dotZ w1zTF5 imgz1 = -291922 := by decide +kernel
theorem pzITF_1_6 : dotZ w1zTF6 imgz1 = -247838 := by decide +kernel
theorem pzITF_1_7 : dotZ w1zTF7 imgz1 = -237476 := by decide +kernel
theorem pzITF_1_8 : dotZ w1zTF8 imgz1 = 704514 := by decide +kernel
theorem pzITF_1_9 : dotZ w1zTF9 imgz1 = 327175 := by decide +kernel
theorem pzITF_1_10 : dotZ w1zTF10 imgz1 = -198892 := by decide +kernel
theorem pzITF_1_11 : dotZ w1zTF11 imgz1 = 75958 := by decide +kernel
theorem pzITF_1_12 : dotZ w1zTF12 imgz1 = -184558 := by decide +kernel
theorem pzITF_1_13 : dotZ w1zTF13 imgz1 = -58318 := by decide +kernel
theorem pzITF_1_14 : dotZ w1zTF14 imgz1 = 155073 := by decide +kernel
theorem pzITF_1_15 : dotZ w1zTF15 imgz1 = 519484 := by decide +kernel

noncomputable def hpreITF1 : Fin 16 → ℝ :=
  ![((656915 : ℝ)/65280), ((-299566 : ℝ)/65280), ((-199022 : ℝ)/65280), ((250067 : ℝ)/65280), ((10603 : ℝ)/65280), ((-291922 : ℝ)/65280), ((-247838 : ℝ)/65280), ((-237476 : ℝ)/65280), ((704514 : ℝ)/65280), ((327175 : ℝ)/65280), ((-198892 : ℝ)/65280), ((75958 : ℝ)/65280), ((-184558 : ℝ)/65280), ((-58318 : ℝ)/65280), ((155073 : ℝ)/65280), ((519484 : ℝ)/65280)]

theorem hpreITF1_eval_0 : denseE W1TF imgF1 0 = hpreITF1 0 := by
  rw [show hpreITF1 0 = ((656915 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF1_apply]
  rw [sum_getD_div w1zTF0_len imgz1_len pzITF_1_0 256 255]
  norm_num

theorem hpreITF1_eval_1 : denseE W1TF imgF1 1 = hpreITF1 1 := by
  rw [show hpreITF1 1 = ((-299566 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF1_apply]
  rw [sum_getD_div w1zTF1_len imgz1_len pzITF_1_1 256 255]
  norm_num

theorem hpreITF1_eval_2 : denseE W1TF imgF1 2 = hpreITF1 2 := by
  rw [show hpreITF1 2 = ((-199022 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF1_apply]
  rw [sum_getD_div w1zTF2_len imgz1_len pzITF_1_2 256 255]
  norm_num

theorem hpreITF1_eval_3 : denseE W1TF imgF1 3 = hpreITF1 3 := by
  rw [show hpreITF1 3 = ((250067 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF1_apply]
  rw [sum_getD_div w1zTF3_len imgz1_len pzITF_1_3 256 255]
  norm_num

theorem hpreITF1_eval_4 : denseE W1TF imgF1 4 = hpreITF1 4 := by
  rw [show hpreITF1 4 = ((10603 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF1_apply]
  rw [sum_getD_div w1zTF4_len imgz1_len pzITF_1_4 256 255]
  norm_num

theorem hpreITF1_eval_5 : denseE W1TF imgF1 5 = hpreITF1 5 := by
  rw [show hpreITF1 5 = ((-291922 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF1_apply]
  rw [sum_getD_div w1zTF5_len imgz1_len pzITF_1_5 256 255]
  norm_num

theorem hpreITF1_eval_6 : denseE W1TF imgF1 6 = hpreITF1 6 := by
  rw [show hpreITF1 6 = ((-247838 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF1_apply]
  rw [sum_getD_div w1zTF6_len imgz1_len pzITF_1_6 256 255]
  norm_num

theorem hpreITF1_eval_7 : denseE W1TF imgF1 7 = hpreITF1 7 := by
  rw [show hpreITF1 7 = ((-237476 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF1_apply]
  rw [sum_getD_div w1zTF7_len imgz1_len pzITF_1_7 256 255]
  norm_num

theorem hpreITF1_eval_8 : denseE W1TF imgF1 8 = hpreITF1 8 := by
  rw [show hpreITF1 8 = ((704514 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF1_apply]
  rw [sum_getD_div w1zTF8_len imgz1_len pzITF_1_8 256 255]
  norm_num

theorem hpreITF1_eval_9 : denseE W1TF imgF1 9 = hpreITF1 9 := by
  rw [show hpreITF1 9 = ((327175 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF1_apply]
  rw [sum_getD_div w1zTF9_len imgz1_len pzITF_1_9 256 255]
  norm_num

theorem hpreITF1_eval_10 : denseE W1TF imgF1 10 = hpreITF1 10 := by
  rw [show hpreITF1 10 = ((-198892 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF1_apply]
  rw [sum_getD_div w1zTF10_len imgz1_len pzITF_1_10 256 255]
  norm_num

theorem hpreITF1_eval_11 : denseE W1TF imgF1 11 = hpreITF1 11 := by
  rw [show hpreITF1 11 = ((75958 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF1_apply]
  rw [sum_getD_div w1zTF11_len imgz1_len pzITF_1_11 256 255]
  norm_num

theorem hpreITF1_eval_12 : denseE W1TF imgF1 12 = hpreITF1 12 := by
  rw [show hpreITF1 12 = ((-184558 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF1_apply]
  rw [sum_getD_div w1zTF12_len imgz1_len pzITF_1_12 256 255]
  norm_num

theorem hpreITF1_eval_13 : denseE W1TF imgF1 13 = hpreITF1 13 := by
  rw [show hpreITF1 13 = ((-58318 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF1_apply]
  rw [sum_getD_div w1zTF13_len imgz1_len pzITF_1_13 256 255]
  norm_num

theorem hpreITF1_eval_14 : denseE W1TF imgF1 14 = hpreITF1 14 := by
  rw [show hpreITF1 14 = ((155073 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF1_apply]
  rw [sum_getD_div w1zTF14_len imgz1_len pzITF_1_14 256 255]
  norm_num

theorem hpreITF1_eval_15 : denseE W1TF imgF1 15 = hpreITF1 15 := by
  rw [show hpreITF1 15 = ((519484 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF1_apply]
  rw [sum_getD_div w1zTF15_len imgz1_len pzITF_1_15 256 255]
  norm_num

theorem hpreITF1_eval : ∀ k : Fin 16, denseE W1TF imgF1 k = hpreITF1 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF1_eval_0; exact hpreITF1_eval_1; exact hpreITF1_eval_2; exact hpreITF1_eval_3; exact hpreITF1_eval_4; exact hpreITF1_eval_5; exact hpreITF1_eval_6; exact hpreITF1_eval_7; exact hpreITF1_eval_8; exact hpreITF1_eval_9; exact hpreITF1_eval_10; exact hpreITF1_eval_11; exact hpreITF1_eval_12; exact hpreITF1_eval_13; exact hpreITF1_eval_14; exact hpreITF1_eval_15 ]

theorem hpreITF1_sum : ∀ t, (∑ j, W1TF t j * imgF1 j) = hpreITF1 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF1_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_1 : ∀ j : Fin 10, j ≠ 2 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF1 q - ((1 : ℝ)/255)) (fun q => imgF1 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF1 q - ((1 : ℝ)/255)) (fun q => imgF1 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF1 q - ((1 : ℝ)/255)) (fun q => imgF1 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF1 q - ((1 : ℝ)/255)) (fun q => imgF1 q + ((1 : ℝ)/255)))) 2 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF1_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF1, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #1 (digit 2): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_1 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 2 → mlpTF (imgF1 + δ) j < mlpTF (imgF1 + δ) 2 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_1 δ hδ

theorem hpreTF2_sum : ∀ t, (∑ j, W1TF t j * imgF2 j) = hpreTF2 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF2_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_2 : ∀ j : Fin 10, j ≠ 1 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF2 q - ((1 : ℝ)/255)) (fun q => imgF2 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF2 q - ((1 : ℝ)/255)) (fun q => imgF2 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF2 q - ((1 : ℝ)/255)) (fun q => imgF2 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF2 q - ((1 : ℝ)/255)) (fun q => imgF2 q + ((1 : ℝ)/255)))) 1 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF2_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF2, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #2 (digit 1): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_2 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 1 → mlpTF (imgF2 + δ) j < mlpTF (imgF2 + δ) 1 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_2 δ hδ

theorem hpreTF3_sum : ∀ t, (∑ j, W1TF t j * imgF3 j) = hpreTF3 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF3_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_3 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF3 q - ((1 : ℝ)/255)) (fun q => imgF3 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF3 q - ((1 : ℝ)/255)) (fun q => imgF3 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF3 q - ((1 : ℝ)/255)) (fun q => imgF3 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF3 q - ((1 : ℝ)/255)) (fun q => imgF3 q + ((1 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF3_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF3, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #3 (digit 0): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_3 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF3 + δ) j < mlpTF (imgF3 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_3 δ hδ

set_option maxHeartbeats 6400000 in
theorem hbTFe2_3 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF3 q - ((2 : ℝ)/255)) (fun q => imgF3 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF3 q - ((2 : ℝ)/255)) (fun q => imgF3 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF3 q - ((2 : ℝ)/255)) (fun q => imgF3 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF3 q - ((2 : ℝ)/255)) (fun q => imgF3 q + ((2 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF3_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF3, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #3 (digit 0): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_3 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF3 + δ) j < mlpTF (imgF3 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_3 δ hδ

theorem hpreTF4_sum : ∀ t, (∑ j, W1TF t j * imgF4 j) = hpreTF4 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF4_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_4 : ∀ j : Fin 10, j ≠ 4 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF4 q - ((1 : ℝ)/255)) (fun q => imgF4 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF4 q - ((1 : ℝ)/255)) (fun q => imgF4 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF4 q - ((1 : ℝ)/255)) (fun q => imgF4 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF4 q - ((1 : ℝ)/255)) (fun q => imgF4 q + ((1 : ℝ)/255)))) 4 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF4_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF4, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #4 (digit 4): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_4 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 4 → mlpTF (imgF4 + δ) j < mlpTF (imgF4 + δ) 4 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_4 δ hδ

set_option maxHeartbeats 6400000 in
theorem hbTFe2_4 : ∀ j : Fin 10, j ≠ 4 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF4 q - ((2 : ℝ)/255)) (fun q => imgF4 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF4 q - ((2 : ℝ)/255)) (fun q => imgF4 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF4 q - ((2 : ℝ)/255)) (fun q => imgF4 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF4 q - ((2 : ℝ)/255)) (fun q => imgF4 q + ((2 : ℝ)/255)))) 4 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF4_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF4, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #4 (digit 4): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_4 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 4 → mlpTF (imgF4 + δ) j < mlpTF (imgF4 + δ) 4 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_4 δ hδ

theorem hpreTF5_sum : ∀ t, (∑ j, W1TF t j * imgF5 j) = hpreTF5 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF5_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_5 : ∀ j : Fin 10, j ≠ 1 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF5 q - ((1 : ℝ)/255)) (fun q => imgF5 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF5 q - ((1 : ℝ)/255)) (fun q => imgF5 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF5 q - ((1 : ℝ)/255)) (fun q => imgF5 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF5 q - ((1 : ℝ)/255)) (fun q => imgF5 q + ((1 : ℝ)/255)))) 1 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF5_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF5, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #5 (digit 1): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_5 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 1 → mlpTF (imgF5 + δ) j < mlpTF (imgF5 + δ) 1 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_5 δ hδ

theorem hpreTF6_sum : ∀ t, (∑ j, W1TF t j * imgF6 j) = hpreTF6 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF6_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_6 : ∀ j : Fin 10, j ≠ 4 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF6 q - ((1 : ℝ)/255)) (fun q => imgF6 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF6 q - ((1 : ℝ)/255)) (fun q => imgF6 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF6 q - ((1 : ℝ)/255)) (fun q => imgF6 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF6 q - ((1 : ℝ)/255)) (fun q => imgF6 q + ((1 : ℝ)/255)))) 4 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF6_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF6, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #6 (digit 4): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_6 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 4 → mlpTF (imgF6 + δ) j < mlpTF (imgF6 + δ) 4 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_6 δ hδ

theorem hpreTF7_sum : ∀ t, (∑ j, W1TF t j * imgF7 j) = hpreTF7 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF7_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe1_7 : ∀ j : Fin 10, j ≠ 9 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF7 q - ((1 : ℝ)/255)) (fun q => imgF7 q + ((1 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF7 q - ((1 : ℝ)/255)) (fun q => imgF7 q + ((1 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF7 q - ((1 : ℝ)/255)) (fun q => imgF7 q + ((1 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF7 q - ((1 : ℝ)/255)) (fun q => imgF7 q + ((1 : ℝ)/255)))) 9 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF7_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF7, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #7 (digit 9): IBP-certified at pixel-L∞ ε = 1/255. -/
theorem certIBPTFe1_7 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((1 : ℝ)/255)) :
    ∀ j, j ≠ 9 → mlpTF (imgF7 + δ) j < mlpTF (imgF7 + δ) 9 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe1_7 δ hδ

-- net TF pre-activations for #10 (not in the base L2-certified set)
theorem pzITF_10_0 : dotZ w1zTF0 imgz10 = 432447 := by decide +kernel
theorem pzITF_10_1 : dotZ w1zTF1 imgz10 = -898104 := by decide +kernel
theorem pzITF_10_2 : dotZ w1zTF2 imgz10 = -465484 := by decide +kernel
theorem pzITF_10_3 : dotZ w1zTF3 imgz10 = 158099 := by decide +kernel
theorem pzITF_10_4 : dotZ w1zTF4 imgz10 = 29888 := by decide +kernel
theorem pzITF_10_5 : dotZ w1zTF5 imgz10 = -226803 := by decide +kernel
theorem pzITF_10_6 : dotZ w1zTF6 imgz10 = -16175 := by decide +kernel
theorem pzITF_10_7 : dotZ w1zTF7 imgz10 = -263951 := by decide +kernel
theorem pzITF_10_8 : dotZ w1zTF8 imgz10 = 207353 := by decide +kernel
theorem pzITF_10_9 : dotZ w1zTF9 imgz10 = 226658 := by decide +kernel
theorem pzITF_10_10 : dotZ w1zTF10 imgz10 = 396221 := by decide +kernel
theorem pzITF_10_11 : dotZ w1zTF11 imgz10 = 292254 := by decide +kernel
theorem pzITF_10_12 : dotZ w1zTF12 imgz10 = -157396 := by decide +kernel
theorem pzITF_10_13 : dotZ w1zTF13 imgz10 = -51584 := by decide +kernel
theorem pzITF_10_14 : dotZ w1zTF14 imgz10 = -236442 := by decide +kernel
theorem pzITF_10_15 : dotZ w1zTF15 imgz10 = 438616 := by decide +kernel

noncomputable def hpreITF10 : Fin 16 → ℝ :=
  ![((432447 : ℝ)/65280), ((-898104 : ℝ)/65280), ((-465484 : ℝ)/65280), ((158099 : ℝ)/65280), ((29888 : ℝ)/65280), ((-226803 : ℝ)/65280), ((-16175 : ℝ)/65280), ((-263951 : ℝ)/65280), ((207353 : ℝ)/65280), ((226658 : ℝ)/65280), ((396221 : ℝ)/65280), ((292254 : ℝ)/65280), ((-157396 : ℝ)/65280), ((-51584 : ℝ)/65280), ((-236442 : ℝ)/65280), ((438616 : ℝ)/65280)]

theorem hpreITF10_eval_0 : denseE W1TF imgF10 0 = hpreITF10 0 := by
  rw [show hpreITF10 0 = ((432447 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF10_apply]
  rw [sum_getD_div w1zTF0_len imgz10_len pzITF_10_0 256 255]
  norm_num

theorem hpreITF10_eval_1 : denseE W1TF imgF10 1 = hpreITF10 1 := by
  rw [show hpreITF10 1 = ((-898104 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF10_apply]
  rw [sum_getD_div w1zTF1_len imgz10_len pzITF_10_1 256 255]
  norm_num

theorem hpreITF10_eval_2 : denseE W1TF imgF10 2 = hpreITF10 2 := by
  rw [show hpreITF10 2 = ((-465484 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF10_apply]
  rw [sum_getD_div w1zTF2_len imgz10_len pzITF_10_2 256 255]
  norm_num

theorem hpreITF10_eval_3 : denseE W1TF imgF10 3 = hpreITF10 3 := by
  rw [show hpreITF10 3 = ((158099 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF10_apply]
  rw [sum_getD_div w1zTF3_len imgz10_len pzITF_10_3 256 255]
  norm_num

theorem hpreITF10_eval_4 : denseE W1TF imgF10 4 = hpreITF10 4 := by
  rw [show hpreITF10 4 = ((29888 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF10_apply]
  rw [sum_getD_div w1zTF4_len imgz10_len pzITF_10_4 256 255]
  norm_num

theorem hpreITF10_eval_5 : denseE W1TF imgF10 5 = hpreITF10 5 := by
  rw [show hpreITF10 5 = ((-226803 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF10_apply]
  rw [sum_getD_div w1zTF5_len imgz10_len pzITF_10_5 256 255]
  norm_num

theorem hpreITF10_eval_6 : denseE W1TF imgF10 6 = hpreITF10 6 := by
  rw [show hpreITF10 6 = ((-16175 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF10_apply]
  rw [sum_getD_div w1zTF6_len imgz10_len pzITF_10_6 256 255]
  norm_num

theorem hpreITF10_eval_7 : denseE W1TF imgF10 7 = hpreITF10 7 := by
  rw [show hpreITF10 7 = ((-263951 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF10_apply]
  rw [sum_getD_div w1zTF7_len imgz10_len pzITF_10_7 256 255]
  norm_num

theorem hpreITF10_eval_8 : denseE W1TF imgF10 8 = hpreITF10 8 := by
  rw [show hpreITF10 8 = ((207353 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF10_apply]
  rw [sum_getD_div w1zTF8_len imgz10_len pzITF_10_8 256 255]
  norm_num

theorem hpreITF10_eval_9 : denseE W1TF imgF10 9 = hpreITF10 9 := by
  rw [show hpreITF10 9 = ((226658 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF10_apply]
  rw [sum_getD_div w1zTF9_len imgz10_len pzITF_10_9 256 255]
  norm_num

theorem hpreITF10_eval_10 : denseE W1TF imgF10 10 = hpreITF10 10 := by
  rw [show hpreITF10 10 = ((396221 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF10_apply]
  rw [sum_getD_div w1zTF10_len imgz10_len pzITF_10_10 256 255]
  norm_num

theorem hpreITF10_eval_11 : denseE W1TF imgF10 11 = hpreITF10 11 := by
  rw [show hpreITF10 11 = ((292254 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF10_apply]
  rw [sum_getD_div w1zTF11_len imgz10_len pzITF_10_11 256 255]
  norm_num

theorem hpreITF10_eval_12 : denseE W1TF imgF10 12 = hpreITF10 12 := by
  rw [show hpreITF10 12 = ((-157396 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF10_apply]
  rw [sum_getD_div w1zTF12_len imgz10_len pzITF_10_12 256 255]
  norm_num

theorem hpreITF10_eval_13 : denseE W1TF imgF10 13 = hpreITF10 13 := by
  rw [show hpreITF10 13 = ((-51584 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF10_apply]
  rw [sum_getD_div w1zTF13_len imgz10_len pzITF_10_13 256 255]
  norm_num

theorem hpreITF10_eval_14 : denseE W1TF imgF10 14 = hpreITF10 14 := by
  rw [show hpreITF10 14 = ((-236442 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF10_apply]
  rw [sum_getD_div w1zTF14_len imgz10_len pzITF_10_14 256 255]
  norm_num

theorem hpreITF10_eval_15 : denseE W1TF imgF10 15 = hpreITF10 15 := by
  rw [show hpreITF10 15 = ((438616 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF10_apply]
  rw [sum_getD_div w1zTF15_len imgz10_len pzITF_10_15 256 255]
  norm_num

theorem hpreITF10_eval : ∀ k : Fin 16, denseE W1TF imgF10 k = hpreITF10 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF10_eval_0; exact hpreITF10_eval_1; exact hpreITF10_eval_2; exact hpreITF10_eval_3; exact hpreITF10_eval_4; exact hpreITF10_eval_5; exact hpreITF10_eval_6; exact hpreITF10_eval_7; exact hpreITF10_eval_8; exact hpreITF10_eval_9; exact hpreITF10_eval_10; exact hpreITF10_eval_11; exact hpreITF10_eval_12; exact hpreITF10_eval_13; exact hpreITF10_eval_14; exact hpreITF10_eval_15 ]

theorem hpreITF10_sum : ∀ t, (∑ j, W1TF t j * imgF10 j) = hpreITF10 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF10_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_10 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF10 q - ((2 : ℝ)/255)) (fun q => imgF10 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF10 q - ((2 : ℝ)/255)) (fun q => imgF10 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF10 q - ((2 : ℝ)/255)) (fun q => imgF10 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF10 q - ((2 : ℝ)/255)) (fun q => imgF10 q + ((2 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF10_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF10, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #10 (digit 0): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_10 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF10 + δ) j < mlpTF (imgF10 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_10 δ hδ

/-- MNIST test image #11 (digit 6), exact pixels k/255. -/
def imgz11 : List ℤ := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 204, 253, 176, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 150, 252, 252, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 252, 186, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 141, 252, 118, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 154, 247, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 253, 196, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 253, 196, 0, 0, 0, 0, 0, 0, 0, 57, 85, 85, 38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 253, 96, 0, 0, 0, 0, 0, 151, 226, 243, 252, 252, 238, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 229, 226, 0, 0, 0, 4, 54, 229, 253, 255, 234, 175, 225, 255, 228, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 252, 150, 0, 0, 26, 128, 252, 252, 227, 134, 28, 0, 0, 178, 252, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 252, 113, 0, 0, 150, 253, 252, 186, 43, 0, 0, 0, 0, 141, 252, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185, 252, 113, 0, 38, 237, 253, 151, 6, 0, 0, 0, 0, 0, 141, 202, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 198, 253, 114, 0, 147, 253, 163, 0, 0, 0, 0, 0, 0, 0, 154, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197, 252, 113, 0, 172, 252, 188, 0, 0, 0, 0, 0, 0, 26, 253, 171, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197, 252, 113, 0, 19, 231, 247, 122, 19, 0, 0, 0, 0, 200, 244, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 222, 252, 113, 0, 0, 25, 203, 252, 193, 13, 0, 76, 200, 249, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 185, 253, 179, 10, 0, 0, 0, 76, 35, 29, 154, 253, 244, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 209, 253, 196, 82, 57, 57, 131, 197, 252, 253, 214, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 216, 252, 252, 252, 253, 252, 252, 252, 156, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 103, 139, 240, 140, 139, 139, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

theorem imgz11_len : (imgz11).length = 784 := by decide +kernel

noncomputable def imgv11 : Fin 784 → ℝ := fun j => ((imgz11).getD j 0 : ℝ)/255

noncomputable def imgF11 : EuclideanSpace ℝ (Fin 784) := WithLp.toLp 2 imgv11

theorem imgF11_apply : ∀ j, imgF11 j = ((imgz11).getD j 0 : ℝ)/255 := fun _ => rfl

-- net TF pre-activations for #11 (not in the base L2-certified set)
theorem pzITF_11_0 : dotZ w1zTF0 imgz11 = 14040 := by decide +kernel
theorem pzITF_11_1 : dotZ w1zTF1 imgz11 = -530694 := by decide +kernel
theorem pzITF_11_2 : dotZ w1zTF2 imgz11 = -308846 := by decide +kernel
theorem pzITF_11_3 : dotZ w1zTF3 imgz11 = 12303 := by decide +kernel
theorem pzITF_11_4 : dotZ w1zTF4 imgz11 = -9645 := by decide +kernel
theorem pzITF_11_5 : dotZ w1zTF5 imgz11 = 119769 := by decide +kernel
theorem pzITF_11_6 : dotZ w1zTF6 imgz11 = -66378 := by decide +kernel
theorem pzITF_11_7 : dotZ w1zTF7 imgz11 = -63039 := by decide +kernel
theorem pzITF_11_8 : dotZ w1zTF8 imgz11 = 326139 := by decide +kernel
theorem pzITF_11_9 : dotZ w1zTF9 imgz11 = 493750 := by decide +kernel
theorem pzITF_11_10 : dotZ w1zTF10 imgz11 = 92772 := by decide +kernel
theorem pzITF_11_11 : dotZ w1zTF11 imgz11 = 449337 := by decide +kernel
theorem pzITF_11_12 : dotZ w1zTF12 imgz11 = 276212 := by decide +kernel
theorem pzITF_11_13 : dotZ w1zTF13 imgz11 = -55898 := by decide +kernel
theorem pzITF_11_14 : dotZ w1zTF14 imgz11 = 185753 := by decide +kernel
theorem pzITF_11_15 : dotZ w1zTF15 imgz11 = 7461 := by decide +kernel

noncomputable def hpreITF11 : Fin 16 → ℝ :=
  ![((14040 : ℝ)/65280), ((-530694 : ℝ)/65280), ((-308846 : ℝ)/65280), ((12303 : ℝ)/65280), ((-9645 : ℝ)/65280), ((119769 : ℝ)/65280), ((-66378 : ℝ)/65280), ((-63039 : ℝ)/65280), ((326139 : ℝ)/65280), ((493750 : ℝ)/65280), ((92772 : ℝ)/65280), ((449337 : ℝ)/65280), ((276212 : ℝ)/65280), ((-55898 : ℝ)/65280), ((185753 : ℝ)/65280), ((7461 : ℝ)/65280)]

theorem hpreITF11_eval_0 : denseE W1TF imgF11 0 = hpreITF11 0 := by
  rw [show hpreITF11 0 = ((14040 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF11_apply]
  rw [sum_getD_div w1zTF0_len imgz11_len pzITF_11_0 256 255]
  norm_num

theorem hpreITF11_eval_1 : denseE W1TF imgF11 1 = hpreITF11 1 := by
  rw [show hpreITF11 1 = ((-530694 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF11_apply]
  rw [sum_getD_div w1zTF1_len imgz11_len pzITF_11_1 256 255]
  norm_num

theorem hpreITF11_eval_2 : denseE W1TF imgF11 2 = hpreITF11 2 := by
  rw [show hpreITF11 2 = ((-308846 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF11_apply]
  rw [sum_getD_div w1zTF2_len imgz11_len pzITF_11_2 256 255]
  norm_num

theorem hpreITF11_eval_3 : denseE W1TF imgF11 3 = hpreITF11 3 := by
  rw [show hpreITF11 3 = ((12303 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF11_apply]
  rw [sum_getD_div w1zTF3_len imgz11_len pzITF_11_3 256 255]
  norm_num

theorem hpreITF11_eval_4 : denseE W1TF imgF11 4 = hpreITF11 4 := by
  rw [show hpreITF11 4 = ((-9645 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF11_apply]
  rw [sum_getD_div w1zTF4_len imgz11_len pzITF_11_4 256 255]
  norm_num

theorem hpreITF11_eval_5 : denseE W1TF imgF11 5 = hpreITF11 5 := by
  rw [show hpreITF11 5 = ((119769 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF11_apply]
  rw [sum_getD_div w1zTF5_len imgz11_len pzITF_11_5 256 255]
  norm_num

theorem hpreITF11_eval_6 : denseE W1TF imgF11 6 = hpreITF11 6 := by
  rw [show hpreITF11 6 = ((-66378 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF11_apply]
  rw [sum_getD_div w1zTF6_len imgz11_len pzITF_11_6 256 255]
  norm_num

theorem hpreITF11_eval_7 : denseE W1TF imgF11 7 = hpreITF11 7 := by
  rw [show hpreITF11 7 = ((-63039 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF11_apply]
  rw [sum_getD_div w1zTF7_len imgz11_len pzITF_11_7 256 255]
  norm_num

theorem hpreITF11_eval_8 : denseE W1TF imgF11 8 = hpreITF11 8 := by
  rw [show hpreITF11 8 = ((326139 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF11_apply]
  rw [sum_getD_div w1zTF8_len imgz11_len pzITF_11_8 256 255]
  norm_num

theorem hpreITF11_eval_9 : denseE W1TF imgF11 9 = hpreITF11 9 := by
  rw [show hpreITF11 9 = ((493750 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF11_apply]
  rw [sum_getD_div w1zTF9_len imgz11_len pzITF_11_9 256 255]
  norm_num

theorem hpreITF11_eval_10 : denseE W1TF imgF11 10 = hpreITF11 10 := by
  rw [show hpreITF11 10 = ((92772 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF11_apply]
  rw [sum_getD_div w1zTF10_len imgz11_len pzITF_11_10 256 255]
  norm_num

theorem hpreITF11_eval_11 : denseE W1TF imgF11 11 = hpreITF11 11 := by
  rw [show hpreITF11 11 = ((449337 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF11_apply]
  rw [sum_getD_div w1zTF11_len imgz11_len pzITF_11_11 256 255]
  norm_num

theorem hpreITF11_eval_12 : denseE W1TF imgF11 12 = hpreITF11 12 := by
  rw [show hpreITF11 12 = ((276212 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF11_apply]
  rw [sum_getD_div w1zTF12_len imgz11_len pzITF_11_12 256 255]
  norm_num

theorem hpreITF11_eval_13 : denseE W1TF imgF11 13 = hpreITF11 13 := by
  rw [show hpreITF11 13 = ((-55898 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF11_apply]
  rw [sum_getD_div w1zTF13_len imgz11_len pzITF_11_13 256 255]
  norm_num

theorem hpreITF11_eval_14 : denseE W1TF imgF11 14 = hpreITF11 14 := by
  rw [show hpreITF11 14 = ((185753 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF11_apply]
  rw [sum_getD_div w1zTF14_len imgz11_len pzITF_11_14 256 255]
  norm_num

theorem hpreITF11_eval_15 : denseE W1TF imgF11 15 = hpreITF11 15 := by
  rw [show hpreITF11 15 = ((7461 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF11_apply]
  rw [sum_getD_div w1zTF15_len imgz11_len pzITF_11_15 256 255]
  norm_num

theorem hpreITF11_eval : ∀ k : Fin 16, denseE W1TF imgF11 k = hpreITF11 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF11_eval_0; exact hpreITF11_eval_1; exact hpreITF11_eval_2; exact hpreITF11_eval_3; exact hpreITF11_eval_4; exact hpreITF11_eval_5; exact hpreITF11_eval_6; exact hpreITF11_eval_7; exact hpreITF11_eval_8; exact hpreITF11_eval_9; exact hpreITF11_eval_10; exact hpreITF11_eval_11; exact hpreITF11_eval_12; exact hpreITF11_eval_13; exact hpreITF11_eval_14; exact hpreITF11_eval_15 ]

theorem hpreITF11_sum : ∀ t, (∑ j, W1TF t j * imgF11 j) = hpreITF11 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF11_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_11 : ∀ j : Fin 10, j ≠ 6 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF11 q - ((2 : ℝ)/255)) (fun q => imgF11 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF11 q - ((2 : ℝ)/255)) (fun q => imgF11 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF11 q - ((2 : ℝ)/255)) (fun q => imgF11 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF11 q - ((2 : ℝ)/255)) (fun q => imgF11 q + ((2 : ℝ)/255)))) 6 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF11_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF11, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #11 (digit 6): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_11 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 6 → mlpTF (imgF11 + δ) j < mlpTF (imgF11 + δ) 6 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_11 δ hδ

-- net TF pre-activations for #13 (not in the base L2-certified set)
theorem pzITF_13_0 : dotZ w1zTF0 imgz13 = 315274 := by decide +kernel
theorem pzITF_13_1 : dotZ w1zTF1 imgz13 = -631046 := by decide +kernel
theorem pzITF_13_2 : dotZ w1zTF2 imgz13 = -526036 := by decide +kernel
theorem pzITF_13_3 : dotZ w1zTF3 imgz13 = -15390 := by decide +kernel
theorem pzITF_13_4 : dotZ w1zTF4 imgz13 = -111197 := by decide +kernel
theorem pzITF_13_5 : dotZ w1zTF5 imgz13 = -164638 := by decide +kernel
theorem pzITF_13_6 : dotZ w1zTF6 imgz13 = -627 := by decide +kernel
theorem pzITF_13_7 : dotZ w1zTF7 imgz13 = -307823 := by decide +kernel
theorem pzITF_13_8 : dotZ w1zTF8 imgz13 = 66700 := by decide +kernel
theorem pzITF_13_9 : dotZ w1zTF9 imgz13 = 272263 := by decide +kernel
theorem pzITF_13_10 : dotZ w1zTF10 imgz13 = 479498 := by decide +kernel
theorem pzITF_13_11 : dotZ w1zTF11 imgz13 = 228046 := by decide +kernel
theorem pzITF_13_12 : dotZ w1zTF12 imgz13 = 43606 := by decide +kernel
theorem pzITF_13_13 : dotZ w1zTF13 imgz13 = -172816 := by decide +kernel
theorem pzITF_13_14 : dotZ w1zTF14 imgz13 = -349191 := by decide +kernel
theorem pzITF_13_15 : dotZ w1zTF15 imgz13 = 184087 := by decide +kernel

noncomputable def hpreITF13 : Fin 16 → ℝ :=
  ![((315274 : ℝ)/65280), ((-631046 : ℝ)/65280), ((-526036 : ℝ)/65280), ((-15390 : ℝ)/65280), ((-111197 : ℝ)/65280), ((-164638 : ℝ)/65280), ((-627 : ℝ)/65280), ((-307823 : ℝ)/65280), ((66700 : ℝ)/65280), ((272263 : ℝ)/65280), ((479498 : ℝ)/65280), ((228046 : ℝ)/65280), ((43606 : ℝ)/65280), ((-172816 : ℝ)/65280), ((-349191 : ℝ)/65280), ((184087 : ℝ)/65280)]

theorem hpreITF13_eval_0 : denseE W1TF imgF13 0 = hpreITF13 0 := by
  rw [show hpreITF13 0 = ((315274 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF13_apply]
  rw [sum_getD_div w1zTF0_len imgz13_len pzITF_13_0 256 255]
  norm_num

theorem hpreITF13_eval_1 : denseE W1TF imgF13 1 = hpreITF13 1 := by
  rw [show hpreITF13 1 = ((-631046 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF13_apply]
  rw [sum_getD_div w1zTF1_len imgz13_len pzITF_13_1 256 255]
  norm_num

theorem hpreITF13_eval_2 : denseE W1TF imgF13 2 = hpreITF13 2 := by
  rw [show hpreITF13 2 = ((-526036 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF13_apply]
  rw [sum_getD_div w1zTF2_len imgz13_len pzITF_13_2 256 255]
  norm_num

theorem hpreITF13_eval_3 : denseE W1TF imgF13 3 = hpreITF13 3 := by
  rw [show hpreITF13 3 = ((-15390 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF13_apply]
  rw [sum_getD_div w1zTF3_len imgz13_len pzITF_13_3 256 255]
  norm_num

theorem hpreITF13_eval_4 : denseE W1TF imgF13 4 = hpreITF13 4 := by
  rw [show hpreITF13 4 = ((-111197 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF13_apply]
  rw [sum_getD_div w1zTF4_len imgz13_len pzITF_13_4 256 255]
  norm_num

theorem hpreITF13_eval_5 : denseE W1TF imgF13 5 = hpreITF13 5 := by
  rw [show hpreITF13 5 = ((-164638 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF13_apply]
  rw [sum_getD_div w1zTF5_len imgz13_len pzITF_13_5 256 255]
  norm_num

theorem hpreITF13_eval_6 : denseE W1TF imgF13 6 = hpreITF13 6 := by
  rw [show hpreITF13 6 = ((-627 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF13_apply]
  rw [sum_getD_div w1zTF6_len imgz13_len pzITF_13_6 256 255]
  norm_num

theorem hpreITF13_eval_7 : denseE W1TF imgF13 7 = hpreITF13 7 := by
  rw [show hpreITF13 7 = ((-307823 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF13_apply]
  rw [sum_getD_div w1zTF7_len imgz13_len pzITF_13_7 256 255]
  norm_num

theorem hpreITF13_eval_8 : denseE W1TF imgF13 8 = hpreITF13 8 := by
  rw [show hpreITF13 8 = ((66700 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF13_apply]
  rw [sum_getD_div w1zTF8_len imgz13_len pzITF_13_8 256 255]
  norm_num

theorem hpreITF13_eval_9 : denseE W1TF imgF13 9 = hpreITF13 9 := by
  rw [show hpreITF13 9 = ((272263 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF13_apply]
  rw [sum_getD_div w1zTF9_len imgz13_len pzITF_13_9 256 255]
  norm_num

theorem hpreITF13_eval_10 : denseE W1TF imgF13 10 = hpreITF13 10 := by
  rw [show hpreITF13 10 = ((479498 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF13_apply]
  rw [sum_getD_div w1zTF10_len imgz13_len pzITF_13_10 256 255]
  norm_num

theorem hpreITF13_eval_11 : denseE W1TF imgF13 11 = hpreITF13 11 := by
  rw [show hpreITF13 11 = ((228046 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF13_apply]
  rw [sum_getD_div w1zTF11_len imgz13_len pzITF_13_11 256 255]
  norm_num

theorem hpreITF13_eval_12 : denseE W1TF imgF13 12 = hpreITF13 12 := by
  rw [show hpreITF13 12 = ((43606 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF13_apply]
  rw [sum_getD_div w1zTF12_len imgz13_len pzITF_13_12 256 255]
  norm_num

theorem hpreITF13_eval_13 : denseE W1TF imgF13 13 = hpreITF13 13 := by
  rw [show hpreITF13 13 = ((-172816 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF13_apply]
  rw [sum_getD_div w1zTF13_len imgz13_len pzITF_13_13 256 255]
  norm_num

theorem hpreITF13_eval_14 : denseE W1TF imgF13 14 = hpreITF13 14 := by
  rw [show hpreITF13 14 = ((-349191 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF13_apply]
  rw [sum_getD_div w1zTF14_len imgz13_len pzITF_13_14 256 255]
  norm_num

theorem hpreITF13_eval_15 : denseE W1TF imgF13 15 = hpreITF13 15 := by
  rw [show hpreITF13 15 = ((184087 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF13_apply]
  rw [sum_getD_div w1zTF15_len imgz13_len pzITF_13_15 256 255]
  norm_num

theorem hpreITF13_eval : ∀ k : Fin 16, denseE W1TF imgF13 k = hpreITF13 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF13_eval_0; exact hpreITF13_eval_1; exact hpreITF13_eval_2; exact hpreITF13_eval_3; exact hpreITF13_eval_4; exact hpreITF13_eval_5; exact hpreITF13_eval_6; exact hpreITF13_eval_7; exact hpreITF13_eval_8; exact hpreITF13_eval_9; exact hpreITF13_eval_10; exact hpreITF13_eval_11; exact hpreITF13_eval_12; exact hpreITF13_eval_13; exact hpreITF13_eval_14; exact hpreITF13_eval_15 ]

theorem hpreITF13_sum : ∀ t, (∑ j, W1TF t j * imgF13 j) = hpreITF13 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF13_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_13 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF13 q - ((2 : ℝ)/255)) (fun q => imgF13 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF13 q - ((2 : ℝ)/255)) (fun q => imgF13 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF13 q - ((2 : ℝ)/255)) (fun q => imgF13 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF13 q - ((2 : ℝ)/255)) (fun q => imgF13 q + ((2 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF13_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF13, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #13 (digit 0): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_13 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF13 + δ) j < mlpTF (imgF13 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_13 δ hδ

/-- MNIST test image #19 (digit 4), exact pixels k/255. -/
def imgz19 : List ℤ := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 234, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 254, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 178, 31, 0, 0, 0, 0, 0, 51, 254, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 94, 254, 83, 0, 0, 0, 0, 0, 87, 254, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 254, 56, 0, 0, 0, 0, 0, 189, 238, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 227, 168, 2, 0, 0, 0, 0, 0, 194, 236, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 254, 114, 0, 0, 0, 0, 0, 16, 235, 167, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 254, 50, 0, 0, 0, 0, 0, 103, 254, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 221, 236, 75, 156, 180, 190, 252, 252, 253, 254, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 254, 254, 254, 252, 211, 179, 179, 179, 246, 254, 247, 94, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 217, 239, 117, 22, 0, 0, 0, 0, 226, 254, 242, 197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 18, 0, 0, 0, 0, 0, 27, 243, 207, 46, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 254, 132, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 116, 254, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 116, 254, 61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 116, 254, 61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 174, 255, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 187, 254, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 176, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

theorem imgz19_len : (imgz19).length = 784 := by decide +kernel

noncomputable def imgv19 : Fin 784 → ℝ := fun j => ((imgz19).getD j 0 : ℝ)/255

noncomputable def imgF19 : EuclideanSpace ℝ (Fin 784) := WithLp.toLp 2 imgv19

theorem imgF19_apply : ∀ j, imgF19 j = ((imgz19).getD j 0 : ℝ)/255 := fun _ => rfl

-- net TF pre-activations for #19 (not in the base L2-certified set)
theorem pzITF_19_0 : dotZ w1zTF0 imgz19 = -35247 := by decide +kernel
theorem pzITF_19_1 : dotZ w1zTF1 imgz19 = 69574 := by decide +kernel
theorem pzITF_19_2 : dotZ w1zTF2 imgz19 = -83787 := by decide +kernel
theorem pzITF_19_3 : dotZ w1zTF3 imgz19 = 35049 := by decide +kernel
theorem pzITF_19_4 : dotZ w1zTF4 imgz19 = 133501 := by decide +kernel
theorem pzITF_19_5 : dotZ w1zTF5 imgz19 = 168897 := by decide +kernel
theorem pzITF_19_6 : dotZ w1zTF6 imgz19 = 305868 := by decide +kernel
theorem pzITF_19_7 : dotZ w1zTF7 imgz19 = -43372 := by decide +kernel
theorem pzITF_19_8 : dotZ w1zTF8 imgz19 = 92064 := by decide +kernel
theorem pzITF_19_9 : dotZ w1zTF9 imgz19 = 192500 := by decide +kernel
theorem pzITF_19_10 : dotZ w1zTF10 imgz19 = 253712 := by decide +kernel
theorem pzITF_19_11 : dotZ w1zTF11 imgz19 = 189799 := by decide +kernel
theorem pzITF_19_12 : dotZ w1zTF12 imgz19 = -27954 := by decide +kernel
theorem pzITF_19_13 : dotZ w1zTF13 imgz19 = -182271 := by decide +kernel
theorem pzITF_19_14 : dotZ w1zTF14 imgz19 = 81866 := by decide +kernel
theorem pzITF_19_15 : dotZ w1zTF15 imgz19 = -90723 := by decide +kernel

noncomputable def hpreITF19 : Fin 16 → ℝ :=
  ![((-35247 : ℝ)/65280), ((69574 : ℝ)/65280), ((-83787 : ℝ)/65280), ((35049 : ℝ)/65280), ((133501 : ℝ)/65280), ((168897 : ℝ)/65280), ((305868 : ℝ)/65280), ((-43372 : ℝ)/65280), ((92064 : ℝ)/65280), ((192500 : ℝ)/65280), ((253712 : ℝ)/65280), ((189799 : ℝ)/65280), ((-27954 : ℝ)/65280), ((-182271 : ℝ)/65280), ((81866 : ℝ)/65280), ((-90723 : ℝ)/65280)]

theorem hpreITF19_eval_0 : denseE W1TF imgF19 0 = hpreITF19 0 := by
  rw [show hpreITF19 0 = ((-35247 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF19_apply]
  rw [sum_getD_div w1zTF0_len imgz19_len pzITF_19_0 256 255]
  norm_num

theorem hpreITF19_eval_1 : denseE W1TF imgF19 1 = hpreITF19 1 := by
  rw [show hpreITF19 1 = ((69574 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF19_apply]
  rw [sum_getD_div w1zTF1_len imgz19_len pzITF_19_1 256 255]
  norm_num

theorem hpreITF19_eval_2 : denseE W1TF imgF19 2 = hpreITF19 2 := by
  rw [show hpreITF19 2 = ((-83787 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF19_apply]
  rw [sum_getD_div w1zTF2_len imgz19_len pzITF_19_2 256 255]
  norm_num

theorem hpreITF19_eval_3 : denseE W1TF imgF19 3 = hpreITF19 3 := by
  rw [show hpreITF19 3 = ((35049 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF19_apply]
  rw [sum_getD_div w1zTF3_len imgz19_len pzITF_19_3 256 255]
  norm_num

theorem hpreITF19_eval_4 : denseE W1TF imgF19 4 = hpreITF19 4 := by
  rw [show hpreITF19 4 = ((133501 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF19_apply]
  rw [sum_getD_div w1zTF4_len imgz19_len pzITF_19_4 256 255]
  norm_num

theorem hpreITF19_eval_5 : denseE W1TF imgF19 5 = hpreITF19 5 := by
  rw [show hpreITF19 5 = ((168897 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF19_apply]
  rw [sum_getD_div w1zTF5_len imgz19_len pzITF_19_5 256 255]
  norm_num

theorem hpreITF19_eval_6 : denseE W1TF imgF19 6 = hpreITF19 6 := by
  rw [show hpreITF19 6 = ((305868 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF19_apply]
  rw [sum_getD_div w1zTF6_len imgz19_len pzITF_19_6 256 255]
  norm_num

theorem hpreITF19_eval_7 : denseE W1TF imgF19 7 = hpreITF19 7 := by
  rw [show hpreITF19 7 = ((-43372 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF19_apply]
  rw [sum_getD_div w1zTF7_len imgz19_len pzITF_19_7 256 255]
  norm_num

theorem hpreITF19_eval_8 : denseE W1TF imgF19 8 = hpreITF19 8 := by
  rw [show hpreITF19 8 = ((92064 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF19_apply]
  rw [sum_getD_div w1zTF8_len imgz19_len pzITF_19_8 256 255]
  norm_num

theorem hpreITF19_eval_9 : denseE W1TF imgF19 9 = hpreITF19 9 := by
  rw [show hpreITF19 9 = ((192500 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF19_apply]
  rw [sum_getD_div w1zTF9_len imgz19_len pzITF_19_9 256 255]
  norm_num

theorem hpreITF19_eval_10 : denseE W1TF imgF19 10 = hpreITF19 10 := by
  rw [show hpreITF19 10 = ((253712 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF19_apply]
  rw [sum_getD_div w1zTF10_len imgz19_len pzITF_19_10 256 255]
  norm_num

theorem hpreITF19_eval_11 : denseE W1TF imgF19 11 = hpreITF19 11 := by
  rw [show hpreITF19 11 = ((189799 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF19_apply]
  rw [sum_getD_div w1zTF11_len imgz19_len pzITF_19_11 256 255]
  norm_num

theorem hpreITF19_eval_12 : denseE W1TF imgF19 12 = hpreITF19 12 := by
  rw [show hpreITF19 12 = ((-27954 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF19_apply]
  rw [sum_getD_div w1zTF12_len imgz19_len pzITF_19_12 256 255]
  norm_num

theorem hpreITF19_eval_13 : denseE W1TF imgF19 13 = hpreITF19 13 := by
  rw [show hpreITF19 13 = ((-182271 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF19_apply]
  rw [sum_getD_div w1zTF13_len imgz19_len pzITF_19_13 256 255]
  norm_num

theorem hpreITF19_eval_14 : denseE W1TF imgF19 14 = hpreITF19 14 := by
  rw [show hpreITF19 14 = ((81866 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF19_apply]
  rw [sum_getD_div w1zTF14_len imgz19_len pzITF_19_14 256 255]
  norm_num

theorem hpreITF19_eval_15 : denseE W1TF imgF19 15 = hpreITF19 15 := by
  rw [show hpreITF19 15 = ((-90723 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF19_apply]
  rw [sum_getD_div w1zTF15_len imgz19_len pzITF_19_15 256 255]
  norm_num

theorem hpreITF19_eval : ∀ k : Fin 16, denseE W1TF imgF19 k = hpreITF19 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF19_eval_0; exact hpreITF19_eval_1; exact hpreITF19_eval_2; exact hpreITF19_eval_3; exact hpreITF19_eval_4; exact hpreITF19_eval_5; exact hpreITF19_eval_6; exact hpreITF19_eval_7; exact hpreITF19_eval_8; exact hpreITF19_eval_9; exact hpreITF19_eval_10; exact hpreITF19_eval_11; exact hpreITF19_eval_12; exact hpreITF19_eval_13; exact hpreITF19_eval_14; exact hpreITF19_eval_15 ]

theorem hpreITF19_sum : ∀ t, (∑ j, W1TF t j * imgF19 j) = hpreITF19 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF19_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_19 : ∀ j : Fin 10, j ≠ 4 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF19 q - ((2 : ℝ)/255)) (fun q => imgF19 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF19 q - ((2 : ℝ)/255)) (fun q => imgF19 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF19 q - ((2 : ℝ)/255)) (fun q => imgF19 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF19 q - ((2 : ℝ)/255)) (fun q => imgF19 q + ((2 : ℝ)/255)))) 4 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF19_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF19, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #19 (digit 4): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_19 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 4 → mlpTF (imgF19 + δ) j < mlpTF (imgF19 + δ) 4 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_19 δ hδ

-- net TF pre-activations for #21 (not in the base L2-certified set)
theorem pzITF_21_0 : dotZ w1zTF0 imgz21 = -7703 := by decide +kernel
theorem pzITF_21_1 : dotZ w1zTF1 imgz21 = -221813 := by decide +kernel
theorem pzITF_21_2 : dotZ w1zTF2 imgz21 = -217124 := by decide +kernel
theorem pzITF_21_3 : dotZ w1zTF3 imgz21 = 69789 := by decide +kernel
theorem pzITF_21_4 : dotZ w1zTF4 imgz21 = -307669 := by decide +kernel
theorem pzITF_21_5 : dotZ w1zTF5 imgz21 = -47833 := by decide +kernel
theorem pzITF_21_6 : dotZ w1zTF6 imgz21 = 167170 := by decide +kernel
theorem pzITF_21_7 : dotZ w1zTF7 imgz21 = -86419 := by decide +kernel
theorem pzITF_21_8 : dotZ w1zTF8 imgz21 = 265064 := by decide +kernel
theorem pzITF_21_9 : dotZ w1zTF9 imgz21 = 35174 := by decide +kernel
theorem pzITF_21_10 : dotZ w1zTF10 imgz21 = 70787 := by decide +kernel
theorem pzITF_21_11 : dotZ w1zTF11 imgz21 = 451751 := by decide +kernel
theorem pzITF_21_12 : dotZ w1zTF12 imgz21 = -296497 := by decide +kernel
theorem pzITF_21_13 : dotZ w1zTF13 imgz21 = -63723 := by decide +kernel
theorem pzITF_21_14 : dotZ w1zTF14 imgz21 = 105714 := by decide +kernel
theorem pzITF_21_15 : dotZ w1zTF15 imgz21 = 173863 := by decide +kernel

noncomputable def hpreITF21 : Fin 16 → ℝ :=
  ![((-7703 : ℝ)/65280), ((-221813 : ℝ)/65280), ((-217124 : ℝ)/65280), ((69789 : ℝ)/65280), ((-307669 : ℝ)/65280), ((-47833 : ℝ)/65280), ((167170 : ℝ)/65280), ((-86419 : ℝ)/65280), ((265064 : ℝ)/65280), ((35174 : ℝ)/65280), ((70787 : ℝ)/65280), ((451751 : ℝ)/65280), ((-296497 : ℝ)/65280), ((-63723 : ℝ)/65280), ((105714 : ℝ)/65280), ((173863 : ℝ)/65280)]

theorem hpreITF21_eval_0 : denseE W1TF imgF21 0 = hpreITF21 0 := by
  rw [show hpreITF21 0 = ((-7703 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF21_apply]
  rw [sum_getD_div w1zTF0_len imgz21_len pzITF_21_0 256 255]
  norm_num

theorem hpreITF21_eval_1 : denseE W1TF imgF21 1 = hpreITF21 1 := by
  rw [show hpreITF21 1 = ((-221813 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF21_apply]
  rw [sum_getD_div w1zTF1_len imgz21_len pzITF_21_1 256 255]
  norm_num

theorem hpreITF21_eval_2 : denseE W1TF imgF21 2 = hpreITF21 2 := by
  rw [show hpreITF21 2 = ((-217124 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF21_apply]
  rw [sum_getD_div w1zTF2_len imgz21_len pzITF_21_2 256 255]
  norm_num

theorem hpreITF21_eval_3 : denseE W1TF imgF21 3 = hpreITF21 3 := by
  rw [show hpreITF21 3 = ((69789 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF21_apply]
  rw [sum_getD_div w1zTF3_len imgz21_len pzITF_21_3 256 255]
  norm_num

theorem hpreITF21_eval_4 : denseE W1TF imgF21 4 = hpreITF21 4 := by
  rw [show hpreITF21 4 = ((-307669 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF21_apply]
  rw [sum_getD_div w1zTF4_len imgz21_len pzITF_21_4 256 255]
  norm_num

theorem hpreITF21_eval_5 : denseE W1TF imgF21 5 = hpreITF21 5 := by
  rw [show hpreITF21 5 = ((-47833 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF21_apply]
  rw [sum_getD_div w1zTF5_len imgz21_len pzITF_21_5 256 255]
  norm_num

theorem hpreITF21_eval_6 : denseE W1TF imgF21 6 = hpreITF21 6 := by
  rw [show hpreITF21 6 = ((167170 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF21_apply]
  rw [sum_getD_div w1zTF6_len imgz21_len pzITF_21_6 256 255]
  norm_num

theorem hpreITF21_eval_7 : denseE W1TF imgF21 7 = hpreITF21 7 := by
  rw [show hpreITF21 7 = ((-86419 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF21_apply]
  rw [sum_getD_div w1zTF7_len imgz21_len pzITF_21_7 256 255]
  norm_num

theorem hpreITF21_eval_8 : denseE W1TF imgF21 8 = hpreITF21 8 := by
  rw [show hpreITF21 8 = ((265064 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF21_apply]
  rw [sum_getD_div w1zTF8_len imgz21_len pzITF_21_8 256 255]
  norm_num

theorem hpreITF21_eval_9 : denseE W1TF imgF21 9 = hpreITF21 9 := by
  rw [show hpreITF21 9 = ((35174 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF21_apply]
  rw [sum_getD_div w1zTF9_len imgz21_len pzITF_21_9 256 255]
  norm_num

theorem hpreITF21_eval_10 : denseE W1TF imgF21 10 = hpreITF21 10 := by
  rw [show hpreITF21 10 = ((70787 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF21_apply]
  rw [sum_getD_div w1zTF10_len imgz21_len pzITF_21_10 256 255]
  norm_num

theorem hpreITF21_eval_11 : denseE W1TF imgF21 11 = hpreITF21 11 := by
  rw [show hpreITF21 11 = ((451751 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF21_apply]
  rw [sum_getD_div w1zTF11_len imgz21_len pzITF_21_11 256 255]
  norm_num

theorem hpreITF21_eval_12 : denseE W1TF imgF21 12 = hpreITF21 12 := by
  rw [show hpreITF21 12 = ((-296497 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF21_apply]
  rw [sum_getD_div w1zTF12_len imgz21_len pzITF_21_12 256 255]
  norm_num

theorem hpreITF21_eval_13 : denseE W1TF imgF21 13 = hpreITF21 13 := by
  rw [show hpreITF21 13 = ((-63723 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF21_apply]
  rw [sum_getD_div w1zTF13_len imgz21_len pzITF_21_13 256 255]
  norm_num

theorem hpreITF21_eval_14 : denseE W1TF imgF21 14 = hpreITF21 14 := by
  rw [show hpreITF21 14 = ((105714 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF21_apply]
  rw [sum_getD_div w1zTF14_len imgz21_len pzITF_21_14 256 255]
  norm_num

theorem hpreITF21_eval_15 : denseE W1TF imgF21 15 = hpreITF21 15 := by
  rw [show hpreITF21 15 = ((173863 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF21_apply]
  rw [sum_getD_div w1zTF15_len imgz21_len pzITF_21_15 256 255]
  norm_num

theorem hpreITF21_eval : ∀ k : Fin 16, denseE W1TF imgF21 k = hpreITF21 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF21_eval_0; exact hpreITF21_eval_1; exact hpreITF21_eval_2; exact hpreITF21_eval_3; exact hpreITF21_eval_4; exact hpreITF21_eval_5; exact hpreITF21_eval_6; exact hpreITF21_eval_7; exact hpreITF21_eval_8; exact hpreITF21_eval_9; exact hpreITF21_eval_10; exact hpreITF21_eval_11; exact hpreITF21_eval_12; exact hpreITF21_eval_13; exact hpreITF21_eval_14; exact hpreITF21_eval_15 ]

theorem hpreITF21_sum : ∀ t, (∑ j, W1TF t j * imgF21 j) = hpreITF21 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF21_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_21 : ∀ j : Fin 10, j ≠ 6 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF21 q - ((2 : ℝ)/255)) (fun q => imgF21 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF21 q - ((2 : ℝ)/255)) (fun q => imgF21 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF21 q - ((2 : ℝ)/255)) (fun q => imgF21 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF21 q - ((2 : ℝ)/255)) (fun q => imgF21 q + ((2 : ℝ)/255)))) 6 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF21_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF21, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #21 (digit 6): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_21 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 6 → mlpTF (imgF21 + δ) j < mlpTF (imgF21 + δ) 6 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_21 δ hδ

/-- MNIST test image #23 (digit 5), exact pixels k/255. -/
def imgz23 : List ℤ := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 69, 152, 237, 254, 254, 255, 254, 252, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 164, 237, 253, 254, 218, 138, 83, 39, 154, 254, 135, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 138, 246, 253, 254, 216, 167, 54, 5, 0, 0, 0, 100, 191, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 233, 254, 169, 53, 6, 0, 0, 0, 0, 0, 0, 35, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 174, 254, 94, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 245, 221, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 254, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151, 254, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 226, 242, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 240, 203, 44, 44, 44, 44, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70, 254, 254, 254, 254, 254, 254, 205, 85, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 184, 169, 133, 133, 162, 212, 254, 254, 166, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 51, 177, 254, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 209, 254, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 209, 254, 194, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 10, 137, 244, 254, 198, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 87, 122, 147, 223, 254, 247, 127, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 118, 250, 210, 248, 254, 252, 199, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 138, 254, 254, 254, 250, 201, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 79, 167, 197, 87, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

theorem imgz23_len : (imgz23).length = 784 := by decide +kernel

noncomputable def imgv23 : Fin 784 → ℝ := fun j => ((imgz23).getD j 0 : ℝ)/255

noncomputable def imgF23 : EuclideanSpace ℝ (Fin 784) := WithLp.toLp 2 imgv23

theorem imgF23_apply : ∀ j, imgF23 j = ((imgz23).getD j 0 : ℝ)/255 := fun _ => rfl

-- net TF pre-activations for #23 (not in the base L2-certified set)
theorem pzITF_23_0 : dotZ w1zTF0 imgz23 = 117335 := by decide +kernel
theorem pzITF_23_1 : dotZ w1zTF1 imgz23 = -130545 := by decide +kernel
theorem pzITF_23_2 : dotZ w1zTF2 imgz23 = 97073 := by decide +kernel
theorem pzITF_23_3 : dotZ w1zTF3 imgz23 = 153164 := by decide +kernel
theorem pzITF_23_4 : dotZ w1zTF4 imgz23 = -212979 := by decide +kernel
theorem pzITF_23_5 : dotZ w1zTF5 imgz23 = -57834 := by decide +kernel
theorem pzITF_23_6 : dotZ w1zTF6 imgz23 = 363713 := by decide +kernel
theorem pzITF_23_7 : dotZ w1zTF7 imgz23 = -198186 := by decide +kernel
theorem pzITF_23_8 : dotZ w1zTF8 imgz23 = 219760 := by decide +kernel
theorem pzITF_23_9 : dotZ w1zTF9 imgz23 = 109401 := by decide +kernel
theorem pzITF_23_10 : dotZ w1zTF10 imgz23 = 140692 := by decide +kernel
theorem pzITF_23_11 : dotZ w1zTF11 imgz23 = 157006 := by decide +kernel
theorem pzITF_23_12 : dotZ w1zTF12 imgz23 = -226290 := by decide +kernel
theorem pzITF_23_13 : dotZ w1zTF13 imgz23 = 80500 := by decide +kernel
theorem pzITF_23_14 : dotZ w1zTF14 imgz23 = -20269 := by decide +kernel
theorem pzITF_23_15 : dotZ w1zTF15 imgz23 = 441720 := by decide +kernel

noncomputable def hpreITF23 : Fin 16 → ℝ :=
  ![((117335 : ℝ)/65280), ((-130545 : ℝ)/65280), ((97073 : ℝ)/65280), ((153164 : ℝ)/65280), ((-212979 : ℝ)/65280), ((-57834 : ℝ)/65280), ((363713 : ℝ)/65280), ((-198186 : ℝ)/65280), ((219760 : ℝ)/65280), ((109401 : ℝ)/65280), ((140692 : ℝ)/65280), ((157006 : ℝ)/65280), ((-226290 : ℝ)/65280), ((80500 : ℝ)/65280), ((-20269 : ℝ)/65280), ((441720 : ℝ)/65280)]

theorem hpreITF23_eval_0 : denseE W1TF imgF23 0 = hpreITF23 0 := by
  rw [show hpreITF23 0 = ((117335 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr0]
  simp only [w1rTF0, imgF23_apply]
  rw [sum_getD_div w1zTF0_len imgz23_len pzITF_23_0 256 255]
  norm_num

theorem hpreITF23_eval_1 : denseE W1TF imgF23 1 = hpreITF23 1 := by
  rw [show hpreITF23 1 = ((-130545 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr1]
  simp only [w1rTF1, imgF23_apply]
  rw [sum_getD_div w1zTF1_len imgz23_len pzITF_23_1 256 255]
  norm_num

theorem hpreITF23_eval_2 : denseE W1TF imgF23 2 = hpreITF23 2 := by
  rw [show hpreITF23 2 = ((97073 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr2]
  simp only [w1rTF2, imgF23_apply]
  rw [sum_getD_div w1zTF2_len imgz23_len pzITF_23_2 256 255]
  norm_num

theorem hpreITF23_eval_3 : denseE W1TF imgF23 3 = hpreITF23 3 := by
  rw [show hpreITF23 3 = ((153164 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr3]
  simp only [w1rTF3, imgF23_apply]
  rw [sum_getD_div w1zTF3_len imgz23_len pzITF_23_3 256 255]
  norm_num

theorem hpreITF23_eval_4 : denseE W1TF imgF23 4 = hpreITF23 4 := by
  rw [show hpreITF23 4 = ((-212979 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr4]
  simp only [w1rTF4, imgF23_apply]
  rw [sum_getD_div w1zTF4_len imgz23_len pzITF_23_4 256 255]
  norm_num

theorem hpreITF23_eval_5 : denseE W1TF imgF23 5 = hpreITF23 5 := by
  rw [show hpreITF23 5 = ((-57834 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr5]
  simp only [w1rTF5, imgF23_apply]
  rw [sum_getD_div w1zTF5_len imgz23_len pzITF_23_5 256 255]
  norm_num

theorem hpreITF23_eval_6 : denseE W1TF imgF23 6 = hpreITF23 6 := by
  rw [show hpreITF23 6 = ((363713 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr6]
  simp only [w1rTF6, imgF23_apply]
  rw [sum_getD_div w1zTF6_len imgz23_len pzITF_23_6 256 255]
  norm_num

theorem hpreITF23_eval_7 : denseE W1TF imgF23 7 = hpreITF23 7 := by
  rw [show hpreITF23 7 = ((-198186 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr7]
  simp only [w1rTF7, imgF23_apply]
  rw [sum_getD_div w1zTF7_len imgz23_len pzITF_23_7 256 255]
  norm_num

theorem hpreITF23_eval_8 : denseE W1TF imgF23 8 = hpreITF23 8 := by
  rw [show hpreITF23 8 = ((219760 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr8]
  simp only [w1rTF8, imgF23_apply]
  rw [sum_getD_div w1zTF8_len imgz23_len pzITF_23_8 256 255]
  norm_num

theorem hpreITF23_eval_9 : denseE W1TF imgF23 9 = hpreITF23 9 := by
  rw [show hpreITF23 9 = ((109401 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr9]
  simp only [w1rTF9, imgF23_apply]
  rw [sum_getD_div w1zTF9_len imgz23_len pzITF_23_9 256 255]
  norm_num

theorem hpreITF23_eval_10 : denseE W1TF imgF23 10 = hpreITF23 10 := by
  rw [show hpreITF23 10 = ((140692 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr10]
  simp only [w1rTF10, imgF23_apply]
  rw [sum_getD_div w1zTF10_len imgz23_len pzITF_23_10 256 255]
  norm_num

theorem hpreITF23_eval_11 : denseE W1TF imgF23 11 = hpreITF23 11 := by
  rw [show hpreITF23 11 = ((157006 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr11]
  simp only [w1rTF11, imgF23_apply]
  rw [sum_getD_div w1zTF11_len imgz23_len pzITF_23_11 256 255]
  norm_num

theorem hpreITF23_eval_12 : denseE W1TF imgF23 12 = hpreITF23 12 := by
  rw [show hpreITF23 12 = ((-226290 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr12]
  simp only [w1rTF12, imgF23_apply]
  rw [sum_getD_div w1zTF12_len imgz23_len pzITF_23_12 256 255]
  norm_num

theorem hpreITF23_eval_13 : denseE W1TF imgF23 13 = hpreITF23 13 := by
  rw [show hpreITF23 13 = ((80500 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr13]
  simp only [w1rTF13, imgF23_apply]
  rw [sum_getD_div w1zTF13_len imgz23_len pzITF_23_13 256 255]
  norm_num

theorem hpreITF23_eval_14 : denseE W1TF imgF23 14 = hpreITF23 14 := by
  rw [show hpreITF23 14 = ((-20269 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr14]
  simp only [w1rTF14, imgF23_apply]
  rw [sum_getD_div w1zTF14_len imgz23_len pzITF_23_14 256 255]
  norm_num

theorem hpreITF23_eval_15 : denseE W1TF imgF23 15 = hpreITF23 15 := by
  rw [show hpreITF23 15 = ((441720 : ℝ)/65280) from rfl,
      denseE_apply, W1TFr15]
  simp only [w1rTF15, imgF23_apply]
  rw [sum_getD_div w1zTF15_len imgz23_len pzITF_23_15 256 255]
  norm_num

theorem hpreITF23_eval : ∀ k : Fin 16, denseE W1TF imgF23 k = hpreITF23 k := by
  intro k
  fin_cases k <;>
    [ exact hpreITF23_eval_0; exact hpreITF23_eval_1; exact hpreITF23_eval_2; exact hpreITF23_eval_3; exact hpreITF23_eval_4; exact hpreITF23_eval_5; exact hpreITF23_eval_6; exact hpreITF23_eval_7; exact hpreITF23_eval_8; exact hpreITF23_eval_9; exact hpreITF23_eval_10; exact hpreITF23_eval_11; exact hpreITF23_eval_12; exact hpreITF23_eval_13; exact hpreITF23_eval_14; exact hpreITF23_eval_15 ]

theorem hpreITF23_sum : ∀ t, (∑ j, W1TF t j * imgF23 j) = hpreITF23 t := by
  intro t
  rw [← denseE_apply]
  exact hpreITF23_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe2_23 : ∀ j : Fin 10, j ≠ 5 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF23 q - ((2 : ℝ)/255)) (fun q => imgF23 q + ((2 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF23 q - ((2 : ℝ)/255)) (fun q => imgF23 q + ((2 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF23 q - ((2 : ℝ)/255)) (fun q => imgF23 q + ((2 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF23 q - ((2 : ℝ)/255)) (fun q => imgF23 q + ((2 : ℝ)/255)))) 5 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreITF23_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreITF23, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #23 (digit 5): IBP-certified at pixel-L∞ ε = 2/255. -/
theorem certIBPTFe2_23 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((2 : ℝ)/255)) :
    ∀ j, j ≠ 5 → mlpTF (imgF23 + δ) j < mlpTF (imgF23 + δ) 5 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe2_23 δ hδ

theorem hpreTF25_sum : ∀ t, (∑ j, W1TF t j * imgF25 j) = hpreTF25 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF25_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe4_25 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF25 q - ((4 : ℝ)/255)) (fun q => imgF25 q + ((4 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF25 q - ((4 : ℝ)/255)) (fun q => imgF25 q + ((4 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF25 q - ((4 : ℝ)/255)) (fun q => imgF25 q + ((4 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF25 q - ((4 : ℝ)/255)) (fun q => imgF25 q + ((4 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF25_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF25, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #25 (digit 0): IBP-certified at pixel-L∞ ε = 4/255. -/
theorem certIBPTFe4_25 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((4 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF25 + δ) j < mlpTF (imgF25 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe4_25 δ hδ

theorem hpreTF71_sum : ∀ t, (∑ j, W1TF t j * imgF71 j) = hpreTF71 t := by
  intro t
  rw [← denseE_apply]
  exact hpreTF71_eval t

set_option maxHeartbeats 6400000 in
theorem hbTFe4_71 : ∀ j : Fin 10, j ≠ 0 →
    denseHi W2TF (reluLo (denseLo W1TF (fun q => imgF71 q - ((4 : ℝ)/255)) (fun q => imgF71 q + ((4 : ℝ)/255))))
                (reluHi (denseHi W1TF (fun q => imgF71 q - ((4 : ℝ)/255)) (fun q => imgF71 q + ((4 : ℝ)/255)))) j
      < denseLo W2TF (reluLo (denseLo W1TF (fun q => imgF71 q - ((4 : ℝ)/255)) (fun q => imgF71 q + ((4 : ℝ)/255))))
                    (reluHi (denseHi W1TF (fun q => imgF71 q - ((4 : ℝ)/255)) (fun q => imgF71 q + ((4 : ℝ)/255)))) 0 := by
  intro j hj
  rw [denseLo2_eval, denseHi2_eval]
  simp only [hpreTF71_sum, absrowTF]
  fin_cases j <;>
    first
    | exact absurd rfl hj
    | · simp [W2TF, hpreTF71, absrTF, Fin.sum_univ_succ, max_def]
        try norm_num

/-- Test #71 (digit 0): IBP-certified at pixel-L∞ ε = 4/255. -/
theorem certIBPTFe4_71 (δ : EuclideanSpace ℝ (Fin 784))
    (hδ : ∀ q, |δ q| ≤ ((4 : ℝ)/255)) :
    ∀ j, j ≠ 0 → mlpTF (imgF71 + δ) j < mlpTF (imgF71 + δ) 0 :=
  ibp2_certified_at_eps W1TF W2TF hbTFe4_71 δ hδ

-- ════════ aggregates (peers of `scorecardFull`) ════════

noncomputable def ibpUnconCertse1 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (1, imgF1, 2),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9)]

theorem ibpUnconCertse1_certified :
    ∀ p ∈ ibpUnconCertse1, CertifiedAtLinf mlpTF ((1 : ℝ)/255) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certIBPTFe1_0, certIBPTFe1_1, certIBPTFe1_2, certIBPTFe1_3, certIBPTFe1_4, certIBPTFe1_5, certIBPTFe1_6, certIBPTFe1_7⟩

noncomputable def ibpUnconCertse2 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(3, imgF3, 0),
   (4, imgF4, 4),
   (10, imgF10, 0),
   (11, imgF11, 6),
   (13, imgF13, 0),
   (19, imgF19, 4),
   (21, imgF21, 6),
   (23, imgF23, 5)]

theorem ibpUnconCertse2_certified :
    ∀ p ∈ ibpUnconCertse2, CertifiedAtLinf mlpTF ((2 : ℝ)/255) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certIBPTFe2_3, certIBPTFe2_4, certIBPTFe2_10, certIBPTFe2_11, certIBPTFe2_13, certIBPTFe2_19, certIBPTFe2_21, certIBPTFe2_23⟩

noncomputable def ibpUnconCertse4 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(25, imgF25, 0),
   (71, imgF71, 0)]

theorem ibpUnconCertse4_certified :
    ∀ p ∈ ibpUnconCertse4, CertifiedAtLinf mlpTF ((4 : ℝ)/255) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certIBPTFe4_25, certIBPTFe4_71⟩

/-- **The IBP L∞ scorecard, unconstrained net (`mlpTF`)** — MEASURED 87/100 @ 1/255, 42/100 @ 2/255, 2/100 @ 4/255, 0/100 @ 8/255 (PGD-L∞ bracket 95/92/85/36). -/
theorem scorecard_ibp_uncon :
    (ibpUnconCertse1.length = 8 ∧ ∀ p ∈ ibpUnconCertse1, CertifiedAtLinf mlpTF ((1 : ℝ)/255) p.2.1 p.2.2) ∧
    (ibpUnconCertse2.length = 8 ∧ ∀ p ∈ ibpUnconCertse2, CertifiedAtLinf mlpTF ((2 : ℝ)/255) p.2.1 p.2.2) ∧
    (ibpUnconCertse4.length = 2 ∧ ∀ p ∈ ibpUnconCertse4, CertifiedAtLinf mlpTF ((4 : ℝ)/255) p.2.1 p.2.2) :=
  ⟨⟨rfl, ibpUnconCertse1_certified⟩, ⟨rfl, ibpUnconCertse2_certified⟩, ⟨rfl, ibpUnconCertse4_certified⟩⟩

end LipschitzCertDemo
end Proofs
