import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsA
import LeanMlir.Proofs.Certificates.LipschitzCertScorecardFullImgsB

/-! # Full-input certified-accuracy scorecard (4/4): the certificates

The pooled 49-dim scorecard, lifted to FULL 784-dim input (the 2026-07 audit's
gap #3): first 100 MNIST test images, per-image `∀ δ, ‖δ‖ < ε → argmax fixed`
theorems at pixel-L2 ε = 1/10 and 3/10, two 784→16→10 nets:

* **spectrally capped** (σ ≤ 2 projected SGD, q-acc 0.924, Schatten-8
  L = 4.95): **92/100 certified at ε = 0.1** (L2-PGD leaves 93/100
  robust — the certificate is within 1 image(s) of the attack bound), and
  **72/100 at ε = 0.3** (PGD: 92/100);
* **unconstrained** (q-acc 0.951, L = 29.85): 76/100 at ε = 0.1
  (PGD: 94/100), collapsing to **2/100 at ε = 0.3** (PGD: 86/100) —
  at the larger radius the σ-projection is what keeps the certificate alive.

ε here is FULL-pixel-space L2 (pixels in [0,1]), not the pooled-feature L2 of
`LipschitzCertScorecard.lean` — a strictly stronger, directly comparable-to-
the-literature perturbation model. Width 16 (vs the canonical 512) is the
honest cost: 512-wide Gram certificates are ~10⁵× this kernel work.
Aggregates are lower bounds only — an upper-bound L cannot prove an image
UNcertifiable. Generated by `scripts/lipschitz_cert_scorecard_full.py`. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 3200000

namespace Proofs
namespace LipschitzCertDemo

open scoped BigOperators

/-- Test #0 (digit 7), net SF: certified at ε = 1/10 — margin 5.632 ≥ √2·L·ε. -/
theorem certSF10_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF0 + δ) j < mlpSF (imgF0 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #1 (digit 2), net SF: certified at ε = 1/10 — margin 2.817 ≥ √2·L·ε. -/
theorem certSF10_1 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF1 + δ) j < mlpSF (imgF1 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF1 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net SF: certified at ε = 1/10 — margin 3.815 ≥ √2·L·ε. -/
theorem certSF10_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF2 + δ) j < mlpSF (imgF2 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net SF: certified at ε = 1/10 — margin 5.384 ≥ √2·L·ε. -/
theorem certSF10_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF3 + δ) j < mlpSF (imgF3 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net SF: certified at ε = 1/10 — margin 2.377 ≥ √2·L·ε. -/
theorem certSF10_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF4 + δ) j < mlpSF (imgF4 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net SF: certified at ε = 1/10 — margin 4.312 ≥ √2·L·ε. -/
theorem certSF10_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF5 + δ) j < mlpSF (imgF5 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net SF: certified at ε = 1/10 — margin 2.587 ≥ √2·L·ε. -/
theorem certSF10_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF6 + δ) j < mlpSF (imgF6 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net SF: certified at ε = 1/10 — margin 2.537 ≥ √2·L·ε. -/
theorem certSF10_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF7 + δ) j < mlpSF (imgF7 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF7 (by norm_num)
    (by norm_num) δ hδ

/-- Test #9 (digit 9), net SF: certified at ε = 1/10 — margin 2.364 ≥ √2·L·ε. -/
theorem certSF10_9 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF9 + δ) j < mlpSF (imgF9 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF9 (by norm_num)
    (by norm_num) δ hδ

/-- Test #10 (digit 0), net SF: certified at ε = 1/10 — margin 2.008 ≥ √2·L·ε. -/
theorem certSF10_10 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF10 + δ) j < mlpSF (imgF10 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF10 (by norm_num)
    (by norm_num) δ hδ

/-- Test #11 (digit 6), net SF: certified at ε = 1/10 — margin 2.129 ≥ √2·L·ε. -/
theorem certSF10_11 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF11 + δ) j < mlpSF (imgF11 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF11 (by norm_num)
    (by norm_num) δ hδ

/-- Test #12 (digit 9), net SF: certified at ε = 1/10 — margin 3.046 ≥ √2·L·ε. -/
theorem certSF10_12 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF12 + δ) j < mlpSF (imgF12 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF12 (by norm_num)
    (by norm_num) δ hδ

/-- Test #13 (digit 0), net SF: certified at ε = 1/10 — margin 3.847 ≥ √2·L·ε. -/
theorem certSF10_13 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF13 + δ) j < mlpSF (imgF13 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF13 (by norm_num)
    (by norm_num) δ hδ

/-- Test #14 (digit 1), net SF: certified at ε = 1/10 — margin 4.654 ≥ √2·L·ε. -/
theorem certSF10_14 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF14 + δ) j < mlpSF (imgF14 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF14 (by norm_num)
    (by norm_num) δ hδ

/-- Test #15 (digit 5), net SF: certified at ε = 1/10 — margin 2.358 ≥ √2·L·ε. -/
theorem certSF10_15 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF15 + δ) j < mlpSF (imgF15 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF15 (by norm_num)
    (by norm_num) δ hδ

/-- Test #16 (digit 9), net SF: certified at ε = 1/10 — margin 2.470 ≥ √2·L·ε. -/
theorem certSF10_16 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF16 + δ) j < mlpSF (imgF16 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF16 (by norm_num)
    (by norm_num) δ hδ

/-- Test #17 (digit 7), net SF: certified at ε = 1/10 — margin 5.558 ≥ √2·L·ε. -/
theorem certSF10_17 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF17 + δ) j < mlpSF (imgF17 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF17 (by norm_num)
    (by norm_num) δ hδ

/-- Test #18 (digit 3), net SF: certified at ε = 1/10 — margin 1.541 ≥ √2·L·ε. -/
theorem certSF10_18 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF18 + δ) j < mlpSF (imgF18 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF18 (by norm_num)
    (by norm_num) δ hδ

/-- Test #19 (digit 4), net SF: certified at ε = 1/10 — margin 3.146 ≥ √2·L·ε. -/
theorem certSF10_19 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF19 + δ) j < mlpSF (imgF19 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF19 (by norm_num)
    (by norm_num) δ hδ

/-- Test #20 (digit 9), net SF: certified at ε = 1/10 — margin 1.783 ≥ √2·L·ε. -/
theorem certSF10_20 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF20 + δ) j < mlpSF (imgF20 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF20 (by norm_num)
    (by norm_num) δ hδ

/-- Test #21 (digit 6), net SF: certified at ε = 1/10 — margin 3.987 ≥ √2·L·ε. -/
theorem certSF10_21 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF21 + δ) j < mlpSF (imgF21 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF21 (by norm_num)
    (by norm_num) δ hδ

/-- Test #22 (digit 6), net SF: certified at ε = 1/10 — margin 2.120 ≥ √2·L·ε. -/
theorem certSF10_22 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF22 + δ) j < mlpSF (imgF22 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF22 (by norm_num)
    (by norm_num) δ hδ

/-- Test #23 (digit 5), net SF: certified at ε = 1/10 — margin 3.708 ≥ √2·L·ε. -/
theorem certSF10_23 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF23 + δ) j < mlpSF (imgF23 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF23 (by norm_num)
    (by norm_num) δ hδ

/-- Test #24 (digit 4), net SF: certified at ε = 1/10 — margin 1.905 ≥ √2·L·ε. -/
theorem certSF10_24 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF24 + δ) j < mlpSF (imgF24 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF24 (by norm_num)
    (by norm_num) δ hδ

/-- Test #25 (digit 0), net SF: certified at ε = 1/10 — margin 5.667 ≥ √2·L·ε. -/
theorem certSF10_25 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF25 + δ) j < mlpSF (imgF25 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF25 (by norm_num)
    (by norm_num) δ hδ

/-- Test #26 (digit 7), net SF: certified at ε = 1/10 — margin 2.789 ≥ √2·L·ε. -/
theorem certSF10_26 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF26 + δ) j < mlpSF (imgF26 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF26 (by norm_num)
    (by norm_num) δ hδ

/-- Test #27 (digit 4), net SF: certified at ε = 1/10 — margin 3.264 ≥ √2·L·ε. -/
theorem certSF10_27 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF27 + δ) j < mlpSF (imgF27 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF27 (by norm_num)
    (by norm_num) δ hδ

/-- Test #28 (digit 0), net SF: certified at ε = 1/10 — margin 5.172 ≥ √2·L·ε. -/
theorem certSF10_28 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF28 + δ) j < mlpSF (imgF28 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF28 (by norm_num)
    (by norm_num) δ hδ

/-- Test #29 (digit 1), net SF: certified at ε = 1/10 — margin 3.351 ≥ √2·L·ε. -/
theorem certSF10_29 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF29 + δ) j < mlpSF (imgF29 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF29 (by norm_num)
    (by norm_num) δ hδ

/-- Test #30 (digit 3), net SF: certified at ε = 1/10 — margin 3.318 ≥ √2·L·ε. -/
theorem certSF10_30 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF30 + δ) j < mlpSF (imgF30 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF30 (by norm_num)
    (by norm_num) δ hδ

/-- Test #31 (digit 1), net SF: certified at ε = 1/10 — margin 2.926 ≥ √2·L·ε. -/
theorem certSF10_31 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF31 + δ) j < mlpSF (imgF31 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF31 (by norm_num)
    (by norm_num) δ hδ

/-- Test #32 (digit 3), net SF: certified at ε = 1/10 — margin 1.587 ≥ √2·L·ε. -/
theorem certSF10_32 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF32 + δ) j < mlpSF (imgF32 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF32 (by norm_num)
    (by norm_num) δ hδ

/-- Test #34 (digit 7), net SF: certified at ε = 1/10 — margin 3.709 ≥ √2·L·ε. -/
theorem certSF10_34 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF34 + δ) j < mlpSF (imgF34 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF34 (by norm_num)
    (by norm_num) δ hδ

/-- Test #35 (digit 2), net SF: certified at ε = 1/10 — margin 4.582 ≥ √2·L·ε. -/
theorem certSF10_35 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF35 + δ) j < mlpSF (imgF35 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF35 (by norm_num)
    (by norm_num) δ hδ

/-- Test #36 (digit 7), net SF: certified at ε = 1/10 — margin 4.271 ≥ √2·L·ε. -/
theorem certSF10_36 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF36 + δ) j < mlpSF (imgF36 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF36 (by norm_num)
    (by norm_num) δ hδ

/-- Test #37 (digit 1), net SF: certified at ε = 1/10 — margin 4.319 ≥ √2·L·ε. -/
theorem certSF10_37 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF37 + δ) j < mlpSF (imgF37 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF37 (by norm_num)
    (by norm_num) δ hδ

/-- Test #38 (digit 2), net SF: certified at ε = 1/10 — margin 1.171 ≥ √2·L·ε. -/
theorem certSF10_38 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF38 + δ) j < mlpSF (imgF38 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF38 (by norm_num)
    (by norm_num) δ hδ

/-- Test #39 (digit 1), net SF: certified at ε = 1/10 — margin 3.382 ≥ √2·L·ε. -/
theorem certSF10_39 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF39 + δ) j < mlpSF (imgF39 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF39 (by norm_num)
    (by norm_num) δ hδ

/-- Test #40 (digit 1), net SF: certified at ε = 1/10 — margin 3.266 ≥ √2·L·ε. -/
theorem certSF10_40 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF40 + δ) j < mlpSF (imgF40 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF40 (by norm_num)
    (by norm_num) δ hδ

/-- Test #41 (digit 7), net SF: certified at ε = 1/10 — margin 2.708 ≥ √2·L·ε. -/
theorem certSF10_41 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF41 + δ) j < mlpSF (imgF41 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF41 (by norm_num)
    (by norm_num) δ hδ

/-- Test #42 (digit 4), net SF: certified at ε = 1/10 — margin 1.566 ≥ √2·L·ε. -/
theorem certSF10_42 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF42 + δ) j < mlpSF (imgF42 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF42 (by norm_num)
    (by norm_num) δ hδ

/-- Test #43 (digit 2), net SF: certified at ε = 1/10 — margin 2.334 ≥ √2·L·ε. -/
theorem certSF10_43 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF43 + δ) j < mlpSF (imgF43 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF43 (by norm_num)
    (by norm_num) δ hδ

/-- Test #44 (digit 3), net SF: certified at ε = 1/10 — margin 1.498 ≥ √2·L·ε. -/
theorem certSF10_44 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF44 + δ) j < mlpSF (imgF44 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF44 (by norm_num)
    (by norm_num) δ hδ

/-- Test #45 (digit 5), net SF: certified at ε = 1/10 — margin 2.919 ≥ √2·L·ε. -/
theorem certSF10_45 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF45 + δ) j < mlpSF (imgF45 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF45 (by norm_num)
    (by norm_num) δ hδ

/-- Test #46 (digit 1), net SF: certified at ε = 1/10 — margin 1.018 ≥ √2·L·ε. -/
theorem certSF10_46 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF46 + δ) j < mlpSF (imgF46 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF46 (by norm_num)
    (by norm_num) δ hδ

/-- Test #47 (digit 2), net SF: certified at ε = 1/10 — margin 1.657 ≥ √2·L·ε. -/
theorem certSF10_47 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF47 + δ) j < mlpSF (imgF47 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF47 (by norm_num)
    (by norm_num) δ hδ

/-- Test #48 (digit 4), net SF: certified at ε = 1/10 — margin 2.845 ≥ √2·L·ε. -/
theorem certSF10_48 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF48 + δ) j < mlpSF (imgF48 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF48 (by norm_num)
    (by norm_num) δ hδ

/-- Test #49 (digit 4), net SF: certified at ε = 1/10 — margin 3.189 ≥ √2·L·ε. -/
theorem certSF10_49 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF49 + δ) j < mlpSF (imgF49 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF49 (by norm_num)
    (by norm_num) δ hδ

/-- Test #50 (digit 6), net SF: certified at ε = 1/10 — margin 4.396 ≥ √2·L·ε. -/
theorem certSF10_50 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF50 + δ) j < mlpSF (imgF50 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF50 (by norm_num)
    (by norm_num) δ hδ

/-- Test #51 (digit 3), net SF: certified at ε = 1/10 — margin 4.313 ≥ √2·L·ε. -/
theorem certSF10_51 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF51 + δ) j < mlpSF (imgF51 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF51 (by norm_num)
    (by norm_num) δ hδ

/-- Test #52 (digit 5), net SF: certified at ε = 1/10 — margin 3.044 ≥ √2·L·ε. -/
theorem certSF10_52 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF52 + δ) j < mlpSF (imgF52 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF52 (by norm_num)
    (by norm_num) δ hδ

/-- Test #53 (digit 5), net SF: certified at ε = 1/10 — margin 2.048 ≥ √2·L·ε. -/
theorem certSF10_53 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF53 + δ) j < mlpSF (imgF53 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF53 (by norm_num)
    (by norm_num) δ hδ

/-- Test #54 (digit 6), net SF: certified at ε = 1/10 — margin 2.308 ≥ √2·L·ε. -/
theorem certSF10_54 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF54 + δ) j < mlpSF (imgF54 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF54 (by norm_num)
    (by norm_num) δ hδ

/-- Test #55 (digit 0), net SF: certified at ε = 1/10 — margin 2.760 ≥ √2·L·ε. -/
theorem certSF10_55 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF55 + δ) j < mlpSF (imgF55 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF55 (by norm_num)
    (by norm_num) δ hδ

/-- Test #56 (digit 4), net SF: certified at ε = 1/10 — margin 5.646 ≥ √2·L·ε. -/
theorem certSF10_56 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF56 + δ) j < mlpSF (imgF56 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF56 (by norm_num)
    (by norm_num) δ hδ

/-- Test #57 (digit 1), net SF: certified at ε = 1/10 — margin 3.801 ≥ √2·L·ε. -/
theorem certSF10_57 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF57 + δ) j < mlpSF (imgF57 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF57 (by norm_num)
    (by norm_num) δ hδ

/-- Test #58 (digit 9), net SF: certified at ε = 1/10 — margin 2.607 ≥ √2·L·ε. -/
theorem certSF10_58 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF58 + δ) j < mlpSF (imgF58 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF58 (by norm_num)
    (by norm_num) δ hδ

/-- Test #59 (digit 5), net SF: certified at ε = 1/10 — margin 1.744 ≥ √2·L·ε. -/
theorem certSF10_59 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF59 + δ) j < mlpSF (imgF59 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF59 (by norm_num)
    (by norm_num) δ hδ

/-- Test #60 (digit 7), net SF: certified at ε = 1/10 — margin 5.167 ≥ √2·L·ε. -/
theorem certSF10_60 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF60 + δ) j < mlpSF (imgF60 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF60 (by norm_num)
    (by norm_num) δ hδ

/-- Test #61 (digit 8), net SF: certified at ε = 1/10 — margin 0.893 ≥ √2·L·ε. -/
theorem certSF10_61 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 8 → mlpSF (imgF61 + δ) j < mlpSF (imgF61 + δ) 8 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF61 (by norm_num)
    (by norm_num) δ hδ

/-- Test #62 (digit 9), net SF: certified at ε = 1/10 — margin 1.065 ≥ √2·L·ε. -/
theorem certSF10_62 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF62 + δ) j < mlpSF (imgF62 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF62 (by norm_num)
    (by norm_num) δ hδ

/-- Test #64 (digit 7), net SF: certified at ε = 1/10 — margin 3.563 ≥ √2·L·ε. -/
theorem certSF10_64 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF64 + δ) j < mlpSF (imgF64 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF64 (by norm_num)
    (by norm_num) δ hδ

/-- Test #65 (digit 4), net SF: certified at ε = 1/10 — margin 1.085 ≥ √2·L·ε. -/
theorem certSF10_65 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF65 + δ) j < mlpSF (imgF65 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF65 (by norm_num)
    (by norm_num) δ hδ

/-- Test #67 (digit 4), net SF: certified at ε = 1/10 — margin 3.978 ≥ √2·L·ε. -/
theorem certSF10_67 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF67 + δ) j < mlpSF (imgF67 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF67 (by norm_num)
    (by norm_num) δ hδ

/-- Test #68 (digit 3), net SF: certified at ε = 1/10 — margin 3.679 ≥ √2·L·ε. -/
theorem certSF10_68 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF68 + δ) j < mlpSF (imgF68 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF68 (by norm_num)
    (by norm_num) δ hδ

/-- Test #69 (digit 0), net SF: certified at ε = 1/10 — margin 3.391 ≥ √2·L·ε. -/
theorem certSF10_69 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF69 + δ) j < mlpSF (imgF69 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF69 (by norm_num)
    (by norm_num) δ hδ

/-- Test #70 (digit 7), net SF: certified at ε = 1/10 — margin 5.972 ≥ √2·L·ε. -/
theorem certSF10_70 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF70 + δ) j < mlpSF (imgF70 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF70 (by norm_num)
    (by norm_num) δ hδ

/-- Test #71 (digit 0), net SF: certified at ε = 1/10 — margin 5.013 ≥ √2·L·ε. -/
theorem certSF10_71 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF71 + δ) j < mlpSF (imgF71 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF71 (by norm_num)
    (by norm_num) δ hδ

/-- Test #72 (digit 2), net SF: certified at ε = 1/10 — margin 3.870 ≥ √2·L·ε. -/
theorem certSF10_72 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF72 + δ) j < mlpSF (imgF72 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF72 (by norm_num)
    (by norm_num) δ hδ

/-- Test #74 (digit 1), net SF: certified at ε = 1/10 — margin 3.649 ≥ √2·L·ε. -/
theorem certSF10_74 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF74 + δ) j < mlpSF (imgF74 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF74 (by norm_num)
    (by norm_num) δ hδ

/-- Test #75 (digit 7), net SF: certified at ε = 1/10 — margin 4.547 ≥ √2·L·ε. -/
theorem certSF10_75 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF75 + δ) j < mlpSF (imgF75 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF75 (by norm_num)
    (by norm_num) δ hδ

/-- Test #76 (digit 3), net SF: certified at ε = 1/10 — margin 1.722 ≥ √2·L·ε. -/
theorem certSF10_76 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF76 + δ) j < mlpSF (imgF76 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF76 (by norm_num)
    (by norm_num) δ hδ

/-- Test #78 (digit 9), net SF: certified at ε = 1/10 — margin 2.097 ≥ √2·L·ε. -/
theorem certSF10_78 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF78 + δ) j < mlpSF (imgF78 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF78 (by norm_num)
    (by norm_num) δ hδ

/-- Test #79 (digit 7), net SF: certified at ε = 1/10 — margin 6.032 ≥ √2·L·ε. -/
theorem certSF10_79 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF79 + δ) j < mlpSF (imgF79 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF79 (by norm_num)
    (by norm_num) δ hδ

/-- Test #80 (digit 7), net SF: certified at ε = 1/10 — margin 1.374 ≥ √2·L·ε. -/
theorem certSF10_80 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF80 + δ) j < mlpSF (imgF80 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF80 (by norm_num)
    (by norm_num) δ hδ

/-- Test #81 (digit 6), net SF: certified at ε = 1/10 — margin 3.414 ≥ √2·L·ε. -/
theorem certSF10_81 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF81 + δ) j < mlpSF (imgF81 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF81 (by norm_num)
    (by norm_num) δ hδ

/-- Test #82 (digit 2), net SF: certified at ε = 1/10 — margin 6.822 ≥ √2·L·ε. -/
theorem certSF10_82 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF82 + δ) j < mlpSF (imgF82 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF82 (by norm_num)
    (by norm_num) δ hδ

/-- Test #83 (digit 7), net SF: certified at ε = 1/10 — margin 2.930 ≥ √2·L·ε. -/
theorem certSF10_83 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF83 + δ) j < mlpSF (imgF83 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF83 (by norm_num)
    (by norm_num) δ hδ

/-- Test #84 (digit 8), net SF: certified at ε = 1/10 — margin 2.534 ≥ √2·L·ε. -/
theorem certSF10_84 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 8 → mlpSF (imgF84 + δ) j < mlpSF (imgF84 + δ) 8 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF84 (by norm_num)
    (by norm_num) δ hδ

/-- Test #85 (digit 4), net SF: certified at ε = 1/10 — margin 5.951 ≥ √2·L·ε. -/
theorem certSF10_85 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF85 + δ) j < mlpSF (imgF85 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF85 (by norm_num)
    (by norm_num) δ hδ

/-- Test #86 (digit 7), net SF: certified at ε = 1/10 — margin 6.791 ≥ √2·L·ε. -/
theorem certSF10_86 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF86 + δ) j < mlpSF (imgF86 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF86 (by norm_num)
    (by norm_num) δ hδ

/-- Test #88 (digit 6), net SF: certified at ε = 1/10 — margin 4.154 ≥ √2·L·ε. -/
theorem certSF10_88 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF88 + δ) j < mlpSF (imgF88 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF88 (by norm_num)
    (by norm_num) δ hδ

/-- Test #89 (digit 1), net SF: certified at ε = 1/10 — margin 5.184 ≥ √2·L·ε. -/
theorem certSF10_89 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF89 + δ) j < mlpSF (imgF89 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF89 (by norm_num)
    (by norm_num) δ hδ

/-- Test #90 (digit 3), net SF: certified at ε = 1/10 — margin 3.818 ≥ √2·L·ε. -/
theorem certSF10_90 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF90 + δ) j < mlpSF (imgF90 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF90 (by norm_num)
    (by norm_num) δ hδ

/-- Test #91 (digit 6), net SF: certified at ε = 1/10 — margin 5.482 ≥ √2·L·ε. -/
theorem certSF10_91 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF91 + δ) j < mlpSF (imgF91 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF91 (by norm_num)
    (by norm_num) δ hδ

/-- Test #93 (digit 3), net SF: certified at ε = 1/10 — margin 3.206 ≥ √2·L·ε. -/
theorem certSF10_93 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF93 + δ) j < mlpSF (imgF93 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF93 (by norm_num)
    (by norm_num) δ hδ

/-- Test #94 (digit 1), net SF: certified at ε = 1/10 — margin 2.949 ≥ √2·L·ε. -/
theorem certSF10_94 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF94 + δ) j < mlpSF (imgF94 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF94 (by norm_num)
    (by norm_num) δ hδ

/-- Test #95 (digit 4), net SF: certified at ε = 1/10 — margin 3.666 ≥ √2·L·ε. -/
theorem certSF10_95 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF95 + δ) j < mlpSF (imgF95 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF95 (by norm_num)
    (by norm_num) δ hδ

/-- Test #96 (digit 1), net SF: certified at ε = 1/10 — margin 1.750 ≥ √2·L·ε. -/
theorem certSF10_96 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF96 + δ) j < mlpSF (imgF96 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF96 (by norm_num)
    (by norm_num) δ hδ

/-- Test #97 (digit 7), net SF: certified at ε = 1/10 — margin 2.050 ≥ √2·L·ε. -/
theorem certSF10_97 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF97 + δ) j < mlpSF (imgF97 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF97 (by norm_num)
    (by norm_num) δ hδ

/-- Test #98 (digit 6), net SF: certified at ε = 1/10 — margin 3.820 ≥ √2·L·ε. -/
theorem certSF10_98 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF98 + δ) j < mlpSF (imgF98 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF98 (by norm_num)
    (by norm_num) δ hδ

/-- Test #99 (digit 9), net SF: certified at ε = 1/10 — margin 3.612 ≥ √2·L·ε. -/
theorem certSF10_99 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF99 + δ) j < mlpSF (imgF99 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF99 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net SF, ε = 1/10. -/
noncomputable def cappedFullCerts10 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (1, imgF1, 2),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9),
   (9, imgF9, 9),
   (10, imgF10, 0),
   (11, imgF11, 6),
   (12, imgF12, 9),
   (13, imgF13, 0),
   (14, imgF14, 1),
   (15, imgF15, 5),
   (16, imgF16, 9),
   (17, imgF17, 7),
   (18, imgF18, 3),
   (19, imgF19, 4),
   (20, imgF20, 9),
   (21, imgF21, 6),
   (22, imgF22, 6),
   (23, imgF23, 5),
   (24, imgF24, 4),
   (25, imgF25, 0),
   (26, imgF26, 7),
   (27, imgF27, 4),
   (28, imgF28, 0),
   (29, imgF29, 1),
   (30, imgF30, 3),
   (31, imgF31, 1),
   (32, imgF32, 3),
   (34, imgF34, 7),
   (35, imgF35, 2),
   (36, imgF36, 7),
   (37, imgF37, 1),
   (38, imgF38, 2),
   (39, imgF39, 1),
   (40, imgF40, 1),
   (41, imgF41, 7),
   (42, imgF42, 4),
   (43, imgF43, 2),
   (44, imgF44, 3),
   (45, imgF45, 5),
   (46, imgF46, 1),
   (47, imgF47, 2),
   (48, imgF48, 4),
   (49, imgF49, 4),
   (50, imgF50, 6),
   (51, imgF51, 3),
   (52, imgF52, 5),
   (53, imgF53, 5),
   (54, imgF54, 6),
   (55, imgF55, 0),
   (56, imgF56, 4),
   (57, imgF57, 1),
   (58, imgF58, 9),
   (59, imgF59, 5),
   (60, imgF60, 7),
   (61, imgF61, 8),
   (62, imgF62, 9),
   (64, imgF64, 7),
   (65, imgF65, 4),
   (67, imgF67, 4),
   (68, imgF68, 3),
   (69, imgF69, 0),
   (70, imgF70, 7),
   (71, imgF71, 0),
   (72, imgF72, 2),
   (74, imgF74, 1),
   (75, imgF75, 7),
   (76, imgF76, 3),
   (78, imgF78, 9),
   (79, imgF79, 7),
   (80, imgF80, 7),
   (81, imgF81, 6),
   (82, imgF82, 2),
   (83, imgF83, 7),
   (84, imgF84, 8),
   (85, imgF85, 4),
   (86, imgF86, 7),
   (88, imgF88, 6),
   (89, imgF89, 1),
   (90, imgF90, 3),
   (91, imgF91, 6),
   (93, imgF93, 3),
   (94, imgF94, 1),
   (95, imgF95, 4),
   (96, imgF96, 1),
   (97, imgF97, 7),
   (98, imgF98, 6),
   (99, imgF99, 9)]

theorem cappedFullCerts10_certified :
    ∀ p ∈ cappedFullCerts10, CertifiedAt mlpSF ((1 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certSF10_0, certSF10_1, certSF10_2, certSF10_3, certSF10_4, certSF10_5, certSF10_6, certSF10_7, certSF10_9, certSF10_10, certSF10_11, certSF10_12, certSF10_13, certSF10_14, certSF10_15, certSF10_16, certSF10_17, certSF10_18, certSF10_19, certSF10_20, certSF10_21, certSF10_22, certSF10_23, certSF10_24, certSF10_25, certSF10_26, certSF10_27, certSF10_28, certSF10_29, certSF10_30, certSF10_31, certSF10_32, certSF10_34, certSF10_35, certSF10_36, certSF10_37, certSF10_38, certSF10_39, certSF10_40, certSF10_41, certSF10_42, certSF10_43, certSF10_44, certSF10_45, certSF10_46, certSF10_47, certSF10_48, certSF10_49, certSF10_50, certSF10_51, certSF10_52, certSF10_53, certSF10_54, certSF10_55, certSF10_56, certSF10_57, certSF10_58, certSF10_59, certSF10_60, certSF10_61, certSF10_62, certSF10_64, certSF10_65, certSF10_67, certSF10_68, certSF10_69, certSF10_70, certSF10_71, certSF10_72, certSF10_74, certSF10_75, certSF10_76, certSF10_78, certSF10_79, certSF10_80, certSF10_81, certSF10_82, certSF10_83, certSF10_84, certSF10_85, certSF10_86, certSF10_88, certSF10_89, certSF10_90, certSF10_91, certSF10_93, certSF10_94, certSF10_95, certSF10_96, certSF10_97, certSF10_98, certSF10_99⟩

/-- Test #0 (digit 7), net SF: certified at ε = 3/10 — margin 5.632 ≥ √2·L·ε. -/
theorem certSF30_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF0 + δ) j < mlpSF (imgF0 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #1 (digit 2), net SF: certified at ε = 3/10 — margin 2.817 ≥ √2·L·ε. -/
theorem certSF30_1 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF1 + δ) j < mlpSF (imgF1 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF1 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net SF: certified at ε = 3/10 — margin 3.815 ≥ √2·L·ε. -/
theorem certSF30_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF2 + δ) j < mlpSF (imgF2 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net SF: certified at ε = 3/10 — margin 5.384 ≥ √2·L·ε. -/
theorem certSF30_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF3 + δ) j < mlpSF (imgF3 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net SF: certified at ε = 3/10 — margin 2.377 ≥ √2·L·ε. -/
theorem certSF30_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF4 + δ) j < mlpSF (imgF4 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net SF: certified at ε = 3/10 — margin 4.312 ≥ √2·L·ε. -/
theorem certSF30_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF5 + δ) j < mlpSF (imgF5 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net SF: certified at ε = 3/10 — margin 2.587 ≥ √2·L·ε. -/
theorem certSF30_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF6 + δ) j < mlpSF (imgF6 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net SF: certified at ε = 3/10 — margin 2.537 ≥ √2·L·ε. -/
theorem certSF30_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF7 + δ) j < mlpSF (imgF7 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF7 (by norm_num)
    (by norm_num) δ hδ

/-- Test #9 (digit 9), net SF: certified at ε = 3/10 — margin 2.364 ≥ √2·L·ε. -/
theorem certSF30_9 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF9 + δ) j < mlpSF (imgF9 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF9 (by norm_num)
    (by norm_num) δ hδ

/-- Test #11 (digit 6), net SF: certified at ε = 3/10 — margin 2.129 ≥ √2·L·ε. -/
theorem certSF30_11 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF11 + δ) j < mlpSF (imgF11 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF11 (by norm_num)
    (by norm_num) δ hδ

/-- Test #12 (digit 9), net SF: certified at ε = 3/10 — margin 3.046 ≥ √2·L·ε. -/
theorem certSF30_12 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF12 + δ) j < mlpSF (imgF12 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF12 (by norm_num)
    (by norm_num) δ hδ

/-- Test #13 (digit 0), net SF: certified at ε = 3/10 — margin 3.847 ≥ √2·L·ε. -/
theorem certSF30_13 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF13 + δ) j < mlpSF (imgF13 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF13 (by norm_num)
    (by norm_num) δ hδ

/-- Test #14 (digit 1), net SF: certified at ε = 3/10 — margin 4.654 ≥ √2·L·ε. -/
theorem certSF30_14 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF14 + δ) j < mlpSF (imgF14 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF14 (by norm_num)
    (by norm_num) δ hδ

/-- Test #15 (digit 5), net SF: certified at ε = 3/10 — margin 2.358 ≥ √2·L·ε. -/
theorem certSF30_15 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF15 + δ) j < mlpSF (imgF15 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF15 (by norm_num)
    (by norm_num) δ hδ

/-- Test #16 (digit 9), net SF: certified at ε = 3/10 — margin 2.470 ≥ √2·L·ε. -/
theorem certSF30_16 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF16 + δ) j < mlpSF (imgF16 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF16 (by norm_num)
    (by norm_num) δ hδ

/-- Test #17 (digit 7), net SF: certified at ε = 3/10 — margin 5.558 ≥ √2·L·ε. -/
theorem certSF30_17 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF17 + δ) j < mlpSF (imgF17 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF17 (by norm_num)
    (by norm_num) δ hδ

/-- Test #19 (digit 4), net SF: certified at ε = 3/10 — margin 3.146 ≥ √2·L·ε. -/
theorem certSF30_19 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF19 + δ) j < mlpSF (imgF19 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF19 (by norm_num)
    (by norm_num) δ hδ

/-- Test #21 (digit 6), net SF: certified at ε = 3/10 — margin 3.987 ≥ √2·L·ε. -/
theorem certSF30_21 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF21 + δ) j < mlpSF (imgF21 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF21 (by norm_num)
    (by norm_num) δ hδ

/-- Test #22 (digit 6), net SF: certified at ε = 3/10 — margin 2.120 ≥ √2·L·ε. -/
theorem certSF30_22 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF22 + δ) j < mlpSF (imgF22 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF22 (by norm_num)
    (by norm_num) δ hδ

/-- Test #23 (digit 5), net SF: certified at ε = 3/10 — margin 3.708 ≥ √2·L·ε. -/
theorem certSF30_23 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF23 + δ) j < mlpSF (imgF23 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF23 (by norm_num)
    (by norm_num) δ hδ

/-- Test #25 (digit 0), net SF: certified at ε = 3/10 — margin 5.667 ≥ √2·L·ε. -/
theorem certSF30_25 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF25 + δ) j < mlpSF (imgF25 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF25 (by norm_num)
    (by norm_num) δ hδ

/-- Test #26 (digit 7), net SF: certified at ε = 3/10 — margin 2.789 ≥ √2·L·ε. -/
theorem certSF30_26 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF26 + δ) j < mlpSF (imgF26 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF26 (by norm_num)
    (by norm_num) δ hδ

/-- Test #27 (digit 4), net SF: certified at ε = 3/10 — margin 3.264 ≥ √2·L·ε. -/
theorem certSF30_27 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF27 + δ) j < mlpSF (imgF27 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF27 (by norm_num)
    (by norm_num) δ hδ

/-- Test #28 (digit 0), net SF: certified at ε = 3/10 — margin 5.172 ≥ √2·L·ε. -/
theorem certSF30_28 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF28 + δ) j < mlpSF (imgF28 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF28 (by norm_num)
    (by norm_num) δ hδ

/-- Test #29 (digit 1), net SF: certified at ε = 3/10 — margin 3.351 ≥ √2·L·ε. -/
theorem certSF30_29 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF29 + δ) j < mlpSF (imgF29 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF29 (by norm_num)
    (by norm_num) δ hδ

/-- Test #30 (digit 3), net SF: certified at ε = 3/10 — margin 3.318 ≥ √2·L·ε. -/
theorem certSF30_30 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF30 + δ) j < mlpSF (imgF30 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF30 (by norm_num)
    (by norm_num) δ hδ

/-- Test #31 (digit 1), net SF: certified at ε = 3/10 — margin 2.926 ≥ √2·L·ε. -/
theorem certSF30_31 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF31 + δ) j < mlpSF (imgF31 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF31 (by norm_num)
    (by norm_num) δ hδ

/-- Test #34 (digit 7), net SF: certified at ε = 3/10 — margin 3.709 ≥ √2·L·ε. -/
theorem certSF30_34 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF34 + δ) j < mlpSF (imgF34 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF34 (by norm_num)
    (by norm_num) δ hδ

/-- Test #35 (digit 2), net SF: certified at ε = 3/10 — margin 4.582 ≥ √2·L·ε. -/
theorem certSF30_35 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF35 + δ) j < mlpSF (imgF35 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF35 (by norm_num)
    (by norm_num) δ hδ

/-- Test #36 (digit 7), net SF: certified at ε = 3/10 — margin 4.271 ≥ √2·L·ε. -/
theorem certSF30_36 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF36 + δ) j < mlpSF (imgF36 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF36 (by norm_num)
    (by norm_num) δ hδ

/-- Test #37 (digit 1), net SF: certified at ε = 3/10 — margin 4.319 ≥ √2·L·ε. -/
theorem certSF30_37 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF37 + δ) j < mlpSF (imgF37 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF37 (by norm_num)
    (by norm_num) δ hδ

/-- Test #39 (digit 1), net SF: certified at ε = 3/10 — margin 3.382 ≥ √2·L·ε. -/
theorem certSF30_39 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF39 + δ) j < mlpSF (imgF39 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF39 (by norm_num)
    (by norm_num) δ hδ

/-- Test #40 (digit 1), net SF: certified at ε = 3/10 — margin 3.266 ≥ √2·L·ε. -/
theorem certSF30_40 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF40 + δ) j < mlpSF (imgF40 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF40 (by norm_num)
    (by norm_num) δ hδ

/-- Test #41 (digit 7), net SF: certified at ε = 3/10 — margin 2.708 ≥ √2·L·ε. -/
theorem certSF30_41 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF41 + δ) j < mlpSF (imgF41 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF41 (by norm_num)
    (by norm_num) δ hδ

/-- Test #43 (digit 2), net SF: certified at ε = 3/10 — margin 2.334 ≥ √2·L·ε. -/
theorem certSF30_43 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF43 + δ) j < mlpSF (imgF43 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF43 (by norm_num)
    (by norm_num) δ hδ

/-- Test #45 (digit 5), net SF: certified at ε = 3/10 — margin 2.919 ≥ √2·L·ε. -/
theorem certSF30_45 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF45 + δ) j < mlpSF (imgF45 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF45 (by norm_num)
    (by norm_num) δ hδ

/-- Test #48 (digit 4), net SF: certified at ε = 3/10 — margin 2.845 ≥ √2·L·ε. -/
theorem certSF30_48 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF48 + δ) j < mlpSF (imgF48 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF48 (by norm_num)
    (by norm_num) δ hδ

/-- Test #49 (digit 4), net SF: certified at ε = 3/10 — margin 3.189 ≥ √2·L·ε. -/
theorem certSF30_49 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF49 + δ) j < mlpSF (imgF49 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF49 (by norm_num)
    (by norm_num) δ hδ

/-- Test #50 (digit 6), net SF: certified at ε = 3/10 — margin 4.396 ≥ √2·L·ε. -/
theorem certSF30_50 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF50 + δ) j < mlpSF (imgF50 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF50 (by norm_num)
    (by norm_num) δ hδ

/-- Test #51 (digit 3), net SF: certified at ε = 3/10 — margin 4.313 ≥ √2·L·ε. -/
theorem certSF30_51 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF51 + δ) j < mlpSF (imgF51 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF51 (by norm_num)
    (by norm_num) δ hδ

/-- Test #52 (digit 5), net SF: certified at ε = 3/10 — margin 3.044 ≥ √2·L·ε. -/
theorem certSF30_52 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpSF (imgF52 + δ) j < mlpSF (imgF52 + δ) 5 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF52 (by norm_num)
    (by norm_num) δ hδ

/-- Test #54 (digit 6), net SF: certified at ε = 3/10 — margin 2.308 ≥ √2·L·ε. -/
theorem certSF30_54 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF54 + δ) j < mlpSF (imgF54 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF54 (by norm_num)
    (by norm_num) δ hδ

/-- Test #55 (digit 0), net SF: certified at ε = 3/10 — margin 2.760 ≥ √2·L·ε. -/
theorem certSF30_55 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF55 + δ) j < mlpSF (imgF55 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF55 (by norm_num)
    (by norm_num) δ hδ

/-- Test #56 (digit 4), net SF: certified at ε = 3/10 — margin 5.646 ≥ √2·L·ε. -/
theorem certSF30_56 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF56 + δ) j < mlpSF (imgF56 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF56 (by norm_num)
    (by norm_num) δ hδ

/-- Test #57 (digit 1), net SF: certified at ε = 3/10 — margin 3.801 ≥ √2·L·ε. -/
theorem certSF30_57 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF57 + δ) j < mlpSF (imgF57 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF57 (by norm_num)
    (by norm_num) δ hδ

/-- Test #58 (digit 9), net SF: certified at ε = 3/10 — margin 2.607 ≥ √2·L·ε. -/
theorem certSF30_58 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF58 + δ) j < mlpSF (imgF58 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF58 (by norm_num)
    (by norm_num) δ hδ

/-- Test #60 (digit 7), net SF: certified at ε = 3/10 — margin 5.167 ≥ √2·L·ε. -/
theorem certSF30_60 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF60 + δ) j < mlpSF (imgF60 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF60 (by norm_num)
    (by norm_num) δ hδ

/-- Test #64 (digit 7), net SF: certified at ε = 3/10 — margin 3.563 ≥ √2·L·ε. -/
theorem certSF30_64 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF64 + δ) j < mlpSF (imgF64 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF64 (by norm_num)
    (by norm_num) δ hδ

/-- Test #67 (digit 4), net SF: certified at ε = 3/10 — margin 3.978 ≥ √2·L·ε. -/
theorem certSF30_67 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF67 + δ) j < mlpSF (imgF67 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF67 (by norm_num)
    (by norm_num) δ hδ

/-- Test #68 (digit 3), net SF: certified at ε = 3/10 — margin 3.679 ≥ √2·L·ε. -/
theorem certSF30_68 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF68 + δ) j < mlpSF (imgF68 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF68 (by norm_num)
    (by norm_num) δ hδ

/-- Test #69 (digit 0), net SF: certified at ε = 3/10 — margin 3.391 ≥ √2·L·ε. -/
theorem certSF30_69 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF69 + δ) j < mlpSF (imgF69 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF69 (by norm_num)
    (by norm_num) δ hδ

/-- Test #70 (digit 7), net SF: certified at ε = 3/10 — margin 5.972 ≥ √2·L·ε. -/
theorem certSF30_70 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF70 + δ) j < mlpSF (imgF70 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF70 (by norm_num)
    (by norm_num) δ hδ

/-- Test #71 (digit 0), net SF: certified at ε = 3/10 — margin 5.013 ≥ √2·L·ε. -/
theorem certSF30_71 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpSF (imgF71 + δ) j < mlpSF (imgF71 + δ) 0 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF71 (by norm_num)
    (by norm_num) δ hδ

/-- Test #72 (digit 2), net SF: certified at ε = 3/10 — margin 3.870 ≥ √2·L·ε. -/
theorem certSF30_72 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF72 + δ) j < mlpSF (imgF72 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF72 (by norm_num)
    (by norm_num) δ hδ

/-- Test #74 (digit 1), net SF: certified at ε = 3/10 — margin 3.649 ≥ √2·L·ε. -/
theorem certSF30_74 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF74 + δ) j < mlpSF (imgF74 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF74 (by norm_num)
    (by norm_num) δ hδ

/-- Test #75 (digit 7), net SF: certified at ε = 3/10 — margin 4.547 ≥ √2·L·ε. -/
theorem certSF30_75 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF75 + δ) j < mlpSF (imgF75 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF75 (by norm_num)
    (by norm_num) δ hδ

/-- Test #79 (digit 7), net SF: certified at ε = 3/10 — margin 6.032 ≥ √2·L·ε. -/
theorem certSF30_79 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF79 + δ) j < mlpSF (imgF79 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF79 (by norm_num)
    (by norm_num) δ hδ

/-- Test #81 (digit 6), net SF: certified at ε = 3/10 — margin 3.414 ≥ √2·L·ε. -/
theorem certSF30_81 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF81 + δ) j < mlpSF (imgF81 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF81 (by norm_num)
    (by norm_num) δ hδ

/-- Test #82 (digit 2), net SF: certified at ε = 3/10 — margin 6.822 ≥ √2·L·ε. -/
theorem certSF30_82 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpSF (imgF82 + δ) j < mlpSF (imgF82 + δ) 2 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF82 (by norm_num)
    (by norm_num) δ hδ

/-- Test #83 (digit 7), net SF: certified at ε = 3/10 — margin 2.930 ≥ √2·L·ε. -/
theorem certSF30_83 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF83 + δ) j < mlpSF (imgF83 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF83 (by norm_num)
    (by norm_num) δ hδ

/-- Test #84 (digit 8), net SF: certified at ε = 3/10 — margin 2.534 ≥ √2·L·ε. -/
theorem certSF30_84 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 8 → mlpSF (imgF84 + δ) j < mlpSF (imgF84 + δ) 8 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF84 (by norm_num)
    (by norm_num) δ hδ

/-- Test #85 (digit 4), net SF: certified at ε = 3/10 — margin 5.951 ≥ √2·L·ε. -/
theorem certSF30_85 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF85 + δ) j < mlpSF (imgF85 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF85 (by norm_num)
    (by norm_num) δ hδ

/-- Test #86 (digit 7), net SF: certified at ε = 3/10 — margin 6.791 ≥ √2·L·ε. -/
theorem certSF30_86 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpSF (imgF86 + δ) j < mlpSF (imgF86 + δ) 7 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF86 (by norm_num)
    (by norm_num) δ hδ

/-- Test #88 (digit 6), net SF: certified at ε = 3/10 — margin 4.154 ≥ √2·L·ε. -/
theorem certSF30_88 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF88 + δ) j < mlpSF (imgF88 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF88 (by norm_num)
    (by norm_num) δ hδ

/-- Test #89 (digit 1), net SF: certified at ε = 3/10 — margin 5.184 ≥ √2·L·ε. -/
theorem certSF30_89 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF89 + δ) j < mlpSF (imgF89 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF89 (by norm_num)
    (by norm_num) δ hδ

/-- Test #90 (digit 3), net SF: certified at ε = 3/10 — margin 3.818 ≥ √2·L·ε. -/
theorem certSF30_90 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF90 + δ) j < mlpSF (imgF90 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF90 (by norm_num)
    (by norm_num) δ hδ

/-- Test #91 (digit 6), net SF: certified at ε = 3/10 — margin 5.482 ≥ √2·L·ε. -/
theorem certSF30_91 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF91 + δ) j < mlpSF (imgF91 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF91 (by norm_num)
    (by norm_num) δ hδ

/-- Test #93 (digit 3), net SF: certified at ε = 3/10 — margin 3.206 ≥ √2·L·ε. -/
theorem certSF30_93 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpSF (imgF93 + δ) j < mlpSF (imgF93 + δ) 3 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF93 (by norm_num)
    (by norm_num) δ hδ

/-- Test #94 (digit 1), net SF: certified at ε = 3/10 — margin 2.949 ≥ √2·L·ε. -/
theorem certSF30_94 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpSF (imgF94 + δ) j < mlpSF (imgF94 + δ) 1 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF94 (by norm_num)
    (by norm_num) δ hδ

/-- Test #95 (digit 4), net SF: certified at ε = 3/10 — margin 3.666 ≥ √2·L·ε. -/
theorem certSF30_95 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpSF (imgF95 + δ) j < mlpSF (imgF95 + δ) 4 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF95 (by norm_num)
    (by norm_num) δ hδ

/-- Test #98 (digit 6), net SF: certified at ε = 3/10 — margin 3.820 ≥ √2·L·ε. -/
theorem certSF30_98 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpSF (imgF98 + δ) j < mlpSF (imgF98 + δ) 6 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF98 (by norm_num)
    (by norm_num) δ hδ

/-- Test #99 (digit 9), net SF: certified at ε = 3/10 — margin 3.612 ≥ √2·L·ε. -/
theorem certSF30_99 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpSF (imgF99 + δ) j < mlpSF (imgF99 + δ) 9 :=
  certified_at_eps mlpSF_lip (by norm_num) marginSF99 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net SF, ε = 3/10. -/
noncomputable def cappedFullCerts30 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (1, imgF1, 2),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9),
   (9, imgF9, 9),
   (11, imgF11, 6),
   (12, imgF12, 9),
   (13, imgF13, 0),
   (14, imgF14, 1),
   (15, imgF15, 5),
   (16, imgF16, 9),
   (17, imgF17, 7),
   (19, imgF19, 4),
   (21, imgF21, 6),
   (22, imgF22, 6),
   (23, imgF23, 5),
   (25, imgF25, 0),
   (26, imgF26, 7),
   (27, imgF27, 4),
   (28, imgF28, 0),
   (29, imgF29, 1),
   (30, imgF30, 3),
   (31, imgF31, 1),
   (34, imgF34, 7),
   (35, imgF35, 2),
   (36, imgF36, 7),
   (37, imgF37, 1),
   (39, imgF39, 1),
   (40, imgF40, 1),
   (41, imgF41, 7),
   (43, imgF43, 2),
   (45, imgF45, 5),
   (48, imgF48, 4),
   (49, imgF49, 4),
   (50, imgF50, 6),
   (51, imgF51, 3),
   (52, imgF52, 5),
   (54, imgF54, 6),
   (55, imgF55, 0),
   (56, imgF56, 4),
   (57, imgF57, 1),
   (58, imgF58, 9),
   (60, imgF60, 7),
   (64, imgF64, 7),
   (67, imgF67, 4),
   (68, imgF68, 3),
   (69, imgF69, 0),
   (70, imgF70, 7),
   (71, imgF71, 0),
   (72, imgF72, 2),
   (74, imgF74, 1),
   (75, imgF75, 7),
   (79, imgF79, 7),
   (81, imgF81, 6),
   (82, imgF82, 2),
   (83, imgF83, 7),
   (84, imgF84, 8),
   (85, imgF85, 4),
   (86, imgF86, 7),
   (88, imgF88, 6),
   (89, imgF89, 1),
   (90, imgF90, 3),
   (91, imgF91, 6),
   (93, imgF93, 3),
   (94, imgF94, 1),
   (95, imgF95, 4),
   (98, imgF98, 6),
   (99, imgF99, 9)]

theorem cappedFullCerts30_certified :
    ∀ p ∈ cappedFullCerts30, CertifiedAt mlpSF ((3 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certSF30_0, certSF30_1, certSF30_2, certSF30_3, certSF30_4, certSF30_5, certSF30_6, certSF30_7, certSF30_9, certSF30_11, certSF30_12, certSF30_13, certSF30_14, certSF30_15, certSF30_16, certSF30_17, certSF30_19, certSF30_21, certSF30_22, certSF30_23, certSF30_25, certSF30_26, certSF30_27, certSF30_28, certSF30_29, certSF30_30, certSF30_31, certSF30_34, certSF30_35, certSF30_36, certSF30_37, certSF30_39, certSF30_40, certSF30_41, certSF30_43, certSF30_45, certSF30_48, certSF30_49, certSF30_50, certSF30_51, certSF30_52, certSF30_54, certSF30_55, certSF30_56, certSF30_57, certSF30_58, certSF30_60, certSF30_64, certSF30_67, certSF30_68, certSF30_69, certSF30_70, certSF30_71, certSF30_72, certSF30_74, certSF30_75, certSF30_79, certSF30_81, certSF30_82, certSF30_83, certSF30_84, certSF30_85, certSF30_86, certSF30_88, certSF30_89, certSF30_90, certSF30_91, certSF30_93, certSF30_94, certSF30_95, certSF30_98, certSF30_99⟩

/-- Test #0 (digit 7), net TF: certified at ε = 1/10 — margin 4.551 ≥ √2·L·ε. -/
theorem certTF10_0 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF0 + δ) j < mlpTF (imgF0 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF0 (by norm_num)
    (by norm_num) δ hδ

/-- Test #2 (digit 1), net TF: certified at ε = 1/10 — margin 7.083 ≥ √2·L·ε. -/
theorem certTF10_2 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF2 + δ) j < mlpTF (imgF2 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF2 (by norm_num)
    (by norm_num) δ hδ

/-- Test #3 (digit 0), net TF: certified at ε = 1/10 — margin 9.403 ≥ √2·L·ε. -/
theorem certTF10_3 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF3 + δ) j < mlpTF (imgF3 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF3 (by norm_num)
    (by norm_num) δ hδ

/-- Test #4 (digit 4), net TF: certified at ε = 1/10 — margin 6.060 ≥ √2·L·ε. -/
theorem certTF10_4 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF4 + δ) j < mlpTF (imgF4 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF4 (by norm_num)
    (by norm_num) δ hδ

/-- Test #5 (digit 1), net TF: certified at ε = 1/10 — margin 6.346 ≥ √2·L·ε. -/
theorem certTF10_5 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF5 + δ) j < mlpTF (imgF5 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF5 (by norm_num)
    (by norm_num) δ hδ

/-- Test #6 (digit 4), net TF: certified at ε = 1/10 — margin 5.388 ≥ √2·L·ε. -/
theorem certTF10_6 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF6 + δ) j < mlpTF (imgF6 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF6 (by norm_num)
    (by norm_num) δ hδ

/-- Test #7 (digit 9), net TF: certified at ε = 1/10 — margin 5.549 ≥ √2·L·ε. -/
theorem certTF10_7 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF7 + δ) j < mlpTF (imgF7 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF7 (by norm_num)
    (by norm_num) δ hδ

/-- Test #9 (digit 9), net TF: certified at ε = 1/10 — margin 5.232 ≥ √2·L·ε. -/
theorem certTF10_9 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF9 + δ) j < mlpTF (imgF9 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF9 (by norm_num)
    (by norm_num) δ hδ

/-- Test #10 (digit 0), net TF: certified at ε = 1/10 — margin 7.446 ≥ √2·L·ε. -/
theorem certTF10_10 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF10 + δ) j < mlpTF (imgF10 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF10 (by norm_num)
    (by norm_num) δ hδ

/-- Test #11 (digit 6), net TF: certified at ε = 1/10 — margin 5.996 ≥ √2·L·ε. -/
theorem certTF10_11 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF11 + δ) j < mlpTF (imgF11 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF11 (by norm_num)
    (by norm_num) δ hδ

/-- Test #12 (digit 9), net TF: certified at ε = 1/10 — margin 4.398 ≥ √2·L·ε. -/
theorem certTF10_12 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF12 + δ) j < mlpTF (imgF12 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF12 (by norm_num)
    (by norm_num) δ hδ

/-- Test #13 (digit 0), net TF: certified at ε = 1/10 — margin 7.910 ≥ √2·L·ε. -/
theorem certTF10_13 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF13 + δ) j < mlpTF (imgF13 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF13 (by norm_num)
    (by norm_num) δ hδ

/-- Test #14 (digit 1), net TF: certified at ε = 1/10 — margin 4.669 ≥ √2·L·ε. -/
theorem certTF10_14 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF14 + δ) j < mlpTF (imgF14 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF14 (by norm_num)
    (by norm_num) δ hδ

/-- Test #15 (digit 5), net TF: certified at ε = 1/10 — margin 4.723 ≥ √2·L·ε. -/
theorem certTF10_15 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpTF (imgF15 + δ) j < mlpTF (imgF15 + δ) 5 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF15 (by norm_num)
    (by norm_num) δ hδ

/-- Test #16 (digit 9), net TF: certified at ε = 1/10 — margin 4.808 ≥ √2·L·ε. -/
theorem certTF10_16 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF16 + δ) j < mlpTF (imgF16 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF16 (by norm_num)
    (by norm_num) δ hδ

/-- Test #17 (digit 7), net TF: certified at ε = 1/10 — margin 4.702 ≥ √2·L·ε. -/
theorem certTF10_17 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF17 + δ) j < mlpTF (imgF17 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF17 (by norm_num)
    (by norm_num) δ hδ

/-- Test #19 (digit 4), net TF: certified at ε = 1/10 — margin 10.007 ≥ √2·L·ε. -/
theorem certTF10_19 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF19 + δ) j < mlpTF (imgF19 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF19 (by norm_num)
    (by norm_num) δ hδ

/-- Test #21 (digit 6), net TF: certified at ε = 1/10 — margin 6.350 ≥ √2·L·ε. -/
theorem certTF10_21 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF21 + δ) j < mlpTF (imgF21 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF21 (by norm_num)
    (by norm_num) δ hδ

/-- Test #23 (digit 5), net TF: certified at ε = 1/10 — margin 8.212 ≥ √2·L·ε. -/
theorem certTF10_23 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpTF (imgF23 + δ) j < mlpTF (imgF23 + δ) 5 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF23 (by norm_num)
    (by norm_num) δ hδ

/-- Test #24 (digit 4), net TF: certified at ε = 1/10 — margin 6.048 ≥ √2·L·ε. -/
theorem certTF10_24 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF24 + δ) j < mlpTF (imgF24 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF24 (by norm_num)
    (by norm_num) δ hδ

/-- Test #25 (digit 0), net TF: certified at ε = 1/10 — margin 13.368 ≥ √2·L·ε. -/
theorem certTF10_25 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF25 + δ) j < mlpTF (imgF25 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF25 (by norm_num)
    (by norm_num) δ hδ

/-- Test #26 (digit 7), net TF: certified at ε = 1/10 — margin 7.068 ≥ √2·L·ε. -/
theorem certTF10_26 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF26 + δ) j < mlpTF (imgF26 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF26 (by norm_num)
    (by norm_num) δ hδ

/-- Test #27 (digit 4), net TF: certified at ε = 1/10 — margin 7.587 ≥ √2·L·ε. -/
theorem certTF10_27 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF27 + δ) j < mlpTF (imgF27 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF27 (by norm_num)
    (by norm_num) δ hδ

/-- Test #28 (digit 0), net TF: certified at ε = 1/10 — margin 11.774 ≥ √2·L·ε. -/
theorem certTF10_28 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF28 + δ) j < mlpTF (imgF28 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF28 (by norm_num)
    (by norm_num) δ hδ

/-- Test #29 (digit 1), net TF: certified at ε = 1/10 — margin 6.216 ≥ √2·L·ε. -/
theorem certTF10_29 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF29 + δ) j < mlpTF (imgF29 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF29 (by norm_num)
    (by norm_num) δ hδ

/-- Test #30 (digit 3), net TF: certified at ε = 1/10 — margin 8.132 ≥ √2·L·ε. -/
theorem certTF10_30 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF30 + δ) j < mlpTF (imgF30 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF30 (by norm_num)
    (by norm_num) δ hδ

/-- Test #32 (digit 3), net TF: certified at ε = 1/10 — margin 7.526 ≥ √2·L·ε. -/
theorem certTF10_32 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF32 + δ) j < mlpTF (imgF32 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF32 (by norm_num)
    (by norm_num) δ hδ

/-- Test #34 (digit 7), net TF: certified at ε = 1/10 — margin 5.066 ≥ √2·L·ε. -/
theorem certTF10_34 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF34 + δ) j < mlpTF (imgF34 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF34 (by norm_num)
    (by norm_num) δ hδ

/-- Test #35 (digit 2), net TF: certified at ε = 1/10 — margin 6.048 ≥ √2·L·ε. -/
theorem certTF10_35 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF35 + δ) j < mlpTF (imgF35 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF35 (by norm_num)
    (by norm_num) δ hδ

/-- Test #36 (digit 7), net TF: certified at ε = 1/10 — margin 5.128 ≥ √2·L·ε. -/
theorem certTF10_36 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF36 + δ) j < mlpTF (imgF36 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF36 (by norm_num)
    (by norm_num) δ hδ

/-- Test #37 (digit 1), net TF: certified at ε = 1/10 — margin 8.037 ≥ √2·L·ε. -/
theorem certTF10_37 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF37 + δ) j < mlpTF (imgF37 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF37 (by norm_num)
    (by norm_num) δ hδ

/-- Test #39 (digit 1), net TF: certified at ε = 1/10 — margin 4.235 ≥ √2·L·ε. -/
theorem certTF10_39 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF39 + δ) j < mlpTF (imgF39 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF39 (by norm_num)
    (by norm_num) δ hδ

/-- Test #40 (digit 1), net TF: certified at ε = 1/10 — margin 6.062 ≥ √2·L·ε. -/
theorem certTF10_40 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF40 + δ) j < mlpTF (imgF40 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF40 (by norm_num)
    (by norm_num) δ hδ

/-- Test #41 (digit 7), net TF: certified at ε = 1/10 — margin 4.682 ≥ √2·L·ε. -/
theorem certTF10_41 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF41 + δ) j < mlpTF (imgF41 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF41 (by norm_num)
    (by norm_num) δ hδ

/-- Test #42 (digit 4), net TF: certified at ε = 1/10 — margin 7.625 ≥ √2·L·ε. -/
theorem certTF10_42 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF42 + δ) j < mlpTF (imgF42 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF42 (by norm_num)
    (by norm_num) δ hδ

/-- Test #43 (digit 2), net TF: certified at ε = 1/10 — margin 5.192 ≥ √2·L·ε. -/
theorem certTF10_43 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF43 + δ) j < mlpTF (imgF43 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF43 (by norm_num)
    (by norm_num) δ hδ

/-- Test #44 (digit 3), net TF: certified at ε = 1/10 — margin 5.271 ≥ √2·L·ε. -/
theorem certTF10_44 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF44 + δ) j < mlpTF (imgF44 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF44 (by norm_num)
    (by norm_num) δ hδ

/-- Test #45 (digit 5), net TF: certified at ε = 1/10 — margin 4.706 ≥ √2·L·ε. -/
theorem certTF10_45 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 5 → mlpTF (imgF45 + δ) j < mlpTF (imgF45 + δ) 5 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF45 (by norm_num)
    (by norm_num) δ hδ

/-- Test #47 (digit 2), net TF: certified at ε = 1/10 — margin 5.378 ≥ √2·L·ε. -/
theorem certTF10_47 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF47 + δ) j < mlpTF (imgF47 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF47 (by norm_num)
    (by norm_num) δ hδ

/-- Test #48 (digit 4), net TF: certified at ε = 1/10 — margin 6.919 ≥ √2·L·ε. -/
theorem certTF10_48 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF48 + δ) j < mlpTF (imgF48 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF48 (by norm_num)
    (by norm_num) δ hδ

/-- Test #49 (digit 4), net TF: certified at ε = 1/10 — margin 8.960 ≥ √2·L·ε. -/
theorem certTF10_49 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF49 + δ) j < mlpTF (imgF49 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF49 (by norm_num)
    (by norm_num) δ hδ

/-- Test #51 (digit 3), net TF: certified at ε = 1/10 — margin 10.295 ≥ √2·L·ε. -/
theorem certTF10_51 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF51 + δ) j < mlpTF (imgF51 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF51 (by norm_num)
    (by norm_num) δ hδ

/-- Test #54 (digit 6), net TF: certified at ε = 1/10 — margin 9.082 ≥ √2·L·ε. -/
theorem certTF10_54 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF54 + δ) j < mlpTF (imgF54 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF54 (by norm_num)
    (by norm_num) δ hδ

/-- Test #55 (digit 0), net TF: certified at ε = 1/10 — margin 8.510 ≥ √2·L·ε. -/
theorem certTF10_55 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF55 + δ) j < mlpTF (imgF55 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF55 (by norm_num)
    (by norm_num) δ hδ

/-- Test #56 (digit 4), net TF: certified at ε = 1/10 — margin 12.027 ≥ √2·L·ε. -/
theorem certTF10_56 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF56 + δ) j < mlpTF (imgF56 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF56 (by norm_num)
    (by norm_num) δ hδ

/-- Test #57 (digit 1), net TF: certified at ε = 1/10 — margin 5.698 ≥ √2·L·ε. -/
theorem certTF10_57 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF57 + δ) j < mlpTF (imgF57 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF57 (by norm_num)
    (by norm_num) δ hδ

/-- Test #58 (digit 9), net TF: certified at ε = 1/10 — margin 4.624 ≥ √2·L·ε. -/
theorem certTF10_58 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF58 + δ) j < mlpTF (imgF58 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF58 (by norm_num)
    (by norm_num) δ hδ

/-- Test #63 (digit 3), net TF: certified at ε = 1/10 — margin 4.394 ≥ √2·L·ε. -/
theorem certTF10_63 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF63 + δ) j < mlpTF (imgF63 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF63 (by norm_num)
    (by norm_num) δ hδ

/-- Test #67 (digit 4), net TF: certified at ε = 1/10 — margin 9.339 ≥ √2·L·ε. -/
theorem certTF10_67 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF67 + δ) j < mlpTF (imgF67 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF67 (by norm_num)
    (by norm_num) δ hδ

/-- Test #68 (digit 3), net TF: certified at ε = 1/10 — margin 7.779 ≥ √2·L·ε. -/
theorem certTF10_68 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF68 + δ) j < mlpTF (imgF68 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF68 (by norm_num)
    (by norm_num) δ hδ

/-- Test #69 (digit 0), net TF: certified at ε = 1/10 — margin 8.325 ≥ √2·L·ε. -/
theorem certTF10_69 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF69 + δ) j < mlpTF (imgF69 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF69 (by norm_num)
    (by norm_num) δ hδ

/-- Test #70 (digit 7), net TF: certified at ε = 1/10 — margin 9.949 ≥ √2·L·ε. -/
theorem certTF10_70 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF70 + δ) j < mlpTF (imgF70 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF70 (by norm_num)
    (by norm_num) δ hδ

/-- Test #71 (digit 0), net TF: certified at ε = 1/10 — margin 14.174 ≥ √2·L·ε. -/
theorem certTF10_71 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF71 + δ) j < mlpTF (imgF71 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF71 (by norm_num)
    (by norm_num) δ hδ

/-- Test #72 (digit 2), net TF: certified at ε = 1/10 — margin 5.806 ≥ √2·L·ε. -/
theorem certTF10_72 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF72 + δ) j < mlpTF (imgF72 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF72 (by norm_num)
    (by norm_num) δ hδ

/-- Test #74 (digit 1), net TF: certified at ε = 1/10 — margin 7.424 ≥ √2·L·ε. -/
theorem certTF10_74 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF74 + δ) j < mlpTF (imgF74 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF74 (by norm_num)
    (by norm_num) δ hδ

/-- Test #75 (digit 7), net TF: certified at ε = 1/10 — margin 7.840 ≥ √2·L·ε. -/
theorem certTF10_75 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF75 + δ) j < mlpTF (imgF75 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF75 (by norm_num)
    (by norm_num) δ hδ

/-- Test #76 (digit 3), net TF: certified at ε = 1/10 — margin 4.796 ≥ √2·L·ε. -/
theorem certTF10_76 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF76 + δ) j < mlpTF (imgF76 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF76 (by norm_num)
    (by norm_num) δ hδ

/-- Test #77 (digit 2), net TF: certified at ε = 1/10 — margin 7.607 ≥ √2·L·ε. -/
theorem certTF10_77 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF77 + δ) j < mlpTF (imgF77 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF77 (by norm_num)
    (by norm_num) δ hδ

/-- Test #78 (digit 9), net TF: certified at ε = 1/10 — margin 5.638 ≥ √2·L·ε. -/
theorem certTF10_78 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF78 + δ) j < mlpTF (imgF78 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF78 (by norm_num)
    (by norm_num) δ hδ

/-- Test #79 (digit 7), net TF: certified at ε = 1/10 — margin 10.572 ≥ √2·L·ε. -/
theorem certTF10_79 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF79 + δ) j < mlpTF (imgF79 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF79 (by norm_num)
    (by norm_num) δ hδ

/-- Test #81 (digit 6), net TF: certified at ε = 1/10 — margin 4.991 ≥ √2·L·ε. -/
theorem certTF10_81 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF81 + δ) j < mlpTF (imgF81 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF81 (by norm_num)
    (by norm_num) δ hδ

/-- Test #82 (digit 2), net TF: certified at ε = 1/10 — margin 12.098 ≥ √2·L·ε. -/
theorem certTF10_82 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 2 → mlpTF (imgF82 + δ) j < mlpTF (imgF82 + δ) 2 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF82 (by norm_num)
    (by norm_num) δ hδ

/-- Test #83 (digit 7), net TF: certified at ε = 1/10 — margin 7.526 ≥ √2·L·ε. -/
theorem certTF10_83 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF83 + δ) j < mlpTF (imgF83 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF83 (by norm_num)
    (by norm_num) δ hδ

/-- Test #85 (digit 4), net TF: certified at ε = 1/10 — margin 10.467 ≥ √2·L·ε. -/
theorem certTF10_85 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF85 + δ) j < mlpTF (imgF85 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF85 (by norm_num)
    (by norm_num) δ hδ

/-- Test #86 (digit 7), net TF: certified at ε = 1/10 — margin 8.945 ≥ √2·L·ε. -/
theorem certTF10_86 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF86 + δ) j < mlpTF (imgF86 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF86 (by norm_num)
    (by norm_num) δ hδ

/-- Test #87 (digit 3), net TF: certified at ε = 1/10 — margin 6.278 ≥ √2·L·ε. -/
theorem certTF10_87 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF87 + δ) j < mlpTF (imgF87 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF87 (by norm_num)
    (by norm_num) δ hδ

/-- Test #88 (digit 6), net TF: certified at ε = 1/10 — margin 9.314 ≥ √2·L·ε. -/
theorem certTF10_88 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF88 + δ) j < mlpTF (imgF88 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF88 (by norm_num)
    (by norm_num) δ hδ

/-- Test #89 (digit 1), net TF: certified at ε = 1/10 — margin 7.852 ≥ √2·L·ε. -/
theorem certTF10_89 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF89 + δ) j < mlpTF (imgF89 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF89 (by norm_num)
    (by norm_num) δ hδ

/-- Test #90 (digit 3), net TF: certified at ε = 1/10 — margin 6.944 ≥ √2·L·ε. -/
theorem certTF10_90 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF90 + δ) j < mlpTF (imgF90 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF90 (by norm_num)
    (by norm_num) δ hδ

/-- Test #91 (digit 6), net TF: certified at ε = 1/10 — margin 8.799 ≥ √2·L·ε. -/
theorem certTF10_91 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF91 + δ) j < mlpTF (imgF91 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF91 (by norm_num)
    (by norm_num) δ hδ

/-- Test #93 (digit 3), net TF: certified at ε = 1/10 — margin 10.153 ≥ √2·L·ε. -/
theorem certTF10_93 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 3 → mlpTF (imgF93 + δ) j < mlpTF (imgF93 + δ) 3 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF93 (by norm_num)
    (by norm_num) δ hδ

/-- Test #94 (digit 1), net TF: certified at ε = 1/10 — margin 8.589 ≥ √2·L·ε. -/
theorem certTF10_94 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 1 → mlpTF (imgF94 + δ) j < mlpTF (imgF94 + δ) 1 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF94 (by norm_num)
    (by norm_num) δ hδ

/-- Test #95 (digit 4), net TF: certified at ε = 1/10 — margin 4.740 ≥ √2·L·ε. -/
theorem certTF10_95 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 4 → mlpTF (imgF95 + δ) j < mlpTF (imgF95 + δ) 4 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF95 (by norm_num)
    (by norm_num) δ hδ

/-- Test #97 (digit 7), net TF: certified at ε = 1/10 — margin 7.057 ≥ √2·L·ε. -/
theorem certTF10_97 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 7 → mlpTF (imgF97 + δ) j < mlpTF (imgF97 + δ) 7 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF97 (by norm_num)
    (by norm_num) δ hδ

/-- Test #98 (digit 6), net TF: certified at ε = 1/10 — margin 7.148 ≥ √2·L·ε. -/
theorem certTF10_98 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 6 → mlpTF (imgF98 + δ) j < mlpTF (imgF98 + δ) 6 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF98 (by norm_num)
    (by norm_num) δ hδ

/-- Test #99 (digit 9), net TF: certified at ε = 1/10 — margin 7.913 ≥ √2·L·ε. -/
theorem certTF10_99 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((1 : ℝ)/10)) :
    ∀ j, j ≠ 9 → mlpTF (imgF99 + δ) j < mlpTF (imgF99 + δ) 9 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF99 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net TF, ε = 1/10. -/
noncomputable def unconFullCerts10 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(0, imgF0, 7),
   (2, imgF2, 1),
   (3, imgF3, 0),
   (4, imgF4, 4),
   (5, imgF5, 1),
   (6, imgF6, 4),
   (7, imgF7, 9),
   (9, imgF9, 9),
   (10, imgF10, 0),
   (11, imgF11, 6),
   (12, imgF12, 9),
   (13, imgF13, 0),
   (14, imgF14, 1),
   (15, imgF15, 5),
   (16, imgF16, 9),
   (17, imgF17, 7),
   (19, imgF19, 4),
   (21, imgF21, 6),
   (23, imgF23, 5),
   (24, imgF24, 4),
   (25, imgF25, 0),
   (26, imgF26, 7),
   (27, imgF27, 4),
   (28, imgF28, 0),
   (29, imgF29, 1),
   (30, imgF30, 3),
   (32, imgF32, 3),
   (34, imgF34, 7),
   (35, imgF35, 2),
   (36, imgF36, 7),
   (37, imgF37, 1),
   (39, imgF39, 1),
   (40, imgF40, 1),
   (41, imgF41, 7),
   (42, imgF42, 4),
   (43, imgF43, 2),
   (44, imgF44, 3),
   (45, imgF45, 5),
   (47, imgF47, 2),
   (48, imgF48, 4),
   (49, imgF49, 4),
   (51, imgF51, 3),
   (54, imgF54, 6),
   (55, imgF55, 0),
   (56, imgF56, 4),
   (57, imgF57, 1),
   (58, imgF58, 9),
   (63, imgF63, 3),
   (67, imgF67, 4),
   (68, imgF68, 3),
   (69, imgF69, 0),
   (70, imgF70, 7),
   (71, imgF71, 0),
   (72, imgF72, 2),
   (74, imgF74, 1),
   (75, imgF75, 7),
   (76, imgF76, 3),
   (77, imgF77, 2),
   (78, imgF78, 9),
   (79, imgF79, 7),
   (81, imgF81, 6),
   (82, imgF82, 2),
   (83, imgF83, 7),
   (85, imgF85, 4),
   (86, imgF86, 7),
   (87, imgF87, 3),
   (88, imgF88, 6),
   (89, imgF89, 1),
   (90, imgF90, 3),
   (91, imgF91, 6),
   (93, imgF93, 3),
   (94, imgF94, 1),
   (95, imgF95, 4),
   (97, imgF97, 7),
   (98, imgF98, 6),
   (99, imgF99, 9)]

theorem unconFullCerts10_certified :
    ∀ p ∈ unconFullCerts10, CertifiedAt mlpTF ((1 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certTF10_0, certTF10_2, certTF10_3, certTF10_4, certTF10_5, certTF10_6, certTF10_7, certTF10_9, certTF10_10, certTF10_11, certTF10_12, certTF10_13, certTF10_14, certTF10_15, certTF10_16, certTF10_17, certTF10_19, certTF10_21, certTF10_23, certTF10_24, certTF10_25, certTF10_26, certTF10_27, certTF10_28, certTF10_29, certTF10_30, certTF10_32, certTF10_34, certTF10_35, certTF10_36, certTF10_37, certTF10_39, certTF10_40, certTF10_41, certTF10_42, certTF10_43, certTF10_44, certTF10_45, certTF10_47, certTF10_48, certTF10_49, certTF10_51, certTF10_54, certTF10_55, certTF10_56, certTF10_57, certTF10_58, certTF10_63, certTF10_67, certTF10_68, certTF10_69, certTF10_70, certTF10_71, certTF10_72, certTF10_74, certTF10_75, certTF10_76, certTF10_77, certTF10_78, certTF10_79, certTF10_81, certTF10_82, certTF10_83, certTF10_85, certTF10_86, certTF10_87, certTF10_88, certTF10_89, certTF10_90, certTF10_91, certTF10_93, certTF10_94, certTF10_95, certTF10_97, certTF10_98, certTF10_99⟩

/-- Test #25 (digit 0), net TF: certified at ε = 3/10 — margin 13.368 ≥ √2·L·ε. -/
theorem certTF30_25 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF25 + δ) j < mlpTF (imgF25 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF25 (by norm_num)
    (by norm_num) δ hδ

/-- Test #71 (digit 0), net TF: certified at ε = 3/10 — margin 14.174 ≥ √2·L·ε. -/
theorem certTF30_71 (δ : EuclideanSpace ℝ (Fin 784)) (hδ : ‖δ‖ < ((3 : ℝ)/10)) :
    ∀ j, j ≠ 0 → mlpTF (imgF71 + δ) j < mlpTF (imgF71 + δ) 0 :=
  certified_at_eps mlpTF_lip (by norm_num) marginTF71 (by norm_num)
    (by norm_num) δ hδ

/-- Certificate witnesses (subset index, image, class), net TF, ε = 3/10. -/
noncomputable def unconFullCerts30 : List (ℕ × EuclideanSpace ℝ (Fin 784) × Fin 10) :=
  [(25, imgF25, 0),
   (71, imgF71, 0)]

theorem unconFullCerts30_certified :
    ∀ p ∈ unconFullCerts30, CertifiedAt mlpTF ((3 : ℝ)/10) p.2.1 p.2.2 :=
  List.forall_iff_forall_mem.mp
    ⟨certTF30_25, certTF30_71⟩

/-- **The full-input scorecard, as a theorem** — counts tied to the per-image
    `CertifiedAt` proofs, both nets, both radii. Lower bounds only. -/
theorem scorecardFull :
    (cappedFullCerts10.length = 92 ∧
      ∀ p ∈ cappedFullCerts10, CertifiedAt mlpSF ((1 : ℝ)/10) p.2.1 p.2.2) ∧
    (cappedFullCerts30.length = 72 ∧
      ∀ p ∈ cappedFullCerts30, CertifiedAt mlpSF ((3 : ℝ)/10) p.2.1 p.2.2) ∧
    (unconFullCerts10.length = 76 ∧
      ∀ p ∈ unconFullCerts10, CertifiedAt mlpTF ((1 : ℝ)/10) p.2.1 p.2.2) ∧
    (unconFullCerts30.length = 2 ∧
      ∀ p ∈ unconFullCerts30, CertifiedAt mlpTF ((3 : ℝ)/10) p.2.1 p.2.2) :=
  ⟨⟨rfl, cappedFullCerts10_certified⟩, ⟨rfl, cappedFullCerts30_certified⟩,
   ⟨rfl, unconFullCerts10_certified⟩, ⟨rfl, unconFullCerts30_certified⟩⟩

end LipschitzCertDemo
end Proofs
