import LeanMlir

/-! # `yolov1-neudet-fpn` — the VisDrone detector, unchanged, on NEU-DET steel defects

```
lake build yolov1-neudet-fpn
CUDA_VISIBLE_DEVICES=0 FPN_TAG=run1 .lake/build/bin/yolov1-neudet-fpn data/neu_det_fpn
CUDA_VISIBLE_DEVICES=0 FPN_TAG=run1 .lake/build/bin/yolov1-neudet-fpn infer data/neu_det_fpn runs/neudet_fpn
python3 scripts/yolo_map_visdrone.py runs/neudet_fpn/logits.bin data/neu_det448/val.bin \
    --fpn data/neu_det --grid 14 --classes neu
```

The R34+FPN detector of `demos/MainYolov1VisdroneFpn.lean` — backbone, neck,
heads, loss, bootstrap, scorer — on NEU-DET: 1,800 grayscale 200×200 crops of
hot-rolled steel, six defect classes, one or two large defects per crop where
VisDrone has seventy 20-px cars per frame (planning/neu_det_fpn_demo.md).

**What changes** — data-derived constants only, nothing in the codegen:
1. the anchor priors: k-means over NEU boxes per level (`scripts/neu_anchors.py`).
   VisDrone's largest P5 prior is 0.18 × 0.15 of the frame; a NEU defect often
   spans half of it;
2. the class weights: off. NEU is 300 crops per class, so the sqrt-inverse
   VisDrone table has nothing to correct;
3. the six classes take ids 0–5 of the ten-slot one-hot. The per-anchor width
   5 + 10 = 15 is baked into the `fpnDetect` codegen (`LeanMlir/Types.lean`), so
   four class logits never see a positive; the scorer averages AP over the
   classes present, and four dead softmax slots cost nothing.

**What the defaults are.** The VisDrone recipe that scored 0.2363
(`FPN_BACKBONE=r34 FPN_AUG=1 FPN_CLSW=none FPN_CLSFOCAL=2 FPN_AFFINE=50
FPN_EPOCHS=30`) is this binary's DEFAULT, so the bare command above IS the
measured arm and none of the VisDrone file's silent-default traps apply here:
the backbone defaults to `r34` (not `r50`), the class weights to `none`. Every
knob keeps its name and can still be overridden — `FPN_AUG=0` and
`FPN_AFFINE=0` are the ablation arms.

⚠ `FPN_TAG` selects the checkpoint prefix and must be set on `infer` as well as
on training. Forgetting it does not fail — it silently evaluates a different
arm's weights, and the only tell is an epoch sweep whose rows are identical.
`FPN_EVAL_SPLIT=test` points `infer` at `test.bin` for the table's row once the
epoch has been chosen on val; `FPN_EVAL_EPOCH=N` evaluates the `_params_eN.bin`
checkpoint instead of the final one, so an epoch sweep never copies files over
the run's own artifacts.

**One file, one binary, either lowerer.** The proven graph goes to whichever
trusted lowerer `$LEAN_MLIR_LOWERER` selects -- XLA/PJRT by default, IREE with
`=iree` -- resolved by dlopen at run time (`ffi/lowerer.h`).
-/

-- Per-scale k-means priors over the NEU-DET TRAIN split, w_rel h_rel
-- (`scripts/neu_anchors.py --save data/neu_det` → data/neu_det/anchors_fpn_{p3,p4,p5}.txt;
-- this table is the source of truth, the files are regenerated by scripts/datasets/download_neu.sh).
-- Measured routing at 448 px, 24 / 64 px thresholds: P3 0.0% / P4 1.9% / P5 98.1%
-- of 2,539 train boxes. P3 has NO boxes, so its table is a fixed fallback spanning
-- its size band — the codegen needs three anchors on every level, and on a level
-- with no positives they only decode what the head emits there.
def neuAnchorsP3 : List (Float × Float) :=
  [(0.026786, 0.026786), (0.017857, 0.044643), (0.044643, 0.017857)]
def neuAnchorsP4 : List (Float × Float) :=
  [(0.067000, 0.122250), (0.127222, 0.091667), (0.115833, 0.122778)]
-- P5 carries 98% of the boxes at every aspect from 64 px to the full frame, and
-- three anchors fit that poorly: mean best wh-IoU 0.52, recall@0.5 0.52 (k=9
-- would give 0.94). That is the prior's FIT, not a ceiling — the head regresses
-- exp(t) off the anchor and the k=3 log-residuals top out at 2.0 against a cap
-- of 8 — and the encoding ceiling that matters, unique (level, cell, anchor)
-- slots per GT box, is 99.9% on NEU against VisDrone's 88%. Recorded here
-- because Gate 0 in the plan asked for ≥ 0.9 on a VisDrone-shaped intuition.
def neuAnchorsP5 : List (Float × Float) :=
  [(0.168713, 0.429203), (0.621498, 0.276457), (0.510919, 0.787666)]

/-- Per-scale (grid, anchors) for P3/P4/P5. Order MUST match the codegen concat
    ([P3|P4|P5]) and the on-disk flat target laid out by scripts/datasets/preprocess_neu_det.py. -/
def neuDetScales : List (Nat × List (Float × Float)) :=
  [(56, neuAnchorsP3), (28, neuAnchorsP4), (14, neuAnchorsP5)]

def neuNtot : Nat :=
  (neuDetScales.map (fun sc => sc.2.length * 15 * sc.1 * sc.1)).foldl (·+·) 0

/-- ResNet-34 + FPN detector, the VisDrone `r34FpnDetT` layer-for-layer; only the
    name differs, so its build prefix and checkpoints never touch the VisDrone
    arm's (which are live references for every number in the book). -/
def r34NeuFpnDetT (tower : Nat) : NetSpec where
  name := if tower == 0 then "ResNet-34 + FPN detector 448 (NEU-DET)"
          else s!"ResNet-34 + FPN detector 448 tower{tower} (NEU-DET)"
  imageH := 448
  imageW := 448
  detStride := 32
  layers := [
    .convBn 3 64 7 2 .same,
    .maxPool 2 2,
    .residualBlock  64  64 3 1,   -- stride 4
    .residualBlock  64 128 4 2,   -- C3: 128ch, 56×56
    .residualBlock 128 256 6 2,   -- C4: 256ch, 28×28
    .residualBlock 256 512 3 2,   -- C5: 512ch, 14×14
    .fpnDetect 256 128 256 512 14 3 tower
  ]

/-- ResNet-50 variant, the VisDrone `r50FpnDetT` layer-for-layer (see that file for
    why the pool is 2×2 and why the bootstrap is conv-only). Selectable with
    `FPN_BACKBONE=r50`; the arm in the tables is R34. -/
def r50NeuFpnDetT (tower : Nat) : NetSpec where
  name := if tower == 0 then "ResNet-50 + FPN detector 448 (NEU-DET)"
          else s!"ResNet-50 + FPN detector 448 tower{tower} (NEU-DET)"
  convPadStyle := .symmetric
  imageH := 448
  imageW := 448
  detStride := 32
  layers := [
    .convBn 3 64 7 2 .same,
    .maxPool 2 2,
    .bottleneckBlock   64  256 3 1,   -- C2: stride 4,  112×112
    .bottleneckBlock  256  512 4 2,   -- C3: 512ch,      56×56
    .bottleneckBlock  512 1024 6 2,   -- C4: 1024ch,     28×28
    .bottleneckBlock 1024 2048 3 2,   -- C5: 2048ch,     14×14
    .fpnDetect 256 512 1024 2048 14 3 tower
  ]

/-- The VisDrone `r34FpnDetConfig` with the measured recipe's env settings folded
    in as defaults (30 epochs, HSV+hflip, affine p=0.5, class focal γ=2, no class
    weights) and the NEU anchor table routed to the loss. Everything numeric —
    LR, batch, clip, warmup, decay, objectness focal, prior bias — is VisDrone's. -/
def neuFpnDetConfig : TrainConfig where
  learningRate := 4.0e-4
  batchSize    := 8
  epochs       := 30
  useAdam      := true
  weightDecay  := 0.0005
  cosineDecay  := true
  warmupEpochs := 3
  gradClipNorm := 4.0
  checkpointEveryNEpochs := 2
  augment      := true                  -- FPN_AUG: HSV jitter + hflip
  focalGamma   := 2.0                   -- objectness focal γ
  fpnScales    := neuDetScales          -- routes the loss to emitMultiScaleYoloLoss
  yoloClsWeights := []                  -- FPN_CLSW=none: NEU is balanced
  yoloClsFocalGamma := 2.0              -- FPN_CLSFOCAL=2, as the 0.2363 arm ran
  fpnAffineProb := 0.5                  -- FPN_AFFINE=50, scale ±0.25 / translate ±0.1
  fpnAffineScale := 0.25
  fpnAffineTranslate := 0.1
  detPriorPi   := 0.01
  bootstrapBackbone := some (".lake/build/jax_r34_imagenet.bin", 21284672)

def r50NeuFpnDetConfig : TrainConfig :=
  { neuFpnDetConfig with
      bootstrapBackbone := some (".lake/build/r50_a3convonly_params.bin", 23508032) }

-- ── env knobs: the VisDrone file's names, NEU's defaults ────────────────────

/-- Backbone selector (`FPN_BACKBONE`): `r34` (default — the arm in the tables) or `r50`. -/
def backboneFromEnv : IO String := do
  match (← IO.getEnv "FPN_BACKBONE") with
  | none => return "r34"
  | some v => return if v.trimAscii.toString.isEmpty then "r34" else v.trimAscii.toString.toLower

def envFlag (name : String) (dflt : Bool) : IO Bool := do
  match (← IO.getEnv name) with
  | none => return dflt
  | some v =>
    let s := v.trimAscii.toString.toLower
    return if s.isEmpty then dflt else (s == "1" || s == "true")

def envNat (name : String) (dflt : Nat) : IO Nat := do
  match (← IO.getEnv name) with
  | none => return dflt
  | some v => return (v.trimAscii.toNat?).getD dflt

/-- Percent knobs (`FPN_AFFINE`, `FPN_AFFINE_SCALE`, `FPN_AFFINE_TRANSLATE`), as in the
    VisDrone file: integers 0–100 because this toolchain has no `String.toFloat?`. -/
def envPct (name : String) (dflt : Nat) : IO Float := do
  return (← envNat name dflt).toFloat / 100.0

/-- Class-weighting strength (`FPN_CLSW`): `none` (default) | `sqrt` | `inv`. The
    VisDrone tables are VisDrone's frequencies and mean nothing on balanced NEU;
    they are kept only so the knob's three values all still parse, and any
    non-`none` value warns. -/
def clsWeightsFromEnv : IO (List Float) := do
  match (← IO.getEnv "FPN_CLSW") with
  | none => return []
  | some v =>
    match v.trimAscii.toString.toLower with
    | "none" | "" => return []
    | other =>
      IO.eprintln s!"  WARN: FPN_CLSW={other} applies VisDrone's class frequencies to NEU; using none"
      return []

/-- Name suffix (`FPN_TAG`). The name IS the on-disk checkpoint prefix, so two runs
    without distinct tags overwrite each other's e2..e30 checkpoints. -/
def tagFromEnv : IO String := do
  match (← IO.getEnv "FPN_TAG") with
  | none => return ""
  | some v => return if v.trimAscii.toString.isEmpty then "" else s!" {v.trimAscii.toString}"

/-- Which split `infer` dumps (`FPN_EVAL_SPLIT`, default `val`). -/
def evalSplitFromEnv : IO String := do
  match (← IO.getEnv "FPN_EVAL_SPLIT") with
  | none => return "val"
  | some v => return if v.trimAscii.toString.isEmpty then "val" else v.trimAscii.toString

/-- Which checkpoint `infer` loads (`FPN_EVAL_EPOCH`): empty = the final
    `_params.bin`, `N` = the `_params_eN.bin` / `_bn_stats_eN.bin` pair. -/
def evalEpochSuffixFromEnv : IO String := do
  match (← IO.getEnv "FPN_EVAL_EPOCH") with
  | none => return ""
  | some v => return if v.trimAscii.toString.isEmpty then "" else s!"_e{v.trimAscii.toString}"

/-- Infer: dump [N, Ntot] logits of the chosen split for scripts/yolo_map_visdrone.py --fpn. -/
def inferDump (spec : NetSpec) (dataDir outDir : String) : IO Unit := do
  IO.FS.createDirAll outDir
  let flat : Nat := neuNtot
  let split ← evalSplitFromEnv
  let esfx ← evalEpochSuffixFromEnv
  let evalVmfb ← NetSpec.graphArtifact spec.buildPrefix "fwd_eval"
  let paramsPath := s!"{spec.buildPrefix}_params{esfx}.bin"
  let bnPath := s!"{spec.buildPrefix}_bn_stats{esfx}.bin"
  -- Announce WHICH ARM is being evaluated (FPN_TAG / FPN_TOWER / FPN_BACKBONE all
  -- select it, and a forgotten one silently evaluates a different checkpoint).
  IO.println s!"  spec   : {spec.name}"
  IO.println s!"  prefix : {spec.buildPrefix}"
  IO.println s!"  params : {paramsPath} ({spec.totalParams} floats expected)"
  IO.println s!"  split  : {split}"
  if !(← System.FilePath.pathExists evalVmfb) then
    IO.eprintln s!"ERROR: no eval graph at {evalVmfb}; train first"; IO.Process.exit 1
  if !(← System.FilePath.pathExists paramsPath) then
    IO.eprintln s!"ERROR: no params at {paramsPath}"; IO.Process.exit 1
  let params ← IO.FS.readBinFile paramsPath
  let bnStats ←
    if ← System.FilePath.pathExists bnPath then IO.FS.readBinFile bnPath
    else F32.const spec.nBnStats.toUSize 0.0
  let evalParams := params.append bnStats
  let sess ← LowererSession.create evalVmfb
  let (valImg, _t, nVal) ← F32.loadDetBinFpn (dataDir ++ s!"/{split}.bin")
                             spec.imageH.toUSize flat.toUSize
  IO.println s!"  loaded {nVal} {split} records ({flat}-wide output); dumping logits"
  let batch : Nat := 8
  let xShape := spec.xShape batch
  let pixelsPerImage := 3 * spec.imageH * spec.imageW
  let evalShapesBA := spec.evalShapesBA
  let nOut : USize := flat.toUSize
  let rowBytes : Nat := flat * 4
  let nBatches := (nVal + batch - 1) / batch
  let mut logitsAll : ByteArray := ByteArray.empty
  for b in [:nBatches] do
    let start := b * batch
    let real  := min batch (nVal - start)
    let mut imgs := F32.sliceImages valImg start real pixelsPerImage
    if real < batch then
      let lastImg := F32.sliceImages valImg (start + real - 1) 1 pixelsPerImage
      for _ in [:batch - real] do imgs := imgs ++ lastImg
    let logitsB ← LowererSession.forwardF32 sess spec.evalFnName
                    evalParams evalShapesBA imgs xShape batch.toUSize nOut
    logitsAll := logitsAll ++ logitsB.extract 0 (real * rowBytes)
  IO.FS.writeBinFile s!"{outDir}/logits.bin" logitsAll
  IO.println s!"  wrote {outDir}/logits.bin ({logitsAll.size} bytes — {nVal}×{flat} f32)"
  IO.println s!"next: python3 scripts/yolo_map_visdrone.py {outDir}/logits.bin data/neu_det448/{split}.bin --fpn data/neu_det --grid 14 --classes neu"

def runYolov1NeuDetFpn (args : List String) : IO Unit := do
  let tower ← envNat "FPN_TOWER" 0
  let tag ← tagFromEnv
  let backbone ← backboneFromEnv
  let baseSpec := if backbone == "r50" then r50NeuFpnDetT tower else r34NeuFpnDetT tower
  let baseCfg  := if backbone == "r50" then r50NeuFpnDetConfig else neuFpnDetConfig
  let spec := { baseSpec with name := baseSpec.name ++ tag }
  match args with
  | "infer" :: rest =>
    let dataDir := rest[0]?.getD "data/neu_det_fpn"
    let outDir  := rest[1]?.getD "runs/neudet_fpn"
    IO.println s!"FPN NEU-DET inference dump (tower={tower}) — {dataDir} → {outDir}"
    inferDump spec dataDir outDir
  | _ =>
    let dataDir := args.head?.getD "data/neu_det_fpn"
    let epochs ← envNat "FPN_EPOCHS" baseCfg.epochs
    let ckptEvery ← envNat "FPN_CKPT_EVERY" baseCfg.checkpointEveryNEpochs
    let lrMult := (← envNat "FPN_LR_MULT" 1).toFloat
    let lr := baseCfg.learningRate * lrMult
    let clip := (← envNat "FPN_CLIP" 4).toFloat
    let aug ← envFlag "FPN_AUG" baseCfg.augment
    let noBoot ← envFlag "FPN_NOBOOTSTRAP" false
    let baseCfg := if noBoot then { baseCfg with bootstrapBackbone := none } else baseCfg
    let clsW ← clsWeightsFromEnv
    let clsGam := (← envNat "FPN_CLSFOCAL" 2).toFloat
    let affProb ← envPct "FPN_AFFINE" 50
    let affScale ← envPct "FPN_AFFINE_SCALE" 25
    let affTrans ← envPct "FPN_AFFINE_TRANSLATE" 10
    let cfg := { baseCfg with epochs := epochs,
                              checkpointEveryNEpochs := ckptEvery,
                              learningRate := lr,
                              gradClipNorm := clip,
                              augment := aug,
                              fpnAffineProb := affProb,
                              fpnAffineScale := affScale,
                              fpnAffineTranslate := affTrans,
                              yoloClsWeights := clsW,
                              yoloClsFocalGamma := clsGam }
    IO.println s!"FPN multi-scale NEU-DET (56/28/14, 3 anchors/scale, Ntot={neuNtot}, head tower={tower}) — data dir: {dataDir}"
    IO.println s!"  spec   : {spec.name}"
    IO.println s!"  epochs : {epochs}"
    IO.println s!"  lr     : {lr}  clip: {clip}"
    IO.println s!"  augment: {aug} (HSV jitter + hflip on the FPN path)"
    IO.println s!"  clsw   : {if clsW.isEmpty then "none" else toString clsW.length} weights, class focal γ={clsGam}"
    if affProb > 0.0 then
      IO.println s!"  affine : p={affProb} scale=±{affScale} translate=±{affTrans} (box-aware, target re-encoded)"
    else
      IO.println s!"  affine : off"
    IO.println s!"  bootstrap: {if noBoot then "OFF (FPN_NOBOOTSTRAP=1, He init)" else "ImageNet R34 prefix"}"
    spec.train cfg dataDir DatasetKind.detection

def main (args : List String) : IO Unit := runYolov1NeuDetFpn args
