import LeanMlir.Proofs.Architectures.MnistCNN

/-! # Trained-weight whole-network VJP witness — CNN rung

The `TrainedMlpWitness` program extended to a CONVOLUTIONAL net (the 2026-07
audit's gap #3): the Chapter-3 `mnistCnnNoBn` conditional whole-net VJP
(`mnistCnnNoBn_has_vjp_at`) instantiated at TRAINED, /128-rationalized
weights and a REAL test input, with every smoothness hypothesis discharged
by exact in-kernel rational arithmetic — inherited from training, not
engineered:

* h1/h2 — all 72+72 conv pre-activations are nonzero (`conv1_eq`/`conv2_eq`
  value tables + `c1_ne`/`c2_ne`);
* h_mp — every 2×2 max-pool window of relu(conv2) has four pairwise-distinct
  values (`r2_smooth`). ReLU zeros collide, so this needs ≤ 1 negative conv2
  pre-activation per window — trained in via a pool-tie margin regularizer
  (the h_mp analogue of the scorecard's spectral cap: the training method
  decides whether the hypotheses hold);
* h3/h4 — the dense pre-activations are nonzero (`d3_ne`/`d4_ne`).

Net: 24×24-center-cropped MNIST, 4×4-average-pooled to 6×6 (exact pixel sums
/4080), conv 1→2 3×3 SAME → relu → conv 2→2 3×3 SAME → relu → maxpool 2×2 →
dense 18→8 → relu → dense 8→8 → relu → dense 8→10. Float test acc
0.852, /128-quantized 0.850. Witness: test digit #0
(label 7, correctly classified).
Generated by `scripts/trained_cnn_witness.py`; weights/input are DATA here. -/

namespace Proofs
namespace TrainedCnn

-- ════════════════════════════════════════════════════════════════
-- § Trained weights and the witness input (data)
-- ════════════════════════════════════════════════════════════════

/-- Test image #0, 4×4-pooled 6×6, exact pixel sums /4080. -/
noncomputable def T0 : Tensor3 1 6 6 :=
  ![![![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)],
      ![(0 : ℝ), ((193 : ℝ)/408), ((116 : ℝ)/255), ((451 : ℝ)/1020), ((299 : ℝ)/816), (0 : ℝ)],
      ![(0 : ℝ), (0 : ℝ), ((97 : ℝ)/4080), ((137 : ℝ)/1360), ((2287 : ℝ)/4080), (0 : ℝ)],
      ![(0 : ℝ), (0 : ℝ), (0 : ℝ), ((573 : ℝ)/1360), ((283 : ℝ)/2040), (0 : ℝ)],
      ![(0 : ℝ), (0 : ℝ), ((517 : ℝ)/4080), ((701 : ℝ)/1360), (0 : ℝ), (0 : ℝ)],
      ![(0 : ℝ), (0 : ℝ), ((2809 : ℝ)/4080), ((13 : ℝ)/204), (0 : ℝ), (0 : ℝ)]]]

/-- The flattened witness input. -/
noncomputable def X : Vec (1 * (2*3) * (2*3)) := Tensor3.flatten T0

/-- conv1 kernel (1→2, 3×3), entries k/128. -/
noncomputable def W1 : Kernel4 2 1 3 3 :=
  ![![![![((67 : ℝ)/128), ((47 : ℝ)/128), ((125 : ℝ)/128)], ![((31 : ℝ)/64), ((133 : ℝ)/128), ((3 : ℝ)/4)], ![((-47 : ℝ)/64), ((-63 : ℝ)/128), ((-13 : ℝ)/128)]]],
   ![![![((-73 : ℝ)/64), ((181 : ℝ)/128), ((131 : ℝ)/128)], ![((-71 : ℝ)/32), ((-123 : ℝ)/64), ((-73 : ℝ)/64)], ![((43 : ℝ)/128), ((71 : ℝ)/128), ((17 : ℝ)/64)]]]]

noncomputable def b1 : Vec 2 := ![((9 : ℝ)/128), ((1 : ℝ)/128)]

/-- conv2 kernel (2→2, 3×3), entries k/128. -/
noncomputable def W2 : Kernel4 2 2 3 3 :=
  ![![![![((-7 : ℝ)/128), ((67 : ℝ)/64), ((13 : ℝ)/128)], ![((45 : ℝ)/64), ((13 : ℝ)/32), ((-47 : ℝ)/128)], ![((7 : ℝ)/64), ((21 : ℝ)/64), ((75 : ℝ)/128)]],
     ![![((-9 : ℝ)/64), ((-5 : ℝ)/64), ((-33 : ℝ)/128)], ![((-31 : ℝ)/64), ((-21 : ℝ)/128), ((19 : ℝ)/64)], ![((9 : ℝ)/32), ((17 : ℝ)/32), ((69 : ℝ)/128)]]],
   ![![![((-1 : ℝ)/64), ((-5 : ℝ)/16), ((-25 : ℝ)/128)], ![((119 : ℝ)/128), ((3 : ℝ)/8), ((37 : ℝ)/128)], ![((5 : ℝ)/64), ((-3 : ℝ)/128), ((-11 : ℝ)/128)]],
     ![![((71 : ℝ)/128), ((71 : ℝ)/64), ((67 : ℝ)/64)], ![((205 : ℝ)/128), ((41 : ℝ)/32), ((1 : ℝ)/128)], ![((5 : ℝ)/32), ((41 : ℝ)/128), ((-9 : ℝ)/32)]]]]

noncomputable def b2 : Vec 2 := ![((5 : ℝ)/16), ((19 : ℝ)/128)]

/-- dense3 (18→8, input×output). -/
noncomputable def W3 : Mat (2*3*3) 8 :=
  ![![((-41 : ℝ)/128), ((5 : ℝ)/64), ((-71 : ℝ)/128), ((199 : ℝ)/128), ((-19 : ℝ)/64), ((7 : ℝ)/128), ((-5 : ℝ)/8), ((-5 : ℝ)/16)],
    ![((-23 : ℝ)/128), ((-1 : ℝ)/8), ((63 : ℝ)/128), ((153 : ℝ)/128), ((51 : ℝ)/128), ((147 : ℝ)/128), ((-27 : ℝ)/128), ((-73 : ℝ)/128)],
    ![((-13 : ℝ)/32), ((23 : ℝ)/128), ((17 : ℝ)/16), ((23 : ℝ)/64), ((29 : ℝ)/64), ((9 : ℝ)/32), ((1 : ℝ)/64), ((3 : ℝ)/16)],
    ![((17 : ℝ)/128), ((101 : ℝ)/128), ((49 : ℝ)/32), ((-83 : ℝ)/128), ((-3 : ℝ)/32), ((-317 : ℝ)/128), ((99 : ℝ)/64), ((1 : ℝ)/8)],
    ![((185 : ℝ)/128), ((47 : ℝ)/128), ((-177 : ℝ)/128), (1 : ℝ), ((-9 : ℝ)/128), ((-11 : ℝ)/32), ((-13 : ℝ)/32), ((-29 : ℝ)/128)],
    ![((-95 : ℝ)/128), ((-7 : ℝ)/64), ((3 : ℝ)/16), ((111 : ℝ)/128), ((-43 : ℝ)/128), ((-113 : ℝ)/128), ((5 : ℝ)/16), ((25 : ℝ)/128)],
    ![((-27 : ℝ)/128), ((-59 : ℝ)/128), ((285 : ℝ)/128), ((-3 : ℝ)/128), ((-23 : ℝ)/128), ((15 : ℝ)/32), ((-245 : ℝ)/128), ((9 : ℝ)/128)],
    ![((67 : ℝ)/128), ((-65 : ℝ)/64), ((-27 : ℝ)/64), ((-97 : ℝ)/128), ((11 : ℝ)/64), ((97 : ℝ)/64), ((317 : ℝ)/128), ((17 : ℝ)/128)],
    ![((-5 : ℝ)/32), ((3 : ℝ)/128), ((-1 : ℝ)/8), ((-173 : ℝ)/128), ((1 : ℝ)/64), ((47 : ℝ)/128), ((-63 : ℝ)/64), ((-29 : ℝ)/128)],
    ![((21 : ℝ)/128), ((-3 : ℝ)/64), ((33 : ℝ)/128), ((9 : ℝ)/32), ((-33 : ℝ)/128), ((9 : ℝ)/128), ((55 : ℝ)/128), ((17 : ℝ)/64)],
    ![((-29 : ℝ)/128), ((137 : ℝ)/128), ((-11 : ℝ)/128), ((113 : ℝ)/64), ((-19 : ℝ)/32), ((81 : ℝ)/128), ((71 : ℝ)/128), ((5 : ℝ)/128)],
    ![((1 : ℝ)/8), ((41 : ℝ)/32), ((17 : ℝ)/128), ((15 : ℝ)/128), ((-61 : ℝ)/128), ((-53 : ℝ)/64), ((1 : ℝ)/8), ((25 : ℝ)/128)],
    ![((-145 : ℝ)/128), ((17 : ℝ)/128), ((-35 : ℝ)/64), ((-19 : ℝ)/128), (0 : ℝ), ((57 : ℝ)/128), ((15 : ℝ)/64), ((-3 : ℝ)/32)],
    ![((11 : ℝ)/32), ((9 : ℝ)/128), ((41 : ℝ)/128), ((-95 : ℝ)/128), ((-17 : ℝ)/128), ((-19 : ℝ)/64), ((-33 : ℝ)/128), ((-11 : ℝ)/128)],
    ![((-93 : ℝ)/128), ((-11 : ℝ)/64), ((-31 : ℝ)/64), ((-5 : ℝ)/128), ((17 : ℝ)/64), ((-45 : ℝ)/64), ((93 : ℝ)/128), ((5 : ℝ)/128)],
    ![((1 : ℝ)/64), ((41 : ℝ)/64), ((-69 : ℝ)/64), ((79 : ℝ)/128), ((-31 : ℝ)/64), ((-21 : ℝ)/64), ((-73 : ℝ)/128), ((-39 : ℝ)/128)],
    ![((3 : ℝ)/4), ((7 : ℝ)/128), ((-3 : ℝ)/16), ((-15 : ℝ)/128), ((-15 : ℝ)/128), ((55 : ℝ)/64), ((-27 : ℝ)/64), ((-23 : ℝ)/128)],
    ![((-51 : ℝ)/128), ((-45 : ℝ)/128), ((9 : ℝ)/8), ((-1 : ℝ)/128), ((-9 : ℝ)/128), ((99 : ℝ)/128), ((-241 : ℝ)/128), ((-25 : ℝ)/128)]]

noncomputable def b3 : Vec 8 := ![((93 : ℝ)/128), ((-3 : ℝ)/64), ((-53 : ℝ)/64), ((-1 : ℝ)/4), ((1 : ℝ)/4), ((1 : ℝ)/16), ((91 : ℝ)/128), ((3 : ℝ)/16)]

noncomputable def W4 : Mat 8 8 :=
  ![![((-15 : ℝ)/128), ((41 : ℝ)/128), ((15 : ℝ)/32), ((-9 : ℝ)/64), ((-19 : ℝ)/16), ((-15 : ℝ)/128), ((-49 : ℝ)/128), ((-7 : ℝ)/64)],
    ![((5 : ℝ)/128), ((39 : ℝ)/128), ((19 : ℝ)/32), ((11 : ℝ)/16), ((25 : ℝ)/32), ((53 : ℝ)/128), ((-45 : ℝ)/64), ((5 : ℝ)/32)],
    ![((-11 : ℝ)/128), ((-7 : ℝ)/16), ((-3 : ℝ)/64), ((5 : ℝ)/128), ((-5 : ℝ)/128), ((187 : ℝ)/128), ((-17 : ℝ)/128), ((-65 : ℝ)/128)],
    ![((-11 : ℝ)/64), ((1 : ℝ)/128), ((-7 : ℝ)/16), (1 : ℝ), ((33 : ℝ)/128), ((-19 : ℝ)/128), ((23 : ℝ)/32), ((-31 : ℝ)/128)],
    ![((-11 : ℝ)/64), ((-47 : ℝ)/128), ((39 : ℝ)/128), ((51 : ℝ)/128), ((-5 : ℝ)/16), ((-19 : ℝ)/64), ((-57 : ℝ)/128), ((-31 : ℝ)/128)],
    ![((-25 : ℝ)/32), ((-43 : ℝ)/64), ((85 : ℝ)/128), ((19 : ℝ)/128), ((67 : ℝ)/64), ((25 : ℝ)/128), ((131 : ℝ)/128), ((7 : ℝ)/128)],
    ![((-7 : ℝ)/64), ((103 : ℝ)/64), ((-29 : ℝ)/32), ((9 : ℝ)/128), ((33 : ℝ)/128), ((-17 : ℝ)/128), ((91 : ℝ)/128), ((-29 : ℝ)/128)],
    ![((25 : ℝ)/128), ((25 : ℝ)/128), ((-25 : ℝ)/128), ((3 : ℝ)/128), ((-1 : ℝ)/4), ((69 : ℝ)/128), ((-21 : ℝ)/128), ((-7 : ℝ)/64)]]

noncomputable def b4 : Vec 8 := ![((27 : ℝ)/128), ((31 : ℝ)/64), ((71 : ℝ)/64), ((-67 : ℝ)/128), ((25 : ℝ)/128), ((-49 : ℝ)/128), ((13 : ℝ)/128), ((33 : ℝ)/128)]

noncomputable def W5 : Mat 8 10 :=
  ![![((-31 : ℝ)/128), ((-5 : ℝ)/64), (0 : ℝ), ((11 : ℝ)/64), ((-17 : ℝ)/128), ((-5 : ℝ)/128), ((-5 : ℝ)/16), ((-3 : ℝ)/16), ((79 : ℝ)/128), ((15 : ℝ)/64)],
    ![((-173 : ℝ)/128), ((-23 : ℝ)/128), ((-29 : ℝ)/128), ((-103 : ℝ)/128), ((131 : ℝ)/128), ((-15 : ℝ)/64), ((-33 : ℝ)/128), ((61 : ℝ)/128), ((1 : ℝ)/16), ((89 : ℝ)/128)],
    ![((-29 : ℝ)/32), ((13 : ℝ)/128), ((3 : ℝ)/16), ((-5 : ℝ)/128), ((31 : ℝ)/128), ((1 : ℝ)/64), ((39 : ℝ)/128), ((-29 : ℝ)/64), ((-113 : ℝ)/128), ((-25 : ℝ)/64)],
    ![((73 : ℝ)/128), ((-25 : ℝ)/128), ((-15 : ℝ)/64), ((19 : ℝ)/16), ((-133 : ℝ)/128), ((83 : ℝ)/128), ((-111 : ℝ)/128), ((-7 : ℝ)/128), ((11 : ℝ)/64), ((45 : ℝ)/128)],
    ![((-11 : ℝ)/128), ((-51 : ℝ)/64), ((103 : ℝ)/128), ((-1 : ℝ)/2), ((-1 : ℝ)/8), ((-1 : ℝ)/16), ((-29 : ℝ)/128), ((107 : ℝ)/128), ((-15 : ℝ)/32), ((-17 : ℝ)/64)],
    ![((89 : ℝ)/128), ((-131 : ℝ)/128), ((3 : ℝ)/16), ((-11 : ℝ)/16), ((23 : ℝ)/128), ((13 : ℝ)/128), ((81 : ℝ)/128), ((-69 : ℝ)/128), ((61 : ℝ)/128), ((-11 : ℝ)/128)],
    ![((-35 : ℝ)/64), ((75 : ℝ)/64), ((7 : ℝ)/64), ((21 : ℝ)/64), ((-69 : ℝ)/128), ((-97 : ℝ)/128), ((-5 : ℝ)/64), ((-1 : ℝ)/16), ((23 : ℝ)/32), ((-21 : ℝ)/32)],
    ![((9 : ℝ)/64), ((-7 : ℝ)/128), ((11 : ℝ)/128), ((-5 : ℝ)/64), ((9 : ℝ)/128), ((-31 : ℝ)/128), ((17 : ℝ)/64), ((-49 : ℝ)/128), ((-15 : ℝ)/64), ((7 : ℝ)/128)]]

noncomputable def b5 : Vec 10 := ![((-49 : ℝ)/128), ((41 : ℝ)/32), ((-85 : ℝ)/128), ((-81 : ℝ)/128), ((123 : ℝ)/128), ((39 : ℝ)/32), ((7 : ℝ)/64), ((-31 : ℝ)/128), ((-151 : ℝ)/128), ((-15 : ℝ)/32)]

-- ════════════════════════════════════════════════════════════════
-- § Generic plumbing
-- ════════════════════════════════════════════════════════════════

/-- ReLU commutes with `Tensor3.flatten` (both are pointwise). -/
theorem relu_flatten {c h w : Nat} (T : Tensor3 c h w) :
    relu (c * h * w) (Tensor3.flatten T) =
      Tensor3.flatten (fun ci hi wi => if T ci hi wi > 0 then T ci hi wi else 0) := rfl

/-- A nowhere-zero tensor flattens to a nowhere-zero vector. -/
theorem flatten_ne_zero {c h w : Nat} {T : Tensor3 c h w}
    (hT : ∀ ci hi wi, T ci hi wi ≠ 0) (k : Fin (c * h * w)) :
    Tensor3.flatten T k ≠ 0 := hT _ _ _

-- ════════════════════════════════════════════════════════════════
-- § conv1: exact value table, nonzero, relu fold
-- ════════════════════════════════════════════════════════════════

/-- conv1 pre-activations at the witness, exact. -/
noncomputable def c1V : Fin 2 → Fin 6 → Fin 6 → ℝ :=
  ![![![((1163 : ℝ)/52224), ((-54499 : ℝ)/261120), ((-7127 : ℝ)/13056), ((-90277 : ℝ)/174080), ((-227041 : ℝ)/522240), ((-10381 : ℝ)/52224)],
      ![((925 : ℝ)/2176), ((31355 : ℝ)/34816), ((282479 : ℝ)/261120), ((78417 : ℝ)/87040), ((3431 : ℝ)/10880), ((-1337 : ℝ)/8160)],
      ![((27797 : ℝ)/52224), ((61457 : ℝ)/87040), ((127193 : ℝ)/130560), ((199103 : ℝ)/174080), ((180131 : ℝ)/261120), ((45095 : ℝ)/104448)],
      ![((9 : ℝ)/128), ((10531 : ℝ)/130560), ((24721 : ℝ)/65280), ((450287 : ℝ)/522240), ((1949 : ℝ)/6528), ((225041 : ℝ)/522240)],
      ![((9 : ℝ)/128), ((9967 : ℝ)/104448), ((341897 : ℝ)/522240), ((21959 : ℝ)/52224), ((284441 : ℝ)/522240), ((37321 : ℝ)/261120)],
      ![((9 : ℝ)/128), ((371009 : ℝ)/522240), ((240817 : ℝ)/174080), ((189469 : ℝ)/261120), ((193741 : ℝ)/522240), ((9 : ℝ)/128)]],
    ![![((205 : ℝ)/1536), ((102107 : ℝ)/261120), ((46697 : ℝ)/87040), ((131401 : ℝ)/261120), ((62599 : ℝ)/174080), ((13673 : ℝ)/104448)],
      ![((-13885 : ℝ)/26112), ((-7239 : ℝ)/5120), ((-1243139 : ℝ)/522240), ((-67123 : ℝ)/32640), ((-28999 : ℝ)/21760), ((-322159 : ℝ)/522240)],
      ![((25691 : ℝ)/52224), ((12133 : ℝ)/10880), ((134569 : ℝ)/261120), ((-129 : ℝ)/1024), ((-46161 : ℝ)/43520), ((-2623 : ℝ)/1632)],
      ![((1 : ℝ)/128), ((2291 : ℝ)/34816), ((-22429 : ℝ)/174080), ((499 : ℝ)/8704), ((-89491 : ℝ)/261120), ((-81761 : ℝ)/87040)],
      ![((1 : ℝ)/128), ((3013 : ℝ)/65280), ((13 : ℝ)/2040), ((-67777 : ℝ)/261120), ((-18263 : ℝ)/13056), ((-19639 : ℝ)/130560)],
      ![((1 : ℝ)/128), ((-112769 : ℝ)/174080), ((-7413 : ℝ)/10880), ((-110495 : ℝ)/104448), ((-188399 : ℝ)/261120), ((1 : ℝ)/128)]]]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r00 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r01 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r02 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r03 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r04 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r05 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨0, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi
      = c1V (⟨0, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r10 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r11 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r12 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r13 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r14 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem conv1_eq_r15 : ∀ wi : Fin 6,
    conv2d W1 b1 T0 (⟨1, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi
      = c1V (⟨1, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W1, b1, T0, c1V, Fin.sum_univ_succ]; try norm_num)

theorem conv1_eq : ∀ (o : Fin 2) (hi wi : Fin 6),
    conv2d W1 b1 T0 o hi wi = c1V o hi wi := by
  intro o hi wi
  fin_cases o <;> fin_cases hi
  · exact conv1_eq_r00 wi
  · exact conv1_eq_r01 wi
  · exact conv1_eq_r02 wi
  · exact conv1_eq_r03 wi
  · exact conv1_eq_r04 wi
  · exact conv1_eq_r05 wi
  · exact conv1_eq_r10 wi
  · exact conv1_eq_r11 wi
  · exact conv1_eq_r12 wi
  · exact conv1_eq_r13 wi
  · exact conv1_eq_r14 wi
  · exact conv1_eq_r15 wi

set_option maxRecDepth 16384 in
theorem c1_ne : ∀ (o : Fin 2) (hi wi : Fin 6), c1V o hi wi ≠ 0 := by
  intro o hi wi
  fin_cases o <;> fin_cases hi <;> fin_cases wi <;> norm_num [c1V]

/-- relu(conv1) at the witness, exact. -/
noncomputable def z1V : Tensor3 2 6 6 :=
  ![![![((1163 : ℝ)/52224), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)],
      ![((925 : ℝ)/2176), ((31355 : ℝ)/34816), ((282479 : ℝ)/261120), ((78417 : ℝ)/87040), ((3431 : ℝ)/10880), (0 : ℝ)],
      ![((27797 : ℝ)/52224), ((61457 : ℝ)/87040), ((127193 : ℝ)/130560), ((199103 : ℝ)/174080), ((180131 : ℝ)/261120), ((45095 : ℝ)/104448)],
      ![((9 : ℝ)/128), ((10531 : ℝ)/130560), ((24721 : ℝ)/65280), ((450287 : ℝ)/522240), ((1949 : ℝ)/6528), ((225041 : ℝ)/522240)],
      ![((9 : ℝ)/128), ((9967 : ℝ)/104448), ((341897 : ℝ)/522240), ((21959 : ℝ)/52224), ((284441 : ℝ)/522240), ((37321 : ℝ)/261120)],
      ![((9 : ℝ)/128), ((371009 : ℝ)/522240), ((240817 : ℝ)/174080), ((189469 : ℝ)/261120), ((193741 : ℝ)/522240), ((9 : ℝ)/128)]],
    ![![((205 : ℝ)/1536), ((102107 : ℝ)/261120), ((46697 : ℝ)/87040), ((131401 : ℝ)/261120), ((62599 : ℝ)/174080), ((13673 : ℝ)/104448)],
      ![(0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ)],
      ![((25691 : ℝ)/52224), ((12133 : ℝ)/10880), ((134569 : ℝ)/261120), (0 : ℝ), (0 : ℝ), (0 : ℝ)],
      ![((1 : ℝ)/128), ((2291 : ℝ)/34816), (0 : ℝ), ((499 : ℝ)/8704), (0 : ℝ), (0 : ℝ)],
      ![((1 : ℝ)/128), ((3013 : ℝ)/65280), ((13 : ℝ)/2040), (0 : ℝ), (0 : ℝ), (0 : ℝ)],
      ![((1 : ℝ)/128), (0 : ℝ), (0 : ℝ), (0 : ℝ), (0 : ℝ), ((1 : ℝ)/128)]]]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem z1_eq :
    (fun o hi wi => if c1V o hi wi > 0 then c1V o hi wi else 0) = z1V := by
  funext o hi wi
  fin_cases o <;> fin_cases hi <;> fin_cases wi <;>
    (simp [c1V, z1V]; try norm_num)

/-- First conv→relu block at the witness = the exact table. -/
theorem block1_eq :
    (relu (2 * (2*3) * (2*3)) ∘ flatConv (h := 2*3) (w := 2*3) W1 b1) X
      = Tensor3.flatten z1V := by
  show relu _ (flatConv W1 b1 (Tensor3.flatten T0)) = _
  rw [flatConv, Tensor3.unflatten_flatten, relu_flatten]
  congr 1
  funext o hi wi
  rw [conv1_eq]
  exact congrFun (congrFun (congrFun z1_eq o) hi) wi

-- ════════════════════════════════════════════════════════════════
-- § conv2: exact value table, nonzero, relu fold
-- ════════════════════════════════════════════════════════════════

/-- conv2 pre-activations at the witness, exact. -/
noncomputable def c2V : Fin 2 → Fin 6 → Fin 6 → ℝ :=
  ![![![((72389167 : ℝ)/66846720), ((44603411 : ℝ)/33423360), ((38965711 : ℝ)/33423360), ((1411183 : ℝ)/2088960), ((16753933 : ℝ)/66846720), ((3372051 : ℝ)/22282240)],
      ![((101435449 : ℝ)/66846720), ((2222167 : ℝ)/983040), ((9760537 : ℝ)/3932160), ((28702279 : ℝ)/13369344), ((1722301 : ℝ)/1114112), ((23080571 : ℝ)/33423360)],
      ![((38980519 : ℝ)/33423360), ((1163037 : ℝ)/696320), ((9013229 : ℝ)/4456448), ((5358817 : ℝ)/2228224), ((551529 : ℝ)/278528), ((12586611 : ℝ)/11141120)],
      ![((16504579 : ℝ)/22282240), ((20282509 : ℝ)/16711680), ((17602323 : ℝ)/11141120), ((55308603 : ℝ)/22282240), ((24946823 : ℝ)/13369344), ((40716743 : ℝ)/33423360)],
      ![((55225669 : ℝ)/66846720), ((44026307 : ℝ)/33423360), ((41892977 : ℝ)/22282240), ((75372937 : ℝ)/33423360), ((22135279 : ℝ)/16711680), ((41983391 : ℝ)/33423360)],
      ![((250201 : ℝ)/1671168), ((3286653 : ℝ)/11141120), ((121890647 : ℝ)/66846720), ((127178749 : ℝ)/66846720), ((2971943 : ℝ)/1966080), ((48160991 : ℝ)/66846720)]],
    ![![((5425413 : ℝ)/22282240), ((10792159 : ℝ)/13369344), ((15971989 : ℝ)/11141120), ((113073701 : ℝ)/66846720), ((32958333 : ℝ)/22282240), ((12255937 : ℝ)/13369344)],
      ![((11890975 : ℝ)/13369344), ((8334589 : ℝ)/3342336), ((109095671 : ℝ)/33423360), ((11348317 : ℝ)/3932160), ((130716427 : ℝ)/66846720), ((13872011 : ℝ)/16711680)],
      ![((57342689 : ℝ)/66846720), ((194146829 : ℝ)/66846720), ((37172403 : ℝ)/11141120), ((143712287 : ℝ)/66846720), ((101267417 : ℝ)/66846720), ((21390413 : ℝ)/22282240)],
      ![((3559057 : ℝ)/2228224), ((68244731 : ℝ)/33423360), ((11173129 : ℝ)/8355840), ((50640181 : ℝ)/66846720), ((8091829 : ℝ)/8355840), ((1004999 : ℝ)/2088960)],
      ![((1286063 : ℝ)/6684672), ((4796603 : ℝ)/13369344), ((15225037 : ℝ)/33423360), ((58258189 : ℝ)/66846720), ((4448839 : ℝ)/6684672), ((8006981 : ℝ)/13369344)],
      ![((13588097 : ℝ)/33423360), ((8868649 : ℝ)/11141120), ((5712643 : ℝ)/4456448), ((104909539 : ℝ)/66846720), ((649945 : ℝ)/835584), ((31854857 : ℝ)/66846720)]]]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r00 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r01 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r02 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r03 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r04 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r05 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨0, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi
      = c2V (⟨0, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r10 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r11 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r12 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r13 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨3, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r14 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨4, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem conv2_eq_r15 : ∀ wi : Fin 6,
    conv2d W2 b2 z1V (⟨1, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi
      = c2V (⟨1, by norm_num⟩ : Fin 2) (⟨5, by norm_num⟩ : Fin 6) wi := by
  intro wi
  fin_cases wi <;> (simp [conv2d, W2, b2, z1V, c2V, Fin.sum_univ_succ]; try norm_num)

theorem conv2_eq : ∀ (o : Fin 2) (hi wi : Fin 6),
    conv2d W2 b2 z1V o hi wi = c2V o hi wi := by
  intro o hi wi
  fin_cases o <;> fin_cases hi
  · exact conv2_eq_r00 wi
  · exact conv2_eq_r01 wi
  · exact conv2_eq_r02 wi
  · exact conv2_eq_r03 wi
  · exact conv2_eq_r04 wi
  · exact conv2_eq_r05 wi
  · exact conv2_eq_r10 wi
  · exact conv2_eq_r11 wi
  · exact conv2_eq_r12 wi
  · exact conv2_eq_r13 wi
  · exact conv2_eq_r14 wi
  · exact conv2_eq_r15 wi

set_option maxRecDepth 16384 in
theorem c2_ne : ∀ (o : Fin 2) (hi wi : Fin 6), c2V o hi wi ≠ 0 := by
  intro o hi wi
  fin_cases o <;> fin_cases hi <;> fin_cases wi <;> norm_num [c2V]

/-- relu(conv2) at the witness (the max-pool input), exact. -/
noncomputable def r2V : Tensor3 2 6 6 :=
  ![![![((72389167 : ℝ)/66846720), ((44603411 : ℝ)/33423360), ((38965711 : ℝ)/33423360), ((1411183 : ℝ)/2088960), ((16753933 : ℝ)/66846720), ((3372051 : ℝ)/22282240)],
      ![((101435449 : ℝ)/66846720), ((2222167 : ℝ)/983040), ((9760537 : ℝ)/3932160), ((28702279 : ℝ)/13369344), ((1722301 : ℝ)/1114112), ((23080571 : ℝ)/33423360)],
      ![((38980519 : ℝ)/33423360), ((1163037 : ℝ)/696320), ((9013229 : ℝ)/4456448), ((5358817 : ℝ)/2228224), ((551529 : ℝ)/278528), ((12586611 : ℝ)/11141120)],
      ![((16504579 : ℝ)/22282240), ((20282509 : ℝ)/16711680), ((17602323 : ℝ)/11141120), ((55308603 : ℝ)/22282240), ((24946823 : ℝ)/13369344), ((40716743 : ℝ)/33423360)],
      ![((55225669 : ℝ)/66846720), ((44026307 : ℝ)/33423360), ((41892977 : ℝ)/22282240), ((75372937 : ℝ)/33423360), ((22135279 : ℝ)/16711680), ((41983391 : ℝ)/33423360)],
      ![((250201 : ℝ)/1671168), ((3286653 : ℝ)/11141120), ((121890647 : ℝ)/66846720), ((127178749 : ℝ)/66846720), ((2971943 : ℝ)/1966080), ((48160991 : ℝ)/66846720)]],
    ![![((5425413 : ℝ)/22282240), ((10792159 : ℝ)/13369344), ((15971989 : ℝ)/11141120), ((113073701 : ℝ)/66846720), ((32958333 : ℝ)/22282240), ((12255937 : ℝ)/13369344)],
      ![((11890975 : ℝ)/13369344), ((8334589 : ℝ)/3342336), ((109095671 : ℝ)/33423360), ((11348317 : ℝ)/3932160), ((130716427 : ℝ)/66846720), ((13872011 : ℝ)/16711680)],
      ![((57342689 : ℝ)/66846720), ((194146829 : ℝ)/66846720), ((37172403 : ℝ)/11141120), ((143712287 : ℝ)/66846720), ((101267417 : ℝ)/66846720), ((21390413 : ℝ)/22282240)],
      ![((3559057 : ℝ)/2228224), ((68244731 : ℝ)/33423360), ((11173129 : ℝ)/8355840), ((50640181 : ℝ)/66846720), ((8091829 : ℝ)/8355840), ((1004999 : ℝ)/2088960)],
      ![((1286063 : ℝ)/6684672), ((4796603 : ℝ)/13369344), ((15225037 : ℝ)/33423360), ((58258189 : ℝ)/66846720), ((4448839 : ℝ)/6684672), ((8006981 : ℝ)/13369344)],
      ![((13588097 : ℝ)/33423360), ((8868649 : ℝ)/11141120), ((5712643 : ℝ)/4456448), ((104909539 : ℝ)/66846720), ((649945 : ℝ)/835584), ((31854857 : ℝ)/66846720)]]]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2_eq :
    (fun o hi wi => if c2V o hi wi > 0 then c2V o hi wi else 0) = r2V := by
  funext o hi wi
  fin_cases o <;> fin_cases hi <;> fin_cases wi <;>
    (simp [c2V, r2V]; try norm_num)

/-- Both conv→relu blocks fold to the exact max-pool input table. -/
theorem blockZ_eq :
    ((relu (2 * (2*3) * (2*3)) ∘ flatConv (h := 2*3) (w := 2*3) W2 b2)
      ∘ (relu (2 * (2*3) * (2*3)) ∘ flatConv (h := 2*3) (w := 2*3) W1 b1)) X
      = Tensor3.flatten r2V := by
  rw [Function.comp_apply, block1_eq]
  show relu _ (flatConv W2 b2 (Tensor3.flatten z1V)) = _
  rw [flatConv, Tensor3.unflatten_flatten, relu_flatten]
  congr 1
  funext o hi wi
  rw [conv2_eq]
  exact congrFun (congrFun (congrFun r2_eq o) hi) wi

-- ════════════════════════════════════════════════════════════════
-- § MaxPool: no ties at the witness (trained, not engineered)
-- ════════════════════════════════════════════════════════════════

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c0h0 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨0, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨0, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c0h1 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨1, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨1, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c0h2 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨2, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨0, by norm_num⟩ : Fin 2) (winRowInv (⟨2, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c1h0 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨0, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨0, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c1h1 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨1, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨1, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r2sm_c1h2 : ∀ (wo : Fin 3) (ab ab' : Fin 2 × Fin 2), ab ≠ ab' →
    r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨2, by norm_num⟩ : Fin 3) ab.1) (winColInv wo ab.2)
      ≠ r2V (⟨1, by norm_num⟩ : Fin 2) (winRowInv (⟨2, by norm_num⟩ : Fin 3) ab'.1) (winColInv wo ab'.2) := by
  rintro wo ⟨a, b⟩ ⟨a', b'⟩ hne
  fin_cases wo <;> fin_cases a <;> fin_cases b <;> fin_cases a' <;> fin_cases b' <;>
    first
      | exact absurd rfl hne
      | (simp [r2V, winRowInv, winColInv]; try norm_num)

/-- **Every 2×2 window of relu(conv2) has pairwise-distinct values** —
    the `MaxPool2Smooth` hypothesis, discharged from the trained tables. -/
theorem r2_smooth : MaxPool2Smooth (c := 2) (h := 3) (w := 3) r2V := by
  intro ci ho wo ab ab' hne
  fin_cases ci <;> fin_cases ho
  · exact r2sm_c0h0 wo ab ab' hne
  · exact r2sm_c0h1 wo ab ab' hne
  · exact r2sm_c0h2 wo ab ab' hne
  · exact r2sm_c1h0 wo ab ab' hne
  · exact r2sm_c1h1 wo ab ab' hne
  · exact r2sm_c1h2 wo ab ab' hne

-- ════════════════════════════════════════════════════════════════
-- § Pooled vector and the dense head
-- ════════════════════════════════════════════════════════════════

/-- The pooled feature vector (flattened maxpool output), exact. -/
noncomputable def p2f : Vec (2 * 3 * 3) := ![((2222167 : ℝ)/983040), ((9760537 : ℝ)/3932160), ((1722301 : ℝ)/1114112), ((1163037 : ℝ)/696320), ((55308603 : ℝ)/22282240), ((551529 : ℝ)/278528), ((44026307 : ℝ)/33423360), ((75372937 : ℝ)/33423360), ((2971943 : ℝ)/1966080), ((8334589 : ℝ)/3342336), ((109095671 : ℝ)/33423360), ((130716427 : ℝ)/66846720), ((194146829 : ℝ)/66846720), ((37172403 : ℝ)/11141120), ((101267417 : ℝ)/66846720), ((8868649 : ℝ)/11141120), ((104909539 : ℝ)/66846720), ((649945 : ℝ)/835584)]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem pooled_eq :
    maxPoolFlat 2 3 3 (Tensor3.flatten r2V) = p2f := by
  show Tensor3.flatten (maxPool2 (Tensor3.unflatten (Tensor3.flatten r2V))) = p2f
  rw [Tensor3.unflatten_flatten]
  funext i
  fin_cases i
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((2222167 : ℝ)/983040)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((9760537 : ℝ)/3932160)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((1722301 : ℝ)/1114112)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((1163037 : ℝ)/696320)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((55308603 : ℝ)/22282240)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((551529 : ℝ)/278528)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((44026307 : ℝ)/33423360)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((75372937 : ℝ)/33423360)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨0, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((2971943 : ℝ)/1966080)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((8334589 : ℝ)/3342336)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((109095671 : ℝ)/33423360)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨0, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((130716427 : ℝ)/66846720)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((194146829 : ℝ)/66846720)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((37172403 : ℝ)/11141120)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨1, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((101267417 : ℝ)/66846720)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨0, by norm_num⟩ : Fin 3)
        = ((8868649 : ℝ)/11141120)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨1, by norm_num⟩ : Fin 3)
        = ((104909539 : ℝ)/66846720)
    simp [maxPool2, r2V, max_def]
    try norm_num
  · show maxPool2 (c := 2) (h := 3) (w := 3) r2V (⟨1, by norm_num⟩ : Fin 2) (⟨2, by norm_num⟩ : Fin 3) (⟨2, by norm_num⟩ : Fin 3)
        = ((649945 : ℝ)/835584)
    simp [maxPool2, r2V, max_def]
    try norm_num

/-- dense3 pre-activations at the witness, exact. -/
noncomputable def d3V : Fin 8 → ℝ := ![((-2206362251 : ℝ)/4278190080), ((3315505013 : ℝ)/570425344), ((663167541 : ℝ)/570425344), ((86836255423 : ℝ)/8556380160), ((-2660411417 : ℝ)/713031680), ((12288523033 : ℝ)/4278190080), ((4316132003 : ℝ)/1069547520), ((-13402606799 : ℝ)/8556380160)]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem d3_eq : ∀ k, dense W3 b3 p2f k = d3V k := by
  intro k
  fin_cases k <;> (simp [dense, W3, b3, p2f, d3V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
theorem d3_ne : ∀ k, dense W3 b3 p2f k ≠ 0 := by
  intro k
  rw [d3_eq]
  fin_cases k <;> norm_num [d3V]

/-- relu(dense3) at the witness, exact. -/
noncomputable def r3V : Vec 8 := ![(0 : ℝ), ((3315505013 : ℝ)/570425344), ((663167541 : ℝ)/570425344), ((86836255423 : ℝ)/8556380160), (0 : ℝ), ((12288523033 : ℝ)/4278190080), ((4316132003 : ℝ)/1069547520), (0 : ℝ)]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem r3_eq : relu 8 (dense W3 b3 p2f) = r3V := by
  funext k
  show (if dense W3 b3 p2f k > 0 then dense W3 b3 p2f k else 0) = r3V k
  rw [d3_eq]
  fin_cases k <;> (simp [d3V, r3V]; try norm_num)

/-- dense4 pre-activations at the witness, exact. -/
noncomputable def d4V : Fin 8 → ℝ := ![((-1120311628553 : ℝ)/273804165120), ((51464713991 : ℝ)/8053063680), ((-461038817003 : ℝ)/273804165120), ((15745692785629 : ℝ)/1095216660480), ((310895222713 : ℝ)/27380416512), ((490858431241 : ℝ)/219043332096), ((9816866083321 : ℝ)/1095216660480), ((-1445401761821 : ℝ)/547608330240)]

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem d4_eq : ∀ k, dense W4 b4 r3V k = d4V k := by
  intro k
  fin_cases k <;> (simp [dense, W4, b4, r3V, d4V, Fin.sum_univ_succ]; try norm_num)

set_option maxRecDepth 16384 in
theorem d4_ne : ∀ k, dense W4 b4 r3V k ≠ 0 := by
  intro k
  rw [d4_eq]
  fin_cases k <;> norm_num [d4V]

-- ════════════════════════════════════════════════════════════════
-- § The capstone: trained-weight whole-net CNN VJP witness
-- ════════════════════════════════════════════════════════════════

/-- **Level 1: the trained-weight whole-net CNN VJP witness** —
    `HasVJPAt (mnistCnnNoBnForward …) X` with every one of the five
    smoothness hypotheses discharged at the trained weights and the real
    test input. The convolutional sibling of `trainedMlp_has_vjp_at`. -/
noncomputable def trainedCnn_has_vjp_at :
    HasVJPAt (mnistCnnNoBnForward W1 b1 W2 b2 W3 b3 W4 b4 W5 b5) X :=
  mnistCnnNoBn_has_vjp_at W1 b1 W2 b2 W3 b3 W4 b4 W5 b5
    (by norm_num) (by norm_num) (by norm_num) X
    -- h1: conv1 pre-activations nonzero
    (by intro k
        have he : flatConv (h := 2*3) (w := 2*3) W1 b1 X
            = Tensor3.flatten (conv2d W1 b1 T0) := by
          show flatConv W1 b1 (Tensor3.flatten T0) = _
          rw [flatConv, Tensor3.unflatten_flatten]
        rw [he]
        exact flatten_ne_zero
          (fun o hi wi => by rw [conv1_eq]; exact c1_ne o hi wi) k)
    -- h2: conv2 pre-activations nonzero
    (by intro k
        rw [block1_eq]
        have he : flatConv (h := 2*3) (w := 2*3) W2 b2 (Tensor3.flatten z1V)
            = Tensor3.flatten (conv2d W2 b2 z1V) := by
          rw [flatConv, Tensor3.unflatten_flatten]
        rw [he]
        exact flatten_ne_zero
          (fun o hi wi => by rw [conv2_eq]; exact c2_ne o hi wi) k)
    -- h_mp: no max-pool ties
    (by rw [blockZ_eq, Tensor3.unflatten_flatten]
        exact r2_smooth)
    -- h3: dense3 pre-activations nonzero
    (by intro k
        rw [blockZ_eq, pooled_eq]
        exact d3_ne k)
    -- h4: dense4 pre-activations nonzero
    (by intro k
        rw [blockZ_eq, pooled_eq, Function.comp_apply, r3_eq]
        exact d4_ne k)

/-- The witness's contract, exposed: the whole-net backward equals the
    `pdiv`-contracted Jacobian at the trained weights and real input. -/
theorem trainedCnn_has_vjp_correct (dy : Vec 10) (i : Fin (1 * (2*3) * (2*3))) :
    trainedCnn_has_vjp_at.backward dy i =
      ∑ j : Fin 10,
        pdiv (mnistCnnNoBnForward W1 b1 W2 b2 W3 b3 W4 b4 W5 b5) X i j * dy j :=
  trainedCnn_has_vjp_at.correct dy i

end TrainedCnn
end Proofs
