import LeanMlir.Proofs.Certificates.IbpConvScorecard.Net

/-! # Conv IBP scorecard, image chunk A — test images #0, #1

Per-image `CertifiedAtLinf3` theorems for the conv net of
`IbpConvScorecard.Net`: each image's exact data and one kernel check of
its box at the largest certifying radius; smaller radii follow by `.mono`.
The aggregate lives in `IbpConvScorecard.Basic`. Generated by
`scripts/certs/ibp_conv_scorecard.py`. -/

namespace Proofs
namespace IBP
namespace ConvNet

-- ═══════════════ MNIST test image #0 (label 7) ═══════════════
/-- MNIST test image #0, pooled to 8×8, exact. -/
def img0Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((193:ℚ)/408), ((116:ℚ)/255), ((451:ℚ)/1020), ((299:ℚ)/816), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((97:ℚ)/4080), ((137:ℚ)/1360), ((2287:ℚ)/4080), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((573:ℚ)/1360), ((283:ℚ)/2040), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((517:ℚ)/4080), ((701:ℚ)/1360), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((2809:ℚ)/4080), ((13:ℚ)/204), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((5:ℚ)/34), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img0 : Tensor3 1 8 8 := castT img0Q

/-- **Certified at ε = 8/255** (MNIST test image #0, class 7): EVERY
    pixel-`L∞` perturbation of size ≤ 8/255 leaves class 7 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert0e8 : CertifiedAtLinf3 net ((8:ℝ)/255) img0 7 := by
  simpa [img0] using net_certified_of_check img0Q ((8:ℚ)/255) 7 (by decide +kernel)

/-- Certified at ε = 1/255 (image #0) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert0e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img0 7 :=
  cert0e8.mono (by norm_num)

/-- Certified at ε = 2/255 (image #0) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert0e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img0 7 :=
  cert0e8.mono (by norm_num)

/-- Certified at ε = 4/255 (image #0) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert0e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img0 7 :=
  cert0e8.mono (by norm_num)

-- ═══════════════ MNIST test image #1 (label 2) ═══════════════
/-- MNIST test image #1, pooled to 8×8, exact. -/
def img1Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((197:ℚ)/1360), ((127:ℚ)/204), ((257:ℚ)/510), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((571:ℚ)/2040), ((33:ℚ)/340), ((927:ℚ)/1360), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((177:ℚ)/340), ((115:ℚ)/408), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((57:ℚ)/340), ((329:ℚ)/510), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((193:ℚ)/408), ((1319:ℚ)/2040), ((937:ℚ)/2040), ((2009:ℚ)/4080), ((753:ℚ)/1360), ((19:ℚ)/408)],
     ![(0:ℚ), (0:ℚ), ((59:ℚ)/2040), ((107:ℚ)/816), ((457:ℚ)/2040), ((287:ℚ)/4080), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img1 : Tensor3 1 8 8 := castT img1Q

/-- **Certified at ε = 4/255** (MNIST test image #1, class 2): EVERY
    pixel-`L∞` perturbation of size ≤ 4/255 leaves class 2 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert1e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img1 2 := by
  simpa [img1] using net_certified_of_check img1Q ((4:ℚ)/255) 2 (by decide +kernel)

/-- Certified at ε = 1/255 (image #1) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert1e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img1 2 :=
  cert1e4.mono (by norm_num)

/-- Certified at ε = 2/255 (image #1) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert1e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img1 2 :=
  cert1e4.mono (by norm_num)

end ConvNet
end IBP
end Proofs
