import LeanMlir.Proofs.Certificates.IbpConvScorecard.Net

/-! # Conv IBP scorecard, image chunk B — test images #2, #3

Per-image `CertifiedAtLinf3` theorems for the conv net of
`IbpConvScorecard.Net`: each image's exact data and one kernel check of
its box at the largest certifying radius; smaller radii follow by `.mono`.
The aggregate lives in `IbpConvScorecard.Basic`. Generated by
`scripts/certs/ibp_conv_scorecard.py`. -/

namespace Proofs
namespace IBP
namespace ConvNet

-- ═══════════════ MNIST test image #2 (label 1) ═══════════════
/-- MNIST test image #2, pooled to 8×8, exact. -/
def img2Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((631:ℚ)/4080), ((191:ℚ)/4080), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((413:ℚ)/1020), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((19:ℚ)/1360), ((1967:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((185:ℚ)/816), ((1129:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((2053:ℚ)/4080), ((277:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((989:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img2 : Tensor3 1 8 8 := castT img2Q

/-- **Certified at ε = 8/255** (MNIST test image #2, class 1): EVERY
    pixel-`L∞` perturbation of size ≤ 8/255 leaves class 1 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert2e8 : CertifiedAtLinf3 net ((8:ℝ)/255) img2 1 := by
  simpa [img2] using net_certified_of_check img2Q ((8:ℚ)/255) 1 (by decide +kernel)

/-- Certified at ε = 1/255 (image #2) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert2e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img2 1 :=
  cert2e8.mono (by norm_num)

/-- Certified at ε = 2/255 (image #2) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert2e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img2 1 :=
  cert2e8.mono (by norm_num)

/-- Certified at ε = 4/255 (image #2) — the radius-8/255
    certificate restricted; no second box. -/
theorem cert2e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img2 1 :=
  cert2e8.mono (by norm_num)

-- ═══════════════ MNIST test image #3 (label 0) ═══════════════
/-- MNIST test image #3, pooled to 8×8, exact. -/
def img3Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((449:ℚ)/4080), ((1097:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((91:ℚ)/2040), ((1097:ℚ)/1360), ((3361:ℚ)/4080), ((839:ℚ)/4080), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((469:ℚ)/1020), ((853:ℚ)/1360), ((91:ℚ)/816), ((179:ℚ)/240), ((5:ℚ)/272), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((2623:ℚ)/4080), (0:ℚ), ((479:ℚ)/4080), ((671:ℚ)/816), ((229:ℚ)/4080), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((257:ℚ)/408), ((2639:ℚ)/4080), ((1199:ℚ)/1360), ((1631:ℚ)/4080), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((1:ℚ)/20), ((419:ℚ)/1020), ((49:ℚ)/255), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img3 : Tensor3 1 8 8 := castT img3Q

/-- **Certified at ε = 4/255** (MNIST test image #3, class 0): EVERY
    pixel-`L∞` perturbation of size ≤ 4/255 leaves class 0 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert3e4 : CertifiedAtLinf3 net ((4:ℝ)/255) img3 0 := by
  simpa [img3] using net_certified_of_check img3Q ((4:ℚ)/255) 0 (by decide +kernel)

/-- Certified at ε = 1/255 (image #3) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert3e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img3 0 :=
  cert3e4.mono (by norm_num)

/-- Certified at ε = 2/255 (image #3) — the radius-4/255
    certificate restricted; no second box. -/
theorem cert3e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img3 0 :=
  cert3e4.mono (by norm_num)

end ConvNet
end IBP
end Proofs
