import LeanMlir.Proofs.Certificates.IbpConvScorecard.Net

/-! # Conv IBP scorecard, image chunk D — test images #8, #9

Per-image `CertifiedAtLinf3` theorems for the conv net of
`IbpConvScorecard.Net`: each image's exact data and one kernel check of
its box at the largest certifying radius; smaller radii follow by `.mono`.
The aggregate lives in `IbpConvScorecard.Basic`. Generated by
`scripts/certs/ibp_conv_scorecard.py`. -/

namespace Proofs
namespace IBP
namespace ConvNet

-- ═══════════════ MNIST test image #8 (label 5) ═══════════════
/-- MNIST test image #8, pooled to 8×8, exact. -/
def img8Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), ((77:ℚ)/680), ((377:ℚ)/1360), ((1013:ℚ)/4080), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((311:ℚ)/2040), ((97:ℚ)/408), ((2803:ℚ)/4080), ((667:ℚ)/1360), ((423:ℚ)/1360), (0:ℚ)],
     ![(0:ℚ), ((127:ℚ)/2040), ((711:ℚ)/1360), ((1:ℚ)/408), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), ((631:ℚ)/4080), ((1147:ℚ)/1360), ((617:ℚ)/1020), ((55:ℚ)/102), ((2:ℚ)/15), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((67:ℚ)/4080), ((159:ℚ)/272), ((211:ℚ)/240), ((481:ℚ)/1360), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((203:ℚ)/4080), ((1097:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img8 : Tensor3 1 8 8 := castT img8Q

/-- **Certified at ε = 2/255** (MNIST test image #8, class 5): EVERY
    pixel-`L∞` perturbation of size ≤ 2/255 leaves class 5 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert8e2 : CertifiedAtLinf3 net ((2:ℝ)/255) img8 5 := by
  simpa [img8] using net_certified_of_check img8Q ((2:ℚ)/255) 5 (by decide +kernel)

/-- Certified at ε = 1/255 (image #8) — the radius-2/255
    certificate restricted; no second box. -/
theorem cert8e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img8 5 :=
  cert8e2.mono (by norm_num)

-- ═══════════════ MNIST test image #9 (label 9) ═══════════════
/-- MNIST test image #9, pooled to 8×8, exact. -/
def img9Q : Fin 1 → Fin 8 → Fin 8 → ℚ :=
  ![![![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((23:ℚ)/2040), ((57:ℚ)/170), ((1193:ℚ)/2040), ((953:ℚ)/2040), ((11:ℚ)/408), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((2617:ℚ)/4080), ((311:ℚ)/680), ((1421:ℚ)/4080), ((97:ℚ)/120), ((377:ℚ)/2040), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((49:ℚ)/240), ((53:ℚ)/120), ((3737:ℚ)/4080), ((3:ℚ)/10), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), (0:ℚ), ((115:ℚ)/204), ((1741:ℚ)/4080), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((263:ℚ)/2040), ((977:ℚ)/1360), ((1:ℚ)/510), (0:ℚ), (0:ℚ), (0:ℚ)],
     ![(0:ℚ), (0:ℚ), ((113:ℚ)/4080), ((121:ℚ)/1360), (0:ℚ), (0:ℚ), (0:ℚ), (0:ℚ)]]]

noncomputable def img9 : Tensor3 1 8 8 := castT img9Q

/-- **Certified at ε = 1/255** (MNIST test image #9, class 9): EVERY
    pixel-`L∞` perturbation of size ≤ 1/255 leaves class 9 the strict argmax of
    the conv net — conv, max-pool and a dense head, four layers. One kernel
    evaluation of the exact box. -/
theorem cert9e1 : CertifiedAtLinf3 net ((1:ℝ)/255) img9 9 := by
  simpa [img9] using net_certified_of_check img9Q ((1:ℚ)/255) 9 (by decide +kernel)

end ConvNet
end IBP
end Proofs
