import LeanMlir.Proofs.LipschitzCertScorecard
import LeanMlir.Proofs.FloatBridge

/-! # The robustness certificate composed with the float bridge

**REDUCED CERTIFICATE MODEL** — this file's concrete net is the 4×4-pooled 49-dim
MNIST family (width-8 hidden, /128–/256 rational weights), NOT the canonical
784→512→512→10 `mlpVerified`; chosen so every margin/norm/SOS check is exact rational
arithmetic in-kernel. Canonical surface: `Proofs/MlpCanonical.lean`.

The 2026-07-02 audit's gap #1, closed: the scorecard's per-image Lipschitz-
margin certificates (`LipschitzCertScorecard.lean`, exact-ℝ net) composed with
the FloatBridge forward budgets, certifying the FLOAT-EVALUATED capped net.

For each image below: for **every** L2 perturbation `‖δ‖ < ε = 1/10` and
**every** rounded input `y` within `u32·(11/10)` of `img + δ` coordinatewise
(covering input quantization), the rounded two-layer forward `M.mlp2F` — for
**any** rounding model `M` at binary32 accuracy or better (`M.u ≤ u32`) —
keeps the true class the strict argmax.

The composition is pure margin arithmetic (`certified_at_eps_close`): the
Tsuzuku gap at `img + δ` is at least `m − √2·L·ε`; the 2-layer float budget
`B ≤ ((14899 : ℝ)/2500000)` (γ-form `layerBudget` chain at the capped net's exact
magnitude bounds `|W1s| ≤ ((475 : ℝ)/256)`, `|W2s| ≤ ((129 : ℝ)/64)`, inputs `≤ 11/10`)
perturbs each logit by at most `B`, so any margin clearing
`(14143/10000)·L·ε + 2·B ≈ 2.8066` (vs the ℝ-only threshold
`≈ 2.7947`) keeps the float argmax:
**33/34** of the ℝ-certified images survive the float widening
(dropped: [41]).

What this does NOT close (unchanged trust boundary, `Binary32Instance.lean`):
the kernel↔model gap — FMA contraction, reduction reassociation, "the GPU
rounds like `rndP`" — and `rndP`'s overflow/subnormal idealization.

Generated by `scripts/lipschitz_cert_float.py` from the committed scorecard
data; weights/images/margins are DATA here. -/

namespace Proofs

-- ════════════════════════════════════════════════════════════════
-- § The rounded two-layer MLP forward and its uniform budget
-- ════════════════════════════════════════════════════════════════

namespace FloatModel

variable (M : FloatModel)

/-- The rounded 2-layer MLP forward: rounded dense, bare (exact) relu,
    rounded dense — the 2-layer face of `mlpF`. -/
noncomputable def mlp2F {d₀ d₁ d₂ : Nat}
    (W₀ : Mat d₀ d₁) (b₀ : Vec d₁) (W₁ : Mat d₁ d₂) (b₁ : Vec d₂)
    (x : Vec d₀) : Vec d₂ :=
  M.dense W₁ b₁ (relu d₁ (M.dense W₀ b₀ x))

/-- **2-layer MLP forward error, uniform budgets, quantized input.** If the
    device input `y` is within `ein` of the real input `x` coordinatewise
    (input quantization), every rounded logit is within the closed-form
    2-layer `layerBudget` chain of the exact-ℝ logit. The 2-layer face of
    `mlp_float_close_uniform`, with the fresh-input `e = 0` generalized to
    `e = ein`. -/
theorem mlp2_float_close_uniform {d₀ d₁ d₂ : Nat}
    {W₀ : Mat d₀ d₁} {b₀ : Vec d₁} {W₁ : Mat d₁ d₂} {b₁ : Vec d₂}
    {x y : Vec d₀} {w₀ β₀ w₁ β₁ a ein : ℝ}
    (hw₀ : 0 ≤ w₀) (hβ₀ : 0 ≤ β₀) (hw₁ : 0 ≤ w₁) (ha : 0 ≤ a)
    (hein : 0 ≤ ein)
    (hW₀ : ∀ i j, |W₀ i j| ≤ w₀) (hb₀ : ∀ j, |b₀ j| ≤ β₀)
    (hW₁ : ∀ i j, |W₁ i j| ≤ w₁) (hb₁ : ∀ j, |b₁ j| ≤ β₁)
    (hx : ∀ i, |x i| ≤ a) (hy : ∀ i, |y i - x i| ≤ ein) (k : Fin d₂) :
    |M.mlp2F W₀ b₀ W₁ b₁ y k -
        Proofs.dense W₁ b₁ (relu d₁ (Proofs.dense W₀ b₀ x)) k| ≤
      layerBudget M.u d₁ w₁ β₁ (layerAct d₀ w₀ β₀ a)
        (layerBudget M.u d₀ w₀ β₀ a ein) := by
  have hE₀0 : 0 ≤ layerBudget M.u d₀ w₀ β₀ a ein :=
    layerBudget_nonneg M.u_nonneg hw₀ hβ₀ ha hein
  -- layer 0 at the quantized input, uniformized
  have l0 : ∀ j, |M.dense W₀ b₀ y j - Proofs.dense W₀ b₀ x j| ≤
      layerBudget M.u d₀ w₀ β₀ a ein :=
    fun j => (M.dense_close W₀ b₀ y x ein hein hy j).trans
      (M.denseErr_le_uniform hw₀ hein hW₀ hb₀ hx j)
  -- relu: exact pass-through
  have r0 : ∀ j, |relu d₁ (M.dense W₀ b₀ y) j -
      relu d₁ (Proofs.dense W₀ b₀ x) j| ≤ layerBudget M.u d₀ w₀ β₀ a ein :=
    fun j => relu_close _ _ _ l0 j
  -- layer 1 with the inherited error; real hidden magnitude ≤ layerAct
  have ha₁ : ∀ i, |relu d₁ (Proofs.dense W₀ b₀ x) i| ≤ layerAct d₀ w₀ β₀ a :=
    fun i => (relu_abs_le _ i).trans (dense_abs_le ha hW₀ hb₀ hx i)
  exact (M.dense_close W₁ b₁ _ _ _ hE₀0 r0 k).trans
    (M.denseErr_le_uniform hw₁ hE₀0 hW₁ hb₁ ha₁ k)

end FloatModel

namespace LipschitzCertDemo

open scoped BigOperators
open FloatModel

-- ════════════════════════════════════════════════════════════════
-- § Generic pieces: coordinate bound, budget monotonicity, composition
-- ════════════════════════════════════════════════════════════════

/-- A single coordinate is bounded by the L2 norm. -/
theorem coord_abs_le_norm {n : ℕ} (v : EuclideanSpace ℝ (Fin n)) (c : Fin n) :
    |v c| ≤ ‖v‖ := by
  have h : (v c) ^ 2 ≤ ‖v‖ ^ 2 := by
    rw [euclid_norm_sq]
    exact Finset.single_le_sum (f := fun l => (v l) ^ 2)
      (fun l _ => sq_nonneg _) (Finset.mem_univ c)
  calc |v c| = Real.sqrt ((v c) ^ 2) := (Real.sqrt_sq_eq_abs _).symm
    _ ≤ Real.sqrt (‖v‖ ^ 2) := Real.sqrt_le_sqrt h
    _ = ‖v‖ := Real.sqrt_sq (norm_nonneg v)

/-- Replacing the γ-factor and the inherited error by upper bounds bounds
    `layerBudget` (public copy of the bridge-internal monotonicity step). -/
theorem layerBudget_le_of' {u : ℝ} {m : ℕ} {w β A E g Ē : ℝ}
    (hu : 0 ≤ u) (hw : 0 ≤ w) (hβ : 0 ≤ β) (hA : 0 ≤ A)
    (hG : (1 + u) ^ (m + 2) - 1 ≤ g) (hE0 : 0 ≤ E) (hE : E ≤ Ē) :
    layerBudget u m w β A E ≤
      g * ((m : ℝ) * w * (A + Ē) + β) + (m : ℝ) * w * Ē := by
  have hG0 : (0 : ℝ) ≤ (1 + u) ^ (m + 2) - 1 :=
    sub_nonneg.mpr (one_le_pow₀ (by linarith))
  have hmw : (0 : ℝ) ≤ (m : ℝ) * w := mul_nonneg (Nat.cast_nonneg m) hw
  have hb0 : (0 : ℝ) ≤ (m : ℝ) * w * (A + E) + β := by
    have : (0:ℝ) ≤ (m : ℝ) * w * (A + E) :=
      mul_nonneg hmw (add_nonneg hA hE0)
    linarith
  have h1 : ((1 + u) ^ (m + 2) - 1) * ((m : ℝ) * w * (A + E) + β)
      ≤ g * ((m : ℝ) * w * (A + Ē) + β) := by
    refine mul_le_mul hG ?_ hb0 (le_trans hG0 hG)
    have : (m : ℝ) * w * (A + E) ≤ (m : ℝ) * w * (A + Ē) :=
      mul_le_mul_of_nonneg_left (by linarith) hmw
    linarith
  have h2 : (m : ℝ) * w * E ≤ (m : ℝ) * w * Ē :=
    mul_le_mul_of_nonneg_left hE hmw
  show ((1 + u) ^ (m + 2) - 1) * ((m : ℝ) * w * (A + E) + β)
      + (m : ℝ) * w * E ≤ _
  linarith

/-- **The certificate composed with a per-logit evaluation budget.** If the
    ℝ logit map is `L`-Lipschitz with margin `m` at `x`, and the margin
    clears the float-widened threshold `(14143/10000)·L·ε + 2·B`, then ANY
    evaluation `z'` within `B` of the ℝ logits at `x + δ` keeps class `i`
    the strict argmax — for every `‖δ‖ < ε`. Pure margin arithmetic; `z'`
    is the deployed (rounded) forward. -/
theorem certified_at_eps_close {n k : ℕ} {L m ε B : ℝ}
    {f : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin k)}
    (hf : LipschitzL2 L f) (hL : 0 < L)
    {x : EuclideanSpace ℝ (Fin n)} {i : Fin k}
    (hmargin : ∀ j, j ≠ i → m ≤ f x i - f x j)
    (hclear : ((14143 : ℝ)/10000) * L * ε + 2 * B < m)
    (hε0 : 0 ≤ ε) (_hB0 : 0 ≤ B)
    (δ : EuclideanSpace ℝ (Fin n)) (hδ : ‖δ‖ < ε) (z' : Fin k → ℝ)
    (hz' : ∀ j, |z' j - f (x + δ) j| ≤ B) :
    ∀ j, j ≠ i → z' j < z' i := by
  intro j hj
  have hgap := logit_gap_stable hf x δ (Ne.symm hj)
  have hmj := hmargin j hj
  have hs2 : Real.sqrt 2 * L * ‖δ‖ ≤ ((14143 : ℝ)/10000) * L * ε := by
    have h2 : (0:ℝ) ≤ Real.sqrt 2 * L :=
      mul_nonneg (Real.sqrt_nonneg 2) hL.le
    calc Real.sqrt 2 * L * ‖δ‖ ≤ Real.sqrt 2 * L * ε :=
          mul_le_mul_of_nonneg_left hδ.le h2
      _ ≤ ((14143 : ℝ)/10000) * L * ε := by
          have h3 : Real.sqrt 2 * L ≤ ((14143 : ℝ)/10000) * L :=
            mul_le_mul_of_nonneg_right sqrt_two_le_rat hL.le
          exact mul_le_mul_of_nonneg_right h3 hε0
  have hi := abs_le.mp (hz' i)
  have hjj := abs_le.mp (hz' j)
  linarith [hgap, hmj, hs2, hi.1, hjj.2]

-- ════════════════════════════════════════════════════════════════
-- § The capped net in `Vec` space + the ℝ-side tie
-- ════════════════════════════════════════════════════════════════

/-- Capped hidden weights in the `Mat` (input×output) convention. -/
noncomputable def W1sV : Mat 49 8 := fun i k => W1s k i
noncomputable def W2sV : Mat 8 10 := fun k c => W2s c k
noncomputable def zb8 : Vec 8 := fun _ => 0
noncomputable def zb10 : Vec 10 := fun _ => 0

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem W1sV_abs_le : ∀ (i : Fin 49) (j : Fin 8), |W1sV i j| ≤ ((475 : ℝ)/256) := by
  intro i j
  fin_cases i <;> fin_cases j <;> (simp [W1sV, W1s]; try norm_num)

set_option maxRecDepth 16384 in
set_option maxHeartbeats 16000000 in
theorem W2sV_abs_le : ∀ (i : Fin 8) (j : Fin 10), |W2sV i j| ≤ ((129 : ℝ)/64) := by
  intro i j
  fin_cases i <;> fin_cases j <;> (simp [W2sV, W2s]; try norm_num)

theorem zb8_abs_le : ∀ j : Fin 8, |zb8 j| ≤ 0 := fun j => by norm_num [zb8]
theorem zb10_abs_le : ∀ j : Fin 10, |zb10 j| ≤ 0 := fun j => by norm_num [zb10]

/-- The `Vec`-space real forward IS `mlpS`, coordinatewise (transposed
    convention, zero biases, `relu = reluE`). -/
theorem real_tie (y : EuclideanSpace ℝ (Fin 49)) (k : Fin 10) :
    Proofs.dense W2sV zb10 (relu 8 (Proofs.dense W1sV zb8 (fun c => y c))) k
      = mlpS y k := by
  have hinner : ∀ m : Fin 8,
      Proofs.dense W1sV zb8 (fun c => y c) m = denseE W1s y m := by
    intro m
    show (∑ i, y i * W1sV i m) + zb8 m = ∑ i, W1s m i * y i
    rw [show zb8 m = (0:ℝ) from rfl, add_zero]
    exact Finset.sum_congr rfl fun i _ => mul_comm _ _
  show (∑ m, relu 8 (Proofs.dense W1sV zb8 (fun c => y c)) m * W2sV m k)
      + zb10 k = ∑ m, W2s k m * reluE (denseE W1s y) m
  rw [show zb10 k = (0:ℝ) from rfl, add_zero]
  refine Finset.sum_congr rfl fun m _ => ?_
  have hr : relu 8 (Proofs.dense W1sV zb8 (fun c => y c)) m
      = reluE (denseE W1s y) m := by
    show (if Proofs.dense W1sV zb8 (fun c => y c) m > 0
          then Proofs.dense W1sV zb8 (fun c => y c) m else 0)
        = max (denseE W1s y m) 0
    rw [hinner m]
    by_cases h : denseE W1s y m > 0
    · rw [if_pos h, max_eq_left h.le]
    · rw [if_neg h, max_eq_right (not_lt.mp h)]
  rw [hr]
  exact mul_comm _ _

-- ════════════════════════════════════════════════════════════════
-- § The rational budget chain (γ-form, parametric in `M.u ≤ u32`)
-- ════════════════════════════════════════════════════════════════

theorem capped_E0_nonneg (M : FloatModel) :
    (0:ℝ) ≤ layerBudget M.u 49 ((475 : ℝ)/256) 0 ((11:ℝ)/10) (u32 * ((11:ℝ)/10)) :=
  layerBudget_nonneg M.u_nonneg (by norm_num) le_rfl (by norm_num)
    (by norm_num [u32])

/-- Layer-0 budget at the capped-net magnitudes, with the input-quantization
    error `u32·(11/10)` inherited. -/
theorem capped_E0_le (M : FloatModel) (hMu : M.u ≤ u32) :
    layerBudget M.u 49 ((475 : ℝ)/256) 0 ((11:ℝ)/10) (u32 * ((11:ℝ)/10))
      ≤ ((38747 : ℝ)/125000000) := by
  refine (layerBudget_le_of' M.u_nonneg (by norm_num) le_rfl (by norm_num)
    (M.gamma_num (q := ((3039847 : ℝ)/1000000000000)) hMu (by norm_num [u32]) (by norm_num [u32]))
    (by norm_num [u32]) le_rfl).trans ?_
  norm_num [u32]

/-- The whole 2-layer budget: every rounded logit within `((14899 : ℝ)/2500000)`. -/
theorem capped_B_le (M : FloatModel) (hMu : M.u ≤ u32) :
    layerBudget M.u 8 ((129 : ℝ)/64) 0 (layerAct 49 ((475 : ℝ)/256) 0 ((11:ℝ)/10))
      (layerBudget M.u 49 ((475 : ℝ)/256) 0 ((11:ℝ)/10) (u32 * ((11:ℝ)/10)))
      ≤ ((14899 : ℝ)/2500000) := by
  have hA : layerAct 49 ((475 : ℝ)/256) 0 ((11:ℝ)/10) = ((51205 : ℝ)/512) := by
    norm_num [layerAct]
  rw [hA]
  refine (layerBudget_le_of' M.u_nonneg (by norm_num) le_rfl (by norm_num)
    (M.gamma_num (q := ((596047 : ℝ)/1000000000000)) hMu (by norm_num [u32]) (by norm_num [u32]))
    (capped_E0_nonneg M) (capped_E0_le M hMu)).trans ?_
  norm_num

/-- **The composed per-image engine**: margin clears the float-widened
    threshold ⇒ the rounded forward of any quantized perturbed input keeps
    the class. -/
theorem certifiedFloat_of_margin (M : FloatModel) (hMu : M.u ≤ u32)
    (x : EuclideanSpace ℝ (Fin 49)) (hx1 : ∀ c, |x c| ≤ 1)
    {i : Fin 10} {m : ℝ}
    (hmargin : ∀ j, j ≠ i → m ≤ mlpS x i - mlpS x j)
    (hclear : ((14143 : ℝ)/10000) * ((19760433 : ℝ)/1000000) * ((1:ℝ)/10)
      + 2 * ((14899 : ℝ)/2500000) < m)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (x + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ i →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y i := by
  have hmag : ∀ c, |(x + δ) c| ≤ (11:ℝ)/10 := by
    intro c
    have h2 : |δ c| ≤ ‖δ‖ := coord_abs_le_norm δ c
    calc |(x + δ) c| = |x c + δ c| := rfl
      _ ≤ |x c| + |δ c| := abs_add_le _ _
      _ ≤ 1 + 1/10 := add_le_add (hx1 c) (by linarith)
      _ = (11:ℝ)/10 := by norm_num
  have hclose : ∀ k, |M.mlp2F W1sV zb8 W2sV zb10 y k - mlpS (x + δ) k|
      ≤ ((14899 : ℝ)/2500000) := by
    intro k
    have h := M.mlp2_float_close_uniform (x := fun c => (x + δ) c) (y := y)
      (by norm_num : (0:ℝ) ≤ ((475 : ℝ)/256)) le_rfl
      (by norm_num : (0:ℝ) ≤ ((129 : ℝ)/64)) (by norm_num : (0:ℝ) ≤ (11:ℝ)/10)
      (by norm_num [u32] : (0:ℝ) ≤ u32 * ((11:ℝ)/10))
      W1sV_abs_le zb8_abs_le W2sV_abs_le zb10_abs_le hmag hy k
    rw [real_tie] at h
    exact h.trans (capped_B_le M hMu)
  exact certified_at_eps_close mlpS_lip_gram2 (by norm_num) hmargin hclear
    (by norm_num) (by norm_num) δ hδ _ hclose

-- ════════════════════════════════════════════════════════════════
-- § The float-certified images
-- ════════════════════════════════════════════════════════════════

set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img0_abs_le : ∀ c : Fin 49, |img0 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img0]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #0): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC0_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img0 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img0 img0_abs_le marginC0
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img3_abs_le : ∀ c : Fin 49, |img3 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img3]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #3): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC3_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img3 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img3 img3_abs_le marginC3
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img5_abs_le : ∀ c : Fin 49, |img5 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img5]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #5): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC5_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img5 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img5 img5_abs_le marginC5
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img10_abs_le : ∀ c : Fin 49, |img10 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img10]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #10): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC10_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img10 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img10 img10_abs_le marginC10
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img13_abs_le : ∀ c : Fin 49, |img13 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img13]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #13): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC13_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img13 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img13 img13_abs_le marginC13
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img14_abs_le : ∀ c : Fin 49, |img14 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img14]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #14): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC14_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img14 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img14 img14_abs_le marginC14
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img17_abs_le : ∀ c : Fin 49, |img17 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img17]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #17): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC17_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img17 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img17 img17_abs_le marginC17
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img25_abs_le : ∀ c : Fin 49, |img25 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img25]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #25): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC25_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img25 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img25 img25_abs_le marginC25
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img28_abs_le : ∀ c : Fin 49, |img28 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img28]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #28): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC28_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img28 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img28 img28_abs_le marginC28
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img29_abs_le : ∀ c : Fin 49, |img29 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img29]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #29): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC29_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img29 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img29 img29_abs_le marginC29
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img34_abs_le : ∀ c : Fin 49, |img34 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img34]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #34): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC34_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img34 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img34 img34_abs_le marginC34
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img36_abs_le : ∀ c : Fin 49, |img36 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img36]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #36): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC36_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img36 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img36 img36_abs_le marginC36
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img37_abs_le : ∀ c : Fin 49, |img37 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img37]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #37): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC37_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img37 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img37 img37_abs_le marginC37
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img39_abs_le : ∀ c : Fin 49, |img39 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img39]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #39): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC39_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img39 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img39 img39_abs_le marginC39
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img52_abs_le : ∀ c : Fin 49, |img52 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img52]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #52): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    5 the strict argmax. -/
theorem certifiedC52_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img52 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 5 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 5 :=
  certifiedFloat_of_margin M hMu img52 img52_abs_le marginC52
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img56_abs_le : ∀ c : Fin 49, |img56 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img56]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #56): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    4 the strict argmax. -/
theorem certifiedC56_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img56 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 4 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 4 :=
  certifiedFloat_of_margin M hMu img56 img56_abs_le marginC56
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img60_abs_le : ∀ c : Fin 49, |img60 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img60]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #60): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC60_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img60 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img60 img60_abs_le marginC60
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img68_abs_le : ∀ c : Fin 49, |img68 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img68]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #68): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    3 the strict argmax. -/
theorem certifiedC68_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img68 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 3 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 3 :=
  certifiedFloat_of_margin M hMu img68 img68_abs_le marginC68
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img69_abs_le : ∀ c : Fin 49, |img69 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img69]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #69): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC69_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img69 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img69 img69_abs_le marginC69
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img70_abs_le : ∀ c : Fin 49, |img70 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img70]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #70): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC70_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img70 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img70 img70_abs_le marginC70
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img71_abs_le : ∀ c : Fin 49, |img71 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img71]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #71): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    0 the strict argmax. -/
theorem certifiedC71_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img71 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 0 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 0 :=
  certifiedFloat_of_margin M hMu img71 img71_abs_le marginC71
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img74_abs_le : ∀ c : Fin 49, |img74 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img74]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #74): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC74_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img74 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img74 img74_abs_le marginC74
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img79_abs_le : ∀ c : Fin 49, |img79 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img79]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #79): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC79_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img79 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img79 img79_abs_le marginC79
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img81_abs_le : ∀ c : Fin 49, |img81 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img81]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #81): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    6 the strict argmax. -/
theorem certifiedC81_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img81 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 6 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 6 :=
  certifiedFloat_of_margin M hMu img81 img81_abs_le marginC81
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img82_abs_le : ∀ c : Fin 49, |img82 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img82]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #82): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    2 the strict argmax. -/
theorem certifiedC82_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img82 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 2 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 2 :=
  certifiedFloat_of_margin M hMu img82 img82_abs_le marginC82
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img85_abs_le : ∀ c : Fin 49, |img85 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img85]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #85): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    4 the strict argmax. -/
theorem certifiedC85_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img85 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 4 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 4 :=
  certifiedFloat_of_margin M hMu img85 img85_abs_le marginC85
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img86_abs_le : ∀ c : Fin 49, |img86 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img86]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #86): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    7 the strict argmax. -/
theorem certifiedC86_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img86 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 7 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 7 :=
  certifiedFloat_of_margin M hMu img86 img86_abs_le marginC86
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img89_abs_le : ∀ c : Fin 49, |img89 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img89]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #89): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC89_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img89 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img89 img89_abs_le marginC89
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img90_abs_le : ∀ c : Fin 49, |img90 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img90]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #90): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    3 the strict argmax. -/
theorem certifiedC90_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img90 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 3 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 3 :=
  certifiedFloat_of_margin M hMu img90 img90_abs_le marginC90
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img93_abs_le : ∀ c : Fin 49, |img93 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img93]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #93): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    3 the strict argmax. -/
theorem certifiedC93_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img93 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 3 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 3 :=
  certifiedFloat_of_margin M hMu img93 img93_abs_le marginC93
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img94_abs_le : ∀ c : Fin 49, |img94 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img94]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #94): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    1 the strict argmax. -/
theorem certifiedC94_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img94 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 1 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 1 :=
  certifiedFloat_of_margin M hMu img94 img94_abs_le marginC94
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img95_abs_le : ∀ c : Fin 49, |img95 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img95]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #95): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    4 the strict argmax. -/
theorem certifiedC95_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img95 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 4 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 4 :=
  certifiedFloat_of_margin M hMu img95 img95_abs_le marginC95
    (by norm_num) δ hδ y hy
set_option maxRecDepth 16384 in
set_option maxHeartbeats 8000000 in
theorem img98_abs_le : ∀ c : Fin 49, |img98 c| ≤ 1 := by
  intro c
  fin_cases c <;> (simp [img98]; try norm_num)

/-- **Float-certified at ε = 1/10** (image #98): every binary32-accuracy
    rounded forward of every quantized input within the L2 ball keeps class
    6 the strict argmax. -/
theorem certifiedC98_float (M : FloatModel) (hMu : M.u ≤ u32)
    (δ : EuclideanSpace ℝ (Fin 49)) (hδ : ‖δ‖ < ((1 : ℝ)/10))
    (y : Vec 49) (hy : ∀ c, |y c - (img98 + δ) c| ≤ u32 * ((11 : ℝ)/10)) :
    ∀ j, j ≠ 6 →
      M.mlp2F W1sV zb8 W2sV zb10 y j < M.mlp2F W1sV zb8 W2sV zb10 y 6 :=
  certifiedFloat_of_margin M hMu img98 img98_abs_le marginC98
    (by norm_num) δ hδ y hy

/-- Indices float-certified at ε = 1/10 on the capped net — one
    `certifiedC<i>_float` theorem each. -/
def certifiedFloatIdx : List ℕ := [0, 3, 5, 10, 13, 14, 17, 25, 28, 29, 34, 36, 37, 39, 52, 56, 60, 68, 69, 70, 71, 74, 79, 81, 82, 85, 86, 89, 90, 93, 94, 95, 98]

/-- **The float scorecard**: 33 of the 34 ℝ-certified images
    survive the `2·B` float widening (binary32 forward + input
    quantization) — lower bound only, as before. -/
theorem float_scorecard_count : certifiedFloatIdx.length = 33 := rfl

end LipschitzCertDemo
end Proofs
