import Mathlib.Analysis.InnerProductSpace.EuclideanDist
import Mathlib.Tactic

/-! # Kernel-fast ℤ-list dot products for certificate data

The pooled 49-dim scorecard (`LipschitzCertScorecard.lean`) evaluates its
rational dot products by `simp [Fin.sum_univ_succ] <;> norm_num` — fine at 49
terms, but quadratic in the sum length and ~15–20 s per 784-term dot, which
priced a FULL-INPUT (un-pooled, 784-dim) scorecard out of CI.

This file is the fix, in three parts:

* certificate data lives in `List ℤ` (weights `k/2⁸`, pixels `k/255` — store
  the integer numerators; negatives as `Int.negSucc` literals, which dodges a
  ~15 ms/element `Neg`-elaboration tax);
* the 784-term arithmetic is ONE kernel evaluation per dot:
  `dotZ xs ys = v := by decide +kernel` — the kernel folds `zipWith (·*·)`
  with GMP integer ops, ~0.1 s per dot, `propext`-only (no `ofReduceBool`:
  `+kernel` is the kernel evaluator, NOT `native_decide`);
* `sum_getD_div` (proved once, by induction) transports the integer fact to
  the `∑ j : Fin n, (xs.getD j 0 : ℝ)/c * ((ys.getD j 0 : ℝ)/d)` sums that
  `denseE`-level certificate statements actually quantify over.

Used by `LipschitzCertScorecardFull*.lean` (generated by
`scripts/lipschitz_cert_scorecard_full.py`). All 3-axiom clean.
-/

namespace Proofs

/-- Integer dot product of two lists — the shape the kernel evaluates fast
    (`decide +kernel`: pointer-shared tails, GMP mul/add, no `Fin` indexing). -/
def dotZ (xs ys : List ℤ) : ℤ := (List.zipWith (· * ·) xs ys).sum

theorem dotZ_comm (xs ys : List ℤ) : dotZ xs ys = dotZ ys xs := by
  unfold dotZ
  rw [List.zipWith_comm]
  simp [mul_comm]

/-- getD-dot over `Fin n` = list dot, generically (proved once, by induction
    on `n` so `Fin.sum_univ_succ` applies syntactically). -/
theorem sum_getD_mul : ∀ (n : ℕ) (xs ys : List ℤ), xs.length = n → ys.length = n →
    (∑ j : Fin n, (xs.getD j 0 : ℝ) * (ys.getD j 0 : ℝ)) = ((dotZ xs ys : ℤ) : ℝ)
  | 0, xs, ys, hx, hy => by
      rw [List.length_eq_zero_iff.mp hx, List.length_eq_zero_iff.mp hy]
      simp [dotZ]
  | n + 1, [], _, hx, _ => by simp at hx
  | n + 1, _ :: _, [], _, hy => by simp at hy
  | n + 1, a :: xs, b :: ys, hx, hy => by
      rw [Fin.sum_univ_succ]
      simp only [List.getD_cons_zero, List.getD_cons_succ, Fin.val_succ, Fin.val_zero]
      rw [sum_getD_mul n xs ys (by simpa using hx) (by simpa using hy)]
      simp only [dotZ, List.zipWith_cons_cons, List.sum_cons]
      push_cast
      ring

/-- The scaled form the certificate files instantiate: rows stored as ℤ-lists
    of numerators over denominators `c`, `d`; once `dotZ xs ys = v` is checked
    in the kernel, the ℝ-level dense-layer dot is `v/(c·d)`. -/
theorem sum_getD_div {xs ys : List ℤ} {n : ℕ} (hx : xs.length = n) (hy : ys.length = n)
    {v : ℤ} (h : dotZ xs ys = v) (c d : ℝ) :
    (∑ j : Fin n, (xs.getD j 0 : ℝ)/c * ((ys.getD j 0 : ℝ)/d)) = (v : ℝ)/(c*d) := by
  have hsplit : (∑ j : Fin n, (xs.getD j 0 : ℝ)/c * ((ys.getD j 0 : ℝ)/d))
      = (∑ j : Fin n, (xs.getD j 0 : ℝ) * (ys.getD j 0 : ℝ))/(c*d) := by
    rw [Finset.sum_div]
    exact Finset.sum_congr rfl fun j _ => by ring
  rw [hsplit, sum_getD_mul n xs ys hx hy, h]

/-- Integer absolute row sum — the `ℓ1` weight of a row, kernel-evaluable
    (`decide +kernel`). Feeds the IBP uniform-radius layer bound
    `denseLo/Hi (x ∓ ε) = ⟨w,x⟩ ∓ ε·Σ|w|` (`IntervalBound.lean`). -/
def absSumZ (xs : List ℤ) : ℤ := (xs.map (fun x => |x|)).sum

/-- getD abs-sum over `Fin n` = list abs-sum (the `sum_getD_mul` sibling). -/
theorem sum_getD_abs : ∀ (n : ℕ) (xs : List ℤ), xs.length = n →
    (∑ j : Fin n, |(xs.getD j 0 : ℝ)|) = ((absSumZ xs : ℤ) : ℝ)
  | 0, xs, hx => by
      rw [List.length_eq_zero_iff.mp hx]
      simp [absSumZ]
  | n + 1, [], hx => by simp at hx
  | n + 1, a :: xs, hx => by
      rw [Fin.sum_univ_succ]
      simp only [List.getD_cons_zero, List.getD_cons_succ, Fin.val_succ, Fin.val_zero]
      rw [sum_getD_abs n xs (by simpa using hx)]
      simp only [absSumZ, List.map_cons, List.sum_cons]
      push_cast [Int.cast_abs]
      ring

/-- Scaled form: a `k/c`-grid row's `ℓ1` norm from one kernel fact. -/
theorem sum_getD_abs_div {xs : List ℤ} {n : ℕ} (hx : xs.length = n)
    {v : ℤ} (h : absSumZ xs = v) {c : ℝ} (hc : 0 ≤ c) :
    (∑ j : Fin n, |(xs.getD j 0 : ℝ)/c|) = (v : ℝ)/c := by
  have hsplit : (∑ j : Fin n, |(xs.getD j 0 : ℝ)/c|)
      = (∑ j : Fin n, |(xs.getD j 0 : ℝ)|)/c := by
    rw [Finset.sum_div]
    exact Finset.sum_congr rfl fun j _ => by
      rw [abs_div, abs_of_nonneg hc]
  rw [hsplit, sum_getD_abs n xs hx, h]

end Proofs
