import LeanMlir.Proofs.Binary32Instance

/-! # Descent at TRAINED weights (post_audit_roadmap §3)

**REDUCED CERTIFICATE MODEL** — this file's concrete net is the 4×4-pooled 49-dim
MNIST family (width-8 hidden, /128–/256 rational weights), NOT the canonical
784→512→512→10 `mlpVerified`; chosen so every margin/norm/SOS check is exact rational
arithmetic in-kernel. Canonical surface: `Proofs/MlpCanonical.lean`.

`binary32_linear_sgd_descends_concrete` (the suite's only concrete descent
instance) holds at the degenerate `W = 0` net — a satisfiability witness.
This file retires that caveat: **one binary32 SGD step on a TRAINED,
/128-rationalized bias-free 49→10 pooled-MNIST linear classifier (test acc
0.874) provably decreases the real cross-entropy loss**, at MNIST test
image #8 with learning rate 1/8192. The rounding model is the CONSTRUCTED
`rndP 23` grid (`binary32`), so the whole statement is axiom-free.

The trick that closes the descent window with zero `exp` evaluations: the
witness sample is MISCLASSIFIED (true label 5, predicted 6), so
`z_5 ≤ z_6` is an exact rational inequality (`hz_lbl_le`) and
exp-monotonicity alone gives `softmax_5 ≤ 1/2` (`sm_lbl_le_half`) —
whence the two gradient sums the window needs are bracketed by rationals:
`Σ|∇| ≤ 2·Σxᵢ` (`gradL1_le`, softmax sums to 1) and `Σ∇² ≥ (Σxᵢ²)/4`
(`gradSq_lower`). The float-forward drift `hδ` is the proven
`dense_close_fresh` budget evaluated exactly per class column (norm_num
computes the exact `(1+2⁻²⁴)⁵¹`); the `exp(2δ)−1` term inside `cotErr` is
bounded by the γ-form `exp_sub_one_le`. Every hypothesis of
`linear_float_sgd_descends` is discharged — nothing assumed.

Being misclassified also makes the guaranteed drop STRICTLY positive
(`trained_linear_sgd_strictly_descends`): the loss drops by ≥ lr·(Σxᵢ²)/8
≈ 6.93e-05. Generated by `scripts/trained_linear_descent.py`;
weights/input are DATA. -/

namespace Proofs
namespace TrainedLinearDescent

/-- Trained linear weights (input×class, entries `k/128`), test acc 0.874. -/
noncomputable def Wd : Mat 49 10 :=
  ![![((2 : ℝ)/128), ((24 : ℝ)/128), ((-25 : ℝ)/128), ((-2 : ℝ)/128), ((-23 : ℝ)/128), ((4 : ℝ)/128), ((-17 : ℝ)/128), ((5 : ℝ)/128), ((-4 : ℝ)/128), ((19 : ℝ)/128)],
    ![((-4 : ℝ)/128), ((6 : ℝ)/128), ((-23 : ℝ)/128), ((-14 : ℝ)/128), ((-17 : ℝ)/128), ((-8 : ℝ)/128), ((19 : ℝ)/128), ((-5 : ℝ)/128), ((-12 : ℝ)/128), ((14 : ℝ)/128)],
    ![((-3 : ℝ)/128), ((-30 : ℝ)/128), ((49 : ℝ)/128), ((19 : ℝ)/128), ((-79 : ℝ)/128), ((35 : ℝ)/128), ((109 : ℝ)/128), ((-34 : ℝ)/128), ((-20 : ℝ)/128), ((27 : ℝ)/128)],
    ![((-41 : ℝ)/128), ((-5 : ℝ)/128), ((110 : ℝ)/128), ((0 : ℝ)/128), ((-104 : ℝ)/128), ((-34 : ℝ)/128), ((273 : ℝ)/128), ((-21 : ℝ)/128), ((-96 : ℝ)/128), ((-38 : ℝ)/128)],
    ![((-67 : ℝ)/128), ((-18 : ℝ)/128), ((10 : ℝ)/128), ((-4 : ℝ)/128), ((-78 : ℝ)/128), ((-45 : ℝ)/128), ((313 : ℝ)/128), ((-14 : ℝ)/128), ((-73 : ℝ)/128), ((-28 : ℝ)/128)],
    ![((-12 : ℝ)/128), ((-32 : ℝ)/128), ((-37 : ℝ)/128), ((-20 : ℝ)/128), ((-30 : ℝ)/128), ((-6 : ℝ)/128), ((124 : ℝ)/128), ((28 : ℝ)/128), ((-41 : ℝ)/128), ((-18 : ℝ)/128)],
    ![((23 : ℝ)/128), ((7 : ℝ)/128), ((16 : ℝ)/128), ((-10 : ℝ)/128), ((-30 : ℝ)/128), ((-1 : ℝ)/128), ((26 : ℝ)/128), ((11 : ℝ)/128), ((6 : ℝ)/128), ((2 : ℝ)/128)],
    ![((17 : ℝ)/128), ((8 : ℝ)/128), ((-23 : ℝ)/128), ((7 : ℝ)/128), ((13 : ℝ)/128), ((16 : ℝ)/128), ((10 : ℝ)/128), ((-26 : ℝ)/128), ((6 : ℝ)/128), ((8 : ℝ)/128)],
    ![((-58 : ℝ)/128), ((-18 : ℝ)/128), ((73 : ℝ)/128), ((141 : ℝ)/128), ((36 : ℝ)/128), ((-77 : ℝ)/128), ((-42 : ℝ)/128), ((87 : ℝ)/128), ((-49 : ℝ)/128), ((-96 : ℝ)/128)],
    ![((-129 : ℝ)/128), ((-167 : ℝ)/128), ((323 : ℝ)/128), ((333 : ℝ)/128), ((-167 : ℝ)/128), ((59 : ℝ)/128), ((-108 : ℝ)/128), ((113 : ℝ)/128), ((-45 : ℝ)/128), ((-295 : ℝ)/128)],
    ![((106 : ℝ)/128), ((-49 : ℝ)/128), ((321 : ℝ)/128), ((204 : ℝ)/128), ((-533 : ℝ)/128), ((-62 : ℝ)/128), ((-197 : ℝ)/128), ((-206 : ℝ)/128), ((146 : ℝ)/128), ((193 : ℝ)/128)],
    ![((232 : ℝ)/128), ((-54 : ℝ)/128), ((111 : ℝ)/128), ((69 : ℝ)/128), ((-237 : ℝ)/128), ((-10 : ℝ)/128), ((-98 : ℝ)/128), ((-212 : ℝ)/128), ((129 : ℝ)/128), ((92 : ℝ)/128)],
    ![((-25 : ℝ)/128), ((22 : ℝ)/128), ((-141 : ℝ)/128), ((-90 : ℝ)/128), ((190 : ℝ)/128), ((331 : ℝ)/128), ((-129 : ℝ)/128), ((-95 : ℝ)/128), ((21 : ℝ)/128), ((-238 : ℝ)/128)],
    ![((-39 : ℝ)/128), ((-6 : ℝ)/128), ((-27 : ℝ)/128), ((-20 : ℝ)/128), ((44 : ℝ)/128), ((182 : ℝ)/128), ((-33 : ℝ)/128), ((-28 : ℝ)/128), ((12 : ℝ)/128), ((-42 : ℝ)/128)],
    ![((-27 : ℝ)/128), ((-10 : ℝ)/128), ((-1 : ℝ)/128), ((10 : ℝ)/128), ((-5 : ℝ)/128), ((34 : ℝ)/128), ((-3 : ℝ)/128), ((41 : ℝ)/128), ((-26 : ℝ)/128), ((-36 : ℝ)/128)],
    ![((-75 : ℝ)/128), ((-48 : ℝ)/128), ((-50 : ℝ)/128), ((15 : ℝ)/128), ((-27 : ℝ)/128), ((-31 : ℝ)/128), ((-94 : ℝ)/128), ((236 : ℝ)/128), ((159 : ℝ)/128), ((-40 : ℝ)/128)],
    ![((9 : ℝ)/128), ((-438 : ℝ)/128), ((-260 : ℝ)/128), ((-436 : ℝ)/128), ((4 : ℝ)/128), ((319 : ℝ)/128), ((-169 : ℝ)/128), ((324 : ℝ)/128), ((320 : ℝ)/128), ((326 : ℝ)/128)],
    ![((75 : ℝ)/128), ((124 : ℝ)/128), ((-270 : ℝ)/128), ((132 : ℝ)/128), ((-432 : ℝ)/128), ((231 : ℝ)/128), ((-225 : ℝ)/128), ((361 : ℝ)/128), ((-113 : ℝ)/128), ((119 : ℝ)/128)],
    ![((138 : ℝ)/128), ((34 : ℝ)/128), ((-45 : ℝ)/128), ((336 : ℝ)/128), ((-22 : ℝ)/128), ((-270 : ℝ)/128), ((-743 : ℝ)/128), ((605 : ℝ)/128), ((-117 : ℝ)/128), ((206 : ℝ)/128)],
    ![((287 : ℝ)/128), ((-370 : ℝ)/128), ((-75 : ℝ)/128), ((20 : ℝ)/128), ((-130 : ℝ)/128), ((103 : ℝ)/128), ((-332 : ℝ)/128), ((109 : ℝ)/128), ((368 : ℝ)/128), ((68 : ℝ)/128)],
    ![((-25 : ℝ)/128), ((-93 : ℝ)/128), ((-23 : ℝ)/128), ((-62 : ℝ)/128), ((-53 : ℝ)/128), ((311 : ℝ)/128), ((-18 : ℝ)/128), ((-47 : ℝ)/128), ((26 : ℝ)/128), ((-87 : ℝ)/128)],
    ![((19 : ℝ)/128), ((1 : ℝ)/128), ((18 : ℝ)/128), ((31 : ℝ)/128), ((-16 : ℝ)/128), ((-12 : ℝ)/128), ((0 : ℝ)/128), ((8 : ℝ)/128), ((-56 : ℝ)/128), ((-24 : ℝ)/128)],
    ![((124 : ℝ)/128), ((-31 : ℝ)/128), ((-319 : ℝ)/128), ((-193 : ℝ)/128), ((299 : ℝ)/128), ((-32 : ℝ)/128), ((10 : ℝ)/128), ((-9 : ℝ)/128), ((-151 : ℝ)/128), ((289 : ℝ)/128)],
    ![((254 : ℝ)/128), ((-595 : ℝ)/128), ((-316 : ℝ)/128), ((-223 : ℝ)/128), ((738 : ℝ)/128), ((377 : ℝ)/128), ((260 : ℝ)/128), ((-439 : ℝ)/128), ((-115 : ℝ)/128), ((169 : ℝ)/128)],
    ![((-735 : ℝ)/128), ((710 : ℝ)/128), ((-180 : ℝ)/128), ((237 : ℝ)/128), ((25 : ℝ)/128), ((83 : ℝ)/128), ((38 : ℝ)/128), ((-568 : ℝ)/128), ((351 : ℝ)/128), ((-1 : ℝ)/128)],
    ![((-376 : ℝ)/128), ((-428 : ℝ)/128), ((-143 : ℝ)/128), ((77 : ℝ)/128), ((467 : ℝ)/128), ((-335 : ℝ)/128), ((-50 : ℝ)/128), ((352 : ℝ)/128), ((-91 : ℝ)/128), ((564 : ℝ)/128)],
    ![((329 : ℝ)/128), ((-126 : ℝ)/128), ((-168 : ℝ)/128), ((-41 : ℝ)/128), ((5 : ℝ)/128), ((-317 : ℝ)/128), ((362 : ℝ)/128), ((90 : ℝ)/128), ((-76 : ℝ)/128), ((-45 : ℝ)/128)],
    ![((40 : ℝ)/128), ((-18 : ℝ)/128), ((9 : ℝ)/128), ((-5 : ℝ)/128), ((2 : ℝ)/128), ((-54 : ℝ)/128), ((24 : ℝ)/128), ((0 : ℝ)/128), ((-6 : ℝ)/128), ((-36 : ℝ)/128)],
    ![((-24 : ℝ)/128), ((15 : ℝ)/128), ((-10 : ℝ)/128), ((43 : ℝ)/128), ((-24 : ℝ)/128), ((-29 : ℝ)/128), ((-28 : ℝ)/128), ((-9 : ℝ)/128), ((-38 : ℝ)/128), ((-12 : ℝ)/128)],
    ![((257 : ℝ)/128), ((-176 : ℝ)/128), ((366 : ℝ)/128), ((24 : ℝ)/128), ((20 : ℝ)/128), ((112 : ℝ)/128), ((-71 : ℝ)/128), ((-163 : ℝ)/128), ((-195 : ℝ)/128), ((-186 : ℝ)/128)],
    ![((281 : ℝ)/128), ((-118 : ℝ)/128), ((394 : ℝ)/128), ((-479 : ℝ)/128), ((-12 : ℝ)/128), ((-305 : ℝ)/128), ((633 : ℝ)/128), ((-441 : ℝ)/128), ((263 : ℝ)/128), ((-125 : ℝ)/128)],
    ![((-584 : ℝ)/128), ((469 : ℝ)/128), ((341 : ℝ)/128), ((-511 : ℝ)/128), ((321 : ℝ)/128), ((-297 : ℝ)/128), ((170 : ℝ)/128), ((98 : ℝ)/128), ((-53 : ℝ)/128), ((-42 : ℝ)/128)],
    ![((39 : ℝ)/128), ((-461 : ℝ)/128), ((131 : ℝ)/128), ((205 : ℝ)/128), ((123 : ℝ)/128), ((14 : ℝ)/128), ((264 : ℝ)/128), ((10 : ℝ)/128), ((-235 : ℝ)/128), ((-87 : ℝ)/128)],
    ![((92 : ℝ)/128), ((-91 : ℝ)/128), ((280 : ℝ)/128), ((219 : ℝ)/128), ((-164 : ℝ)/128), ((73 : ℝ)/128), ((223 : ℝ)/128), ((-146 : ℝ)/128), ((-214 : ℝ)/128), ((-303 : ℝ)/128)],
    ![((11 : ℝ)/128), ((-29 : ℝ)/128), ((187 : ℝ)/128), ((-50 : ℝ)/128), ((-33 : ℝ)/128), ((24 : ℝ)/128), ((-55 : ℝ)/128), ((-2 : ℝ)/128), ((-49 : ℝ)/128), ((-1 : ℝ)/128)],
    ![((-2 : ℝ)/128), ((-25 : ℝ)/128), ((34 : ℝ)/128), ((53 : ℝ)/128), ((-33 : ℝ)/128), ((0 : ℝ)/128), ((-9 : ℝ)/128), ((-1 : ℝ)/128), ((-18 : ℝ)/128), ((-12 : ℝ)/128)],
    ![((47 : ℝ)/128), ((18 : ℝ)/128), ((255 : ℝ)/128), ((367 : ℝ)/128), ((-213 : ℝ)/128), ((79 : ℝ)/128), ((-148 : ℝ)/128), ((-106 : ℝ)/128), ((-88 : ℝ)/128), ((-159 : ℝ)/128)],
    ![((311 : ℝ)/128), ((42 : ℝ)/128), ((185 : ℝ)/128), ((66 : ℝ)/128), ((-489 : ℝ)/128), ((372 : ℝ)/128), ((9 : ℝ)/128), ((-170 : ℝ)/128), ((83 : ℝ)/128), ((-501 : ℝ)/128)],
    ![((195 : ℝ)/128), ((-170 : ℝ)/128), ((-137 : ℝ)/128), ((27 : ℝ)/128), ((-128 : ℝ)/128), ((156 : ℝ)/128), ((353 : ℝ)/128), ((-14 : ℝ)/128), ((87 : ℝ)/128), ((-300 : ℝ)/128)],
    ![((-53 : ℝ)/128), ((7 : ℝ)/128), ((93 : ℝ)/128), ((153 : ℝ)/128), ((-56 : ℝ)/128), ((129 : ℝ)/128), ((56 : ℝ)/128), ((-248 : ℝ)/128), ((130 : ℝ)/128), ((-287 : ℝ)/128)],
    ![((-81 : ℝ)/128), ((-7 : ℝ)/128), ((337 : ℝ)/128), ((-41 : ℝ)/128), ((-51 : ℝ)/128), ((112 : ℝ)/128), ((-117 : ℝ)/128), ((-166 : ℝ)/128), ((13 : ℝ)/128), ((20 : ℝ)/128)],
    ![((24 : ℝ)/128), ((-8 : ℝ)/128), ((84 : ℝ)/128), ((-8 : ℝ)/128), ((-23 : ℝ)/128), ((-17 : ℝ)/128), ((-21 : ℝ)/128), ((-21 : ℝ)/128), ((-8 : ℝ)/128), ((-9 : ℝ)/128)],
    ![((24 : ℝ)/128), ((29 : ℝ)/128), ((5 : ℝ)/128), ((-6 : ℝ)/128), ((-57 : ℝ)/128), ((-18 : ℝ)/128), ((6 : ℝ)/128), ((-8 : ℝ)/128), ((-4 : ℝ)/128), ((1 : ℝ)/128)],
    ![((-3 : ℝ)/128), ((-17 : ℝ)/128), ((-33 : ℝ)/128), ((38 : ℝ)/128), ((-41 : ℝ)/128), ((-30 : ℝ)/128), ((-32 : ℝ)/128), ((61 : ℝ)/128), ((-43 : ℝ)/128), ((16 : ℝ)/128)],
    ![((-63 : ℝ)/128), ((-196 : ℝ)/128), ((-167 : ℝ)/128), ((165 : ℝ)/128), ((-112 : ℝ)/128), ((12 : ℝ)/128), ((-112 : ℝ)/128), ((254 : ℝ)/128), ((-57 : ℝ)/128), ((247 : ℝ)/128)],
    ![((-78 : ℝ)/128), ((-164 : ℝ)/128), ((-175 : ℝ)/128), ((103 : ℝ)/128), ((-173 : ℝ)/128), ((50 : ℝ)/128), ((-268 : ℝ)/128), ((291 : ℝ)/128), ((171 : ℝ)/128), ((203 : ℝ)/128)],
    ![((-33 : ℝ)/128), ((3 : ℝ)/128), ((-82 : ℝ)/128), ((-31 : ℝ)/128), ((-122 : ℝ)/128), ((-44 : ℝ)/128), ((-118 : ℝ)/128), ((138 : ℝ)/128), ((54 : ℝ)/128), ((256 : ℝ)/128)],
    ![((23 : ℝ)/128), ((0 : ℝ)/128), ((-24 : ℝ)/128), ((-13 : ℝ)/128), ((-31 : ℝ)/128), ((10 : ℝ)/128), ((-11 : ℝ)/128), ((-9 : ℝ)/128), ((-10 : ℝ)/128), ((127 : ℝ)/128)],
    ![((33 : ℝ)/128), ((-11 : ℝ)/128), ((-33 : ℝ)/128), ((30 : ℝ)/128), ((32 : ℝ)/128), ((14 : ℝ)/128), ((26 : ℝ)/128), ((-10 : ℝ)/128), ((13 : ℝ)/128), ((1 : ℝ)/128)]]

noncomputable def bd : Vec 10 := fun _ => 0

/-- MNIST test image #8 (digit 5), 4×4-pooled exact pixel sums. -/
noncomputable def xd : Vec 49 :=
  ![((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((1570 : ℝ)/4080), ((3011 : ℝ)/4080), ((2979 : ℝ)/4080), ((723 : ℝ)/4080), ((0 : ℝ)/4080), ((592 : ℝ)/4080), ((1404 : ℝ)/4080), ((822 : ℝ)/4080), ((383 : ℝ)/4080), ((11 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((2639 : ℝ)/4080), ((946 : ℝ)/4080), ((290 : ℝ)/4080), ((113 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((919 : ℝ)/4080), ((2450 : ℝ)/4080), ((3741 : ℝ)/4080), ((3314 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((59 : ℝ)/4080), ((2802 : ℝ)/4080), ((1966 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080), ((0 : ℝ)/4080)]

def lblD : Fin 10 := 5
def cD : Fin 10 := 6

theorem xd_nonneg : ∀ i, 0 ≤ xd i := by
  intro i
  fin_cases i <;> norm_num [xd]

theorem xd_le_one : ∀ i, |xd i| ≤ 1 := by
  intro i
  fin_cases i <;> norm_num [xd]

/-- `Σᵢ xᵢ` exactly (all coordinates nonneg). -/
theorem xd_sum : (∑ i, xd i) = ((15367 : ℝ)/2040) := by
  simp [xd, Fin.sum_univ_succ]
  norm_num

theorem xd_sq_sum : (∑ i, xd i ^ 2) = ((1511461 : ℝ)/332928) := by
  simp [xd, Fin.sum_univ_succ]
  norm_num

/-- The witness is misclassified: logit 5 ≤ logit 6, exactly. -/
theorem hz_lbl_le : dense Wd bd xd lblD ≤ dense Wd bd xd cD := by
  show (∑ i, xd i * Wd i lblD) + bd lblD ≤ (∑ i, xd i * Wd i cD) + bd cD
  simp [Wd, xd, bd, lblD, cD, Fin.sum_univ_succ]
  norm_num

-- ── softmax facts at the trained logits (no `exp` is ever evaluated) ──

theorem sm_pos : ∀ j, 0 < softmax 10 (dense Wd bd xd) j := fun j =>
  div_pos (Real.exp_pos _)
    (Finset.sum_pos (fun _ _ => Real.exp_pos _) ⟨j, Finset.mem_univ j⟩)

theorem sm_sum : (∑ j, softmax 10 (dense Wd bd xd) j) = 1 := by
  show (∑ j, Real.exp (dense Wd bd xd j) / ∑ k, Real.exp (dense Wd bd xd k)) = 1
  simp only [div_eq_mul_inv, ← Finset.sum_mul]
  exact mul_inv_cancel₀ (ne_of_gt (Finset.sum_pos
    (fun k _ => Real.exp_pos _) ⟨lblD, Finset.mem_univ _⟩))

theorem sm_le_one : ∀ j, softmax 10 (dense Wd bd xd) j ≤ 1 := by
  intro j
  have h := Finset.single_le_sum
    (f := fun k => softmax 10 (dense Wd bd xd) k)
    (fun k _ => (sm_pos k).le) (Finset.mem_univ j)
  rw [sm_sum] at h
  exact h

/-- **Softmax at the true label ≤ 1/2** — from misclassification alone:
    `exp z_lbl ≤ exp z_c` and both terms sit inside the positive sum. -/
theorem sm_lbl_le_half : softmax 10 (dense Wd bd xd) lblD ≤ 1 / 2 := by
  have hee : Real.exp (dense Wd bd xd lblD) ≤ Real.exp (dense Wd bd xd cD) :=
    Real.exp_le_exp.mpr hz_lbl_le
  have hSpos : 0 < ∑ k, Real.exp (dense Wd bd xd k) :=
    Finset.sum_pos (fun k _ => Real.exp_pos _) ⟨lblD, Finset.mem_univ _⟩
  have hpair : Real.exp (dense Wd bd xd lblD) + Real.exp (dense Wd bd xd cD) ≤
      ∑ k, Real.exp (dense Wd bd xd k) := by
    have hsub := Finset.sum_le_sum_of_subset_of_nonneg
      (Finset.subset_univ ({lblD, cD} : Finset (Fin 10)))
      (fun k _ _ => (Real.exp_pos (dense Wd bd xd k)).le)
    rwa [Finset.sum_pair (by decide : lblD ≠ cD)] at hsub
  show Real.exp (dense Wd bd xd lblD) / (∑ k, Real.exp (dense Wd bd xd k)) ≤ 1 / 2
  rw [div_le_iff₀ hSpos]
  nlinarith [Real.exp_pos (dense Wd bd xd lblD)]

/-- `Σⱼ |softmaxⱼ − onehotⱼ| = 2(1 − softmax_lbl) ≤ 2`. -/
theorem sm_cot_l1 :
    (∑ j, |softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j|) ≤ 2 := by
  have hsplit := Finset.add_sum_erase Finset.univ
    (fun j => |softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j|)
    (Finset.mem_univ lblD)
  have hsplit1 := Finset.add_sum_erase Finset.univ
    (fun j => softmax 10 (dense Wd bd xd) j) (Finset.mem_univ lblD)
  rw [sm_sum] at hsplit1
  have herase : (∑ j ∈ Finset.univ.erase lblD,
      |softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j|) =
      ∑ j ∈ Finset.univ.erase lblD, softmax 10 (dense Wd bd xd) j := by
    refine Finset.sum_congr rfl fun j hj => ?_
    rw [show oneHot 10 lblD j = 0 from if_neg (Finset.mem_erase.mp hj).1,
        sub_zero, abs_of_pos (sm_pos j)]
  have hlbl : |softmax 10 (dense Wd bd xd) lblD - oneHot 10 lblD lblD| =
      1 - softmax 10 (dense Wd bd xd) lblD := by
    rw [show oneHot 10 lblD lblD = 1 from if_pos rfl,
        abs_of_nonpos (by linarith [sm_le_one lblD]), neg_sub]
  have hs := sm_pos lblD
  linarith [hsplit, hsplit1, herase, hlbl]

/-- `Σⱼ (softmaxⱼ − onehotⱼ)² ≥ 1/4` — the label term alone, via
    `softmax_lbl ≤ 1/2`. -/
theorem sm_cot_sq :
    (1 : ℝ) / 4 ≤ ∑ j, (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j) ^ 2 := by
  have hterm : (1 : ℝ) / 4 ≤
      (softmax 10 (dense Wd bd xd) lblD - oneHot 10 lblD lblD) ^ 2 := by
    rw [show oneHot 10 lblD lblD = 1 from if_pos rfl]
    nlinarith [sm_lbl_le_half, (sm_pos lblD).le]
  exact hterm.trans (Finset.single_le_sum
    (f := fun j => (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j) ^ 2)
    (fun j _ => sq_nonneg _) (Finset.mem_univ lblD))

-- ── the gradient sums, bracketed by exact rationals ──

theorem grad_key (i : Fin 49) (j : Fin 10) :
    gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) (finProdFinEquiv (i, j)) =
      xd i * (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j) := by
  rw [linear_loss_gradAt, Mat.unflatten_flatten]

/-- `Σ|∇L| ≤ ((15367 : ℝ)/1020)` (= 2·Σxᵢ, exact). -/
theorem gradL1_le :
    (∑ idx, |gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx|) ≤ ((15367 : ℝ)/1020) := by
  rw [← finProdFinEquiv.sum_comp (fun idx => |gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx|)]
  rw [Fintype.sum_prod_type]
  simp_rw [grad_key]
  calc (∑ i : Fin 49, ∑ j : Fin 10,
        |xd i * (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j)|)
      = ∑ i : Fin 49, xd i * ∑ j : Fin 10,
          |softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j| := by
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [abs_mul, abs_of_nonneg (xd_nonneg i)]
    _ ≤ ∑ i : Fin 49, xd i * 2 :=
        Finset.sum_le_sum fun i _ =>
          mul_le_mul_of_nonneg_left sm_cot_l1 (xd_nonneg i)
    _ = 2 * ∑ i, xd i := by
        rw [← Finset.sum_mul, mul_comm]
    _ = ((15367 : ℝ)/1020) := by rw [xd_sum]; norm_num

/-- `Σ(∇L)² ≥ ((1511461 : ℝ)/332928)/4` (= (Σxᵢ²)/4, exact). -/
theorem gradSq_lower :
    ((1511461 : ℝ)/332928) / 4 ≤ ∑ idx, gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx ^ 2 := by
  rw [← finProdFinEquiv.sum_comp (fun idx => gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx ^ 2)]
  rw [Fintype.sum_prod_type]
  simp_rw [grad_key]
  have hfac : (∑ i : Fin 49, ∑ j : Fin 10,
      (xd i * (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j)) ^ 2) =
      (∑ i, xd i ^ 2) * ∑ j : Fin 10,
        (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j) ^ 2 := by
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  rw [hfac]
  have hB0 : (0:ℝ) ≤ ∑ i, xd i ^ 2 := Finset.sum_nonneg fun i _ => sq_nonneg _
  calc ((1511461 : ℝ)/332928) / 4 = ((1511461 : ℝ)/332928) * (1/4) := by norm_num
    _ = (∑ i, xd i ^ 2) * (1/4) := by rw [xd_sq_sum]
    _ ≤ (∑ i, xd i ^ 2) * ∑ j : Fin 10,
        (softmax 10 (dense Wd bd xd) j - oneHot 10 lblD j) ^ 2 :=
        mul_le_mul_of_nonneg_left sm_cot_sq hB0

-- ── the float-side budgets, evaluated ──

/-- Float-forward drift: `denseErr` at `b = 0`, `e = 0`, evaluated exactly per
    class column — `((1+2⁻²⁴)⁵¹ − 1)·Σᵢ|Wᵢₖ|·|xᵢ| ≤ ((1 : ℝ)/25000)`. -/
theorem hdelta : ∀ k, |binary32.dense Wd bd xd k - dense Wd bd xd k| ≤
    ((1 : ℝ)/25000) := by
  intro k
  refine (binary32.dense_close_fresh Wd bd xd k).trans ?_
  simp only [FloatModel.denseErr, binary32_u]
  fin_cases k <;>
    · simp [Wd, xd, bd, Fin.sum_univ_succ]
      norm_num [u32]

theorem hrho : FloatModel.smRho binary32.u 0 10 < 1 := by
  simp only [FloatModel.smRho, binary32_u]
  norm_num [u32]

/-- The gradient-oracle budget `η = mulErr u32 1 1 0 (cotErr u32 0 δ 10)`,
    bounded by `((81 : ℝ)/1000000)` — the `exp(2δ)−1` term via the γ-form. -/
theorem heta : FloatModel.mulErr binary32.u 1 1 0
    (FloatModel.cotErr binary32.u 0 ((1 : ℝ)/25000) 10) ≤ ((81 : ℝ)/1000000) := by
  have hE : Real.exp (2 * ((1 : ℝ)/25000)) - 1 ≤ ((801 : ℝ)/10000000) :=
    (FloatModel.exp_sub_one_le (by norm_num)).trans (by norm_num)
  simp only [FloatModel.mulErr, FloatModel.cotErr, FloatModel.smErr,
    FloatModel.smKappa, FloatModel.smRho, binary32_u]
  norm_num [u32]
  nlinarith [hE]

theorem heta0 : 0 ≤ FloatModel.mulErr binary32.u 1 1 0
    (FloatModel.cotErr binary32.u 0 ((1 : ℝ)/25000) 10) := by
  have hE0 : (0:ℝ) ≤ Real.exp (2 * ((1 : ℝ)/25000)) - 1 := by
    nlinarith [Real.add_one_le_exp (2 * ((1 : ℝ)/25000))]
  simp only [FloatModel.mulErr, FloatModel.cotErr, FloatModel.smErr,
    FloatModel.smKappa, FloatModel.smRho, binary32_u]
  norm_num [u32]
  nlinarith [hE0]

-- ── the capstone ──

set_option maxRecDepth 8192 in
/-- **Descent at TRAINED weights.** One binary32 SGD step (lr = ((1 : ℝ)/8192)) on
    the trained linear classifier, at the misclassified witness, decreases
    the real cross-entropy by ≥ lr·‖∇L‖²/2 — every hypothesis of
    `linear_float_sgd_descends` discharged, the rounding model constructed
    (`rndP 23`), zero axioms. Retires the `W = 0` degeneracy caveat of
    `binary32_linear_sgd_descends_concrete`. -/
theorem trained_linear_sgd_descends_concrete :
    crossEntropy 10 (dense (Mat.unflatten (Mat.flatten Wd -
        ((1 : ℝ)/8192) • binary32.linearFloatGrad Wd bd xd Real.exp lblD)) bd xd)
        lblD ≤
      crossEntropy 10 (dense (Mat.unflatten (Mat.flatten Wd)) bd xd) lblD -
        ((1 : ℝ)/8192) * (∑ idx, gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx ^ 2) / 2 := by
  have hS1 := gradL1_le
  have hS2 := gradSq_lower
  have hS10 : (0:ℝ) ≤ ∑ idx, |gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx| :=
    Finset.sum_nonneg fun _ _ => abs_nonneg _
  have hη := heta
  have hη0 := heta0
  have hfexp : ∀ t, |Real.exp t - Real.exp t| ≤ (0:ℝ) * Real.exp t := by
    intro t; simp
  refine linear_float_sgd_descends binary32 Wd bd xd lblD Real.exp
    (lr := ((1 : ℝ)/8192)) (a := 1) (eexp := 0) (δ := ((1 : ℝ)/25000))
    (by norm_num) xd_le_one (by norm_num) le_rfl (by norm_num) (by norm_num)
    hfexp hrho hdelta ?_ ?_ ?_
  · -- hsmall
    push_cast
    nlinarith [hS1, hS10, hη, hη0]
  · -- h1
    push_cast
    nlinarith [hS1, hS2, hS10, hη, hη0]
  · -- h2
    set S1 := ∑ idx, |gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx| with hS1def
    set S2 := ∑ idx, gradAt (fun w => crossEntropy 10 (dense (Mat.unflatten w) bd xd) lblD)
        (Mat.flatten Wd) idx ^ 2 with hS2def
    set η := FloatModel.mulErr binary32.u 1 1 0
      (FloatModel.cotErr binary32.u 0 ((1 : ℝ)/25000) 10) with hηdef
    have hD : ((1 : ℝ)/8192) * (S1 + ((49 * 10 : ℕ) : ℝ) * η) ≤ ((77037419 : ℝ)/41779200000) := by
      push_cast
      nlinarith [hS1, hη, hη0]
    have hD0 : (0:ℝ) ≤ ((1 : ℝ)/8192) * (S1 + ((49 * 10 : ℕ) : ℝ) * η) := by
      push_cast
      nlinarith [hS10, hη0]
    have hTpos : (0:ℝ) < 1 - 2 * ((1:ℝ) * (((1 : ℝ)/8192) * (S1 + ((49 * 10 : ℕ) : ℝ) * η))) := by
      nlinarith [hD, hD0]
    rw [div_mul_eq_mul_div, div_le_iff₀ hTpos]
    have hRHS0 : (0:ℝ) ≤ ((1 : ℝ)/8192) * S2 / 4 := by
      have : (0:ℝ) ≤ S2 := Finset.sum_nonneg fun _ _ => sq_nonneg _
      positivity
    nlinarith [hD, hD0, hS2, hTpos, hRHS0,
      mul_le_mul_of_nonneg_left hD hD0]

/-- **The drop is strictly positive**: the witness is misclassified, so
    `Σ∇² ≥ ((1511461 : ℝ)/332928)/4 > 0` and the loss strictly decreases. -/
theorem trained_linear_sgd_strictly_descends :
    crossEntropy 10 (dense (Mat.unflatten (Mat.flatten Wd -
        ((1 : ℝ)/8192) • binary32.linearFloatGrad Wd bd xd Real.exp lblD)) bd xd)
        lblD <
      crossEntropy 10 (dense (Mat.unflatten (Mat.flatten Wd)) bd xd) lblD := by
  have h := trained_linear_sgd_descends_concrete
  have h2 := gradSq_lower
  linarith [h, h2]

end TrainedLinearDescent
end Proofs
